import{getApps}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,onSnapshot,query,where}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{getManagementProfile}from"../assets/js/admin-access.js";
const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let profile,person,attendance=[],payments=[];
onSnapshot(doc(db,'adminTea','state'),s=>{const open=s.data()?.serviceOpen!==false,button=$('toggleTeaService');if(button)button.innerHTML=`<i class="fa-solid fa-circle-${open?'stop':'play'}"></i><span>Servisi ${open?'Kapat':'Başlat'}</span>`});
onAuthStateChanged(auth,async user=>{if(!user)return;profile=await getManagementProfile(user,db);const personnel=profile?.permissions?.includes("personnel");document.documentElement.dataset.personnel=personnel?"true":"false";if(!personnel)return;$('posPageTitle').textContent='Personel Adisyonu';document.querySelector('.panel-menu')?.remove();document.querySelector('.header-page-link')?.remove();['cashCountButton','closeDayButton'].forEach(id=>$(id).hidden=true);document.querySelectorAll('.personnel-only').forEach(x=>x.hidden=false);if(!profile.personnelId)return;onSnapshot(query(collection(db,'adminPersonnel'),where('linkedUserUid','==',user.uid)),s=>{person=s.docs[0]?{id:s.docs[0].id,...s.docs[0].data()}:null;render()});onSnapshot(query(collection(db,'adminPersonnelAttendance'),where('personnelId','==',profile.personnelId)),s=>{attendance=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,'adminPersonnelPayments'),where('personnelId','==',profile.personnelId)),s=>{payments=s.docs.map(d=>({id:d.id,...d.data()}));render()})});
$('personnelWageButton').onclick=()=>{$('personnelWageDialog').showModal()};$('closePersonnelWage').onclick=$('closePersonnelWageBottom').onclick=()=>$('personnelWageDialog').close();
function render(){if(!person)return;const worked=attendance.filter(x=>x.status==='worked'),earned=worked.reduce((s,x)=>s+Number(x.wageSnapshot||0),0),paid=payments.reduce((s,x)=>s+Number(x.amount||0),0);$('personnelWageSummary').innerHTML=`<div class="daily-money-grid"><article class="daily-money-card"><span>Çalıştığım Gün</span><b>${worked.length}</b></article><article class="daily-money-card is-bank"><span>Hak Ettiğim</span><b>${money(earned)}</b></article><article class="daily-money-card is-card"><span>Aldığım</span><b>${money(paid)}</b></article></div><article class="daily-detail-item"><span>Kalan Alacağım</span><b>${money(earned-paid)}</b></article>`;$('personnelAttendanceList').innerHTML=[...attendance].sort((a,b)=>String(b.businessDate).localeCompare(String(a.businessDate))).map(x=>`<article class="recent-payment-row"><div><strong>${date(x.businessDate)}</strong><small>${x.status==='worked'?'Çalıştı':x.status==='leave'?'İzinli':'Gelmedi'}</small></div><b>${x.status==='worked'?money(x.wageSnapshot):'—'}</b></article>`).join('')||'<p class="empty">Henüz çalışma kaydı yok.</p>'}
function money(v){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(v)||0)}function date(v){const[y,m,d]=String(v||'').split('-');return d?`${d}.${m}.${y}`:v}
