import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{firebaseConfig}from"./firebase-config.js";
const app=getApps().find(x=>x.name==="[DEFAULT]")||initializeApp(firebaseConfig),auth=getAuth(app),functions=getFunctions(app,"europe-west1"),verifyPin=httpsCallable(functions,"verifySensitivePin"),SESSION_KEY="fatih-sensitive-access-until",SESSION_MS=10*60*1000;let pending=null;
export function sensitiveAccessOpen(){return Number(sessionStorage.getItem(SESSION_KEY)||0)>Date.now()}
export async function requireSensitiveAccess(options={}){if(sensitiveAccessOpen())return true;if(pending)return pending;pending=openPinDialog(options).finally(()=>{pending=null});return pending}
export function lockSensitiveAccess(){sessionStorage.removeItem(SESSION_KEY)}
function openPinDialog({title="Yönetici PIN'i",message="Bu bölümü açmak için yönetici PIN'ini girin."}={}){ensureStyles();return new Promise(resolve=>{const dialog=document.createElement("dialog");dialog.className="sensitive-pin-dialog";dialog.innerHTML=`<form><button class="pin-close" type="button" aria-label="Kapat">×</button><div class="pin-icon"><i class="fa-solid fa-lock"></i></div><p class="pin-kicker">Korumalı bölüm</p><h2>${esc(title)}</h2><p class="pin-copy">${esc(message)}</p><label>Yönetici PIN'i<input name="pin" type="password" inputmode="numeric" pattern="[0-9]*" minlength="4" maxlength="6" autocomplete="off" required></label><p class="pin-message" aria-live="polite"></p><button class="pin-submit" type="submit"><i class="fa-solid fa-unlock-keyhole"></i> Kilidi Aç</button></form>`;document.body.append(dialog);const form=dialog.querySelector("form"),input=form.elements.pin,msg=dialog.querySelector(".pin-message"),submit=dialog.querySelector(".pin-submit"),finish=value=>{if(dialog.open)dialog.close();dialog.remove();resolve(value)};dialog.querySelector(".pin-close").onclick=()=>finish(false);dialog.addEventListener("cancel",e=>{e.preventDefault();finish(false)},{once:true});form.onsubmit=async e=>{e.preventDefault();const pin=input.value.trim();if(!/^\d{4,6}$/.test(pin)){msg.textContent="PIN 4–6 rakam olmalı.";return}submit.disabled=true;msg.textContent="Kontrol ediliyor…";try{await verifyPin({pin});sessionStorage.setItem(SESSION_KEY,String(Date.now()+SESSION_MS));finish(true)}catch(error){const code=String(error.code||"");msg.textContent=code.includes("failed-precondition")?"Önce Kullanıcı Yönetimi'nden yönetici PIN'i oluşturun.":code.includes("resource-exhausted")?"Çok fazla hatalı deneme yapıldı. Birkaç dakika bekleyin.":"PIN yanlış. Tekrar deneyin.";input.value="";input.focus()}finally{submit.disabled=false}};dialog.showModal();setTimeout(()=>input.focus(),80)})}
function ensureStyles(){if(document.getElementById("sensitivePinStyle"))return;const style=document.createElement("style");style.id="sensitivePinStyle";style.textContent=`.sensitive-pin-dialog{border:0;padding:0;background:transparent}.sensitive-pin-dialog::backdrop{background:#271416b8;backdrop-filter:blur(3px)}.sensitive-pin-dialog form{position:relative;width:min(90vw,390px);padding:24px;border:1px solid #eadfd2;border-radius:20px;background:#fffdf9;box-shadow:0 24px 65px #25090c55;font-family:Poppins,Arial,sans-serif}.pin-close{position:absolute;right:14px;top:10px;border:0;color:#786b67;background:transparent;font-size:1.7rem}.pin-icon{display:grid;width:50px;height:50px;place-items:center;border-radius:15px;color:#fff;background:linear-gradient(145deg,#8f2028,#5a1018)}.pin-kicker{margin:14px 0 2px;color:#b68117;font-size:.62rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.sensitive-pin-dialog h2{margin:0;color:#5a1018;font-size:1.2rem}.pin-copy{margin:8px 0 14px;color:#766c68;font-size:.72rem}.sensitive-pin-dialog label{display:grid;gap:6px;color:#5a1018;font-size:.7rem;font-weight:700}.sensitive-pin-dialog input{width:100%;height:48px;padding:0 14px;border:1px solid #dac9bc;border-radius:12px;background:#fff;font:700 1.1rem Poppins;text-align:center;letter-spacing:.25em}.pin-message{min-height:20px;margin:8px 0;color:#a22a32;font-size:.65rem}.pin-submit{width:100%;min-height:46px;border:0;border-radius:12px;color:#fff;background:linear-gradient(145deg,#8f2028,#5a1018);font:700 .75rem Poppins}.pin-submit:disabled{opacity:.55}`;document.head.append(style)}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
if(document.body?.dataset.sensitiveGuard==="credit")onAuthStateChanged(auth,async user=>{if(!user)return;const unlocked=await requireSensitiveAccess({title:"Açık Hesap",message:"Müşteri bakiyelerini görüntülemek ve değiştirmek için yönetici PIN'ini girin."});if(unlocked)document.body.classList.add("sensitive-unlocked");else location.replace(new URL("./yonetim-merkezi/",import.meta.url).href)});
