"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {makeRecord,clean,eventKey,buildHistory,SOURCES}=require('../operation-history');
class HttpsError extends Error{constructor(code,msg){super(msg);this.code=code}}
class DB{
 constructor(){this.data=new Map();this.tail=Promise.resolve()}
 snap(p){const value=this.data.get(p);return{id:p.split('/').at(-1),exists:value!==undefined,data:()=>structuredClone(value)}}
 doc(p){return{path:p,get:async()=>this.snap(p),delete:async()=>this.data.delete(p),create:async v=>{if(this.data.has(p))throw Object.assign(new Error('exists'),{code:6});this.data.set(p,structuredClone(v))}}}
 collection(p){const db=this,conditions=[];let cursor,cap=Infinity;const q={where:(k,op,v)=>{conditions.push([k,op,v]);return q},orderBy:()=>q,startAfter:(time,id)=>{cursor={time,id};return q},limit:n=>{cap=n;return q},get:async()=>{const docs=[...db.data.keys()].filter(k=>k.startsWith(p+'/')).map(k=>db.snap(k)).filter(d=>conditions.every(([k,op,v])=>op==='>='?d.data()[k]>=v:d.data()[k]<=v)).sort((a,b)=>b.data().eventAtMs-a.data().eventAtMs||b.id.localeCompare(a.id)).filter(d=>!cursor||d.data().eventAtMs<cursor.time||(d.data().eventAtMs===cursor.time&&d.id<cursor.id)).slice(0,cap);return{docs,size:docs.length}}};return q}
 runTransaction(fn){const job=this.tail.then(async()=>{const writes=[];let written=false;const tx={get:async ref=>{assert.equal(written,false);return ref.get()},set:(ref,data)=>{written=true;writes.push([ref.path,data])}};const r=await fn(tx);for(const [p,v]of writes)this.data.set(p,structuredClone(v));return r});this.tail=job.catch(()=>{});return job}
}
function fixture(){const db=new DB(),time=Date.parse('2026-10-02T10:00:00+03:00');db.data.set('adminSecurity/sensitiveAccess',{salt:'salt',pinHash:'123456:salt',updatedAtMs:1});const api=buildHistory({db,FieldValue:{serverTimestamp:()=>0},HttpsError,ownerUid:'owner',pinHash:(p,s)=>p+':'+s,safeHashEqual:(a,b)=>a===b,now:()=>time});return{db,api,time,call:(m,data={},uid='owner')=>api[m]({auth:uid?{uid}:null,data})}}
const event=(extra={})=>({source:'adminCashMovements',id:'cash-1',before:{amount:200,updatedBy:'old-user'},after:{amount:100,updatedBy:'claimed-user'},eventId:'event-1',time:'2026-10-02T10:00:00Z',authId:'actual-user',authType:'unknown',...extra});
test('before/after capture, authenticated actor wins over document metadata',()=>{const r=makeRecord(event());assert.equal(r.actorUid,'actual-user');assert.equal(r.actorVerified,true);assert.deepEqual(r.changes,[{field:'amount',before:200,after:100}]);assert.equal(r.action,'update')});
test('hard deletion preserves values and does not blame earlier author',()=>{const r=makeRecord(event({after:null,authId:null,authType:'service_account'}));assert.equal(r.before.amount,200);assert.equal(r.after,null);assert.equal(r.action,'delete');assert.equal(r.actorUid,'');assert.equal(r.actorVerified,false)});
test('explicit cancellation, reversal and payment reopen classify correctly',()=>{for(const after of[{reversed:true},{status:'cancelled'},{action:'cancel'},{correctionType:'payment-undo'}])assert.equal(makeRecord(event({after})).action,'cancel');assert.equal(makeRecord(event({after:{recordType:'correction',correctionType:'sale-reopened'}})).action,'reopen')});
test('no recursive logging, no secrets at any depth, no timestamp-only rows',()=>{assert.equal(makeRecord(event({source:'adminOperationHistory'})),null);assert.equal(makeRecord(event({before:{updatedAtMs:1},after:{updatedAtMs:2}})),null);const result=clean({password:'SECRET',pinHash:'SECRET',salt:'SECRET',nested:{token:'SECRET',name:'Ali'}});assert.deepEqual(result,{nested:{name:'Ali'}});assert.ok(SOURCES.adminInternalConsumptions)});
test('huge documents fit under Firestore limit and truncation is explicit',()=>{const r=makeRecord(event({before:null,after:{items:Array.from({length:1000},(_,i)=>({id:i,description:'x'.repeat(5000)}))}}));assert.ok(Buffer.byteLength(JSON.stringify(r))<1000000);assert.ok(JSON.stringify(r).includes('Büyük kayıt')||r.truncated)});
test('capture retry is idempotent and never mutates business data',async()=>{const f=fixture();f.db.data.set('adminCashMovements/cash-1',{amount:100});const e={id:'evt',params:{source:'adminCashMovements',recordId:'cash-1'},time:'2026-10-02T10:00:00Z',authId:'owner',authType:'unknown',data:{before:{exists:true,data:()=>({amount:200})},after:{exists:true,data:()=>({amount:100})}}};await f.api.capture(e);await f.api.capture(e);assert.equal([...f.db.data.keys()].filter(k=>k.startsWith('adminOperationHistory/')).length,1);assert.deepEqual(f.db.data.get('adminCashMovements/cash-1'),{amount:100});assert.equal(f.db.data.get('adminOperationHistory/'+eventKey('evt')).before.amount,200)});
test('owner and server PIN are required; lock, expiry and PIN change revoke access',async()=>{const f=fixture(),range={start:'2026-10-02',end:'2026-10-02'};await assert.rejects(f.call('read',range,null),{code:'unauthenticated'});await assert.rejects(f.call('unlock',{pin:'123456'},'staff'),{code:'permission-denied'});await assert.rejects(f.call('read',range),{code:'permission-denied'});await f.call('unlock',{pin:'123456'});assert.equal((await f.call('read',range)).records.length,0);f.db.data.get('adminHistorySessions/owner').expiresAtMs=f.time;await assert.rejects(f.call('read',range),{code:'permission-denied'});await f.call('unlock',{pin:'123456'});f.db.data.get('adminSecurity/sensitiveAccess').updatedAtMs=2;await assert.rejects(f.call('read',range),{code:'permission-denied'});await f.call('unlock',{pin:'123456'});await f.call('lock');await assert.rejects(f.call('read',range),{code:'permission-denied'})});
test('five wrong PINs persist despite rejection; concurrent calls cannot bypass counter',async()=>{const f=fixture();await Promise.all(Array.from({length:5},()=>assert.rejects(f.call('unlock',{pin:'999999'}))));assert.equal(f.db.data.get('adminHistoryAttempts/owner').lockedUntilMs,f.time+300000);await assert.rejects(f.call('unlock',{pin:'123456'}),{code:'resource-exhausted'})});
test('same-timestamp pagination has no duplicates, filters and Istanbul dates work',async()=>{const f=fixture();await f.call('unlock',{pin:'123456'});for(let i=0;i<205;i++)f.db.data.set('adminOperationHistory/'+eventKey('e'+i),{eventAtMs:f.time,section:'Stok',action:'delete',actorName:'Ali',title:'Elmalı soda',recordId:String(i),before:{amount:1},after:null,changes:[]});f.db.data.set('adminOperationHistory/'+eventKey('outside'),{eventAtMs:Date.parse('2026-10-01T20:59:59Z'),section:'Stok'});const range={start:'2026-10-02',end:'2026-10-02',section:'Stok',search:'ELMALI',actor:'ali',action:'delete'};const a=await f.call('read',range),b=await f.call('read',{...range,cursor:a.cursor});assert.equal(a.records.length,200);assert.equal(b.records.length,5);assert.equal(new Set([...a.records,...b.records].map(r=>r.id)).size,205);assert.equal(b.cursor,null);assert.ok(!('before'in a.records[0]));assert.ok((await f.call('read',{id:a.records[0].id})).record.before);await assert.rejects(f.call('read',{id:'../private'}),{code:'invalid-argument'})});
test('history collections excluded from broad owner permissions; receipts tied to deletion',()=>{const rules=fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8'),fallback=rules.slice(rules.lastIndexOf('match /{collection}/'));for(const name of['adminOperationHistory','adminHistorySessions','adminHistoryAttempts','adminCancellationEvents'])assert.ok(fallback.includes("'"+name+"'"));assert.ok(rules.includes('!existsAfter('));});
test('cancellation receipt shows source order before and cancelled status',async()=>{const f=fixture();await f.api.capture({id:'cancel-event',time:'2026-10-02T10:00:00Z',params:{source:'adminCancellationEvents',recordId:'receipt'},authId:'owner',authType:'unknown',data:{before:{exists:false},after:{exists:true,data:()=>({action:'cancel',orderId:'order-1',title:'Masa 1',before:{items:[{name:'Çay',quantity:2}],status:'open'}})}}});const r=f.db.data.get('adminOperationHistory/'+eventKey('cancel-event'));assert.equal(r.action,'cancel');assert.equal(r.before.items[0].quantity,2);assert.equal(r.sourcePath,'adminOrders/order-1')});
test('actual adisyon cancellation atomically writes receipt and deletion; fresh paid order blocks both',async()=>{const vm=require('node:vm'),source=fs.readFileSync(path.join(__dirname,'../../adisyon/script.js'),'utf8'),code=source.match(/async function confirmCancelOrder\(\)\{[^\n]+/)[0];for(const paid of [0,20]){const writes=[],messages=[],fresh={title:'Masa 2',payments:paid?[{amount:paid}]:[],items:[{name:'Çay',quantity:2}],status:'open'};const context={isPersonnel:false,selectedKey:'table-2',orderFor:()=>({id:'order-2',payments:[]}),orderPaid:o=>(o.payments||[]).reduce((sum,p)=>sum+p.amount,0),el:{cancelDialog:{close(){}}},show:v=>messages.push(v),showTables(){},console:{error(){}},doc:(col,id)=>({path:col+'/'+(id||'new')}),collection:(db,col)=>col,ordersCol:'adminOrders',db:{},businessDate:'2026-10-02',auth:{currentUser:{uid:'owner'}},serverTimestamp:()=>123,runTransaction:async(db,fn)=>{const pending=[];await fn({get:async()=>({exists:()=>true,data:()=>fresh}),set:(r,d)=>pending.push(['set',r,d]),delete:r=>pending.push(['delete',r])});writes.push(...pending)}};vm.createContext(context);await vm.runInContext(code+';confirmCancelOrder()',context);if(paid)assert.equal(writes.length,0);else{assert.equal(writes.length,2);assert.equal(writes[0][1].path,'adminCancellationEvents/new');assert.equal(writes[0][2].before.items[0].quantity,2);assert.equal(writes[1][1].path,'adminOrders/order-2')}}});
