"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("crypto"),core=require("../savings-core"),{buildSavings}=require("../savings");
class HttpsError extends Error{constructor(code,msg){super(msg);this.code=code}}
class DB{
 constructor(data){this.data=new Map(Object.entries(structuredClone(data)));this.queue=Promise.resolve();this.failure=null}
 doc(path){const db=this;return{path,id:path.split("/").pop(),async set(data){db.data.set(path,structuredClone(data))}}}
 collection(path){const db=this;return{path,limit:n=>({get:async()=>{const docs=[...db.data].filter(([p])=>p.startsWith(path+"/")).slice(0,n);return{size:docs.length}}}),where:(field,op,value)=>({path,field,value,query:true}),query:true}}
 runTransaction(fn){const work=this.queue.then(async()=>{const pending=new Map(this.data);let written=false;const tx={get:async ref=>{assert.equal(written,false,"Transaction must read before writing");if(ref.query){const docs=[...pending].filter(([p,v])=>p.startsWith(ref.path+"/")&&p.split("/").length===ref.path.split("/").length+1&&(!ref.field||v[ref.field]===ref.value)).map(([path,data])=>({id:path.split("/").pop(),exists:true,data:()=>structuredClone(data)}));return{docs,size:docs.length}}const data=pending.get(ref.path);return{exists:data!==undefined,data:()=>data===undefined?undefined:structuredClone(data)}}};const write=(ref,data,create,merge)=>{written=true;if(create&&pending.has(ref.path))throw Error("Duplicate");if(merge&&!pending.has(ref.path))throw Error("Missing update");if(this.failure===ref.path)throw Error("Injected write error");pending.set(ref.path,merge?{...pending.get(ref.path),...structuredClone(data)}:structuredClone(data))};tx.set=(r,d)=>write(r,d,false,false);tx.create=(r,d)=>write(r,d,true,false);tx.update=(r,d)=>write(r,d,false,true);const result=await fn(tx);this.data=pending;return result});this.queue=work.catch(()=>{});return work}
}
const VALID_PIN=String(crypto.randomInt(100000,999999)),WRONG_PIN=String(Number(VALID_PIN)===999998?100001:Number(VALID_PIN)+1);
const now=Date.parse("2026-10-02T10:00:00+03:00"),hash=(p,s)=>crypto.scryptSync(p,s,64).toString("hex");
function fixture(){const db=new DB({"adminSecurity/sensitiveAccess":{salt:"test-salt",pinHash:hash(VALID_PIN,"test-salt"),updatedAtMs:1},"adminCashSettings/config":{financeV3Configured:true,financeV3StartDate:"2026-08-13",financeV3OpeningCash:10000,financeV3OpeningBank:5000,financeV3OpeningCard:3000},"adminFinanceDays/2026-10-01":{locked:true}}),api=buildSavings({db,FieldValue:{serverTimestamp:()=>"test-timestamp"},HttpsError,ownerUid:"test-owner",now:()=>now,pinHash:hash,safeHashEqual:(a,b)=>a===b});const call=(method,data={},uid="test-owner")=>api[method]({auth:uid?{uid}:null,data});return{db,api,call}}
const account=(key="account-0001",kind="currency",name="Dolar")=>({action:"create",clientKey:key,businessDate:"2026-10-02",name,kind,symbol:kind==="equity"?"THYAO":"USD",unit:"pay"});
const move=(key="movement-001",extra={})=>({action:"create",clientKey:key,businessDate:"2026-10-02",accountId:"account-0001",direction:"invest",tlAccount:"cash",quantity:"100",amount:"3000",rate:"30",description:"Test yatırımı",...extra});
async function ready(){const f=fixture();await f.call("unlock",{pin:VALID_PIN});await f.call("account",account());return f}
function snapshot(db){return JSON.stringify([...db.data].sort())}
test("scaled decimals and TL half-up rounding use exact integer arithmetic",()=>{assert.equal(core.scaled("0,1234",4),1234);assert.equal(core.tlFor(1234,4,30000000),370);assert.equal(core.tlFor(100,4,500000),1);assert.equal(core.decimal(1234,4),"0.1234");for(const v of ["0","-1","NaN","1.12345","1e5","9000000000000000"])assert.throws(()=>core.scaled(v,4))});
test("supported account kinds; metals grams and fixed codes; immutable schema cannot take overrides",()=>{for(const kind of ["tl","currency","gold","silver","term"]){const a=core.normalAccount(account("account-0001",kind));assert.equal(a.balanceUnits,0);if(["gold","silver"].includes(kind))assert.equal(a.unit,"gram")}assert.throws(()=>core.normalAccount({...account(),kind:"anything"}));assert.throws(()=>core.normalAccount({...account(),kind:"equity",symbol:"THYAO"}));assert.equal(core.normalAccount({...account(),precision:8,balanceUnits:900}).precision,2)});
test("authentication, owner permission and PIN gate all sensitive APIs",async()=>{const f=fixture();await assert.rejects(f.call("read",{},null),{code:"unauthenticated"});await assert.rejects(f.call("unlock",{pin:VALID_PIN},"staff"),{code:"permission-denied"});for(const m of ["read","account","movement"])await assert.rejects(f.call(m,m==="account"?account():move()),{code:"permission-denied"});await f.call("unlock",{pin:VALID_PIN});assert.ok((await f.call("read")).accessUntilMs>now);await f.call("lockSession");await assert.rejects(f.call("read"),{code:"permission-denied"})});
test("five invalid PIN attempts persist and lock; correct PIN cannot bypass lock",async()=>{const f=fixture();for(let i=1;i<=5;i++)await assert.rejects(f.call("unlock",{pin:WRONG_PIN}),{code:i===5?"resource-exhausted":"permission-denied"});await assert.rejects(f.call("unlock",{pin:VALID_PIN}),{code:"resource-exhausted"});assert.equal(f.db.data.get("sensitivePinAttempts/test-owner").lockedUntilMs,now+300000)});
test("PIN session expiry and PIN version changes revoke access",async()=>{const f=await ready();f.db.data.get("adminSavingsSessions/test-owner").expiresAtMs=now;await assert.rejects(f.call("read"),{code:"permission-denied"});await f.call("unlock",{pin:VALID_PIN});f.db.data.get("adminSecurity/sensitiveAccess").updatedAtMs=2;await assert.rejects(f.call("read"),{code:"permission-denied"})});
test("duplicate account names and IDs rejected; multiple accounts of same kind allowed",async()=>{const f=await ready();await assert.rejects(f.call("account",account("account-0002")),{code:"already-exists"});await f.call("account",account("account-0002","currency","İkinci dolar"));assert.equal((await f.call("read")).accounts.length,2);assert.deepEqual(await f.call("account",account()),{accountId:"account-0001"})});
test("investment atomically links source, asset ledger and cash projection; replay creates no duplicate",async()=>{const f=await ready();await f.call("movement",move());const before=snapshot(f.db);const repeat=await f.call("movement",move());assert.equal(repeat.alreadyApplied,true);assert.equal(snapshot(f.db),before);const a=f.db.data.get("adminSavingsAccounts/account-0001");assert.equal(a.balanceUnits,10000);assert.equal(a.costCents,300000);for(const path of ["adminSavingsOperations/movement-001","adminSavingsLedger/movement-001-tl","adminSavingsLedger/movement-001-asset","adminCashMovements/savings-movement-001","adminSavingsAudit/movement-movement-001"])assert.equal(f.db.data.get(path).transactionId,"movement-001");await assert.rejects(f.call("movement",move("movement-001",{quantity:"50"})),{code:"already-exists"})});
test("investment can use POS balance while redemption remains limited to cash or bank",async()=>{const f=await ready();await f.call("movement",move("pos-invest-001",{tlAccount:"card",quantity:"50",amount:"1500"}));assert.equal(f.db.data.get("adminCashMovements/savings-pos-invest-001").fromAccount,"card");await assert.rejects(f.call("movement",move("pos-redeem-001",{direction:"redeem",tlAccount:"card",quantity:"10",amount:"300"})),{code:"invalid-argument"})});
test("invalid amounts, precision, rate, target and insufficient TL balance cause zero writes",async()=>{const f=await ready();for(const override of [{quantity:"0"},{quantity:"-1"},{quantity:"1.001"},{amount:"0"},{amount:"-30"},{amount:"30.0000001"},{tlAccount:"creditCard"},{tlAccount:"savings"},{quantity:"1000",amount:"20000"},{direction:"other"}]){const before=snapshot(f.db);await assert.rejects(f.call("movement",move("invalid-0001",override)));assert.equal(snapshot(f.db),before)}});
test("redemption uses saved transaction TL value, reduces cost proportionally, supports bank",async()=>{const f=await ready();await f.call("movement",move());await f.call("movement",move("redemption-001",{direction:"redeem",quantity:"25",amount:"1000",rate:"40",tlAccount:"bank"}));const a=f.db.data.get("adminSavingsAccounts/account-0001");assert.equal(a.balanceUnits,7500);assert.equal(a.costCents,225000);const projection=f.db.data.get("adminCashMovements/savings-redemption-001");assert.equal(projection.toAccount,"bank");assert.equal(projection.amountCents,100000);const before=snapshot(f.db);await assert.rejects(f.call("movement",move("redemption-002",{direction:"redeem",quantity:"1000",amount:"30000"})));assert.equal(snapshot(f.db),before)});
test("closed accounts retain history and nonzero balance; new operations rejected; reopening works",async()=>{const f=await ready();await f.call("movement",move());await f.call("account",{action:"close",accountId:"account-0001",clientKey:"close-0001",businessDate:"2026-10-02"});assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,10000);await assert.rejects(f.call("movement",move("blocked-001")),{code:"failed-precondition"});await f.call("account",{action:"reopen",accountId:"account-0001",clientKey:"reopen-001",businessDate:"2026-10-02"});await f.call("movement",move("new-move-001",{quantity:"1",amount:"30"}));await assert.rejects(f.call("account",{action:"delete",accountId:"account-0001",clientKey:"delete-001",businessDate:"2026-10-02"}),{code:"invalid-argument"})});
test("valuation changes leave historical rates and TL values unchanged; account type update rejected",async()=>{const f=await ready();await f.call("movement",move());const before=structuredClone(f.db.data.get("adminSavingsOperations/movement-001"));await f.call("account",{action:"rate",accountId:"account-0001",rate:"40",clientKey:"rate-0001",businessDate:"2026-10-02"});assert.deepEqual(f.db.data.get("adminSavingsOperations/movement-001"),before);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").valuationRateMicros,40000000);await assert.rejects(f.call("account",{action:"update",kind:"gold",accountId:"account-0001",clientKey:"update-001",businessDate:"2026-10-02"}),{code:"invalid-argument"})});
test("edit reverses old pair, retains original record and audit, then replaces atomically",async()=>{const f=await ready();await f.call("movement",move());await f.call("movement",move("edit-move-001",{action:"edit",operationId:"movement-001",quantity:"50",amount:"1500"}));assert.equal(f.db.data.get("adminSavingsOperations/movement-001").status,"superseded");assert.equal(f.db.data.get("adminCashMovements/savings-movement-001").reversed,true);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,5000);assert.equal(f.db.data.get("adminSavingsOperations/edit-move-001").replacementOf,"movement-001");const audit=f.db.data.get("adminSavingsAudit/movement-edit-move-001");assert.equal(audit.actor,"test-owner");assert.equal(audit.before.operation.quantityUnits,10000);assert.equal(audit.after.operation.quantityUnits,5000);assert.ok(f.db.data.has("adminSavingsLedger/edit-move-001-reverse-tl"))});
test("cancel retains original and balances reconcile; insufficient remaining units reject reversal",async()=>{const f=await ready();await f.call("movement",move());await f.call("movement",{action:"cancel",operationId:"movement-001",clientKey:"cancel-001",businessDate:"2026-10-02"});assert.equal(f.db.data.get("adminSavingsOperations/movement-001").status,"cancelled");assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,0);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").costCents,0);const g=await ready();await g.call("movement",move());await g.call("movement",move("redeem-0001",{direction:"redeem",quantity:"50",amount:"1500"}));const before=snapshot(g.db);await assert.rejects(g.call("movement",{action:"cancel",operationId:"movement-001",clientKey:"cancel-001",businessDate:"2026-10-02"}));assert.equal(snapshot(g.db),before)});
test("reversal of redemption rejected if its target TL balance has since been spent",async()=>{const f=await ready();await f.call("movement",move());await f.call("movement",move("redeem-0001",{direction:"redeem",quantity:"50",amount:"1500",tlAccount:"bank"}));f.db.data.set("adminCashMovements/legacy-expense",{type:"expense",account:"bank",amount:6500,businessDate:"2026-10-02"});const before=snapshot(f.db);await assert.rejects(f.call("movement",{action:"cancel",operationId:"redeem-0001",clientKey:"cancel-001",businessDate:"2026-10-02"}),{code:"failed-precondition"});assert.equal(snapshot(f.db),before)});
test("injected failure at source, target, audit or reversal leaves absolutely no writes",async()=>{for(const path of ["adminCashMovements/savings-movement-001","adminSavingsAccounts/account-0001","adminSavingsLedger/movement-001-asset","adminSavingsAudit/movement-movement-001"]){const f=await ready();f.db.failure=path;const before=snapshot(f.db);await assert.rejects(f.call("movement",move()),{code:"internal"});assert.equal(snapshot(f.db),before)}const f=await ready();await f.call("movement",move());f.db.failure="adminSavingsLedger/cancel-001-reverse-asset";const before=snapshot(f.db);await assert.rejects(f.call("movement",{action:"cancel",operationId:"movement-001",clientKey:"cancel-001",businessDate:"2026-10-02"}));assert.equal(snapshot(f.db),before)});
test("simultaneous investment requests cannot overdraw within serialized transaction model",async()=>{const f=await ready();const results=await Promise.allSettled([f.call("movement",move("parallel-001",{quantity:"200",amount:"6000"})),f.call("movement",move("parallel-002",{quantity:"200",amount:"6000"}))]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,20000)});
test("closed date rejects new, edit, cancel and account management; idempotent replay remains safe",async()=>{const f=await ready();await f.call("movement",move());f.db.data.set("adminFinanceDays/2026-10-02",{locked:true});for(const data of [move("new-move-001"),move("edit-move-001",{action:"edit",operationId:"movement-001"}),{action:"cancel",operationId:"movement-001",clientKey:"cancel-001",businessDate:"2026-10-02"}])await assert.rejects(f.call("movement",data),{code:"failed-precondition"});assert.equal((await f.call("movement",move())).alreadyApplied,true);await assert.rejects(f.call("account",account("other-account","gold","Altın")),{code:"failed-precondition"});await assert.rejects(f.call("movement",move("old-date-001",{businessDate:"2026-10-01"})),{code:"failed-precondition"})});
test("backup includes ledger/audit/cash projections but excludes PIN and sessions",async()=>{const f=await ready();await f.call("movement",move());const backup=await f.call("read",{backup:true});assert.equal(backup.collections.adminSavingsLedger.length,2);assert.equal(backup.cashProjections.length,1);assert.ok(!JSON.stringify(backup).includes("pinHash"));assert.ok(!backup.collections.adminSavingsSessions)});
test("legacy cash rules preserved: current cash income waits for closing, bank income is available",()=>{const s={financeV3Configured:true,financeV3StartDate:"2026-08-13",financeV3OpeningCash:100,financeV3OpeningBank:200,financeV3OpeningCard:300},m=[{type:"income",account:"cash",amount:50,businessDate:"2026-10-02"},{type:"income",account:"bank",amount:60,businessDate:"2026-10-02"},{type:"transfer",fromAccount:"cash",toAccount:"savings",amount:20,businessDate:"2026-10-02"},{type:"transfer",fromAccount:"savings",toAccount:"bank",amount:30,businessDate:"2026-10-02",reversed:true}];assert.deepEqual(core.cashBalances(s,m,[],[{id:"2026-10-01",locked:true}],"2026-10-02"),{cash:8000,bank:26000,card:30000});assert.deepEqual(core.cashBalances(s,m,[],[],"2026-10-02"),{cash:-2000,bank:6000,card:0})});
test("invest and redeem all supported account kinds with their correct fixed units",async()=>{for(const kind of ["tl","currency","gold","silver","term"]){const f=fixture();await f.call("unlock",{pin:VALID_PIN});await f.call("account",account("account-0001",kind,"Tür testi"));const quantity=["tl","term","currency"].includes(kind)?"10.25":"0.1234",rate=["tl","term"].includes(kind)?"1":"30.123456",amount=["tl","term"].includes(kind)?quantity:"3.71";await f.call("movement",move("type-invest-001",{quantity,rate,amount}));const a=f.db.data.get("adminSavingsAccounts/account-0001");assert.equal(a.balanceUnits,core.scaled(quantity,a.precision));await f.call("movement",move("type-redeem-001",{direction:"redeem",tlAccount:"bank",quantity,rate,amount}));assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,0);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").costCents,0)}});
test("simultaneous duplicate sends create exactly one source-target pair",async()=>{const f=await ready();const results=await Promise.all([f.call("movement",move()),f.call("movement",move())]);assert.equal(results.filter(x=>x.alreadyApplied).length,1);assert.equal([...f.db.data].filter(([p])=>p.startsWith("adminSavingsLedger/")).length,2);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,10000)});
test("simultaneous redemptions cannot create a negative asset balance in transaction model",async()=>{const f=await ready();await f.call("movement",move());const results=await Promise.allSettled([f.call("movement",move("redeem-par-001",{direction:"redeem",quantity:"75",amount:"2250"})),f.call("movement",move("redeem-par-002",{direction:"redeem",quantity:"75",amount:"2250"}))]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal(f.db.data.get("adminSavingsAccounts/account-0001").balanceUnits,2500)});
test("new savings cash projection stores only integer cents; legacy adapter reconciles exact TL",async()=>{const f=await ready();await f.call("movement",move("fractional-001",{quantity:"1.23",amount:"37.05",rate:"30.123456"}));const p=f.db.data.get("adminCashMovements/savings-fractional-001");assert.equal(p.amount,undefined);assert.equal(p.amountCents,3705);const read=await f.call("read",{backup:true});const balance=core.cashBalances(f.db.data.get("adminCashSettings/config"),read.cashProjections,[],[{id:"2026-10-01",locked:true}],"2026-10-02");assert.equal(balance.cash,1000000-3705)});
test("actual Kasa dayTotals excludes savings flows from income and expenses",()=>{const fs=require("fs"),path=require("path"),vm=require("vm"),source=fs.readFileSync(path.join(__dirname,"../../kasa-hesap-yonetimi/script.js"),"utf8"),fn=source.split("\n").find(l=>l.startsWith("function dayTotals("));const context=vm.createContext({});vm.runInContext('function number(v){return Number(v)||0}\n'+fn,context);const baseline=[{type:"income",account:"cash",amount:100},{type:"expense",account:"bank",amount:20}],base=context.dayTotals(baseline),withSavings=context.dayTotals([...baseline,{type:"transfer",source:"savings",fromAccount:"cash",toAccount:"savings",amount:300},{type:"transfer",source:"savings",fromAccount:"savings",toAccount:"bank",amount:400}]);for(const field of ["income","expense","cashIncome","bankIncome","cardIncome","cashExpense","bankExpense","cardExpense"])assert.equal(withSavings[field],base[field])});

test("savings status reveals only existence to owner and leaves legacy empty backup path usable",async()=>{const f=fixture();assert.deepEqual(await f.call("status"),{hasSavings:false});await assert.rejects(f.call("status",{},"staff"),{code:"permission-denied"});await f.call("unlock",{pin:VALID_PIN});await f.call("account",account());assert.deepEqual(await f.call("status"),{hasSavings:true})});
