import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";import{getFirestore,doc,setDoc,getDoc,collection,getDocs,query,orderBy,limit}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";import{firebaseConfig}from"../assets/js/firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id);const screens=["nameScreen","readyScreen","playScreen","resultScreen","scoresScreen"];let nickname=localStorage.getItem("fceGameNickname")||"",deviceId=localStorage.getItem("fceGameDeviceId")||crypto.randomUUID(),soundOn=localStorage.getItem("fceGameSound")!=="off",raf=0,startAt=0,duration=0,level=0,previousScreen="readyScreen",scoreBoard="daily",audioCtx;
localStorage.setItem("fceGameDeviceId",deviceId);const banned=["amk","aq","sik","orospu","piç","pic","yarrak","amına","amina","göt","got","ibne"];
function show(id){screens.forEach(x=>$(x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}function cleanName(value){return value.replace(/\s+/g," ").trim().slice(0,18)}function validName(value){const low=value.toLocaleLowerCase("tr-TR");return value.length>=2&&!banned.some(x=>low.includes(x))&&/[a-zA-ZçğıöşüÇĞİÖŞÜ0-9]/.test(value)}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function toast(text){$("toast").textContent=text;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2300)}function tone(freq=520,seconds=.08,type="sine",gain=.06){if(!soundOn)return;audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+seconds);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+seconds)}function syncSound(){$("soundButton").innerHTML=`<i class="fa-solid fa-volume-${soundOn?"high":"xmark"}"></i>`}syncSound();
function ready(){$("playerName").textContent=nickname;show("readyScreen")}if(nickname)ready();else{show("nameScreen");setTimeout(()=>$("nickname").focus(),250)}
$("nameForm").addEventListener("submit",e=>{e.preventDefault();const value=cleanName($("nickname").value);if(!validName(value)){$("nameError").textContent="2–18 karakterlik uygun bir takma ad yazmalısın.";tone(180,.18,"square",.035);return}nickname=value;localStorage.setItem("fceGameNickname",nickname);$("nameError").textContent="";tone(600);ready()});
$("changeName").onclick=()=>{$("nickname").value=nickname;show("nameScreen");setTimeout(()=>$("nickname").select(),200)};$("soundButton").onclick=()=>{soundOn=!soundOn;localStorage.setItem("fceGameSound",soundOn?"on":"off");syncSound();tone(620)};
function begin(){level=0;duration=4300+Math.random()*1900;startAt=performance.now();$("livePlayer").textContent=nickname;$("teaLiquid").style.height="0%";$("teaScene").className="tea-scene realistic-scene";$("teaStream").hidden=false;show("playScreen");tone(420,.08);cancelAnimationFrame(raf);raf=requestAnimationFrame(fill)}function fill(now){const elapsed=now-startAt;level=Math.min(108,elapsed/duration*108);$("teaLiquid").style.height=`${Math.min(level,100)}%`;$("timer").textContent=(elapsed/1000).toFixed(1);if(level>100)$("teaScene").classList.add("is-overflow");if(level<108)raf=requestAnimationFrame(fill);else finish()}
function finish(){cancelAnimationFrame(raf);$("teaScene").classList.add("is-stopped");const center=78,dist=Math.abs(level-center);let score=Math.max(0,Math.round(100-dist*4.25));if(level>100)score=Math.max(0,Math.round(42-(level-100)*5));let title,badge,msg,label;if(level<68){title="Biraz açık olmuş";badge="Çay Çırağı";msg="Biraz daha sabredersen çayın tam kıvamını yakalayacaksın.";label="ERKEN DURDURDUN"}else if(level<=88){title=score>=95?"Usta işi çay!":"Kıvama çok yakın!";badge=score>=95?"Dem Ustası":"Çay Uzmanı";msg=score>=95?"Tam kıvamında, rengi yerinde. Bu iş sende!":"İdeal seviyeye çok yaklaştın, bir tur daha dene.";label="GÜZEL DEM"}else if(level<=100){title="Biraz fazla doldu";badge="Cesur Çaycı";msg="Az daha geç kalsan çay taşıyordu. Biraz daha erken durdur.";label="GEÇ DURDURDUN"}else{title="Çay taştı!";badge="Taşıran Çaycı";msg="Tabağa kadar doldu. Bu kez Durdur'a biraz daha erken bas.";label="EYVAH!"}tone(score>=90?760:score>=55?420:180,.2,score>=90?"sine":"square",.05);setTimeout(()=>{setResult(score,title,badge,msg,label);saveScore(score)},430)}
function setResult(score,title,badge,msg,label){$("scoreValue").textContent=score;$("resultTitle").textContent=title;$("resultBadge").textContent=bannerSafe(badge);$("resultMessage").textContent=msg;$("resultLabel").textContent=label;show("resultScreen")}
function bannerSafe(x){return x}
function getLocalScore(){try{return JSON.parse(localStorage.getItem("fceGameLocalScore")||"null")}catch{return null}}
function saveLocalScore(score){const old=getLocalScore(),date=today(),best=Math.max(score,Number(old?.bestScore||0)),dailyBest=old?.scoreDate===date?Math.max(score,Number(old?.dailyBest||0)):score,data={deviceId,nickname,bestScore:best,dailyBest,scoreDate:date,gamesPlayed:Number(old?.gamesPlayed||0)+1,updatedAtMs:Date.now()};localStorage.setItem("fceGameLocalScore",JSON.stringify(data));return data}
async function saveScore(score){const local=saveLocalScore(score);if(score===local.bestScore&&score>0)toast("Skorun kaydedildi!");try{const ref=doc(db,"publicGameScores",deviceId),old=await getDoc(ref).catch(()=>null),remote=old?.exists()?old.data():null,best=Math.max(local.bestScore,Number(remote?.bestScore||0)),dailyBest=remote?.scoreDate===today()?Math.max(local.dailyBest,Number(remote?.dailyBest||0)):local.dailyBest;await setDoc(ref,{deviceId,nickname,bestScore:best,dailyBest,scoreDate:today(),gamesPlayed:Number(remote?.gamesPlayed||0)+1,updatedAtMs:Date.now()})}catch(e){console.warn("Çevrimiçi skor kaydı yapılamadı; cihaz kaydı kullanılıyor.",e)}}
$("startButton").onclick=begin;$("stopButton").onclick=()=>{if($("playScreen").hidden)return;finish()};$("playAgain").onclick=begin;
function openScores(from){previousScreen=from;show("scoresScreen");loadScores()}$("showScores").onclick=()=>openScores("readyScreen");$("showScoresFromName").onclick=()=>openScores("nameScreen");$("resultScores").onclick=()=>openScores("resultScreen");$("closeScores").onclick=()=>show(previousScreen);document.querySelectorAll("[data-board]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("[data-board]").forEach(x=>x.classList.toggle("active",x===btn));scoreBoard=btn.dataset.board;loadScores()});
function renderScores(rows){const unique=new Map;rows.forEach(x=>{const current=unique.get(x.id);if(!current||x.score>current.score)unique.set(x.id,x)});const sorted=[...unique.values()].filter(x=>x.score>=0).sort((a,b)=>b.score-a.score).slice(0,10);$("scoreList").innerHTML="";sorted.forEach((x,i)=>{const li=document.createElement("li");if(x.id===deviceId)li.classList.add("is-me");const rank=document.createElement("span"),player=document.createElement("span"),points=document.createElement("span");rank.className="rank";player.className="player";points.className="points";rank.textContent=i+1;player.textContent=x.name+(x.id===deviceId?" (Sen)":"");points.textContent=`${x.score} puan`;li.append(rank,player,points);$("scoreList").append(li)});$("scoreEmpty").textContent="Henüz kaydedilmiş skor yok. İlk çay ustası sen ol!";$("scoreEmpty").hidden=sorted.length>0}
async function loadScores(){$("scoreLoading").hidden=false;$("scoreEmpty").hidden=true;$("scoreList").innerHTML="";const rows=[],local=getLocalScore();if(local&&(scoreBoard!=="daily"||local.scoreDate===today()))rows.push({name:local.nickname||nickname||"Çay Ustası",score:Number(scoreBoard==="daily"?local.dailyBest:local.bestScore)||0,id:deviceId});try{const snap=await getDocs(query(collection(db,"publicGameScores"),orderBy(scoreBoard==="daily"?"updatedAtMs":"bestScore","desc"),limit(scoreBoard==="daily"?200:50)));snap.forEach(d=>{const x=d.data();if(scoreBoard==="daily"&&x.scoreDate!==today())return;rows.push({name:x.nickname||"Çay Ustası",score:Number(scoreBoard==="daily"?x.dailyBest:x.bestScore)||0,id:x.deviceId})})}catch(e){console.warn("Ortak skor tablosu yüklenemedi; cihaz skoru gösteriliyor.",e)}finally{renderScores(rows);$("scoreLoading").hidden=true}}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&!$("playScreen").hidden){cancelAnimationFrame(raf);show("readyScreen");toast("Oyun durduruldu; yeniden başlayabilirsin.")}});
