import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,getFirestore,onSnapshot,orderBy,query}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{ADMIN_UID,firebaseConfig}from"../assets/js/firebase-config.js";
import{PERMISSION_DEFINITIONS,normalizePhone,profileHasPermission}from"../assets/js/admin-access.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),functions=getFunctions(app,"europe-west1"),$=id=>document.getElementById(id);
const api={create:httpsCallable(functions,"createStaffUser"),update:httpsCallable(functions,"updateStaffUser"),remove:httpsCallable(functions,"deleteStaffUser"),owner:httpsCallable(functions,"configureOwnerLogin"),setPin:httpsCallable(functions,"setSensitivePin"),clearDevices:httpsCallable(functions,"clearLoginDevices")};
let users=[],pendingDelete="",pendingDeviceReset=null,toastTimer;
$("permissionGrid").innerHTML=PERMISSION_DEFINITIONS.map(x=>`<label class="${x.kind==="action"?"permission-action":""}"><input type="checkbox" name="permission" value="${x.id}"><i class="fa-solid ${x.icon}"></i><span>${x.name}</span></label>`).join("");
$("permissionGrid").onchange=e=>{const input=e.target.closest('input[name="permission"]');if(!input)return;const pos=document.querySelector('input[name="permission"][value="pos"]'),transfer=document.querySelector('input[name="permission"][value="currentAccountTransfer"]');if(input.value==="currentAccountTransfer"&&input.checked)pos.checked=true;if(input.value==="pos"&&!input.checked)transfer.checked=false};
onAuthStateChanged(auth,user=>{if(!user||user.uid!==ADMIN_UID){location.replace("../yonetici-giris.html?next=kullanici-yonetimi/");return}onSnapshot(query(collection(db,"staffUsers"),orderBy("displayName")),snap=>{users=snap.docs.map(d=>({uid:d.id,...d.data()})).filter(x=>x.uid!==ADMIN_UID);render()})});
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("newUserButton").onclick=()=>openUser();
$("closeUserDialog").onclick=()=>$("userDialog").close();
$("closeOwnerDialog").onclick=()=>$("ownerDialog").close();
$("closePinDialog").onclick=()=>$("pinDialog").close();
$("ownerSetupButton").onclick=()=>{$("ownerForm").reset();message("ownerMessage","");$("ownerDialog").showModal()};
$("ownerPinButton").onclick=()=>{$("pinForm").reset();message("pinMessage","");$("pinDialog").showModal()};
$("ownerDevicesButton").onclick=()=>openDeviceReset(ADMIN_UID,"Ana yönetici",$("ownerDevicesButton"));
$("searchInput").oninput=render;
$("userList").onclick=e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]"),devices=e.target.closest("[data-clear-devices]");if(edit)openUser(users.find(x=>x.uid===edit.dataset.edit));if(devices){const user=users.find(x=>x.uid===devices.dataset.clearDevices);openDeviceReset(devices.dataset.clearDevices,user?.displayName||"Bu kullanıcı",devices)}if(del){const user=users.find(x=>x.uid===del.dataset.delete);pendingDelete=user.uid;$("deleteText").textContent=`${user.displayName} adlı kullanıcının girişi kalıcı olarak silinecek.`;$("deleteDialog").showModal()}};
$("confirmDeviceReset").onclick=clearSelectedDevices;
$("deviceResetDialog").addEventListener("close",()=>{if($("deviceResetDialog").returnValue!=="confirm")pendingDeviceReset=null});
function openDeviceReset(uid,name,sourceButton){pendingDeviceReset={uid,name,sourceButton};$("deviceResetName").textContent=name;$("deviceResetDialog").showModal()}
async function clearSelectedDevices(){if(!pendingDeviceReset)return;const{uid,name,sourceButton}=pendingDeviceReset,confirmButton=$("confirmDeviceReset"),oldHtml=sourceButton?.innerHTML||"";confirmButton.disabled=true;confirmButton.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Temizleniyor';if(sourceButton){sourceButton.disabled=true;sourceButton.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Temizleniyor'}try{const result=await api.clearDevices({uid});if(result.data?.verified!==true)throw new Error("Sunucu temizliği doğrulanamadı.");$("deviceResetDialog").close("confirm");const count=Number(result.data?.cleared)||0;toast(count?`${name}: ${count} cihaz kaydı silindi. Yeniden giriş yapılabilir.`:`${name} için cihaz listesi zaten boştu. Yeniden giriş yapılabilir.`)}catch(error){console.error(error);toast(error?.message||"Cihazlar kaldırılamadı.")}finally{confirmButton.disabled=false;confirmButton.innerHTML='<i class="fa-solid fa-mobile-screen-button"></i> Cihazları Sıfırla';if(sourceButton){sourceButton.disabled=false;sourceButton.innerHTML=oldHtml}pendingDeviceReset=null}}
$("deleteDialog").addEventListener("close",async()=>{if($("deleteDialog").returnValue!=="confirm"||!pendingDelete)return;try{await api.remove({uid:pendingDelete});toast("Kullanıcı silindi.")}catch(error){console.error(error);toast(callableMessage(error))}finally{pendingDelete=""}});
$("userForm").onsubmit=async e=>{e.preventDefault();const uid=$("editingUid").value,permissions=[...document.querySelectorAll('input[name="permission"]:checked')].map(x=>x.value),phone=normalizePhone($("phone").value),password=$("password").value,deviceLimit=Math.min(10,Math.max(1,Math.floor(Number($("deviceLimit").value)||1)));if(!phone)return message("userMessage","Geçerli bir telefon numarası girin.");if(!permissions.length)return message("userMessage","En az bir panel yetkisi seçin.");if(!uid&&password.length<8)return message("userMessage","Şifre en az 8 karakter olmalı.");setBusy(true);try{const data={uid,displayName:$("displayName").value.trim(),phone,password,permissions,deviceLimit,active:$("active").checked};await(uid?api.update(data):api.create(data));$("userDialog").close();toast(uid?"Kullanıcı güncellendi.":"Yeni kullanıcı oluşturuldu.")}catch(error){console.error(error);message("userMessage",callableMessage(error))}finally{setBusy(false)}};
$("ownerForm").onsubmit=async e=>{e.preventDefault();const phone=normalizePhone($("ownerPhone").value),password=$("ownerPassword").value;if(!phone)return message("ownerMessage","Geçerli bir telefon numarası girin.");if(password.length<8)return message("ownerMessage","Şifre en az 8 karakter olmalı.");if(password!==$("ownerPasswordAgain").value)return message("ownerMessage","Yazdığınız şifreler aynı değil.");e.submitter.disabled=true;try{await api.owner({phone,password});$("ownerDialog").close();toast("Telefon girişin etkinleştirildi. Sonraki girişte telefonunu kullanabilirsin.")}catch(error){console.error(error);message("ownerMessage",callableMessage(error))}finally{e.submitter.disabled=false}};
$("pinForm").onsubmit=async e=>{e.preventDefault();const currentPin=$("currentPin").value.trim(),newPin=$("newPin").value.trim();if(!/^\d{4,6}$/.test(newPin))return message("pinMessage","Yeni PIN 4–6 rakam olmalı.");if(newPin!==$("newPinAgain").value.trim())return message("pinMessage","Yeni PIN'ler aynı değil.");e.submitter.disabled=true;try{await api.setPin({currentPin,newPin});$("pinDialog").close();sessionStorage.removeItem("fatih-sensitive-access-until");toast("Yönetici PIN'i güncellendi.")}catch(error){console.error(error);message("pinMessage",String(error.code||"").includes("permission-denied")?"Mevcut PIN yanlış.":callableMessage(error))}finally{e.submitter.disabled=false}};
function openUser(user=null){const f=$("userForm");f.reset();$("editingUid").value=user?.uid||"";$("userDialogTitle").textContent=user?"Kullanıcıyı Düzenle":"Yeni Kullanıcı Oluştur";$("displayName").value=user?.displayName||"";$("phone").value=user?.phone||"";$("deviceLimit").value=user?.deviceLimit||1;$("active").checked=user?.active!==false;$("password").required=!user;$("passwordHint").textContent=user?"(değişmeyecekse boş bırakın)":"(en az 8 karakter)";document.querySelectorAll('input[name="permission"]').forEach(x=>x.checked=user?profileHasPermission(user,x.value):false);message("userMessage","");$("userDialog").showModal()}
function render(){const q=$("searchInput").value.trim().toLocaleLowerCase("tr-TR"),shown=users.filter(x=>`${x.displayName} ${x.phone}`.toLocaleLowerCase("tr-TR").includes(q));$("userCount").textContent=users.length;$("activeCount").textContent=users.filter(x=>x.active!==false).length;$("emptyState").hidden=shown.length>0;$("userList").innerHTML=shown.map(x=>`<article class="user-card"><div class="user-head"><span class="avatar"><i class="fa-solid fa-user"></i></span><div class="user-copy"><strong>${esc(x.displayName)}</strong><span>${formatPhone(x.phone)} • ${x.deviceLimit||1} cihaz</span></div><span class="status ${x.active===false?"off":""}">${x.active===false?"Pasif":"Aktif"}</span></div><div class="permission-tags">${PERMISSION_DEFINITIONS.filter(permission=>profileHasPermission(x,permission.id)).map(permission=>`<span>${permission.name}</span>`).join("")}</div><div class="card-actions"><button data-edit="${x.uid}"><i class="fa-solid fa-pen"></i> Düzenle</button><button data-clear-devices="${x.uid}"><i class="fa-solid fa-mobile-screen"></i> Cihazları Sil</button><button class="delete" data-delete="${x.uid}" title="Sil"><i class="fa-solid fa-trash"></i></button></div></article>`).join("")}
function setBusy(v){$("saveUserButton").disabled=v}function message(id,t){$(id).textContent=t}function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}function callableMessage(e){const code=String(e.code||"");if(code.includes("already-exists"))return"Bu telefon numarası zaten kayıtlı.";if(code.includes("permission-denied"))return"Bu işlem yalnızca ana yönetici tarafından yapılabilir.";if(code.includes("invalid-argument"))return"Bilgileri ve şifreyi kontrol edin.";return"İşlem tamamlanamadı. İnternet bağlantısını kontrol edin."}function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML}function formatPhone(v=""){const d=String(v).replace(/\D/g,"").replace(/^90/,"0");return d.length===11?`${d.slice(0,4)} ${d.slice(4,7)} ${d.slice(7,9)} ${d.slice(9)}`:v}function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
