import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";import{doc,getFirestore,onSnapshot,serverTimestamp,setDoc}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";import{getDownloadURL,getStorage,ref,uploadBytes}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js";import{ADMIN_UID,firebaseConfig}from"../firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),configRef=doc(db,"publicSite","config"),$=id=>document.getElementById(id);let config={},timer;
onAuthStateChanged(auth,async user=>{if(!user||user.uid!==ADMIN_UID){if(user)await signOut(auth);location.replace("../yonetici-giris.html?next=ana-sayfa-yonetimi/");return}onSnapshot(configRef,s=>{config=s.data()||{};render()})});$("logout").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("generalForm").onsubmit=async e=>{e.preventDefault();const fields=["businessName","heroTitle","subtitle","slogan","welcomeTitle","welcomeText","instagramUrl","mapsUrl","phone","reviewUrl"],data={};fields.forEach(id=>data[id]=$(id).value.trim());await save(data,"Ana sayfa bilgileri kaydedildi.")};
$("logoForm").onsubmit=async e=>{e.preventDefault();if(!confirm("Yeni logo bütün sistemde kullanılacak. Onaylıyor musunuz?"))return;const url=await upload($("logoFile").files[0],"site/logo");await save({logoUrl:url},"Sistem logosu değiştirildi.")};
$("galleryForm").onsubmit=async e=>{e.preventDefault();const url=await upload($("galleryFile").files[0],"site/gallery");await save({gallery:[...(config.gallery||[]),{id:crypto.randomUUID(),url,alt:$("galleryAlt").value.trim()}]},"Görsel galeriye eklendi.");e.target.reset()};
$("announcementForm").onsubmit=e=>addContent(e,"announcements","announcement");$("campaignForm").onsubmit=e=>addContent(e,"campaigns","campaign");
$("galleryAdmin").onclick=e=>{const b=e.target.closest("[data-gallery-delete]");if(b)save({gallery:(config.gallery||[]).filter(x=>x.id!==b.dataset.galleryDelete)},"Görsel kaldırıldı.")};$("contentAdmin").onclick=e=>{const b=e.target.closest("[data-content-delete]");if(b)save({[b.dataset.type]:(config[b.dataset.type]||[]).filter(x=>x.id!==b.dataset.contentDelete)},"Kayıt kaldırıldı.")};
async function addContent(e,type,prefix){e.preventDefault();const item={id:crypto.randomUUID(),title:$(`${prefix}Title`).value.trim(),text:$(`${prefix}Text`).value.trim(),endDate:$(`${prefix}End`).value,active:true};await save({[type]:[...(config[type]||[]),item]},"İçerik yayınlandı.");e.target.reset()}
async function upload(file,path){if(!file)throw Error("file");const target=ref(storage,`${path}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`);await uploadBytes(target,file);return getDownloadURL(target)}
async function save(data,message){try{await setDoc(configRef,{...data,updatedAt:serverTimestamp()},{merge:true});toast(message)}catch(e){console.error(e);toast("İşlem kaydedilemedi.")}}
function render(){["businessName","heroTitle","subtitle","slogan","welcomeTitle","welcomeText","instagramUrl","mapsUrl","phone","reviewUrl"].forEach(id=>$(id).value=config[id]||"");if(config.logoUrl)$("logoPreview").src=config.logoUrl;$("galleryAdmin").innerHTML=(config.gallery||[]).map(x=>`<article><img src="${x.url}" alt=""><button data-gallery-delete="${x.id}">×</button></article>`).join("");$("contentAdmin").innerHTML=[...(config.announcements||[]).map(x=>({...x,type:"announcements"})),...(config.campaigns||[]).map(x=>({...x,type:"campaigns"}))].map(x=>`<article class="content-item"><div><strong>${x.title}</strong><small> • ${x.type==="announcements"?"Duyuru":"Kampanya"}</small><p>${x.text}</p></div><button data-content-delete="${x.id}" data-type="${x.type}">Sil</button></article>`).join("");$("status").textContent="Güncel"}
function toast(t){clearTimeout(timer);$("toast").textContent=t;$("toast").classList.add("show");timer=setTimeout(()=>$("toast").classList.remove("show"),2500)}
