import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{hasPanelAccess}from"../assets/js/admin-access.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const stocksCol=collection(db,"adminStockItems"),ordersCol=collection(db,"adminPurchaseOrders"),movesCol=collection(db,"adminStockMovements"),menuRef=doc(db,"publicMenu","catalog");
const el={saveStatus:$("saveStatus"),stockEmpty:$("stockEmpty"),categoryLists:$("categoryLists"),selectedCount:$("selectedCount"),selectedUnits:$("selectedUnits"),createOrderButton:$("createOrderButton"),historyEmpty:$("historyEmpty"),historyList:$("historyList"),orderSummaryDialog:$("orderSummaryDialog"),summaryTitle:$("summaryTitle"),summaryMeta:$("summaryMeta"),summaryTable:$("summaryTable"),summaryPdfButton:$("summaryPdfButton"),saveOrderButton:$("saveOrderButton"),confirmOrderDialog:$("confirmOrderDialog"),historyDialog:$("historyDialog"),historyTitle:$("historyTitle"),historyMeta:$("historyMeta"),historyDetail:$("historyDetail"),historyPdfButton:$("historyPdfButton"),receiveOrderButton:$("receiveOrderButton"),receiveDialog:$("receiveDialog"),receiveTable:$("receiveTable"),saveReceiptButton:$("saveReceiptButton"),confirmReceiptDialog:$("confirmReceiptDialog"),confirmReceiptText:$("confirmReceiptText"),logoutButton:$("logoutButton"),toast:$("toast")};
let stocks=[],orders=[],catalog={categories:[],items:[]},draft=[],activeOrderId="",toastTimer,busy=false;

el.categoryLists.oninput=e=>{if(e.target.matches("[data-target]"))updateDraftTotals()};
el.createOrderButton.onclick=openDraftSummary;el.saveOrderButton.onclick=()=>{el.confirmOrderDialog.returnValue="cancel";el.confirmOrderDialog.showModal()};
el.confirmOrderDialog.addEventListener("close",()=>{if(el.confirmOrderDialog.returnValue==="confirm")saveOrder()});
el.summaryPdfButton.onclick=()=>printOrder(draft,"Yeni Sipariş Listesi",new Date());
el.historyList.onclick=e=>{const card=e.target.closest("[data-order]");if(card)openHistory(card.dataset.order)};
el.historyPdfButton.onclick=()=>{const order=getActiveOrder();if(order)printOrder(order.items,orderNumber(order),order.createdAt?.toDate?.()||new Date(order.createdAtMs||Date.now()),order)};
el.receiveOrderButton.onclick=openReceive;el.saveReceiptButton.onclick=prepareReceipt;
el.confirmReceiptDialog.addEventListener("close",()=>{if(el.confirmReceiptDialog.returnValue==="confirm")saveReceipt()});
document.addEventListener("click",e=>{const close=e.target.closest("[data-close]");if(close)$(close.dataset.close).close();const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});
el.logoutButton.onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};tick();setInterval(tick,1000);

onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=siparis-listesi/");return}if(!await hasPanelAccess(user,db,"stock")){location.replace("../yonetici-giris.html");return}subscribe()});
function subscribe(){onSnapshot(stocksCol,s=>{stocks=s.docs.map(d=>normalizeStock(d.id,d.data())).filter(x=>x.active);connected();renderStocks()},fail);onSnapshot(menuRef,s=>{const d=s.data()||{};catalog={categories:Array.isArray(d.categories)?d.categories:[],items:Array.isArray(d.items)?d.items:[]};renderStocks()},fail);onSnapshot(query(ordersCol,orderBy("createdAtMs","desc"),limit(100)),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderHistory()},fail)}
function connected(){el.saveStatus.innerHTML='<i class="fa-solid fa-circle-check"></i> Canlı bağlantı';el.saveStatus.classList.remove("is-error")}
function fail(error){console.error(error);el.saveStatus.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';el.saveStatus.classList.add("is-error");show("Sipariş verileri alınamadı.")}
function normalizeStock(id,d){return{id,name:String(d.name||"Stok ürünü"),quantity:Math.max(0,num(d.quantity)),warningThreshold:Math.max(0,num(d.warningThreshold)),unit:String(d.unit||"adet"),linkedMenuItemId:String(d.linkedMenuItemId||""),active:d.active!==false}}
function categoryOf(stock){const menu=catalog.items.find(x=>x.id===stock.linkedMenuItemId),category=catalog.categories.find(x=>x.id===menu?.categoryId);return category?{id:category.id,name:category.name,order:num(category.order)}:{id:"diger",name:"Diğer Stok Ürünleri",order:999}}
function stockRank(x){return x.quantity<=0?0:x.quantity<=x.warningThreshold?1:2}
function renderStocks(){if(!stocks.length){el.categoryLists.innerHTML="";el.stockEmpty.hidden=false;updateDraftTotals();return}el.stockEmpty.hidden=true;const groups=new Map;stocks.forEach(stock=>{const cat=categoryOf(stock);if(!groups.has(cat.id))groups.set(cat.id,{...cat,items:[]});groups.get(cat.id).items.push(stock)});el.categoryLists.innerHTML=[...groups.values()].sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name,"tr")).map(group=>`<section class="category-block"><div class="category-title"><i class="fa-solid ${group.id.includes("sicak")?"fa-mug-hot":group.id.includes("soguk")?"fa-bottle-water":group.id.includes("atistir")?"fa-cookie-bite":"fa-box"}"></i><strong>${esc(group.name)}</strong><span>${group.items.length} ürün</span></div>${group.items.sort((a,b)=>stockRank(a)-stockRank(b)||a.name.localeCompare(b.name,"tr")).map(productRow).join("")}</section>`).join("");updateDraftTotals()}
function productRow(x){const state=x.quantity<=0?"is-empty":x.quantity<=x.warningThreshold?"is-critical":"is-ok";return`<div class="product-row order-grid ${state}"><div class="product-name"><span class="stock-dot"></span><span>${esc(x.name)}</span></div><span class="stock-value">${format(x.quantity)}</span><input class="target-input" data-target="${x.id}" type="number" min="0" max="999999" step="1" inputmode="numeric" aria-label="${esc(x.name)} hedef stok"><span class="order-amount" data-amount="${x.id}">0</span></div>`}
function collectDraft(){return stocks.map(stock=>{const target=Math.max(0,Math.floor(num(document.querySelector(`[data-target="${cssEscape(stock.id)}"]`)?.value))),ordered=Math.max(0,target-stock.quantity);return{stockItemId:stock.id,name:stock.name,category:categoryOf(stock).name,currentStock:stock.quantity,targetStock:target,orderedQuantity:ordered,receivedQuantity:0,unit:stock.unit}}).filter(x=>x.orderedQuantity>0)}
function updateDraftTotals(){draft=collectDraft();stocks.forEach(stock=>{const row=draft.find(x=>x.stockItemId===stock.id),node=document.querySelector(`[data-amount="${cssEscape(stock.id)}"]`);if(node){node.textContent=format(row?.orderedQuantity||0);node.classList.toggle("has-order",!!row)}});el.selectedCount.textContent=draft.length;el.selectedUnits.textContent=`${format(draft.reduce((s,x)=>s+x.orderedQuantity,0))} Adet`;el.createOrderButton.disabled=!draft.length}
function openDraftSummary(){draft=collectDraft();if(!draft.length)return show("Sipariş verilecek en az bir ürün belirleyin.");el.summaryTitle.textContent="Yeni Sipariş Listesi";el.summaryMeta.innerHTML=`<span>${draft.length} ürün</span><span>${format(draft.reduce((s,x)=>s+x.orderedQuantity,0))} Adet</span>`;el.summaryTable.innerHTML=summaryRows(draft,false);el.orderSummaryDialog.showModal()}
function summaryRows(items,history){return`<div class="summary-row is-head"><span>Ürün</span><b>Sipariş</b><b>Gelen</b><b>Kalan</b></div>`+items.map(x=>{const received=num(x.receivedQuantity),remaining=Math.max(0,num(x.orderedQuantity)-received);return`<div class="summary-row"><span>${esc(x.name)}</span><b>${format(x.orderedQuantity)}</b><b class="received">${history?format(received):"—"}</b><b class="remaining">${history?format(remaining):"—"}</b></div>`}).join("")}
async function saveOrder(){if(busy||!draft.length)return;busy=true;el.saveOrderButton.disabled=true;try{const ref=doc(ordersCol),now=Date.now();await setDoc(ref,{items:draft,status:"pending",totalProducts:draft.length,totalOrdered:draft.reduce((s,x)=>s+x.orderedQuantity,0),totalReceived:0,createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid,updatedAt:serverTimestamp()});activeOrderId=ref.id;el.orderSummaryDialog.close();clearTargets();show("Sipariş listesi geçmiş siparişlere kaydedildi.");setTimeout(()=>openHistory(ref.id),250)}catch(error){console.error(error);show("Sipariş listesi kaydedilemedi.")}finally{busy=false;el.saveOrderButton.disabled=false}}
function clearTargets(){document.querySelectorAll("[data-target]").forEach(x=>x.value="");updateDraftTotals()}
function renderHistory(){el.historyEmpty.hidden=orders.length>0;el.historyList.innerHTML=orders.map(order=>{const status=orderStatus(order),date=order.createdAt?.toDate?.()||new Date(order.createdAtMs||Date.now());return`<article class="history-card" data-order="${order.id}"><span class="history-icon"><i class="fa-solid fa-clipboard-list"></i></span><div class="history-copy"><strong>${orderNumber(order)}</strong><small>${dateTime(date)} • ${num(order.totalProducts)||order.items?.length||0} ürün • ${format(order.totalOrdered)} Adet</small></div><span class="status-badge ${status.className}">${status.label}</span></article>`}).join("")}
function orderStatus(order){const ordered=num(order.totalOrdered)||order.items?.reduce((s,x)=>s+num(x.orderedQuantity),0)||0,received=num(order.totalReceived)||order.items?.reduce((s,x)=>s+num(x.receivedQuantity),0)||0;if(received>=ordered&&ordered>0)return{label:"Tamamlandı",className:"complete"};if(received>0)return{label:"Eksik Geldi",className:""};return{label:"Gelmedi",className:"none"}}
function orderNumber(order){const d=order.createdAt?.toDate?.()||new Date(order.createdAtMs||Date.now());return`Sipariş • ${d.toLocaleDateString("tr-TR")}`}
function openHistory(id){const order=orders.find(x=>x.id===id);if(!order)return show("Sipariş kaydı yükleniyor, tekrar deneyin.");activeOrderId=id;const status=orderStatus(order),date=order.createdAt?.toDate?.()||new Date(order.createdAtMs||Date.now());el.historyTitle.textContent=orderNumber(order);el.historyMeta.innerHTML=`<span>${dateTime(date)}</span><span>${order.items.length} ürün</span><span>${status.label}</span>`;el.historyDetail.innerHTML=summaryRows(order.items,true);el.receiveOrderButton.hidden=status.className==="complete";el.historyDialog.showModal()}
function getActiveOrder(){return orders.find(x=>x.id===activeOrderId)}
function openReceive(){const order=getActiveOrder();if(!order)return;const pending=order.items.filter(x=>num(x.receivedQuantity)<num(x.orderedQuantity));if(!pending.length)return show("Bu siparişin tamamı teslim alınmış.");el.receiveTable.innerHTML=pending.map(x=>{const remaining=Math.max(0,num(x.orderedQuantity)-num(x.receivedQuantity));return`<label class="receive-row"><span><strong>${esc(x.name)}</strong><small>Kalan: ${format(remaining)} ${esc(x.unit||"adet")}</small></span><b>${format(remaining)}</b><input data-receive="${esc(x.stockItemId)}" type="number" min="0" max="${remaining}" step="1" inputmode="numeric" placeholder="Gelen"></label>`}).join("");el.historyDialog.close();el.receiveDialog.showModal();setTimeout(()=>el.receiveTable.querySelector("input")?.focus(),80)}
function receiptEntries(){const order=getActiveOrder();if(!order)return[];return[...el.receiveTable.querySelectorAll("[data-receive]")].map(input=>{const item=order.items.find(x=>x.stockItemId===input.dataset.receive),remaining=Math.max(0,num(item?.orderedQuantity)-num(item?.receivedQuantity)),amount=Math.min(remaining,Math.max(0,Math.floor(num(input.value))));return{item,amount}}).filter(x=>x.item&&x.amount>0)}
function prepareReceipt(){const entries=receiptEntries();if(!entries.length)return show("Bu teslimatta gelen ürün adetlerini yazın.");el.confirmReceiptText.textContent=`${entries.length} ürün için toplam ${format(entries.reduce((s,x)=>s+x.amount,0))} Adet stoka eklenecek.`;el.confirmReceiptDialog.returnValue="cancel";el.confirmReceiptDialog.showModal()}
async function saveReceipt(){const order=getActiveOrder(),entries=receiptEntries();if(!order||!entries.length||busy)return;busy=true;el.saveReceiptButton.disabled=true;try{const orderRef=doc(ordersCol,order.id),now=Date.now();await runTransaction(db,async tx=>{const orderSnap=await tx.get(orderRef);if(!orderSnap.exists())throw new Error("missing-order");const fresh=orderSnap.data(),freshItems=Array.isArray(fresh.items)?fresh.items.map(x=>({...x})):[];for(const entry of entries){const freshLine=freshItems.find(x=>x.stockItemId===entry.item.stockItemId),stockRef=doc(stocksCol,entry.item.stockItemId),stockSnap=await tx.get(stockRef);if(!freshLine||!stockSnap.exists())throw new Error("missing-stock");const remaining=Math.max(0,num(freshLine.orderedQuantity)-num(freshLine.receivedQuantity)),amount=Math.min(remaining,entry.amount),stockData=stockSnap.data(),previous=Math.max(0,num(stockData.quantity)),result=previous+amount,moveRef=doc(movesCol);if(amount<=0)continue;freshLine.receivedQuantity=num(freshLine.receivedQuantity)+amount;tx.update(stockRef,{quantity:result,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:entry.item.stockItemId,linkedMenuItemId:String(stockData.linkedMenuItemId||""),stockName:String(stockData.name||entry.item.name),type:"in",amount,enteredAmount:amount,enteredUnit:"adet",previousQuantity:previous,resultingQuantity:result,unit:String(stockData.unit||"adet"),operationDate:today(),note:`${orderNumber(order)} teslimatı`,purchaseOrderId:order.id,createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})}const totalOrdered=freshItems.reduce((s,x)=>s+num(x.orderedQuantity),0),totalReceived=freshItems.reduce((s,x)=>s+num(x.receivedQuantity),0);tx.update(orderRef,{items:freshItems,totalReceived,status:totalReceived>=totalOrdered?"completed":"partial",lastReceivedAtMs:now,lastReceivedAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid})});el.confirmReceiptDialog.close();el.receiveDialog.close();show("Gelen ürünler stoka eklendi ve sipariş güncellendi.");setTimeout(()=>openHistory(order.id),350)}catch(error){console.error(error);show("Teslimat ve stok kaydı tamamlanamadı.")}finally{busy=false;el.saveReceiptButton.disabled=false}}
async function saveReceipt(){const order=getActiveOrder(),entries=receiptEntries();if(!order||!entries.length||busy)return;busy=true;el.saveReceiptButton.disabled=true;try{const orderRef=doc(ordersCol,order.id),now=Date.now();await runTransaction(db,async tx=>{const orderSnap=await tx.get(orderRef),stockRefs=entries.map(entry=>doc(stocksCol,entry.item.stockItemId)),stockSnaps=[];for(const stockRef of stockRefs)stockSnaps.push(await tx.get(stockRef));if(!orderSnap.exists())throw new Error("missing-order");const fresh=orderSnap.data(),freshItems=Array.isArray(fresh.items)?fresh.items.map(x=>({...x})):[];entries.forEach((entry,index)=>{const freshLine=freshItems.find(x=>x.stockItemId===entry.item.stockItemId),stockRef=stockRefs[index],stockSnap=stockSnaps[index];if(!freshLine||!stockSnap.exists())throw new Error("missing-stock");const remaining=Math.max(0,num(freshLine.orderedQuantity)-num(freshLine.receivedQuantity)),amount=Math.min(remaining,entry.amount),stockData=stockSnap.data(),previous=Math.max(0,num(stockData.quantity)),result=previous+amount,moveRef=doc(movesCol);if(amount<=0)return;freshLine.receivedQuantity=num(freshLine.receivedQuantity)+amount;tx.update(stockRef,{quantity:result,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:entry.item.stockItemId,linkedMenuItemId:String(stockData.linkedMenuItemId||""),stockName:String(stockData.name||entry.item.name),type:"in",amount,enteredAmount:amount,enteredUnit:"adet",previousQuantity:previous,resultingQuantity:result,unit:String(stockData.unit||"adet"),operationDate:today(),note:`${orderNumber(order)} teslimatı`,purchaseOrderId:order.id,createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});const totalOrdered=freshItems.reduce((s,x)=>s+num(x.orderedQuantity),0),totalReceived=freshItems.reduce((s,x)=>s+num(x.receivedQuantity),0);tx.update(orderRef,{items:freshItems,totalReceived,status:totalReceived>=totalOrdered?"completed":"partial",lastReceivedAtMs:now,lastReceivedAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid})});el.confirmReceiptDialog.close();el.receiveDialog.close();show("Gelen ürünler stoka eklendi ve sipariş güncellendi.");setTimeout(()=>openHistory(order.id),350)}catch(error){console.error(error);show("Teslimat ve stok kaydı tamamlanamadı.")}finally{busy=false;el.saveReceiptButton.disabled=false}}
function printOrder(items,title,date,order=null){if(!items?.length)return;const popup=window.open("","_blank","width=1000,height=760");if(!popup)return show("PDF penceresi açılamadı. Açılır pencereye izin verin.");const logo=new URL("../assets/images/logo.png",location.href).href,history=!!order;popup.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#342522;font:12px Arial}.watermark{position:fixed;inset:20% 15%;width:70%;height:60%;object-fit:contain;opacity:.045;z-index:-1}.head{display:flex;justify-content:space-between;border-bottom:3px solid #7d1b24;padding-bottom:12px}.brand img{width:88px}.brand p,.date p{margin:2px 0}.date{text-align:right}.title{text-align:center;color:#7d1b24;margin:22px 0 14px}table{width:100%;border-collapse:collapse}th{color:#fff;background:#7d1b24}th,td{padding:9px;border:1px solid #d8c6ba;text-align:left}tbody tr:nth-child(even){background:#fff7ef}.totals{width:48%;margin:16px 0 0 auto;padding:10px;border:1px solid #d8c6ba;background:#fff2e2}</style></head><body><img class="watermark" src="${logo}"><header class="head"><div class="brand"><img src="${logo}"><p><b>Fatih Ali Altınlı</b></p><p>0554 118 08 06</p><p>Ulukavak Mah. Osmancık Cad. No:285<br>Çorum/Merkez</p></div><div class="date"><b>Sipariş Tarihi</b><p>${dateTime(date)}</p><b>Oluşturma Tarihi</b><p>${dateTime(new Date())}</p></div></header><h1 class="title">${esc(title)}</h1><table><thead><tr><th>Ürün</th><th>Mevcut Stok</th><th>Hedef Stok</th><th>Sipariş</th>${history?"<th>Gelen</th><th>Gelmeyen</th>":""}</tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.name)}</td><td>${format(x.currentStock)}</td><td>${format(x.targetStock)}</td><td>${format(x.orderedQuantity)}</td>${history?`<td>${format(x.receivedQuantity)}</td><td>${format(Math.max(0,num(x.orderedQuantity)-num(x.receivedQuantity)))}</td>`:""}</tr>`).join("")}</tbody></table><div class="totals"><b>Toplam: ${format(items.reduce((s,x)=>s+num(x.orderedQuantity),0))} Adet</b></div><script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`);popup.document.close()}
function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}
function today(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Istanbul"}).format(new Date)}function dateTime(d){return new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(d)}function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function format(v){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(num(v))}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function cssEscape(v){return globalThis.CSS?.escape?CSS.escape(v):String(v).replace(/[^a-zA-Z0-9_-]/g,"\\$&")}function show(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),2800)}
