import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{hasPanelAccess}from"../assets/js/admin-access.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const stocksCol=collection(db,"adminStockItems"),movesCol=collection(db,"adminStockMovements"),cashMovesCol=collection(db,"adminCashMovements"),menuRef=doc(db,"publicMenu","catalog");
const el={itemCount:$("itemCount"),totalUnits:$("totalUnits"),criticalCount:$("criticalCount"),emptyCount:$("emptyCount"),saveStatus:$("saveStatus"),stockSearch:$("stockSearch"),stockEmpty:$("stockEmpty"),stockList:$("stockList"),movementEmpty:$("movementEmpty"),movementList:$("movementList"),manageProductsButton:$("manageProductsButton"),productsDialog:$("productsDialog"),productForm:$("productForm"),menuProduct:$("menuProduct"),defaultUnitsPerPackage:$("defaultUnitsPerPackage"),warningThreshold:$("warningThreshold"),definedProducts:$("definedProducts"),entryDialog:$("entryDialog"),entryForm:$("entryForm"),entryTitle:$("entryTitle"),entryStockId:$("entryStockId"),packageCount:$("packageCount"),entryUnitsPerPackage:$("entryUnitsPerPackage"),purchaseTotal:$("purchaseTotal"),addCashExpense:$("addCashExpense"),cashExpenseAccountLabel:$("cashExpenseAccountLabel"),cashExpenseAccount:$("cashExpenseAccount"),entryDate:$("entryDate"),entryNote:$("entryNote"),costPreview:$("costPreview"),adjustDialog:$("adjustDialog"),adjustForm:$("adjustForm"),adjustTitle:$("adjustTitle"),adjustStockId:$("adjustStockId"),adjustAmount:$("adjustAmount"),adjustAmountLabel:$("adjustAmountLabel"),adjustDate:$("adjustDate"),adjustNote:$("adjustNote"),adjustPreview:$("adjustPreview"),logoutButton:$("logoutButton"),toast:$("toast")};
let stocks=[],movements=[],catalog={categories:[],items:[]},busy=false,toastTimer;

el.manageProductsButton.onclick=()=>{renderProductManager();el.productsDialog.showModal()};
el.productForm.onsubmit=addTrackedProduct;
el.definedProducts.onclick=e=>{const button=e.target.closest("[data-archive]");if(button)archiveProduct(button.dataset.archive)};
el.stockList.onclick=e=>{const entry=e.target.closest("[data-entry]"),adjust=e.target.closest("[data-adjust]");if(entry)openEntry(entry.dataset.entry);if(adjust)openAdjust(adjust.dataset.adjust)};
el.stockSearch.oninput=renderStocks;
el.entryForm.oninput=renderCostPreview;
el.addCashExpense.onchange=()=>{el.cashExpenseAccountLabel.hidden=!el.addCashExpense.checked};
el.entryForm.onsubmit=saveEntry;
el.adjustForm.oninput=renderAdjustPreview;
el.adjustForm.onsubmit=saveAdjustment;
document.addEventListener("click",e=>{const close=e.target.closest("[data-close]");if(close)$(close.dataset.close).close();const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});
el.logoutButton.onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
updateClock();setInterval(updateClock,1000);

onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=stok-yonetimi/");return}if(!await hasPanelAccess(user,db,"stock")){location.replace("../yonetici-giris.html");return}subscribe()});
function subscribe(){
  onSnapshot(stocksCol,s=>{stocks=s.docs.map(d=>normalizeStock(d.id,d.data()));connected();renderAll()},fail);
  onSnapshot(query(movesCol,orderBy("createdAt","desc"),limit(80)),s=>{movements=s.docs.map(d=>({id:d.id,...d.data()}));renderMovements()},fail);
  onSnapshot(menuRef,s=>{const d=s.data()||{};catalog={categories:Array.isArray(d.categories)?d.categories:[],items:Array.isArray(d.items)?d.items:[]};renderProductManager()},fail);
}
function connected(){el.saveStatus.innerHTML='<i class="fa-solid fa-circle-check"></i> Canlı bağlantı';el.saveStatus.classList.remove("is-error")}
function fail(error){console.error(error);el.saveStatus.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';el.saveStatus.classList.add("is-error");show("Stok verileri alınamadı.")}

function renderAll(){const active=stocks.filter(x=>x.active);el.itemCount.textContent=active.length;el.totalUnits.textContent=formatNumber(active.reduce((sum,x)=>sum+x.quantity,0));el.criticalCount.textContent=active.filter(x=>x.quantity>0&&x.quantity<=x.warningThreshold).length;el.emptyCount.textContent=active.filter(x=>x.quantity<=0).length;renderStocks();renderProductManager()}
function renderStocks(){const q=el.stockSearch.value.trim().toLocaleLowerCase("tr-TR"),items=stocks.filter(x=>x.active&&x.name.toLocaleLowerCase("tr-TR").includes(q)).sort((a,b)=>a.name.localeCompare(b.name,"tr"));el.stockList.innerHTML=items.map(x=>`<article class="stock-card ${x.quantity<=0?"is-empty":x.quantity<=x.warningThreshold?"is-critical":""}"><div class="stock-main"><div class="stock-title-row"><strong>${esc(x.name)}</strong><span class="status-badge ${x.quantity<=0?"is-empty":x.quantity<=x.warningThreshold?"is-critical":"is-ok"}">${x.quantity<=0?"Tükendi":x.quantity<=x.warningThreshold?"Kritik":"Stokta"}</span></div><div class="stock-quantity-row"><strong>${formatNumber(x.quantity)}</strong><span>${esc(displayUnit(x.unit))}</span></div><div class="stock-cost"><span>1 Koli: ${formatNumber(x.unitsPerPackage)} ${esc(displayUnit(x.unit))}</span>${x.unitCost>0?`<span>Birim maliyet: ${money(x.unitCost)}</span>`:""}${x.lastPurchaseTotal>0?`<span>Son alım: ${money(x.lastPurchaseTotal)}</span>`:""}</div></div><div class="card-actions"><button class="entry-button" data-entry="${x.id}"><i class="fa-solid fa-plus"></i> Stok Ekle</button><button class="icon-button" data-adjust="${x.id}" title="Stok düzelt"><i class="fa-solid fa-pen"></i></button></div></article>`).join("");el.stockEmpty.hidden=items.length>0}
function renderProductManager(){if(!el.menuProduct)return;const activeIds=new Set(stocks.filter(x=>x.active).map(x=>x.linkedMenuItemId)),available=catalog.items.filter(x=>x.available!==false&&!activeIds.has(x.id)).sort((a,b)=>String(a.name).localeCompare(String(b.name),"tr"));el.menuProduct.innerHTML='<option value="">Ürün seçin</option>'+available.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");const defined=stocks.filter(x=>x.active).sort((a,b)=>a.name.localeCompare(b.name,"tr"));el.definedProducts.innerHTML=defined.map(x=>`<div class="defined-product"><div><strong>${esc(x.name)}</strong><small>1 Koli = ${formatNumber(x.unitsPerPackage)} ${esc(displayUnit(x.unit))} • Adisyondan otomatik düşer</small></div><button class="icon-button is-danger" type="button" data-archive="${x.id}" title="Takipten çıkar"><i class="fa-solid fa-trash"></i></button></div>`).join("")}

async function addTrackedProduct(e){e.preventDefault();if(busy)return;const menuItem=catalog.items.find(x=>x.id===el.menuProduct.value);if(!menuItem)return show("Menüden Ürün seçin.");const archived=stocks.find(x=>x.linkedMenuItemId===menuItem.id&&!x.active),data={name:menuItem.name,linkedMenuItemId:menuItem.id,quantity:archived?.quantity||0,unit:"adet",packageMode:true,packageUnit:"koli",unitsPerPackage:Math.max(1,num(el.defaultUnitsPerPackage.value)),warningThreshold:Math.max(0,num(el.warningThreshold.value)),automaticDeduction:true,deductionAmount:1,active:true,updatedAt:serverTimestamp()};busy=true;try{if(archived)await updateDoc(doc(stocksCol,archived.id),data);else await setDoc(doc(stocksCol),{...data,createdAt:serverTimestamp()});el.productForm.reset();el.defaultUnitsPerPackage.value=24;el.warningThreshold.value=10;show("Ürün stok takibine eklendi.")}catch(error){console.error(error);show("Ürün eklenemedi.")}finally{busy=false}}
async function archiveProduct(id){const item=stocks.find(x=>x.id===id);if(!item)return;try{await updateDoc(doc(stocksCol,id),{active:false,automaticDeduction:false,updatedAt:serverTimestamp()});show(`${item.name} stok takibinden çıkarıldı.`)}catch(error){console.error(error);show("Ürün kaldırılamadı.")}}

function openEntry(id){const item=stocks.find(x=>x.id===id);if(!item)return;el.entryStockId.value=id;el.entryTitle.textContent=`${item.name} Stok Girişi`;el.packageCount.value="";el.entryUnitsPerPackage.value=item.unitsPerPackage;el.purchaseTotal.value="";el.addCashExpense.checked=false;el.cashExpenseAccount.value="cash";el.cashExpenseAccountLabel.hidden=true;el.entryDate.value=today();el.entryNote.value="";renderCostPreview();el.entryDialog.showModal()}
function renderCostPreview(){const count=num(el.packageCount.value),perPackage=num(el.entryUnitsPerPackage.value),totalUnits=count*perPackage,totalPaid=num(el.purchaseTotal.value),unitCost=totalUnits>0?totalPaid/totalUnits:0;el.costPreview.innerHTML=`<span>Toplam Adet: <b>${formatNumber(totalUnits)}</b></span><strong>Birim maliyet: ${totalUnits>0?money(unitCost):"—"}</strong>`}
async function saveEntry(e){e.preventDefault();if(busy)return;const item=stocks.find(x=>x.id===el.entryStockId.value),packageCount=num(el.packageCount.value),unitsPerPackage=num(el.entryUnitsPerPackage.value),purchaseTotal=num(el.purchaseTotal.value),amount=packageCount*unitsPerPackage,addExpense=el.addCashExpense.checked;if(!item||packageCount<=0||unitsPerPackage<=0||purchaseTotal<0)return show("Koli, Adet ve tutar bilgilerini kontrol edin.");if(addExpense&&purchaseTotal<=0)return show("Kasaya gider eklemek için ödenen tutarı girin.");busy=true;try{const itemRef=doc(stocksCol,item.id),moveRef=doc(movesCol),cashRef=doc(cashMovesCol),createdAtMs=Date.now();await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error("missing");const fresh=normalizeStock(snap.id,snap.data()),result=fresh.quantity+amount,unitCost=amount>0?purchaseTotal/amount:0;tx.update(itemRef,{quantity:result,unitsPerPackage,lastPurchaseTotal:purchaseTotal,unitCost,purchasePrice:purchaseTotal,purchasePriceBasis:"total",purchaseDate:el.entryDate.value,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:item.id,linkedMenuItemId:item.linkedMenuItemId,stockName:item.name,type:"in",packageCount,unitsPerPackage,amount,enteredAmount:packageCount,enteredUnit:"koli",purchaseTotal,unitCost,previousQuantity:fresh.quantity,resultingQuantity:result,unit:item.unit,operationDate:el.entryDate.value,note:el.entryNote.value.trim(),cashMovementId:addExpense?cashRef.id:"",createdAtMs,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});if(addExpense)tx.set(cashRef,{type:"expense",amount:purchaseTotal,account:el.cashExpenseAccount.value,fromAccount:"",toAccount:"",category:"Toptancı / Ürün Alımı",description:`${item.name} stok alımı`,businessDate:el.entryDate.value,automatic:true,source:"stock-purchase",sourceId:moveRef.id,createdAtMs,updatedAtMs:createdAtMs,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.entryDialog.close();show(addExpense?`${formatNumber(amount)} Adet stoka, alış gideri kasaya eklendi.`:`${formatNumber(amount)} Adet stoka eklendi.`)}catch(error){console.error(error);show("Stok ve kasa kaydı tamamlanamadı.")}finally{busy=false}}

function openAdjust(id){const item=stocks.find(x=>x.id===id);if(!item)return;el.adjustStockId.value=id;el.adjustTitle.textContent=`${item.name} Stok Düzeltme`;el.adjustAmount.value="";el.adjustDate.value=today();el.adjustNote.value="";el.adjustForm.elements.adjustType.value="out";renderAdjustPreview();el.adjustDialog.showModal()}
function renderAdjustPreview(){const item=stocks.find(x=>x.id===el.adjustStockId.value);if(!item)return;const type=el.adjustForm.elements.adjustType.value,amount=num(el.adjustAmount.value),result=type==="out"?item.quantity-amount:amount;el.adjustAmountLabel.textContent=type==="out"?"Düşülecek Adet":"Yeni toplam Adet";el.adjustPreview.textContent=`Mevcut: ${formatNumber(item.quantity)} → Yeni: ${formatNumber(result)}`;el.adjustPreview.style.color=result<0?"#a22a32":""}
async function saveAdjustment(e){e.preventDefault();if(busy)return;const item=stocks.find(x=>x.id===el.adjustStockId.value),type=el.adjustForm.elements.adjustType.value,amount=num(el.adjustAmount.value);if(!item||amount<0)return;busy=true;try{const itemRef=doc(stocksCol,item.id),moveRef=doc(movesCol);await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error("missing");const fresh=normalizeStock(snap.id,snap.data()),result=type==="out"?fresh.quantity-amount:amount;if(result<0)throw new Error("insufficient");tx.update(itemRef,{quantity:result,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:item.id,linkedMenuItemId:item.linkedMenuItemId,stockName:item.name,type,amount,previousQuantity:fresh.quantity,resultingQuantity:result,unit:item.unit,operationDate:el.adjustDate.value,note:el.adjustNote.value.trim(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.adjustDialog.close();show("Stok İşlemi kaydedildi.")}catch(error){console.error(error);show(error.message==="insufficient"?"Stok miktarı sıfırın altına düşemez.":"İşlem kaydedilemedi.")}finally{busy=false}}

function renderMovements(){const items=movements.slice(0,50);el.movementList.innerHTML=items.map(x=>{const incoming=x.type==="in"||x.type==="initial",sign=incoming?"+":x.type==="out"||x.type==="sale"?"−":"=",label=x.type==="in"?"Stok Girişi":x.type==="out"?"Stoktan Düşüm":x.type==="sale"?"Adisyon Satışı":x.type==="initial"?"İlk Stok":"Sayım Düzeltmesi",purchase=num(x.purchaseTotal)||(x.purchasePriceBasis==="total"?num(x.purchasePrice):0);return`<article class="movement-item"><span class="movement-icon ${incoming?"":"out"}"><i class="fa-solid ${incoming?"fa-plus":x.type==="set"?"fa-pen":"fa-minus"}"></i></span><div class="movement-copy"><strong>${esc(x.stockName||"Stok")}</strong><span>${label} • ${formatDate(x.operationDate)}${num(x.packageCount)>0?` • ${formatNumber(x.packageCount)} Koli`:""}${purchase>0?` • ${money(purchase)} Alış`:""}${x.note?` • ${esc(x.note)}`:""}</span></div><div class="movement-amount">${sign}${formatNumber(x.amount)} ${esc(displayUnit(x.unit||""))}<span class="movement-result">Kalan: ${formatNumber(x.resultingQuantity)}</span></div></article>`}).join("");el.movementEmpty.hidden=items.length>0}

function normalizeStock(id,d){const units=Math.max(1,num(d.unitsPerPackage)||1),legacyUnitCost=d.purchasePriceBasis==="package"?num(d.purchasePrice)/units:d.purchasePriceBasis==="unit"?num(d.purchasePrice):0;return{id,name:String(d.name||"Ürün"),linkedMenuItemId:String(d.linkedMenuItemId||""),quantity:num(d.quantity),unit:String(d.unit||"adet"),unitsPerPackage:units,warningThreshold:num(d.warningThreshold),unitCost:num(d.unitCost)||legacyUnitCost,lastPurchaseTotal:num(d.lastPurchaseTotal),active:d.active!==false}}
function timestamp(v){return v?.toMillis?.()||0}function num(v){return Number(v)||0}function displayUnit(v){const value=String(v||"");return value?value.charAt(0).toLocaleUpperCase("tr-TR")+value.slice(1).toLocaleLowerCase("tr-TR"):""}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function formatDate(v){const[y,m,d]=String(v||"").split("-");return y&&m&&d?`${d}.${m}.${y}`:"—"}function formatNumber(v){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(num(v))}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",minimumFractionDigits:num(v)%1?2:0}).format(num(v))}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function updateClock(){const n=new Date();$("currentTime").textContent=new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(n);$("currentDate").textContent=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"Europe/Istanbul"}).format(n).replace(/\./g,"/")}function show(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),3000)}
