import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getDocs,getFirestore,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc,where}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{hasPanelAccess}from"../assets/js/admin-access.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const stocksCol=collection(db,"adminStockItems"),movesCol=collection(db,"adminStockMovements"),cashMovesCol=collection(db,"adminCashMovements"),menuRef=doc(db,"publicMenu","catalog");
const el={itemCount:$("itemCount"),totalUnits:$("totalUnits"),criticalCount:$("criticalCount"),emptyCount:$("emptyCount"),itemStat:$("itemStat"),criticalStat:$("criticalStat"),emptyStat:$("emptyStat"),saveStatus:$("saveStatus"),stockSearch:$("stockSearch"),stockEmpty:$("stockEmpty"),stockList:$("stockList"),movementEmpty:$("movementEmpty"),movementList:$("movementList"),manageProductsButton:$("manageProductsButton"),productsDialog:$("productsDialog"),productForm:$("productForm"),menuProduct:$("menuProduct"),defaultUnitsPerPackage:$("defaultUnitsPerPackage"),warningThreshold:$("warningThreshold"),definedProducts:$("definedProducts"),entryDialog:$("entryDialog"),entryForm:$("entryForm"),entryTitle:$("entryTitle"),entryStockId:$("entryStockId"),packageCount:$("packageCount"),entryUnitsPerPackage:$("entryUnitsPerPackage"),purchaseTotal:$("purchaseTotal"),addCashExpense:$("addCashExpense"),cashExpenseAccountLabel:$("cashExpenseAccountLabel"),cashExpenseAccount:$("cashExpenseAccount"),entryDate:$("entryDate"),entryNote:$("entryNote"),costPreview:$("costPreview"),adjustDialog:$("adjustDialog"),adjustForm:$("adjustForm"),adjustTitle:$("adjustTitle"),adjustStockId:$("adjustStockId"),adjustAmount:$("adjustAmount"),adjustAmountLabel:$("adjustAmountLabel"),adjustDate:$("adjustDate"),adjustNote:$("adjustNote"),adjustPreview:$("adjustPreview"),historyDialog:$("historyDialog"),historyTitle:$("historyTitle"),historySummary:$("historySummary"),historyEmpty:$("historyEmpty"),historyList:$("historyList"),historyEntryButton:$("historyEntryButton"),historyAdjustButton:$("historyAdjustButton"),historyDeleteButton:$("historyDeleteButton"),deleteStockDialog:$("deleteStockDialog"),deleteStockText:$("deleteStockText"),barcodeButton:$("barcodeButton"),barcodeSearchButton:$("barcodeSearchButton"),barcodeDialog:$("barcodeDialog"),barcodeKicker:$("barcodeKicker"),barcodeTitle:$("barcodeTitle"),cameraFrame:$("cameraFrame"),barcodeVideo:$("barcodeVideo"),cameraStatus:$("cameraStatus"),switchCameraButton:$("switchCameraButton"),barcodeInput:$("barcodeInput"),useBarcodeButton:$("useBarcodeButton"),barcodeMatch:$("barcodeMatch"),barcodeMessage:$("barcodeMessage"),barcodeProduct:$("barcodeProduct"),saveBarcodeButton:$("saveBarcodeButton"),logoutButton:$("logoutButton"),toast:$("toast")};
let stocks=[],movements=[],catalog={categories:[],items:[]},userNames=new Map(),busy=false,toastTimer,cameraStream=null,scanFrame=0,pendingBarcode="",barcodeMode="add",cameraFacing="environment",stockFilter="all",historyStockId="",pendingDeleteStockId="";

el.manageProductsButton.onclick=()=>{renderProductManager();el.productsDialog.showModal()};
el.productForm.onsubmit=addTrackedProduct;
el.definedProducts.onclick=e=>{const button=e.target.closest("[data-archive]");if(button)confirmArchiveProduct(button.dataset.archive)};
el.stockList.onclick=e=>{const entry=e.target.closest("[data-entry]"),adjust=e.target.closest("[data-adjust]"),card=e.target.closest("[data-history]");if(entry)return openEntry(entry.dataset.entry);if(adjust)return openAdjust(adjust.dataset.adjust);if(card)openHistory(card.dataset.history)};
el.barcodeButton.onclick=()=>openBarcode("add");
el.barcodeSearchButton.onclick=()=>openBarcode("search");
el.switchCameraButton.onclick=switchCamera;
el.useBarcodeButton.onclick=()=>handleBarcode(el.barcodeInput.value);
el.barcodeInput.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();handleBarcode(el.barcodeInput.value)}};
el.saveBarcodeButton.onclick=saveBarcodeMatch;
el.stockSearch.oninput=renderStocks;
el.itemStat.onclick=()=>setStockFilter("all");
el.criticalStat.onclick=()=>toggleStockFilter("critical");
el.emptyStat.onclick=()=>toggleStockFilter("empty");
[el.itemStat,el.criticalStat,el.emptyStat].forEach(node=>node.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();node.click()}});
el.entryForm.oninput=renderCostPreview;
el.addCashExpense.onchange=()=>{el.cashExpenseAccountLabel.hidden=!el.addCashExpense.checked};
el.entryForm.onsubmit=saveEntry;
el.adjustForm.oninput=renderAdjustPreview;
el.adjustForm.onsubmit=saveAdjustment;
el.historyEntryButton.onclick=()=>{if(historyStockId){el.historyDialog.close();openEntry(historyStockId)}};
el.historyAdjustButton.onclick=()=>{if(historyStockId){el.historyDialog.close();openAdjust(historyStockId)}};
el.historyDeleteButton.onclick=()=>{if(historyStockId)confirmArchiveProduct(historyStockId)};
el.deleteStockDialog.addEventListener("close",()=>{if(el.deleteStockDialog.returnValue==="confirm"&&pendingDeleteStockId)archiveProduct(pendingDeleteStockId);else pendingDeleteStockId=""});
document.addEventListener("click",e=>{const close=e.target.closest("[data-close]");if(close){if(close.dataset.close==="barcodeDialog")stopCamera();$(close.dataset.close).close()}const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});
el.barcodeDialog.addEventListener("close",stopCamera);
el.logoutButton.onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
updateClock();setInterval(updateClock,1000);

onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=stok-yonetimi/");return}if(!await hasPanelAccess(user,db,"stock")){location.replace("../yonetici-giris.html");return}userNames.set(user.uid,"Siz");loadUserNames();subscribe()});
function subscribe(){
  onSnapshot(stocksCol,s=>{stocks=s.docs.map(d=>normalizeStock(d.id,d.data()));connected();renderAll()},fail);
  onSnapshot(query(movesCol,orderBy("createdAt","desc"),limit(80)),s=>{movements=s.docs.map(d=>({id:d.id,...d.data()}));renderMovements()},fail);
  onSnapshot(menuRef,s=>{const d=s.data()||{};catalog={categories:Array.isArray(d.categories)?d.categories:[],items:Array.isArray(d.items)?d.items:[]};renderProductManager()},fail);
}
function connected(){el.saveStatus.innerHTML='<i class="fa-solid fa-circle-check"></i> Canlı bağlantı';el.saveStatus.classList.remove("is-error")}
function fail(error){console.error(error);el.saveStatus.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';el.saveStatus.classList.add("is-error");show("Stok verileri alınamadı.")}

function renderAll(){const active=stocks.filter(x=>x.active);el.itemCount.textContent=active.length;el.totalUnits.textContent=formatNumber(active.reduce((sum,x)=>sum+x.quantity,0));el.criticalCount.textContent=active.filter(x=>x.quantity>0&&x.quantity<=x.warningThreshold).length;el.emptyCount.textContent=active.filter(x=>x.quantity<=0).length;renderStocks();renderProductManager()}
function renderStocks(){const q=el.stockSearch.value.trim().toLocaleLowerCase("tr-TR"),items=stocks.filter(x=>x.active&&x.name.toLocaleLowerCase("tr-TR").includes(q)&&(stockFilter==="empty"?x.quantity<=0:stockFilter==="critical"?x.quantity>0&&x.quantity<=x.warningThreshold:true)).sort((a,b)=>a.name.localeCompare(b.name,"tr"));el.stockList.innerHTML=items.map(x=>`<article class="stock-card ${x.quantity<=0?"is-empty":x.quantity<=x.warningThreshold?"is-critical":""}" data-history="${x.id}" title="Ürün detayını aç"><div class="stock-card-top"><span class="stock-card-icon"><i class="fa-solid fa-box"></i></span><span class="status-badge ${x.quantity<=0?"is-empty":x.quantity<=x.warningThreshold?"is-critical":"is-ok"}">${x.quantity<=0?"Tükendi":x.quantity<=x.warningThreshold?"Kritik":"Stokta"}</span></div><strong class="stock-card-name">${esc(x.name)}</strong><div class="stock-quantity-row"><strong>${formatNumber(x.quantity)}</strong><span>${esc(displayUnit(x.unit))}</span></div><div class="stock-card-meta"><span>1 Koli: ${formatNumber(x.unitsPerPackage)}</span>${x.unitCost>0?`<span>${money(x.unitCost)} / adet</span>`:""}${x.barcode?`<span><i class="fa-solid fa-barcode"></i> Kayıtlı</span>`:""}</div><small class="stock-card-hint">İşlemler için dokun</small></article>`).join("");el.stockEmpty.textContent=stockFilter==="empty"?"Tükenen ürün bulunmuyor.":stockFilter==="critical"?"Kritik seviyede ürün bulunmuyor.":"Henüz stok ürünü tanımlanmadı.";el.stockEmpty.hidden=items.length>0}
function setStockFilter(type){stockFilter=type;el.itemStat.classList.toggle("is-selected",stockFilter==="all");el.criticalStat.classList.toggle("is-selected",stockFilter==="critical");el.emptyStat.classList.toggle("is-selected",stockFilter==="empty");renderStocks();document.querySelector(".list-panel")?.scrollIntoView({behavior:"smooth",block:"start"})}
function toggleStockFilter(type){setStockFilter(stockFilter===type?"all":type)}
function renderProductManager(){if(!el.menuProduct)return;const activeIds=new Set(stocks.filter(x=>x.active).map(x=>x.linkedMenuItemId)),available=catalog.items.filter(x=>x.available!==false&&!activeIds.has(x.id)).sort((a,b)=>String(a.name).localeCompare(String(b.name),"tr"));el.menuProduct.innerHTML='<option value="">Ürün seçin</option>'+available.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");const defined=stocks.filter(x=>x.active).sort((a,b)=>a.name.localeCompare(b.name,"tr"));el.definedProducts.innerHTML=defined.map(x=>`<div class="defined-product"><div><strong>${esc(x.name)}</strong><small>1 Koli = ${formatNumber(x.unitsPerPackage)} ${esc(displayUnit(x.unit))} • Adisyondan otomatik düşer</small></div><button class="icon-button is-danger" type="button" data-archive="${x.id}" title="Takipten çıkar"><i class="fa-solid fa-trash"></i></button></div>`).join("")}

async function addTrackedProduct(e){e.preventDefault();if(busy)return;const menuItem=catalog.items.find(x=>x.id===el.menuProduct.value);if(!menuItem)return show("Menüden Ürün seçin.");const archived=stocks.find(x=>x.linkedMenuItemId===menuItem.id&&!x.active),data={name:menuItem.name,linkedMenuItemId:menuItem.id,quantity:archived?.quantity||0,unit:"adet",packageMode:true,packageUnit:"koli",unitsPerPackage:Math.max(1,num(el.defaultUnitsPerPackage.value)),warningThreshold:Math.max(0,num(el.warningThreshold.value)),automaticDeduction:true,deductionAmount:1,active:true,updatedAt:serverTimestamp()};busy=true;try{if(archived)await updateDoc(doc(stocksCol,archived.id),data);else await setDoc(doc(stocksCol),{...data,createdAt:serverTimestamp()});el.productForm.reset();el.defaultUnitsPerPackage.value=24;el.warningThreshold.value=10;show("Ürün stok takibine eklendi.")}catch(error){console.error(error);show("Ürün eklenemedi.")}finally{busy=false}}
function confirmArchiveProduct(id){const item=stocks.find(x=>x.id===id);if(!item)return;pendingDeleteStockId=id;el.deleteStockText.textContent=`${item.name} stok takibinden kaldırılacak. Kritik, tükenen ve tüm ürünler listelerinde artık görünmeyecek. Geçmiş hareket kayıtları korunacak.`;el.deleteStockDialog.returnValue="cancel";el.deleteStockDialog.showModal()}
async function archiveProduct(id){const item=stocks.find(x=>x.id===id);if(!item)return;pendingDeleteStockId="";try{await updateDoc(doc(stocksCol,id),{active:false,automaticDeduction:false,barcode:"",deletedAt:serverTimestamp(),deletedBy:auth.currentUser.uid,updatedAt:serverTimestamp()});if(el.historyDialog.open)el.historyDialog.close();if(el.productsDialog.open)renderProductManager();setStockFilter("all");show(`${item.name} stok takibinden silindi.`)}catch(error){console.error(error);show("Ürün stok takibinden silinemedi.")}}

function openEntry(id){const item=stocks.find(x=>x.id===id);if(!item)return;el.entryStockId.value=id;el.entryTitle.textContent=`${item.name} Stok Girişi`;el.packageCount.value="";el.entryUnitsPerPackage.value=item.unitsPerPackage;el.purchaseTotal.value="";el.addCashExpense.checked=false;el.cashExpenseAccount.value="cash";el.cashExpenseAccountLabel.hidden=true;el.entryDate.value=today();el.entryNote.value="";renderCostPreview();el.entryDialog.showModal()}
function renderCostPreview(){const count=num(el.packageCount.value),perPackage=num(el.entryUnitsPerPackage.value),totalUnits=count*perPackage,totalPaid=num(el.purchaseTotal.value),unitCost=totalUnits>0?totalPaid/totalUnits:0;el.costPreview.innerHTML=`<span>Toplam Adet: <b>${formatNumber(totalUnits)}</b></span><strong>Birim maliyet: ${totalUnits>0?money(unitCost):"—"}</strong>`}
async function saveEntry(e){e.preventDefault();if(busy)return;const item=stocks.find(x=>x.id===el.entryStockId.value),packageCount=num(el.packageCount.value),unitsPerPackage=num(el.entryUnitsPerPackage.value),purchaseTotal=num(el.purchaseTotal.value),amount=packageCount*unitsPerPackage,addExpense=el.addCashExpense.checked;if(!item||packageCount<=0||unitsPerPackage<=0||purchaseTotal<0)return show("Koli, Adet ve tutar bilgilerini kontrol edin.");if(addExpense&&purchaseTotal<=0)return show("Kasaya gider eklemek için ödenen tutarı girin.");busy=true;try{const itemRef=doc(stocksCol,item.id),moveRef=doc(movesCol),cashRef=doc(cashMovesCol),createdAtMs=Date.now();await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error("missing");const fresh=normalizeStock(snap.id,snap.data()),result=fresh.quantity+amount,unitCost=amount>0?purchaseTotal/amount:0;tx.update(itemRef,{quantity:result,unitsPerPackage,lastPurchaseTotal:purchaseTotal,unitCost,purchasePrice:purchaseTotal,purchasePriceBasis:"total",purchaseDate:el.entryDate.value,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:item.id,linkedMenuItemId:item.linkedMenuItemId,stockName:item.name,type:"in",packageCount,unitsPerPackage,amount,enteredAmount:packageCount,enteredUnit:"koli",purchaseTotal,unitCost,previousQuantity:fresh.quantity,resultingQuantity:result,unit:item.unit,operationDate:el.entryDate.value,note:el.entryNote.value.trim(),cashMovementId:addExpense?cashRef.id:"",createdAtMs,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});if(addExpense)tx.set(cashRef,{type:"expense",amount:purchaseTotal,account:el.cashExpenseAccount.value,fromAccount:"",toAccount:"",category:"Toptancı / Ürün Alımı",description:`${item.name} stok alımı`,businessDate:el.entryDate.value,automatic:true,source:"stock-purchase",sourceId:moveRef.id,createdAtMs,updatedAtMs:createdAtMs,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.entryDialog.close();show(addExpense?`${formatNumber(amount)} Adet stoka, alış gideri kasaya eklendi.`:`${formatNumber(amount)} Adet stoka eklendi.`)}catch(error){console.error(error);show("Stok ve kasa kaydı tamamlanamadı.")}finally{busy=false}}

function openAdjust(id){const item=stocks.find(x=>x.id===id);if(!item)return;el.adjustStockId.value=id;el.adjustTitle.textContent=`${item.name} Stok Düzeltme`;el.adjustAmount.value="";el.adjustDate.value=today();el.adjustNote.value="";el.adjustForm.elements.adjustType.value="out";renderAdjustPreview();el.adjustDialog.showModal()}
function renderAdjustPreview(){const item=stocks.find(x=>x.id===el.adjustStockId.value);if(!item)return;const type=el.adjustForm.elements.adjustType.value,amount=num(el.adjustAmount.value),result=type==="out"?item.quantity-amount:amount;el.adjustAmountLabel.textContent=type==="out"?"Düşülecek Adet":"Yeni toplam Adet";el.adjustPreview.textContent=`Mevcut: ${formatNumber(item.quantity)} → Yeni: ${formatNumber(result)}`;el.adjustPreview.style.color=result<0?"#a22a32":""}
async function saveAdjustment(e){e.preventDefault();if(busy)return;const item=stocks.find(x=>x.id===el.adjustStockId.value),type=el.adjustForm.elements.adjustType.value,amount=num(el.adjustAmount.value);if(!item||amount<0)return;busy=true;try{const itemRef=doc(stocksCol,item.id),moveRef=doc(movesCol);await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error("missing");const fresh=normalizeStock(snap.id,snap.data()),result=type==="out"?fresh.quantity-amount:amount;if(result<0)throw new Error("insufficient");tx.update(itemRef,{quantity:result,updatedAt:serverTimestamp()});tx.set(moveRef,{stockItemId:item.id,linkedMenuItemId:item.linkedMenuItemId,stockName:item.name,type,amount,previousQuantity:fresh.quantity,resultingQuantity:result,unit:item.unit,operationDate:el.adjustDate.value,note:el.adjustNote.value.trim(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.adjustDialog.close();show("Stok İşlemi kaydedildi.")}catch(error){console.error(error);show(error.message==="insufficient"?"Stok miktarı sıfırın altına düşemez.":"İşlem kaydedilemedi.")}finally{busy=false}}

function renderMovements(){const items=movements.slice(0,50);el.movementList.innerHTML=items.map(x=>{const incoming=x.type==="in"||x.type==="initial",sign=incoming?"+":x.type==="out"||x.type==="sale"?"−":"=",label=x.type==="in"?"Stok Girişi":x.type==="out"?"Stoktan Düşüm":x.type==="sale"?"Adisyon Satışı":x.type==="initial"?"İlk Stok":"Sayım Düzeltmesi",purchase=num(x.purchaseTotal)||(x.purchasePriceBasis==="total"?num(x.purchasePrice):0);return`<article class="movement-item"><span class="movement-icon ${incoming?"":"out"}"><i class="fa-solid ${incoming?"fa-plus":x.type==="set"?"fa-pen":"fa-minus"}"></i></span><div class="movement-copy"><strong>${esc(x.stockName||"Stok")}</strong><span>${label} • ${formatDate(x.operationDate)}${num(x.packageCount)>0?` • ${formatNumber(x.packageCount)} Koli`:""}${purchase>0?` • ${money(purchase)} Alış`:""}${x.note?` • ${esc(x.note)}`:""}</span></div><div class="movement-amount">${sign}${formatNumber(x.amount)} ${esc(displayUnit(x.unit||""))}<span class="movement-result">Kalan: ${formatNumber(x.resultingQuantity)}</span></div></article>`}).join("");el.movementEmpty.hidden=items.length>0}

async function openHistory(id){const item=stocks.find(x=>x.id===id);if(!item)return;historyStockId=id;const menuItem=catalog.items.find(x=>x.id===item.linkedMenuItemId),menuPrice=num(menuItem?.price);el.historyTitle.textContent=item.name;el.historySummary.innerHTML=`<span>Mevcut stok<b>${formatNumber(item.quantity)} ${esc(displayUnit(item.unit))}</b></span><span>Alış fiyatı<b>${item.unitCost?`${money(item.unitCost)} / adet`:"—"}</b></span><span>Menü fiyatı<b>${menuPrice?money(menuPrice):"—"}</b></span><span>Son alım<b>${item.lastPurchaseTotal?money(item.lastPurchaseTotal):"—"}</b></span><span>Koli içi<b>${formatNumber(item.unitsPerPackage)} ${esc(displayUnit(item.unit))}</b></span><span>Barkod<b>${esc(item.barcode||"Tanımlı değil")}</b></span>`;el.historyList.innerHTML='<p class="empty-copy"><i class="fa-solid fa-circle-notch fa-spin"></i> Hareketler yükleniyor…</p>';el.historyEmpty.hidden=true;el.historyDialog.showModal();try{const snap=await getDocs(query(movesCol,where("stockItemId","==",id),limit(300))),items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>movementTime(b)-movementTime(a));renderProductHistory(items)}catch(error){console.error(error);el.historyList.innerHTML="";el.historyEmpty.textContent="Stok hareketleri yüklenemedi.";el.historyEmpty.hidden=false}}
function renderProductHistory(items){el.historyEmpty.hidden=items.length>0;el.historyList.innerHTML=items.map(x=>{const incoming=x.type==="in"||x.type==="initial",label=movementLabel(x.type),sign=incoming?"+":x.type==="set"?"=":"−",purchase=num(x.purchaseTotal)||(x.purchasePriceBasis==="total"?num(x.purchasePrice):0),who=userNames.get(x.createdBy)||shortUser(x.createdBy);return`<article class="history-row"><span class="movement-icon ${incoming?"":"out"}"><i class="fa-solid ${incoming?"fa-plus":x.type==="set"?"fa-pen":"fa-minus"}"></i></span><div class="history-copy"><strong>${label} • ${formatMovementDate(x)}</strong><span>${esc(who)}${x.note?` • ${esc(x.note)}`:""}${purchase?` • Alış ${money(purchase)}`:""}</span></div><div class="history-values">${sign}${formatNumber(x.amount)} ${esc(displayUnit(x.unit||"adet"))}<small>${formatNumber(x.previousQuantity)} → ${formatNumber(x.resultingQuantity)}</small></div></article>`}).join("")}
function movementLabel(type){return type==="in"?"Stok Girişi":type==="out"?"Stoktan Düşüm":type==="sale"?"Adisyon Satışı":type==="initial"?"İlk Stok":"Sayım Düzeltmesi"}
function movementTime(x){return num(x.createdAtMs)||timestamp(x.createdAt)||Date.parse(x.operationDate||"")||0}
function formatMovementDate(x){const ms=movementTime(x);return ms?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(ms)):formatDate(x.operationDate)}
function shortUser(uid){return uid?`Kullanıcı • ${String(uid).slice(0,6)}`:"Sistem"}
async function loadUserNames(){try{const snap=await getDocs(collection(db,"staffUsers"));snap.docs.forEach(d=>userNames.set(d.id,d.data().displayName||"Yönetim kullanıcısı"))}catch(error){console.info("Kullanıcı adları sınırlı erişimle gösteriliyor.")}}

async function openBarcode(mode="add"){barcodeMode=mode;cameraFacing="environment";pendingBarcode="";el.barcodeInput.value="";el.barcodeMatch.hidden=true;el.saveBarcodeButton.hidden=false;el.barcodeProduct.closest("label").hidden=false;el.barcodeKicker.textContent=mode==="search"?"Ürün sorgulama":"Hızlı stok girişi";el.barcodeTitle.textContent=mode==="search"?"Barkodlu Ürün Ara":"Barkodla Stok Ekle";el.cameraStatus.textContent="Kamera hazırlanıyor…";el.barcodeDialog.showModal();setTimeout(()=>el.barcodeInput.focus(),100);await startCamera()}
async function startCamera(){stopCamera();el.cameraFrame.classList.toggle("is-front",cameraFacing==="user");if(!navigator.mediaDevices?.getUserMedia){el.cameraStatus.textContent="Bu cihazda kamera kullanılamıyor. Barkodu elle girin.";return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:cameraFacing},width:{ideal:640},height:{ideal:360}},audio:false});el.barcodeVideo.srcObject=cameraStream;await el.barcodeVideo.play();if("BarcodeDetector"in window){el.cameraStatus.textContent=`${cameraFacing==="environment"?"Arka":"Ön"} kamera • Barkodu ortalayın.`;scanBarcode()}else el.cameraStatus.textContent="Otomatik okuma desteklenmiyor. Barkodu elle girin."}catch(error){console.error(error);el.cameraStatus.textContent="Kamera açılamadı. İzin verin veya barkodu elle girin."}}
async function switchCamera(){cameraFacing=cameraFacing==="environment"?"user":"environment";el.switchCameraButton.disabled=true;el.cameraStatus.textContent="Kamera değiştiriliyor…";await startCamera();el.switchCameraButton.disabled=false}
async function scanBarcode(){if(!cameraStream||el.barcodeDialog.open===false)return;try{const detector=new BarcodeDetector({formats:["ean_13","ean_8","code_128","upc_a","upc_e"]}),codes=await detector.detect(el.barcodeVideo);if(codes[0]?.rawValue)return handleBarcode(codes[0].rawValue)}catch(error){console.info("Barkod taraması bekliyor.")}scanFrame=requestAnimationFrame(scanBarcode)}
function stopCamera(){cancelAnimationFrame(scanFrame);scanFrame=0;if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}if(el.barcodeVideo)el.barcodeVideo.srcObject=null}
function handleBarcode(raw){const code=String(raw||"").replace(/\s/g,"");if(code.length<4)return show("Geçerli barkod numarasını girin.");pendingBarcode=code;el.barcodeInput.value=code;const item=stocks.find(x=>x.active&&x.barcode===code);if(item){stopCamera();el.barcodeDialog.close();beep();if(barcodeMode==="search"){openHistory(item.id);show(`${item.name} bulundu.`)}else{openEntry(item.id);show(`${item.name} bulundu.`)}return}if(barcodeMode==="search"){el.barcodeMessage.textContent=`${code} barkoduyla kayıtlı stok ürünü bulunamadı.`;el.barcodeProduct.closest("label").hidden=true;el.saveBarcodeButton.hidden=true;el.barcodeMatch.hidden=false;return}el.barcodeProduct.closest("label").hidden=false;el.saveBarcodeButton.hidden=false;el.barcodeMessage.textContent=`${code} barkodu henüz bir ürüne bağlı değil.`;const active=stocks.filter(x=>x.active).sort((a,b)=>a.name.localeCompare(b.name,"tr"));el.barcodeProduct.innerHTML='<option value="">Ürün seçin</option>'+active.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");el.barcodeMatch.hidden=false;el.barcodeProduct.focus()}
async function saveBarcodeMatch(){const item=stocks.find(x=>x.id===el.barcodeProduct.value);if(!item||!pendingBarcode)return show("Barkodun bağlanacağı ürünü seçin.");if(stocks.some(x=>x.id!==item.id&&x.barcode===pendingBarcode))return show("Bu barkod başka bir ürüne bağlı.");el.saveBarcodeButton.disabled=true;try{await updateDoc(doc(stocksCol,item.id),{barcode:pendingBarcode,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});stopCamera();el.barcodeDialog.close();beep();openEntry(item.id);show(`${item.name} barkodla eşleştirildi.`)}catch(error){console.error(error);show("Barkod eşleştirilemedi.")}finally{el.saveBarcodeButton.disabled=false}}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch(error){}}

function normalizeStock(id,d){const units=Math.max(1,num(d.unitsPerPackage)||1),legacyUnitCost=d.purchasePriceBasis==="package"?num(d.purchasePrice)/units:d.purchasePriceBasis==="unit"?num(d.purchasePrice):0;return{id,name:String(d.name||"Ürün"),linkedMenuItemId:String(d.linkedMenuItemId||""),barcode:String(d.barcode||""),quantity:num(d.quantity),unit:String(d.unit||"adet"),unitsPerPackage:units,warningThreshold:num(d.warningThreshold),unitCost:num(d.unitCost)||legacyUnitCost,lastPurchaseTotal:num(d.lastPurchaseTotal),active:d.active!==false}}
function timestamp(v){return v?.toMillis?.()||0}function num(v){return Number(v)||0}function displayUnit(v){const value=String(v||"");return value?value.charAt(0).toLocaleUpperCase("tr-TR")+value.slice(1).toLocaleLowerCase("tr-TR"):""}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function formatDate(v){const[y,m,d]=String(v||"").split("-");return y&&m&&d?`${d}.${m}.${y}`:"—"}function formatNumber(v){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(num(v))}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",minimumFractionDigits:num(v)%1?2:0}).format(num(v))}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function updateClock(){const n=new Date();$("currentTime").textContent=new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(n);$("currentDate").textContent=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"Europe/Istanbul"}).format(n).replace(/\./g,"/")}function show(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),3000)}
