import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, doc, getFirestore, limit, onSnapshot, orderBy, query, runTransaction, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { ADMIN_UID, firebaseConfig } from "../firebase-config.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const customersCol=collection(db,"adminCreditCustomers"),movesCol=collection(db,"adminCreditMovements"),salesCol=collection(db,"adminSales");
const $=id=>document.getElementById(id);
const el={customerForm:$("customerForm"),editingCustomerId:$("editingCustomerId"),customerFormTitle:$("customerFormTitle"),customerName:$("customerName"),customerPhone:$("customerPhone"),customerLimit:$("customerLimit"),openingBalance:$("openingBalance"),customerNote:$("customerNote"),creditEnabled:$("creditEnabled"),resetEnabled:$("resetEnabled"),cancelEditButton:$("cancelEditButton"),saveCustomerButton:$("saveCustomerButton"),customerCount:$("customerCount"),totalBalance:$("totalBalance"),totalCredit:$("totalCredit"),overLimitCount:$("overLimitCount"),todayPayment:$("todayPayment"),saveStatus:$("saveStatus"),customerFilter:$("customerFilter"),customerSearch:$("customerSearch"),customerEmpty:$("customerEmpty"),customerList:$("customerList"),movementEmpty:$("movementEmpty"),movementList:$("movementList"),movementDialog:$("movementDialog"),movementForm:$("movementForm"),movementTitle:$("movementTitle"),movementCustomerId:$("movementCustomerId"),movementAmount:$("movementAmount"),movementAmountLabel:$("movementAmountLabel"),movementDate:$("movementDate"),movementNote:$("movementNote"),movementPreview:$("movementPreview"),closeMovementDialog:$("closeMovementDialog"),cancelMovementButton:$("cancelMovementButton"),topupDialog:$("topupDialog"),topupForm:$("topupForm"),topupTitle:$("topupTitle"),topupCustomerId:$("topupCustomerId"),topupAmount:$("topupAmount"),topupDate:$("topupDate"),topupNote:$("topupNote"),topupPreview:$("topupPreview"),closeTopupDialog:$("closeTopupDialog"),cancelTopupButton:$("cancelTopupButton"),limitDialog:$("limitDialog"),limitDialogText:$("limitDialogText"),confirmLimitButton:$("confirmLimitButton"),resetDialog:$("resetDialog"),resetDialogText:$("resetDialogText"),confirmResetButton:$("confirmResetButton"),summaryDialog:$("summaryDialog"),summaryTitle:$("summaryTitle"),summaryContent:$("summaryContent"),closeSummaryDialog:$("closeSummaryDialog"),shareSummaryButton:$("shareSummaryButton"),pdfSummaryButton:$("pdfSummaryButton"),currentDate:$("currentDate"),currentTime:$("currentTime"),logoutButton:$("logoutButton"),toast:$("toast")};
let customers=[],movements=[],pendingMovement=null,pendingResetId="",summaryCustomerId="",busy=false,toastTimer;

el.customerForm.onsubmit=saveCustomer;el.cancelEditButton.onclick=resetForm;el.customerList.onclick=customerAction;el.customerFilter.onchange=renderCustomers;el.customerSearch.oninput=renderCustomers;el.movementForm.onsubmit=prepareMovement;el.movementForm.oninput=updatePreview;el.closeMovementDialog.onclick=closeMovement;el.cancelMovementButton.onclick=closeMovement;el.topupForm.onsubmit=saveTopup;el.topupForm.oninput=updateTopupPreview;el.closeTopupDialog.onclick=closeTopup;el.cancelTopupButton.onclick=closeTopup;el.confirmLimitButton.onclick=()=>pendingMovement&&executeMovement(pendingMovement);el.confirmResetButton.onclick=resetAccount;el.closeSummaryDialog.onclick=()=>el.summaryDialog.close();el.shareSummaryButton.onclick=shareSummary;el.pdfSummaryButton.onclick=printSummary;el.logoutButton.onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});
updateClock();setInterval(updateClock,1000);
onAuthStateChanged(auth,async user=>{if(!user||user.uid!==ADMIN_UID){if(user)await signOut(auth);location.replace("../yonetici-giris.html?next=acik-hesap/");return}subscribe()});

function subscribe(){
  onSnapshot(customersCol,s=>{customers=s.docs.map(d=>normalizeCustomer(d.id,d.data()));connection(true);renderAll()},connectionError);
  onSnapshot(query(movesCol,orderBy("createdAt","desc"),limit(300)),s=>{movements=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},connectionError);
}
async function saveCustomer(e){
  e.preventDefault();if(busy)return;
  const id=el.editingCustomerId.value,phone=normalizePhone(el.customerPhone.value),opening=amount(el.openingBalance.value);
  if(phone.length!==10)return toast("Telefon numarasını 05xx xxx xx xx şeklinde girin.");
  if(customers.some(c=>c.phone===phone&&c.id!==id))return toast("Bu telefon numarası başka bir müşteride kayıtlı.");
  const data={name:el.customerName.value.trim(),phone,creditLimit:amount(el.customerLimit.value),note:el.customerNote.value.trim(),creditEnabled:el.creditEnabled.checked,resetEnabled:el.resetEnabled.checked,updatedAt:serverTimestamp()};
  if(!data.name)return;
  busy=true;
  try{
    if(id){await updateDoc(doc(customersCol,id),data);toast("Müşteri bilgileri güncellendi.")}
    else{
      const customerRef=doc(customersCol),moveRef=doc(movesCol);
      await runTransaction(db,async tx=>{tx.set(customerRef,{...data,openingBalance:opening,balance:opening,createdAt:serverTimestamp()});if(opening>0)tx.set(moveRef,{customerId:customerRef.id,customerName:data.name,type:"opening",amount:opening,previousBalance:0,resultingBalance:opening,operationDate:today(),note:"Başlangıç Bakiyesi",source:"opening",createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});
      toast("Açık Hesap müşterisi oluşturuldu.");
    }
    resetForm();
  }catch(err){console.error(err);toast("Müşteri kaydedilemedi.")}finally{busy=false}
}
function customerAction(e){
  const debt=e.target.closest("[data-debt]"),payment=e.target.closest("[data-payment]"),topup=e.target.closest("[data-topup]"),edit=e.target.closest("[data-edit]"),toggle=e.target.closest("[data-toggle]"),reset=e.target.closest("[data-reset]"),summary=e.target.closest("[data-summary]");
  if(debt)openMovement(debt.dataset.debt,"debt");if(payment)openMovement(payment.dataset.payment,"payment");if(topup)openTopup(topup.dataset.topup);if(edit)beginEdit(edit.dataset.edit);if(toggle)toggleCustomer(toggle.dataset.toggle);if(reset)confirmReset(reset.dataset.reset);if(summary)openSummary(summary.dataset.summary);
}
function beginEdit(id){const c=customers.find(x=>x.id===id);if(!c)return;el.editingCustomerId.value=id;el.customerName.value=c.name;el.customerPhone.value=formatPhone(c.phone);el.customerLimit.value=c.creditLimit;el.openingBalance.value=c.openingBalance;el.openingBalance.disabled=true;el.customerNote.value=c.note;el.creditEnabled.checked=c.creditEnabled;el.resetEnabled.checked=c.resetEnabled;el.customerFormTitle.textContent="Müşteriyi Düzenle";el.cancelEditButton.hidden=false;el.saveCustomerButton.innerHTML='<i class="fa-solid fa-floppy-disk"></i> Değişiklikleri Kaydet';el.customerForm.scrollIntoView({behavior:"smooth"})}
async function toggleCustomer(id){const c=customers.find(x=>x.id===id);if(!c||busy)return;try{await updateDoc(doc(customersCol,id),{creditEnabled:!c.creditEnabled,updatedAt:serverTimestamp()});toast(c.creditEnabled?"Açık Hesap yetkisi kapatıldı.":"Açık Hesap yetkisi açıldı.")}catch(err){console.error(err);toast("Müşteri yetkisi değiştirilemedi.")}}
function openMovement(id,type){const c=customers.find(x=>x.id===id);if(!c)return;if(type==="debt"&&!c.creditEnabled)return toast("Bu müşterinin Açık Hesap yetkisi kapalı.");if(type!=="debt"&&c.balance<=0)return toast("Bu müşterinin tahsil edilecek borcu yok.");el.movementCustomerId.value=id;el.movementTitle.textContent=c.name;el.movementAmount.value="";el.movementNote.value="";el.movementDate.value=today();el.movementForm.querySelector(`[name="movementType"][value="${type}"]`).checked=true;updatePreview();el.movementDialog.showModal()}
function closeMovement(){el.movementDialog.close();pendingMovement=null}
function openTopup(id){const c=customers.find(x=>x.id===id);if(!c)return;el.topupCustomerId.value=id;el.topupTitle.textContent=`${c.name} — Artı Bakiye Yükle`;el.topupAmount.value="";el.topupDate.value=today();el.topupNote.value="";el.topupForm.elements.topupType.value="cash";updateTopupPreview();el.topupDialog.showModal();setTimeout(()=>el.topupAmount.focus(),50)}
function closeTopup(){el.topupDialog.close()}
function updateTopupPreview(){const c=customers.find(x=>x.id===el.topupCustomerId.value);if(!c)return;const value=amount(el.topupAmount.value),debtPaid=Math.min(c.balance,value),creditAdded=Math.max(0,value-debtPaid);el.topupPreview.textContent=`Mevcut borç ${money(c.balance)} → Yeni borç ${money(c.balance-debtPaid)} • Artı bakiye ${money(c.creditBalance)} → ${money(c.creditBalance+creditAdded)}`}
async function saveTopup(e){e.preventDefault();if(busy)return;const customerId=el.topupCustomerId.value,value=amount(el.topupAmount.value),paymentType=el.topupForm.elements.topupType.value,operationDate=el.topupDate.value,note=el.topupNote.value.trim();if(!customerId||value<=0)return toast("Geçerli bir bakiye tutarı girin.");busy=true;try{const customerRef=doc(customersCol,customerId),moveRef=doc(movesCol),saleRef=doc(salesCol);await runTransaction(db,async tx=>{const snap=await tx.get(customerRef);if(!snap.exists())throw Error("missing");const c=normalizeCustomer(snap.id,snap.data()),debtPaid=Math.min(c.balance,value),creditAdded=Math.max(0,value-debtPaid),resultingBalance=c.balance-debtPaid,resultingCredit=c.creditBalance+creditAdded;tx.update(customerRef,{balance:resultingBalance,creditBalance:resultingCredit,updatedAt:serverTimestamp()});tx.set(moveRef,{customerId:c.id,customerName:c.name,type:paymentType==="transfer"?"topup-transfer":"topup-cash",amount:value,debtPaid,creditAdded,previousBalance:c.balance,resultingBalance,previousCreditBalance:c.creditBalance,resultingCreditBalance:resultingCredit,operationDate,note:note||"Bakiye Yükleme",source:"topup",createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});tx.set(saleRef,{recordType:"credit-topup",customerId:c.id,customerName:c.name,amount:value,debtPaid,creditAdded,cashAmount:paymentType==="cash"?value:0,transferAmount:paymentType==="transfer"?value:0,paymentType,businessDate:operationDate,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.topupDialog.close();toast(paymentType==="transfer"?"Banka Havalesi ile bakiye yüklendi.":"Nakit ile bakiye yüklendi.")}catch(err){console.error(err);toast("Bakiye yüklenemedi.")}finally{busy=false}}
function prepareMovement(e){e.preventDefault();if(busy)return;const c=customers.find(x=>x.id===el.movementCustomerId.value);if(!c)return;const type=el.movementForm.elements.movementType.value,m={customerId:c.id,type,amount:amount(el.movementAmount.value),operationDate:el.movementDate.value,note:el.movementNote.value.trim()};if(m.amount<=0)return toast("Geçerli bir tutar girin.");if(type!=="debt"&&m.amount>c.balance)return toast("Tahsilat tutarı mevcut borçtan fazla olamaz.");const creditUsed=type==="debt"?Math.min(c.creditBalance,m.amount):0,next=type==="debt"?c.balance+m.amount-creditUsed:c.balance-m.amount;if(type==="debt"&&c.creditLimit>0&&next>c.creditLimit){pendingMovement=m;el.limitDialogText.textContent=`${c.name} için yeni borç ${money(next)} olacak. Belirlenen limit ${money(c.creditLimit)}.`;el.movementDialog.close();el.limitDialog.showModal();return}executeMovement(m)}
async function executeMovement(m){
  if(busy)return;busy=true;
  try{
    const customerRef=doc(customersCol,m.customerId),moveRef=doc(movesCol),saleRef=m.type==="debt"?null:doc(salesCol);
    await runTransaction(db,async tx=>{const snap=await tx.get(customerRef);if(!snap.exists())throw Error("missing");const c=normalizeCustomer(snap.id,snap.data()),creditUsed=m.type==="debt"?Math.min(c.creditBalance,m.amount):0,result=m.type==="debt"?c.balance+m.amount-creditUsed:c.balance-m.amount,resultingCredit=m.type==="debt"?c.creditBalance-creditUsed:c.creditBalance;if(result<0)throw Error("high");tx.update(customerRef,{balance:result,creditBalance:resultingCredit,updatedAt:serverTimestamp()});tx.set(moveRef,{customerId:c.id,customerName:c.name,type:m.type,amount:m.amount,creditUsed,previousBalance:c.balance,resultingBalance:result,previousCreditBalance:c.creditBalance,resultingCreditBalance:resultingCredit,operationDate:m.operationDate,note:m.note,source:"manual",createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});if(saleRef)tx.set(saleRef,{recordType:"credit-payment",customerId:c.id,customerName:c.name,amount:m.amount,cashAmount:m.type==="payment"?m.amount:0,transferAmount:m.type==="transfer"?m.amount:0,paymentType:m.type==="transfer"?"transfer":"cash",businessDate:m.operationDate,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});
    pendingMovement=null;el.limitDialog.close();el.movementDialog.close();toast(m.type==="debt"?"Borç hesaba eklendi.":m.type==="transfer"?"Banka Havalesi kaydedildi.":"Nakit tahsilat kaydedildi.");
  }catch(err){console.error(err);toast(err.message==="high"?"Tahsilat mevcut borçtan fazla olamaz.":"Hesap hareketi kaydedilemedi.")}finally{busy=false}
}
function updatePreview(){const c=customers.find(x=>x.id===el.movementCustomerId.value);if(!c)return;const type=el.movementForm.elements.movementType.value,value=amount(el.movementAmount.value),creditUsed=type==="debt"?Math.min(c.creditBalance,value):0,next=type==="debt"?c.balance+value-creditUsed:Math.max(0,c.balance-value),nextCredit=type==="debt"?c.creditBalance-creditUsed:c.creditBalance,labels={debt:"Eklenecek Borç (TL)",payment:"Nakit Tahsilat (TL)",transfer:"Banka Havalesi (TL)"};el.movementAmountLabel.textContent=labels[type];el.movementPreview.textContent=`Borç: ${money(c.balance)} → ${money(next)} • Artı Bakiye: ${money(c.creditBalance)} → ${money(nextCredit)}`}
function confirmReset(id){const c=customers.find(x=>x.id===id);if(!c)return;pendingResetId=id;el.resetDialogText.textContent=`${c.name} müşterisinin ${money(c.balance)} geçmiş dönem bakiyesi sıfırlanacak. Sıfırlamak istiyor musunuz?`;el.resetDialog.showModal()}
async function resetAccount(){const c=customers.find(x=>x.id===pendingResetId);if(!c||busy)return;busy=true;try{const customerRef=doc(customersCol,c.id),moveRef=doc(movesCol);await runTransaction(db,async tx=>{const snap=await tx.get(customerRef);if(!snap.exists())throw Error("missing");const fresh=normalizeCustomer(snap.id,snap.data());tx.update(customerRef,{balance:0,lastResetAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.set(moveRef,{customerId:fresh.id,customerName:fresh.name,type:"reset",amount:fresh.balance,previousBalance:fresh.balance,resultingBalance:0,operationDate:today(),note:"Geçmiş Dönem Hesabı Sıfırlandı",source:"reset",createdAt:serverTimestamp(),createdBy:auth.currentUser.uid})});el.resetDialog.close();pendingResetId="";toast("Müşterinin geçmiş dönem hesabı sıfırlandı.")}catch(err){console.error(err);toast("Hesap sıfırlanamadı.")}finally{busy=false}}
function customerMovements(id){return movements.filter(m=>m.customerId===id).sort((a,b)=>movementTime(a)-movementTime(b))}
function openSummary(id){const c=customers.find(x=>x.id===id);if(!c)return;summaryCustomerId=id;el.summaryTitle.textContent=`${c.name} Hesap Özeti`;el.summaryContent.innerHTML=summaryHtml(c,customerMovements(id));el.summaryDialog.showModal()}
function summaryHtml(c,list){return`<div class="account-summary-head"><span>Başlangıç Bakiyesi <b>${money(c.openingBalance)}</b></span><span>Güncel Borç <b>${money(c.balance)}</b></span><span>Artı Bakiye <b>${money(c.creditBalance)}</b></span></div><div class="account-table"><div class="account-row account-row-head"><span>No</span><span>Tarih</span><span>İşlem</span><span>Tutar</span><span>Bakiye</span></div>${list.map((m,i)=>`<div class="account-row"><span>${i+1}</span><span>${formatDate(m.operationDate)}</span><span>${movementName(m)}${m.note?`<small>${escapeHtml(m.note)}</small>`:""}</span><span>${movementSign(m)}${money(m.amount)}</span><span>${movementResult(m)}</span></div>`).join("")||'<p class="empty-copy">Hesap hareketi bulunmuyor.</p>'}</div>`}
function summaryText(c,list){return[`FATİH ÇAY EVİ`,`Müşteri Hesap Özeti`,`Müşteri: ${c.name}`,`Başlangıç Bakiyesi: ${money(c.openingBalance)}`,...list.map((m,i)=>`${i+1}. ${formatDate(m.operationDate)} - ${movementName(m)} - ${movementSign(m)}${money(m.amount)} - ${movementResult(m)}`),`Güncel Borç: ${money(c.balance)}`,`Artı Bakiye: ${money(c.creditBalance)}`].join("\n")}
async function shareSummary(){const c=customers.find(x=>x.id===summaryCustomerId);if(!c)return;const text=summaryText(c,customerMovements(c.id));try{if(navigator.share){await navigator.share({title:`${c.name} Hesap Özeti`,text});return}window.open(`https://wa.me/90${c.phone}?text=${encodeURIComponent(text)}`,"_blank","noopener")}catch(err){if(err?.name!=="AbortError"){console.error(err);toast("WhatsApp paylaşımı açılamadı.")}}}
function printSummary(){const c=customers.find(x=>x.id===summaryCustomerId);if(!c)return;const list=customerMovements(c.id),rows=list.map((m,i)=>`<tr><td>${i+1}</td><td>${formatDate(m.operationDate)}</td><td>${escapeHtml(movementName(m))}${m.note?`<small>${escapeHtml(m.note)}</small>`:""}</td><td>${movementSign(m)}${money(m.amount)}</td><td>${movementResult(m)}</td></tr>`).join("");openReportPrint(`${c.name} — Müşteri Hesap Özeti`,`<table><thead><tr><th>No</th><th>Tarih</th><th>İşlem</th><th>Tutar</th><th>Bakiye</th></tr></thead><tbody>${rows}</tbody></table>`,[["Başlangıç Bakiyesi",money(c.openingBalance)],["Güncel Borç",money(c.balance)],["Artı Bakiye",money(c.creditBalance)]])}
function openReportPrint(title,body,totals){const popup=window.open("","_blank","width=1000,height=760");if(!popup)return toast("PDF penceresi açılamadı.");popup.document.write(reportDocument(title,body,totals));popup.document.close()}
function reportDocument(title,body,totals){const logo=new URL("../logo.png",location.href).href,created=new Intl.DateTimeFormat("tr-TR",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date());return`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#342522;font:12px Arial,sans-serif}.watermark{position:fixed;inset:20% 15%;width:70%;height:60%;object-fit:contain;opacity:.045;z-index:-1}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #7d1b24;padding-bottom:12px}.brand img{width:90px}.brand p{margin:2px 0}.date{text-align:right}.title{text-align:center;color:#7d1b24;margin:22px 0 14px}table{width:100%;border-collapse:collapse}thead{display:table-header-group}th{background:#7d1b24;color:#fff}th,td{padding:9px;border:1px solid #d8c6ba;text-align:left}tbody tr:nth-child(even){background:#fff7ef}td small{display:block;color:#76635d;margin-top:3px}.totals{width:48%;margin:16px 0 0 auto;border:1px solid #d8c6ba}.totals div{display:flex;justify-content:space-between;padding:9px;border-bottom:1px solid #eaded6}.totals div:last-child{border:0;background:#fff2e2;color:#7d1b24;font-weight:bold}</style></head><body><img class="watermark" src="${logo}"><header class="head"><div class="brand"><img src="${logo}"><p><b>Fatih Ali Altınlı</b></p><p>0554 118 08 06</p><p>Ulukavak Mah. Osmancık Cad. No:285<br>Çorum/Merkez</p></div><div class="date"><b>Oluşturma Tarihi</b><p>${created}</p></div></header><h1 class="title">${escapeHtml(title)}</h1>${body}<section class="totals">${totals.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</section><script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`}
function renderAll(){renderSummary();renderCustomers();renderMovements()}
function renderSummary(){const enabled=customers.filter(c=>c.creditEnabled),date=today();el.customerCount.textContent=enabled.length;el.totalBalance.textContent=money(customers.reduce((s,c)=>s+c.balance,0));el.totalCredit.textContent=money(customers.reduce((s,c)=>s+c.creditBalance,0));el.overLimitCount.textContent=customers.filter(c=>c.creditLimit>0&&c.balance>c.creditLimit).length;el.todayPayment.textContent=money(movements.filter(m=>["payment","transfer","topup-cash","topup-transfer"].includes(m.type)&&m.operationDate===date).reduce((s,m)=>s+amount(m.amount),0))}
function renderCustomers(){const filter=el.customerFilter.value,q=el.customerSearch.value.trim().toLocaleLowerCase("tr-TR"),list=customers.filter(c=>`${c.name} ${c.phone} ${c.note}`.toLocaleLowerCase("tr-TR").includes(q)).filter(c=>filter==="enabled"?c.creditEnabled:filter==="disabled"?!c.creditEnabled:filter==="debt"?c.balance>0:filter==="credit"?c.creditBalance>0:filter==="over-limit"?c.creditLimit>0&&c.balance>c.creditLimit:true).sort((a,b)=>b.balance-a.balance||b.creditBalance-a.creditBalance||a.name.localeCompare(b.name,"tr"));el.customerEmpty.hidden=list.length>0;el.customerList.innerHTML=list.map(customerCard).join("")}
function customerCard(c){const over=c.creditLimit>0&&c.balance>c.creditLimit,remaining=Math.max(0,c.creditLimit-c.balance),hasCredit=c.creditBalance>0;return`<article class="customer-card ${over?"is-over":""} ${hasCredit?"has-credit":""} ${c.creditEnabled?"":"is-disabled"}"><div><div class="customer-title"><strong>${escapeHtml(c.name)}</strong><span class="badge ${over?"is-over":"is-ok"}">${over?"Limit Aşıldı":c.creditEnabled?"Açık Hesap Aktif":"Yetki Kapalı"}</span></div><div class="balance ${hasCredit&&!c.balance?"is-credit":""}">${c.balance?`${money(c.balance)} Borç`:hasCredit?`+${money(c.creditBalance)} Artı Bakiye`:"Borç Yok"}</div>${c.balance&&hasCredit?`<div class="balance is-credit">+${money(c.creditBalance)} Artı Bakiye</div>`:""}<div class="customer-meta"><span>${formatPhone(c.phone)}</span><span>Başlangıç: ${money(c.openingBalance)}</span><span>Limit: ${money(c.creditLimit)}</span><span>Kalan Limit: ${money(remaining)}</span></div>${c.note?`<p class="customer-note">${escapeHtml(c.note)}</p>`:""}</div><div class="item-actions">${c.creditEnabled?`<button class="icon-button" data-debt="${c.id}" title="Borç Ekle"><i class="fa-solid fa-plus"></i></button>`:""}<button class="icon-button is-topup" data-topup="${c.id}" title="Artı Bakiye Yükle"><i class="fa-solid fa-wallet"></i></button><button class="icon-button is-payment" data-payment="${c.id}" title="Tahsilat"><i class="fa-solid fa-money-bill-wave"></i></button><button class="icon-button is-share" data-summary="${c.id}" title="Hesap Özeti"><i class="fa-solid fa-file-invoice"></i></button>${c.resetEnabled?`<button class="icon-button is-danger" data-reset="${c.id}" title="Hesabı Sıfırla"><i class="fa-solid fa-rotate-left"></i></button>`:""}<button class="icon-button" data-edit="${c.id}" title="Düzenle"><i class="fa-solid fa-pen"></i></button><button class="icon-button is-danger" data-toggle="${c.id}" title="Yetkiyi Değiştir"><i class="fa-solid ${c.creditEnabled?"fa-lock":"fa-lock-open"}"></i></button></div></article>`}
function renderMovements(){el.movementEmpty.hidden=movements.length>0;el.movementList.innerHTML=movements.slice(0,100).map(m=>{const topup=["topup-cash","topup-transfer"].includes(m.type),incoming=["payment","transfer","reset"].includes(m.type);return`<article class="movement-item"><span class="movement-icon ${topup?"topup":incoming?"payment":""}"><i class="fa-solid ${["transfer","topup-transfer"].includes(m.type)?"fa-building-columns":topup?"fa-wallet":incoming?"fa-money-bill-wave":"fa-plus"}"></i></span><div class="movement-copy"><strong>${escapeHtml(m.customerName||"Müşteri")}</strong><span>${movementName(m)} • ${formatDate(m.operationDate)}${m.note?` • ${escapeHtml(m.note)}`:""}</span></div><div class="movement-amount">${movementSign(m)}${money(m.amount)}<span class="movement-result">${movementResult(m)}</span></div></article>`}).join("")}
function movementName(m){return m.type==="opening"?"Başlangıç Bakiyesi":m.type==="debt"?"Borç Eklendi":m.type==="transfer"?"Banka Havalesi":m.type==="topup-cash"?"Bakiye Yükleme — Nakit":m.type==="topup-transfer"?"Bakiye Yükleme — Banka Havalesi":m.type==="reset"?"Hesap Sıfırlandı":"Nakit Tahsilat"}function movementSign(m){return["payment","transfer","reset"].includes(m.type)?"−":"+"}function movementResult(m){const debt=amount(m.resultingBalance),credit=amount(m.resultingCreditBalance);return credit?`Borç: ${money(debt)} • Artı: ${money(credit)}`:`Borç: ${money(debt)}`}function movementTime(m){return m.createdAt?.toMillis?.()||new Date(`${m.operationDate||"1970-01-01"}T00:00:00+03:00`).getTime()}
function resetForm(){el.customerForm.reset();el.editingCustomerId.value="";el.creditEnabled.checked=true;el.resetEnabled.checked=false;el.openingBalance.value=0;el.openingBalance.disabled=false;el.customerFormTitle.textContent="Yeni Açık Hesap Müşterisi";el.cancelEditButton.hidden=true;el.saveCustomerButton.innerHTML='<i class="fa-solid fa-floppy-disk"></i> Müşteriyi Kaydet'}
function normalizeCustomer(id,d){return{id,name:String(d.name||""),phone:normalizePhone(d.phone||""),creditLimit:amount(d.creditLimit),openingBalance:amount(d.openingBalance),balance:amount(d.balance),creditBalance:amount(d.creditBalance),note:String(d.note||""),creditEnabled:d.creditEnabled!==false,resetEnabled:d.resetEnabled===true}}
function normalizePhone(v){let d=String(v).replace(/\D/g,"");if(d.startsWith("90"))d=`0${d.slice(2)}`;if(d.length===10&&d.startsWith("5"))d=`0${d}`;return d.slice(-11).replace(/^0/,"")}function formatPhone(v){const d=normalizePhone(v);return d.length===10?`0${d.slice(0,3)} ${d.slice(3,6)} ${d.slice(6,8)} ${d.slice(8)}`:v}function amount(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,n):0}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",minimumFractionDigits:2}).format(amount(v))}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function formatDate(v){const[y,m,d]=String(v||"").split("-");return y&&m&&d?`${d}.${m}.${y}`:"—"}function updateClock(){const n=new Date();el.currentTime.textContent=new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(n);el.currentDate.textContent=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"Europe/Istanbul"}).format(n).replace(/\./g,"/")}function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function connection(ok){el.saveStatus.innerHTML=ok?'<i class="fa-solid fa-circle-check"></i> Canlı Bağlantı':'<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı Hatası'}function connectionError(err){console.error(err);connection(false);toast("Veriler alınamadı.")}function toast(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),3200)}
