import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,onSnapshot}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{hasPanelAccess}from"../assets/js/admin-access.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const salesCol=collection(db,"adminSales"),closingsCol=collection(db,"adminDailyClosings"),cashMovementsCol=collection(db,"adminCashMovements"),stocksCol=collection(db,"adminStockItems"),stockMovesCol=collection(db,"adminStockMovements"),internalConsumptionsCol=collection(db,"adminInternalConsumptions"),menuRef=doc(db,"publicMenu","catalog"),settingsRef=doc(db,"adminAppSettings","pos");
const el={periodButtons:$("periodButtons"),dateRange:$("dateRange"),startDate:$("startDate"),endDate:$("endDate"),applyRange:$("applyRange"),periodLabel:$("periodLabel"),connection:$("connection"),salesTotal:$("salesTotal"),cashTotal:$("cashTotal"),transferTotal:$("transferTotal"),cardTotal:$("cardTotal"),cashExpenseTotal:$("cashExpenseTotal"),bankExpenseTotal:$("bankExpenseTotal"),creditCardExpenseTotal:$("creditCardExpenseTotal"),expenseTotal:$("expenseTotal"),itemCount:$("itemCount"),orderCount:$("orderCount"),giftCount:$("giftCount"),tipTotal:$("tipTotal"),roundingTotal:$("roundingTotal"),categoryTabs:$("categoryTabs"),productSearch:$("productSearch"),productReport:$("productReport"),productEmpty:$("productEmpty"),rankingList:$("rankingList"),rankingEmpty:$("rankingEmpty"),categoryReport:$("categoryReport"),purchaseProductCount:$("purchaseProductCount"),purchasePackageCount:$("purchasePackageCount"),purchaseUnitCount:$("purchaseUnitCount"),allPurchaseTotal:$("allPurchaseTotal"),purchaseList:$("purchaseList"),purchaseEmpty:$("purchaseEmpty"),internalRecordCount:$("internalRecordCount"),internalProductCount:$("internalProductCount"),internalQuantity:$("internalQuantity"),internalConsumptionList:$("internalConsumptionList"),internalConsumptionEmpty:$("internalConsumptionEmpty"),stockProductSelect:$("stockProductSelect"),stockReportHint:$("stockReportHint"),stockReportContent:$("stockReportContent"),stockPackages:$("stockPackages"),stockReceived:$("stockReceived"),stockPurchaseTotal:$("stockPurchaseTotal"),stockAverageCost:$("stockAverageCost"),stockSold:$("stockSold"),stockRevenue:$("stockRevenue"),stockProfit:$("stockProfit"),stockRemaining:$("stockRemaining"),stockEntryCount:$("stockEntryCount"),stockEntryList:$("stockEntryList"),stockEntryEmpty:$("stockEntryEmpty"),closingList:$("closingList"),closingEmpty:$("closingEmpty"),closingDetailDialog:$("closingDetailDialog"),closingDetailTitle:$("closingDetailTitle"),closingDetailPeriod:$("closingDetailPeriod"),closingDetailSummary:$("closingDetailSummary"),closingDetailProducts:$("closingDetailProducts"),closingDetailEmpty:$("closingDetailEmpty"),closingProductCount:$("closingProductCount"),closingDetailPdf:$("closingDetailPdf"),closingDetailExcel:$("closingDetailExcel"),closeClosingDetail:$("closeClosingDetail"),closeClosingDetailBottom:$("closeClosingDetailBottom"),exportPdf:$("exportPdf"),exportExcel:$("exportExcel"),logoutButton:$("logoutButton"),toast:$("toast")};
el.internalCost=$("internalCost");
Object.assign(el,{manualIncomeTotal:$("manualIncomeTotal"),periodIncomeTotal:$("periodIncomeTotal"),periodExpenseTotal:$("periodExpenseTotal"),periodNetTotal:$("periodNetTotal"),periodStockPurchaseTotal:$("periodStockPurchaseTotal"),periodInternalCostTotal:$("periodInternalCostTotal"),incomeCategorySummary:$("incomeCategorySummary"),incomeCategoryEmpty:$("incomeCategoryEmpty"),expenseCategorySummary:$("expenseCategorySummary"),expenseCategoryEmpty:$("expenseCategoryEmpty"),movementDetailDialog:$("movementDetailDialog"),movementDetailTitle:$("movementDetailTitle"),movementDetailPeriod:$("movementDetailPeriod"),movementDetailSummary:$("movementDetailSummary"),movementDetailCount:$("movementDetailCount"),movementDetailList:$("movementDetailList"),movementDetailEmpty:$("movementDetailEmpty"),closeMovementDetail:$("closeMovementDetail"),closeMovementDetailBottom:$("closeMovementDetailBottom")});
let sales=[],closings=[],cashMovements=[],stocks=[],stockMovements=[],internalConsumptions=[],catalog={categories:[],items:[]},period="today",category="all",range={start:today(),end:today()},currentBusinessDate=today(),currentBusinessDayStartedAtMs=0,report=emptyReport(),selectedClosing=null,selectedMovementGroup=null,loaded=0,toastTimer;

el.periodButtons.onclick=e=>{const button=e.target.closest("[data-period]");if(!button)return;period=button.dataset.period;[...el.periodButtons.children].forEach(x=>x.classList.toggle("active",x===button));el.dateRange.hidden=period!=="custom";if(period!=="custom"){range=periodRange(period);render()}};
el.applyRange.onclick=()=>{if(!el.startDate.value||!el.endDate.value)return show("Başlangıç ve bitiş tarihini seçin.");if(el.startDate.value>el.endDate.value)return show("Başlangıç tarihi bitişten sonra olamaz.");range={start:el.startDate.value,end:el.endDate.value};render()};
el.categoryTabs.onclick=e=>{const button=e.target.closest("[data-category]");if(!button)return;category=button.dataset.category;renderProducts()};
el.productSearch.oninput=renderProducts;
el.stockProductSelect.onchange=renderStockReport;
el.closingList.onclick=e=>{const row=e.target.closest("[data-closing-id]");if(row)openClosingDetail(row.dataset.closingId)};
el.closeClosingDetail.onclick=closeClosingDetail;
el.closeClosingDetailBottom.onclick=closeClosingDetail;
el.closingDetailPdf.onclick=exportClosingDetailPdf;
el.closingDetailExcel.onclick=exportClosingDetailExcel;
el.incomeCategorySummary.onclick=movementGroupAction;
el.expenseCategorySummary.onclick=movementGroupAction;
el.closeMovementDetail.onclick=closeMovementDetail;
el.closeMovementDetailBottom.onclick=closeMovementDetail;
el.exportPdf.onclick=exportPdf;
el.exportExcel.onclick=exportExcel;
el.logoutButton.onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});
updateClock();setInterval(updateClock,1000);el.startDate.value=range.start;el.endDate.value=range.end;

onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=raporlar/");return}if(!await hasPanelAccess(user,db,"reports")){location.replace("../yonetici-giris.html");return}subscribe()});
function subscribe(){
  onSnapshot(salesCol,s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));ready()},fail);
  onSnapshot(closingsCol,s=>{closings=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.businessDate||b.id).localeCompare(String(a.businessDate||a.id)));ready()},fail);
  onSnapshot(cashMovementsCol,s=>{cashMovements=s.docs.map(d=>({id:d.id,...d.data()}));ready()},fail);
  onSnapshot(menuRef,s=>{const d=s.data()||{};catalog={categories:Array.isArray(d.categories)?d.categories:[],items:Array.isArray(d.items)?d.items:[]};ready()},fail);
  onSnapshot(stocksCol,s=>{stocks=s.docs.map(d=>({id:d.id,...d.data()}));ready()},fail);
  onSnapshot(stockMovesCol,s=>{stockMovements=s.docs.map(d=>({id:d.id,...d.data()}));ready()},fail);
  onSnapshot(internalConsumptionsCol,s=>{internalConsumptions=s.docs.map(d=>({id:d.id,...d.data()}));ready()},fail);
  onSnapshot(settingsRef,s=>{const d=s.data()||{};currentBusinessDate=d.currentBusinessDate||today();currentBusinessDayStartedAtMs=Number(d.currentBusinessDayStartedAtMs)||0;if(period==="today"){range={start:currentBusinessDate,end:currentBusinessDate};el.startDate.value=range.start;el.endDate.value=range.end}ready()},fail);
}
function ready(){loaded++;el.connection.innerHTML='<i class="fa-solid fa-circle-check"></i> Canlı veri';el.connection.classList.remove("error");render()}
function fail(error){console.error(error);el.connection.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';el.connection.classList.add("error");show("Rapor verileri alınamadı.")}

function buildReport(){
  const selected=sales.filter(s=>{const date=s.businessDate||dateFromTimestamp(s.closedAt||s.createdAt),inRange=date>=range.start&&date<=range.end;if(!inRange)return false;if(range.start===currentBusinessDate&&range.end===currentBusinessDate)return reportTime(s)>=currentBusinessDayStartedAtMs;return true});
  const result=emptyReport(),products=new Map();
  for(const sale of selected){
    if(["merchant-topup","merchant-topup-correction"].includes(sale.recordType))continue
    if(["merchant-delivery","merchant-manual-delivery"].includes(sale.recordType))continue
    if(["payment","credit-payment","credit-topup"].includes(sale.recordType)){const tip=num(sale.tipAmount),cash=Math.max(0,num(sale.cashAmount??(sale.paymentType==="cash"?sale.amount:0))-tip),bank=num(sale.transferAmount),card=num(sale.cardAmount??(sale.paymentType==="card"?sale.amount:0));result.cashTotal+=cash;result.transferTotal+=bank;result.cardTotal+=card;result.tipTotal+=tip;result.salesIncomeRows.push(normalizeSaleIncome(sale,cash,bank,card,tip));continue}
    if(sale.recordType!=="sale"&&sale.items==null)continue;
    const tip=num(sale.tipAmount),rounding=num(sale.roundingDiscount)||Math.max(0,-num(sale.roundingAmount));
    result.salesTotal+=Math.max(0,(num(sale.baseTotal)||sumBillableItems(sale.items))-rounding);
    result.cashTotal+=Math.max(0,num(sale.cashAmount??(sale.paymentType==="cash"?(sale.paymentAmount??sale.paidTotal):0))-tip);
    result.transferTotal+=num(sale.transferAmount);
    result.cardTotal+=num(sale.cardAmount??(sale.paymentType==="card"?(sale.paymentAmount??sale.paidTotal):0));
    result.tipTotal+=tip;
    result.roundingTotal+=rounding;
    result.orderCount++;
    result.salesIncomeRows.push(normalizeSaleIncome(sale,Math.max(0,num(sale.cashAmount??(sale.paymentType==="cash"?(sale.paymentAmount??sale.paidTotal):0))-tip),num(sale.transferAmount),num(sale.cardAmount??(sale.paymentType==="card"?(sale.paymentAmount??sale.paidTotal):0)),tip));
    for(const item of sale.items||[]){
      const qty=num(item.quantity),price=num(item.unitPrice);
      if(item.complimentary){result.giftCount+=qty;continue}
      result.itemCount+=qty;
      const id=item.id||`${item.name}|${price}`,menuItem=catalog.items.find(x=>x.id===item.id),categoryId=menuItem?.categoryId||"other",current=products.get(id)||{id,name:item.name||menuItem?.name||"Ürün",quantity:0,total:0,categoryId};
      current.quantity+=qty;current.total+=qty*price;products.set(id,current);
    }
  }
  for(const movement of cashMovements){
    if(!cashMovementInRange(movement)||movement.type==="transfer")continue;
    const amount=num(movement.amount);
    if(movement.type==="expense"){
      result.expenseMovements.push(movement);result.expenseTotal+=amount;
      if(movement.account==="cash")result.cashExpenseTotal+=amount;
      if(movement.account==="bank")result.bankExpenseTotal+=amount;
      if(movement.account==="creditCard"||movement.account==="card")result.creditCardExpenseTotal+=amount;
    }
    if(movement.type==="income"&&movement.automatic!==true){result.incomeMovements.push(movement);result.manualIncomeTotal+=amount}
  }
  result.products=[...products.values()].sort((a,b)=>b.quantity-a.quantity||b.total-a.total);
  const salesIncomeTotal=result.cashTotal+result.transferTotal+result.cardTotal+result.tipTotal;
  result.incomeGroups=groupMoneyMovements(result.incomeMovements,"income");
  if(salesIncomeTotal>0)result.incomeGroups.unshift({name:"Adisyon ve Satış Gelirleri",total:salesIncomeTotal,cash:result.cashTotal+result.tipTotal,bank:result.transferTotal,card:result.cardTotal,rows:result.salesIncomeRows.filter(x=>x.amount>0),type:"income",icon:"fa-receipt",sales:true});
  result.expenseGroups=groupMoneyMovements(result.expenseMovements,"expense");
  result.totalIncome=salesIncomeTotal+result.manualIncomeTotal;
  result.netCashFlow=result.totalIncome-result.expenseTotal;
  const purchases=purchaseReportData(),internal=internalReportData();
  result.stockPurchaseTotal=purchases.total;result.internalCostTotal=internal.totalCost;
  return result;
}
function render(){
  report=buildReport();
  el.periodLabel.textContent=`${formatDate(range.start)}${range.start===range.end?"":` – ${formatDate(range.end)}`}`;
  el.salesTotal.textContent=money(report.salesTotal);el.cashTotal.textContent=money(report.cashTotal);el.transferTotal.textContent=money(report.transferTotal);el.cardTotal.textContent=money(report.cardTotal||0);el.manualIncomeTotal.textContent=money(report.manualIncomeTotal);el.cashExpenseTotal.textContent=money(report.cashExpenseTotal||0);el.bankExpenseTotal.textContent=money(report.bankExpenseTotal||0);el.creditCardExpenseTotal.textContent=money(report.creditCardExpenseTotal||0);el.expenseTotal.textContent=money(report.expenseTotal||0);el.itemCount.textContent=formatNumber(report.itemCount);el.orderCount.textContent=formatNumber(report.orderCount);el.giftCount.textContent=formatNumber(report.giftCount);el.tipTotal.textContent=money(report.tipTotal);el.roundingTotal.textContent=money(report.roundingTotal);
  el.periodIncomeTotal.textContent=money(report.totalIncome);el.periodExpenseTotal.textContent=money(report.expenseTotal);el.periodNetTotal.textContent=money(report.netCashFlow);el.periodNetTotal.closest("article").classList.toggle("negative",report.netCashFlow<0);el.periodStockPurchaseTotal.textContent=money(report.stockPurchaseTotal);el.periodInternalCostTotal.textContent=money(report.internalCostTotal);
  renderMovementGroups();renderTabs();renderProducts();renderRanking();renderCategories();renderPurchases();renderInternalConsumptions();renderStockOptions();renderStockReport();renderClosings();
  if(selectedMovementGroup&&el.movementDetailDialog.open)openMovementDetail(selectedMovementGroup.type,selectedMovementGroup.name);
}
function renderTabs(){const cats=catalog.categories.filter(c=>report.products.some(p=>p.categoryId===c.id));el.categoryTabs.innerHTML=`<button class="${category==="all"?"active":""}" data-category="all">Tümü</button>`+cats.map(c=>`<button class="${category===c.id?"active":""}" data-category="${esc(c.id)}">${esc(c.name)}</button>`).join("")}
function renderProducts(){const q=el.productSearch.value.trim().toLocaleLowerCase("tr-TR"),items=report.products.filter(p=>(category==="all"||p.categoryId===category)&&p.name.toLocaleLowerCase("tr-TR").includes(q));el.productReport.innerHTML=items.map(p=>`<div class="product-row"><div class="product-copy"><strong>${esc(p.name)}</strong><span>${esc(categoryName(p.categoryId))}</span></div><b>${formatNumber(p.quantity)} Adet</b><em>${money(p.total)}</em></div>`).join("");el.productEmpty.hidden=items.length>0}
function renderRanking(){const top=report.products.slice(0,5),least=[...report.products].sort((a,b)=>a.quantity-b.quantity||a.total-b.total).slice(0,5),max=top[0]?.quantity||1,row=(p,i)=>`<div class="ranking-item"><span>${i+1}</span><div><strong>${esc(p.name)}</strong><small>${Math.round(p.quantity/max*100)}% Satış yoğunluğu</small></div><b>${formatNumber(p.quantity)} Adet</b></div>`;el.rankingList.innerHTML=top.length?`<p class="ranking-group-title">En çok satan 5 Ürün</p>${top.map(row).join("")}<p class="ranking-group-title">En az satan 5 Ürün</p>${least.map(row).join("")}`:"";el.rankingEmpty.hidden=top.length>0}
function renderCategories(){const map=new Map();for(const p of report.products){const key=p.categoryId||"other",x=map.get(key)||{name:categoryName(key),quantity:0,total:0};x.quantity+=p.quantity;x.total+=p.total;map.set(key,x)}const items=[...map.values()].sort((a,b)=>b.quantity-a.quantity),max=items[0]?.quantity||1;el.categoryReport.innerHTML=items.map(x=>`<article class="category-card"><header><h3>${esc(x.name)}</h3><b>${formatNumber(x.quantity)} Adet</b></header><div class="bar"><i style="width:${Math.max(4,x.quantity/max*100)}%"></i></div><p>${money(x.total)} Ürün Toplamı</p></article>`).join("")||'<p class="empty">Seçilen dönemde kategori verisi bulunmuyor.</p>'}
function cashMovementInRange(movement){const date=String(movement.businessDate||dateFromTimestamp(movement.createdAt)||"");if(date<range.start||date>range.end)return false;if(range.start===currentBusinessDate&&range.end===currentBusinessDate&&currentBusinessDayStartedAtMs&&reportTime(movement)&&reportTime(movement)<currentBusinessDayStartedAtMs)return false;return true}
function normalizeSaleIncome(sale,cash,bank,card,tip){const type=["payment","credit-payment","credit-topup"].includes(sale.recordType),label=type?"Açık Hesap Tahsilatı":String(sale.tableName||sale.orderName||sale.description||"Adisyon Satışı");return{...sale,description:label,category:"Adisyon ve Satış Gelirleri",businessDate:sale.businessDate||dateFromTimestamp(sale.closedAt||sale.createdAt),createdAtMs:reportTime(sale),amount:cash+bank+card+tip,accountBreakdown:{cash:cash+tip,bank,card},automatic:true}}
function groupMoneyMovements(rows,type){const groups=new Map();for(const row of rows){const name=String(row.category||"Diğer"),current=groups.get(name)||{name,total:0,cash:0,bank:0,card:0,rows:[],type,icon:movementCategoryIcon(name)};const amount=num(row.amount);current.total+=amount;if(row.account==="cash")current.cash+=amount;if(row.account==="bank")current.bank+=amount;if(row.account==="card"||row.account==="creditCard")current.card+=amount;current.rows.push(row);groups.set(name,current)}return[...groups.values()].map(group=>({...group,rows:group.rows.sort((a,b)=>reportTime(b)-reportTime(a))})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,"tr"))}
function movementCategoryIcon(name){const value=String(name).toLocaleLowerCase("tr-TR");if(value.includes("personel")||value.includes("maaş"))return"fa-users";if(value.includes("fatura"))return"fa-file-invoice";if(value.includes("toptancı")||value.includes("malzeme")||value.includes("stok"))return"fa-truck-ramp-box";if(value.includes("kira"))return"fa-house";if(value.includes("yemek"))return"fa-utensils";if(value.includes("satış")||value.includes("adisyon"))return"fa-receipt";return"fa-wallet"}
function movementChips(group,type){const labels=[["cash","Nakit"],["bank","Banka/Havale"],["card",type==="expense"?"Kredi Kartı":"Kart/POS"]];return labels.filter(([key])=>num(group[key])>0).map(([key,label])=>`<span><b>${label}</b> ${money(group[key])}</span>`).join("")}
function movementGroupMarkup(group){return`<button class="movement-category-card" type="button" data-movement-type="${group.type}" data-movement-name="${esc(group.name)}"><i class="fa-solid ${group.icon||movementCategoryIcon(group.name)}"></i><div class="movement-category-copy"><span>${group.rows.length} İşlem</span><strong>${esc(group.name)}</strong><div class="movement-category-chips">${movementChips(group,group.type)||"<span>Ödeme türü belirtilmemiş</span>"}</div></div><b>${group.type==="income"?"+":"−"} ${money(group.total)}</b><em>Detayı Gör <i class="fa-solid fa-chevron-right"></i></em></button>`}
function renderMovementGroups(){el.incomeCategorySummary.innerHTML=report.incomeGroups.map(movementGroupMarkup).join("");el.expenseCategorySummary.innerHTML=report.expenseGroups.map(movementGroupMarkup).join("");el.incomeCategoryEmpty.hidden=report.incomeGroups.length>0;el.expenseCategoryEmpty.hidden=report.expenseGroups.length>0}
function movementGroupAction(event){const button=event.target.closest("[data-movement-name]");if(button)openMovementDetail(button.dataset.movementType,button.dataset.movementName)}
function openMovementDetail(type,name){const groups=type==="income"?report.incomeGroups:report.expenseGroups,group=groups.find(x=>x.name===name);if(!group){closeMovementDetail();return}selectedMovementGroup={type,name};el.movementDetailTitle.textContent=group.name;el.movementDetailPeriod.textContent=`${formatDate(range.start)}${range.start===range.end?"":` – ${formatDate(range.end)}`} • ${type==="income"?"Gelir":"Gider"} detayı`;el.movementDetailCount.textContent=`${group.rows.length} İşlem`;el.movementDetailSummary.innerHTML=[["Toplam",group.total,"fa-calculator"],["Nakit",group.cash,"fa-money-bill-wave"],["Banka/Havale",group.bank,"fa-building-columns"],[type==="income"?"Kart/POS":"Kredi Kartı",group.card,"fa-credit-card"]].map(x=>`<article><i class="fa-solid ${x[2]}"></i><span>${x[0]}</span><strong>${money(x[1])}</strong></article>`).join("");el.movementDetailList.innerHTML=group.rows.map(row=>movementDetailMarkup(row,type)).join("");el.movementDetailEmpty.hidden=group.rows.length>0;if(!el.movementDetailDialog.open)el.movementDetailDialog.showModal()}
function movementDetailMarkup(row,type){const breakdown=row.accountBreakdown||{},payments=Object.keys(breakdown).length?[["cash","Nakit"],["bank","Banka/Havale"],["card","Kart/POS"]].filter(([key])=>num(breakdown[key])>0).map(([key,label])=>`${label}: ${money(breakdown[key])}`).join(" • "):accountLabel(row.account,type),time=formatTime(reportTime(row));return`<article class="movement-detail-row ${type}"><i class="fa-solid ${movementCategoryIcon(row.category)}"></i><div><strong>${esc(row.description||row.category||"İşlem")}</strong><small>${formatDate(row.businessDate||dateFromTimestamp(row.createdAt))}${time!=="—"?` • ${time}`:""}</small><span>${esc(payments)}</span></div><b>${type==="income"?"+":"−"} ${money(row.amount)}</b></article>`}
function accountLabel(account,type){if(account==="cash")return"Nakit";if(account==="bank")return"Banka/Havale";if(account==="card")return type==="expense"?"Kredi Kartı":"Kart/POS";if(account==="creditCard")return"Kredi Kartı";return"Ödeme türü belirtilmemiş"}
function closeMovementDetail(){if(el.movementDetailDialog.open)el.movementDetailDialog.close();selectedMovementGroup=null}
function purchaseReportData(){const grouped=new Map();for(const move of stockMovements){const date=movementDate(move);if((move.type!=="in"&&move.type!=="initial")||date<range.start||date>range.end)continue;const stock=stocks.find(x=>x.id===move.stockItemId)||{id:move.stockItemId,name:move.stockName||"Stok",unitsPerPackage:move.unitsPerPackage||1,packageUnit:"koli"},key=stock.id||move.stockName,current=grouped.get(key)||{name:stock.name||move.stockName||"Stok",packages:0,units:0,total:0,entries:0};current.packages+=movementPackages(move,stock);current.units+=num(move.amount);current.total+=movementPurchase(move,stock);current.entries++;grouped.set(key,current)}const items=[...grouped.values()].sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,"tr"));return{items,packages:items.reduce((sum,x)=>sum+x.packages,0),units:items.reduce((sum,x)=>sum+x.units,0),total:items.reduce((sum,x)=>sum+x.total,0)}}
function renderPurchases(){const data=purchaseReportData();el.purchaseProductCount.textContent=formatNumber(data.items.length);el.purchasePackageCount.textContent=formatNumber(data.packages);el.purchaseUnitCount.textContent=formatNumber(data.units);el.allPurchaseTotal.textContent=money(data.total);el.purchaseList.innerHTML=data.items.map(x=>`<article class="purchase-row"><i class="fa-solid fa-boxes-stacked"></i><div><strong>${esc(x.name)}</strong><small>${x.entries} Stok Girişi • ${formatNumber(x.packages)} Koli • ${formatNumber(x.units)} Adet</small></div><b>${money(x.total)}</b></article>`).join("");el.purchaseEmpty.hidden=data.items.length>0}
function internalReportData(){const records=internalConsumptions.filter(x=>{const date=String(x.businessDate||dateFromTimestamp(x.createdAt)||"");if(date<range.start||date>range.end)return false;if(range.start===currentBusinessDate&&range.end===currentBusinessDate&&currentBusinessDayStartedAtMs)return reportTime(x)>=currentBusinessDayStartedAtMs;return true}).sort((a,b)=>reportTime(b)-reportTime(a)),products=new Map();let total=0,totalCost=0;for(const record of records)for(const item of record.items||[]){const name=String(item.name||"Ürün"),qty=num(item.quantity),cost=internalItemCost(item);products.set(name,(products.get(name)||0)+qty);total+=qty;totalCost+=cost}return{records,products,total,totalCost}}
function renderInternalConsumptions(){
  const {records,products,total,totalCost}=internalReportData();
  el.internalRecordCount.textContent=formatNumber(records.length);el.internalProductCount.textContent=formatNumber(products.size);el.internalQuantity.textContent=`${formatNumber(total)} Adet`;el.internalCost.textContent=money(totalCost);
  el.internalConsumptionList.innerHTML=records.map(record=>{const items=record.items||[],recordCost=num(record.totalCost)||items.reduce((sum,item)=>sum+internalItemCost(item),0),list=items.map(item=>`${esc(item.name||"Ürün")} <b>${formatNumber(item.quantity)} Adet</b>`).join(" • ");return`<article class="internal-consumption-row"><i class="fa-solid fa-box-open"></i><div><strong>${formatDate(record.businessDate||dateFromTimestamp(record.createdAt))} • ${formatTime(reportTime(record))}</strong><small>${record.note?esc(record.note):"İşletme içi kullanım"}</small><span>${list||"Ürün bilgisi bulunmuyor"}</span></div><b>${formatNumber(record.totalQuantity||items.reduce((sum,item)=>sum+num(item.quantity),0))} Adet<small>${money(recordCost)}</small></b></article>`}).join("");
  el.internalConsumptionEmpty.hidden=records.length>0;
}
function internalItemCost(item){if(num(item.totalCost)>0)return num(item.totalCost);const stock=stocks.find(x=>x.linkedMenuItemId===item.id);return num(item.quantity)*num(stock?.unitCost)}
function renderStockOptions(){const selected=el.stockProductSelect.value,items=stocks.filter(x=>x.active!==false&&x.linkedMenuItemId).sort((a,b)=>String(a.name).localeCompare(String(b.name),"tr"));el.stockProductSelect.innerHTML='<option value="">Stok Ürünü seçin</option>'+items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");if(items.some(x=>x.id===selected))el.stockProductSelect.value=selected}
function renderStockReport(){const stock=stocks.find(x=>x.id===el.stockProductSelect.value);el.stockReportHint.hidden=!!stock;el.stockReportContent.hidden=!stock;if(!stock)return;const entries=stockMovements.filter(x=>x.stockItemId===stock.id&&(x.type==="in"||x.type==="initial")&&movementDate(x)>=range.start&&movementDate(x)<=range.end).sort((a,b)=>movementDate(a).localeCompare(movementDate(b))),packageCount=entries.reduce((sum,x)=>sum+movementPackages(x,stock),0),received=entries.reduce((sum,x)=>sum+num(x.amount),0),purchaseTotal=entries.reduce((sum,x)=>sum+movementPurchase(x,stock),0),averageCost=received>0?purchaseTotal/received:num(stock.unitCost);let sold=0,revenue=0;for(const sale of sales){const date=sale.businessDate||dateFromTimestamp(sale.closedAt||sale.createdAt);if(date<range.start||date>range.end||["payment","credit-payment","credit-topup"].includes(sale.recordType))continue;for(const item of sale.items||[]){if(item.id!==stock.linkedMenuItemId||item.complimentary)continue;const qty=num(item.quantity);sold+=qty;revenue+=qty*num(item.unitPrice)}}const profit=revenue-sold*averageCost;el.stockPackages.textContent=formatNumber(packageCount);el.stockReceived.textContent=formatNumber(received);el.stockPurchaseTotal.textContent=money(purchaseTotal);el.stockAverageCost.textContent=money(averageCost);el.stockSold.textContent=formatNumber(sold);el.stockRevenue.textContent=money(revenue);el.stockProfit.textContent=money(profit);el.stockRemaining.textContent=`${formatNumber(stock.quantity)} ${displayUnit(stock.unit||"adet")}`;el.stockEntryCount.textContent=`${entries.length} İşlem`;el.stockEntryList.innerHTML=entries.map(x=>{const packages=movementPackages(x,stock),amount=num(x.amount),paid=movementPurchase(x,stock),cost=amount>0?paid/amount:0;return`<div class="stock-entry-row"><i class="fa-solid fa-box"></i><div><strong>${formatDate(movementDate(x))}</strong><small>${x.note?esc(x.note):"Stok Girişi"}</small></div><b>${formatNumber(packages)} Koli</b><b>${formatNumber(amount)} Adet</b><b>${money(paid)} • ${money(cost)}/Adet</b></div>`}).join("");el.stockEntryEmpty.hidden=entries.length>0}
function closingCash(c){return num(c.cashIncomeTotal??c.cashTotal)}function closingCashSales(c){return Math.max(0,closingCash(c)-num(c.tipTotal))}function closingBank(c){return num(c.bankIncomeTotal??c.transferTotal)}function closingNetSales(c){return Math.max(0,num(c.salesTotal)-num(c.roundingTotal))}
function renderClosings(){const items=closings.slice(0,40);el.closingList.innerHTML=items.map(c=>`<button class="closing-row" type="button" data-closing-id="${esc(c.id)}"><i class="fa-solid fa-calendar-check"></i><div><strong>${formatDate(c.businessDate||c.id)}</strong><small>${formatNumber(c.orderCount)} Adisyon • ${formatNumber(c.itemCount)} Ürün • ${formatNumber(c.brewedPotCount)} Demlik</small></div><b>${money(closingNetSales(c))} Satış</b><b>${money(closingCashSales(c))} Nakit</b><b>${money(closingBank(c))} Banka</b><i class="fa-solid fa-chevron-right closing-arrow"></i></button>`).join("");el.closingEmpty.hidden=items.length>0}

function openClosingDetail(id){
  const closing=closings.find(x=>x.id===id);
  if(!closing)return show("Gün sonu kaydı bulunamadı.");
  selectedClosing=closing;
  const products=Array.isArray(closing.products)?closing.products:[];
  el.closingDetailTitle.textContent=`${formatDate(closing.businessDate||closing.id)} Gün Sonu`;
  el.closingDetailPeriod.textContent=closing.closedAtMs?`${formatDateTime(closing.businessDayStartedAtMs)} — ${formatDateTime(closing.closedAtMs)}`:"Kaydedilmiş gün sonu raporu";
  el.closingDetailSummary.innerHTML=[
    ["Toplam Satış",money(closingNetSales(closing)),"fa-chart-line"],
    ["Nakit Satış",money(closingCashSales(closing)),"fa-money-bill-wave"],
    ["Banka Geliri",money(closingBank(closing)),"fa-building-columns"],
    ["Demlenen Çay",`${formatNumber(closing.brewedPotCount)} Demlik`,"fa-mug-hot"],
    ["Bahşiş",money(closing.tipTotal),"fa-hand-holding-dollar"],
    ["Hesap yuvarlama",money(closing.roundingTotal),"fa-scale-balanced"],
    ["Kapanan Adisyon",formatNumber(closing.orderCount),"fa-receipt"],
    ["İkram",`${formatNumber(closing.giftCount)} Adet`,"fa-gift"]
  ].map(x=>`<article><i class="fa-solid ${x[2]}"></i><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join("");
  el.closingProductCount.textContent=`${formatNumber(products.reduce((sum,x)=>sum+num(x.quantity),0))} Adet`;
  el.closingDetailProducts.innerHTML=products.map(p=>`<article><div><strong>${esc(p.name||"Ürün")}</strong><small>${formatNumber(p.quantity)} × ${money(p.unitPrice)}</small></div><b>${money(p.total??num(p.quantity)*num(p.unitPrice))}</b></article>`).join("");
  el.closingDetailEmpty.hidden=products.length>0;
  el.closingDetailDialog.showModal();
}
function closeClosingDetail(){el.closingDetailDialog.close();selectedClosing=null}
function exportClosingDetailPdf(){if(!selectedClosing)return;const c=selectedClosing,rows=(c.products||[]).map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${formatNumber(p.quantity)}</td><td>${money(p.unitPrice)}</td><td>${money(p.total)}</td></tr>`).join(""),body=`<table><thead><tr><th>No</th><th>Ürün</th><th>Adet</th><th>Birim Fiyat</th><th>Toplam</th></tr></thead><tbody>${rows}</tbody></table>`;openCorporatePdf(`${formatDate(c.businessDate||c.id)} Gün Sonu Raporu`,body,[["Demlenen Çay",`${formatNumber(c.brewedPotCount)} Demlik`],["Nakit Satış",money(closingCashSales(c))],["Banka Satış",money(closingBank(c))],["Bahşiş",money(c.tipTotal)],["Yuvarlama",money(c.roundingTotal)],["Toplam Satış",money(closingNetSales(c))]])}
function exportClosingDetailExcel(){if(!selectedClosing)return;const c=selectedClosing,rows=(c.products||[]).map(p=>`<Row><Cell><Data ss:Type="String">${xml(p.name)}</Data></Cell><Cell><Data ss:Type="Number">${num(p.quantity)}</Data></Cell><Cell><Data ss:Type="Number">${num(p.unitPrice)}</Data></Cell><Cell><Data ss:Type="Number">${num(p.total)}</Data></Cell></Row>`).join(""),summary=[["Demlenen Çay",num(c.brewedPotCount)],["Toplam Satış",closingNetSales(c)],["Nakit Satış",closingCashSales(c)],["Banka Satış",closingBank(c)],["Bahşiş",num(c.tipTotal)],["Hesap Yuvarlama",num(c.roundingTotal)],["Kapanan Adisyon",num(c.orderCount)]].map(x=>`<Row><Cell><Data ss:Type="String">${x[0]}</Data></Cell><Cell/><Cell/><Cell><Data ss:Type="Number">${x[1]}</Data></Cell></Row>`).join(""),content=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Gün Sonu"><Table><Row><Cell><Data ss:Type="String">Ürün</Data></Cell><Cell><Data ss:Type="String">Adet</Data></Cell><Cell><Data ss:Type="String">Birim Fiyat</Data></Cell><Cell><Data ss:Type="String">Toplam</Data></Cell></Row>${rows}${summary}</Table></Worksheet></Workbook>`;download(content,`gun-sonu-${c.businessDate||c.id}.xls`,"application/vnd.ms-excel")}

function exportPdf(){const productRows=report.products.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${esc(categoryName(p.categoryId))}</td><td>${formatNumber(p.quantity)}</td><td>${money(p.total)}</td></tr>`).join(""),incomeRows=report.incomeGroups.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.cash)}</td><td>${money(x.bank)}</td><td>${money(x.card)}</td><td>${money(x.total)}</td></tr>`).join(""),expenseRows=report.expenseGroups.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.cash)}</td><td>${money(x.bank)}</td><td>${money(x.card)}</td><td>${money(x.total)}</td></tr>`).join(""),body=`<h2>Gelir Kaynakları</h2><table><thead><tr><th>Kategori</th><th>Nakit</th><th>Banka</th><th>Kart/POS</th><th>Toplam</th></tr></thead><tbody>${incomeRows}</tbody></table><h2>Gider Kategorileri</h2><table><thead><tr><th>Kategori</th><th>Nakit</th><th>Banka</th><th>Kredi Kartı</th><th>Toplam</th></tr></thead><tbody>${expenseRows}</tbody></table><h2>Satılan Ürünler</h2><table><thead><tr><th>No</th><th>Ürün</th><th>Kategori</th><th>Adet</th><th>Toplam</th></tr></thead><tbody>${productRows}</tbody></table>`;openCorporatePdf(`Dönem Raporu — ${formatDate(range.start)}${range.start===range.end?"":` / ${formatDate(range.end)}`}`,body,[["Toplam Para Girişi",money(report.totalIncome)],["Toplam Gider",money(report.expenseTotal)],["Gelir − Gider",money(report.netCashFlow)],["Alınan Stok",money(report.stockPurchaseTotal)],["Dahili Tüketim",money(report.internalCostTotal)]])}
function exportExcel(){const row=(name,cash,bank,card,total)=>`<Row><Cell><Data ss:Type="String">${xml(name)}</Data></Cell><Cell><Data ss:Type="Number">${cash}</Data></Cell><Cell><Data ss:Type="Number">${bank}</Data></Cell><Cell><Data ss:Type="Number">${card}</Data></Cell><Cell><Data ss:Type="Number">${total}</Data></Cell></Row>`,head=title=>`<Row><Cell><Data ss:Type="String">${title}</Data></Cell></Row><Row><Cell><Data ss:Type="String">Kategori</Data></Cell><Cell><Data ss:Type="String">Nakit</Data></Cell><Cell><Data ss:Type="String">Banka</Data></Cell><Cell><Data ss:Type="String">Kart</Data></Cell><Cell><Data ss:Type="String">Toplam</Data></Cell></Row>`,incomeRows=report.incomeGroups.map(x=>row(x.name,x.cash,x.bank,x.card,x.total)).join(""),expenseRows=report.expenseGroups.map(x=>row(x.name,x.cash,x.bank,x.card,x.total)).join(""),productRows=report.products.map(p=>`<Row><Cell><Data ss:Type="String">${xml(p.name)}</Data></Cell><Cell><Data ss:Type="String">${xml(categoryName(p.categoryId))}</Data></Cell><Cell><Data ss:Type="Number">${p.quantity}</Data></Cell><Cell><Data ss:Type="Number">${p.total}</Data></Cell></Row>`).join(""),summary=[["Toplam Para Girişi",report.totalIncome],["Toplam Gider",report.expenseTotal],["Gelir - Gider",report.netCashFlow],["Alınan Stok",report.stockPurchaseTotal],["Dahili Tüketim",report.internalCostTotal]].map(x=>`<Row><Cell><Data ss:Type="String">${x[0]}</Data></Cell><Cell/><Cell/><Cell/><Cell><Data ss:Type="Number">${x[1]}</Data></Cell></Row>`).join(""),content=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Dönem Raporu"><Table>${head("GELİR KAYNAKLARI")}${incomeRows}${head("GİDER KATEGORİLERİ")}${expenseRows}${summary}</Table></Worksheet><Worksheet ss:Name="Satılan Ürünler"><Table><Row><Cell><Data ss:Type="String">Ürün</Data></Cell><Cell><Data ss:Type="String">Kategori</Data></Cell><Cell><Data ss:Type="String">Adet</Data></Cell><Cell><Data ss:Type="String">Toplam</Data></Cell></Row>${productRows}</Table></Worksheet></Workbook>`;download(content,`donem-raporu-${range.start}-${range.end}.xls`,"application/vnd.ms-excel")}

function periodRange(type){const d=new Date(`${today()}T12:00:00`);if(type==="week"){const day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);return{start:iso(start),end:iso(d)}}if(type==="month")return{start:`${today().slice(0,7)}-01`,end:today()};return{start:today(),end:today()}}
function emptyReport(){return{salesTotal:0,cashTotal:0,transferTotal:0,cardTotal:0,manualIncomeTotal:0,totalIncome:0,netCashFlow:0,cashExpenseTotal:0,bankExpenseTotal:0,creditCardExpenseTotal:0,expenseTotal:0,stockPurchaseTotal:0,internalCostTotal:0,itemCount:0,orderCount:0,giftCount:0,tipTotal:0,roundingTotal:0,merchantMarkaCount:0,merchantTopupTotal:0,products:[],salesIncomeRows:[],incomeMovements:[],expenseMovements:[],incomeGroups:[],expenseGroups:[]}}
function sumBillableItems(items){return(items||[]).filter(x=>!x.complimentary).reduce((sum,x)=>sum+num(x.unitPrice)*num(x.quantity),0)}
function movementDate(x){return String(x.operationDate||dateFromTimestamp(x.createdAt)||"")}
function movementPackages(x,stock){if(num(x.packageCount)>0)return num(x.packageCount);if(x.enteredUnit&&(x.enteredUnit===stock.packageUnit||x.enteredUnit==="koli"))return num(x.enteredAmount);return num(x.amount)/Math.max(1,num(x.unitsPerPackage)||num(stock.unitsPerPackage)||1)}
function movementPurchase(x,stock){if(num(x.purchaseTotal)>0)return num(x.purchaseTotal);if(x.purchasePriceBasis==="total")return num(x.purchasePrice);if(x.purchasePriceBasis==="package")return num(x.purchasePrice)*movementPackages(x,stock);if(x.purchasePriceBasis==="unit")return num(x.purchasePrice)*num(x.amount);return 0}
function categoryName(id){return catalog.categories.find(c=>c.id===id)?.name||(id==="other"?"Diğer":"Kategorisiz")}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}
function iso(d){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(d)}
function dateFromTimestamp(v){const d=v?.toDate?.();return d?new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(d):""}
function reportTime(v){return v.closedAt?.toMillis?.()||v.createdAt?.toMillis?.()||num(v.closedAtMs)||num(v.createdAtMs)}
function formatDate(v){const [y,m,d]=String(v||"").split("-");return y&&m&&d?`${d}.${m}.${y}`:"—"}
function formatDateTime(v){if(!num(v))return"—";return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(new Date(num(v)))}
function formatTime(v){if(!num(v))return"—";return new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(new Date(num(v)))}
function num(v){return Number(v)||0}
function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",minimumFractionDigits:num(v)%1?2:0}).format(num(v))}
function formatNumber(v){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(num(v))}
function displayUnit(v){const value=String(v||"");return value?value.charAt(0).toLocaleUpperCase("tr-TR")+value.slice(1).toLocaleLowerCase("tr-TR"):""}
function updateClock(){const n=new Date();$("currentTime").textContent=new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/Istanbul"}).format(n);$("currentDate").textContent=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"Europe/Istanbul"}).format(n).replace(/\./g,"/")}
function show(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),3000)}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function xml(v){return String(v??"").replace(/[<>&'"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]))}
function openCorporatePdf(title,body,totals){const popup=window.open("","_blank","width=1000,height=760");if(!popup)return show("PDF penceresi açılamadı. Açılır pencereye izin verin.");const logo=new URL("../assets/images/logo.png",location.href).href,created=new Intl.DateTimeFormat("tr-TR",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date());popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#342522;font:12px Arial,sans-serif}.watermark{position:fixed;inset:20% 15%;width:70%;height:60%;object-fit:contain;opacity:.045;z-index:-1}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #7d1b24;padding-bottom:12px}.brand img{width:90px}.brand p{margin:2px 0}.date{text-align:right}.title{text-align:center;color:#7d1b24;margin:22px 0 14px}table{width:100%;border-collapse:collapse}thead{display:table-header-group}th{background:#7d1b24;color:#fff}th,td{padding:9px;border:1px solid #d8c6ba;text-align:left}tbody tr:nth-child(even){background:#fff7ef}.totals{width:50%;margin:16px 0 0 auto;border:1px solid #d8c6ba}.totals div{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #eaded6}.totals div:last-child{border:0;background:#fff2e2;color:#7d1b24;font-weight:bold}</style></head><body><img class="watermark" src="${logo}"><header class="head"><div class="brand"><img src="${logo}"><p><b>Fatih Ali Altınlı</b></p><p>0554 118 08 06</p><p>Ulukavak Mah. Osmancık Cad. No:285<br>Çorum/Merkez</p></div><div class="date"><b>Oluşturma Tarihi</b><p>${created}</p></div></header><h1 class="title">${esc(title)}</h1>${body}<section class="totals">${totals.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</section><script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`);popup.document.close()}
