(()=>{"use strict";const $=s=>document.querySelector(s),els={name:$("#playerName"),best:$("#bestScore"),phase:$("#phaseText"),timer:$("#timer"),meter:$("#meterFill"),hint:$("#hint"),kettle:$("#kettle"),stream:$("#pourStream"),liquid:$("#teaLiquid"),splash:$("#splashLayer"),stars:$("#celebration"),result:$("#result"),resultTitle:$("#resultTitle"),resultScore:$("#resultScore"),resultMessage:$("#resultMessage"),resultTimer:$("#resultTimer"),start:$("#startButton"),pour:$("#pourButton"),sound:$("#soundButton"),nickDialog:$("#nickDialog"),nickInput:$("#nickInput"),nickError:$("#nickError"),nickCancel:$("#nickCancel"),nickSave:$("#nickSave"),changeNick:$("#changeNick")};let phase="idle",fill=0,pouring=false,muted=false,raf=0,last=0,timerId=0,overflowed=false,audio=null,noise=null,pourNode=null;
const NAME_KEY="fce_cay_ustasi_nick",BEST_KEY="fce_cay_ustasi_best";const getBest=()=>Number(localStorage.getItem(BEST_KEY)||0),setPlayer=()=>{els.name.textContent=localStorage.getItem(NAME_KEY)||"Misafir";els.best.textContent=getBest()};
function initAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)();const len=audio.sampleRate*2;noise=audio.createBuffer(1,len,audio.sampleRate);const d=noise.getChannelData(0);let v=0;for(let i=0;i<len;i++){v=v*.93+(Math.random()*2-1)*.07;d[i]=v}audio.resume()}
function tone(freq,dur=.12,type="sine",vol=.08,delay=0){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime+delay);g.gain.setValueAtTime(.001,audio.currentTime+delay);g.gain.exponentialRampToValueAtTime(vol,audio.currentTime+delay+.015);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+delay+dur);o.connect(g).connect(audio.destination);o.start(audio.currentTime+delay);o.stop(audio.currentTime+delay+dur+.03)}
function startPourSound(){if(muted||!audio||pourNode)return;const src=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();src.buffer=noise;src.loop=true;filter.type="bandpass";filter.frequency.value=1200;filter.Q.value=.55;gain.gain.value=.15;src.connect(filter).connect(gain).connect(audio.destination);src.start();pourNode={src,gain}}
function stopPourSound(){if(!pourNode)return;pourNode.gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);pourNode.src.stop(audio.currentTime+.1);pourNode=null}
function spoonSound(){if(muted||!audio)return;[980,1320,1760].forEach((f,i)=>tone(f,.08,"sine",.045,i*.12));setTimeout(()=>[1080,1480].forEach((f,i)=>tone(f,.07,"sine",.04,i*.14)),450)}
function setFill(v){fill=Math.max(0,v);const visual=Math.min(fill,100);els.liquid.style.height=visual+"%";els.meter.style.width=Math.min(fill,100)+"%";if(fill>100&&!overflowed){overflowed=true;splash();tone(125,.35,"sawtooth",.09)}}
function splash(){for(let i=0;i<18;i++){const d=document.createElement("i");d.style.left=(38+Math.random()*24)+"%";d.style.top=(42+Math.random()*15)+"%";d.style.setProperty("--x",(Math.random()*280-140)+"px");d.style.setProperty("--y",(Math.random()*240-100)+"px");els.splash.append(d);setTimeout(()=>d.remove(),950)}}
function sparkle(){for(let i=0;i<28;i++){const d=document.createElement("i");d.textContent=i%3?"★":"✦";d.style.left=(45+Math.random()*10)+"%";d.style.top=(48+Math.random()*8)+"%";d.style.setProperty("--x",(Math.random()*400-200)+"px");d.style.setProperty("--y",(Math.random()*340-190)+"px");d.style.animationDelay=(Math.random()*.7)+"s";els.stars.append(d);setTimeout(()=>d.remove(),2300)}}
function setPour(on){if(phase!=="play")return;pouring=on;els.kettle.classList.toggle("pouring",on);els.stream.classList.toggle("on",on);if(on)startPourSound();else stopPourSound()}
function frame(t){if(phase!=="play")return;if(!last)last=t;const dt=Math.min(40,t-last);last=t;if(pouring)setFill(fill+dt*.0145);raf=requestAnimationFrame(frame)}
function countdown(seconds,onTick,onDone){let left=seconds;els.timer.textContent=left;clearInterval(timerId);timerId=setInterval(()=>{left--;els.timer.textContent=Math.max(0,left);onTick?.(left);if(left<=0){clearInterval(timerId);onDone()}},1000)}
function begin(){initAudio();overflowed=false;setFill(0);els.result.hidden=true;els.splash.innerHTML="";els.stars.innerHTML="";els.start.hidden=true;els.pour.classList.add("active");els.pour.disabled=true;phase="ready";els.phase.textContent="Hazırlan!";els.hint.textContent="Demlik hazır... Çay doldurma 10 saniye sürecek.";els.kettle.classList.add("waiting");countdown(10,l=>{if(l<=3&&l>0)tone(520,.1,"sine",.05)},()=>{tone(820,.22,"sine",.08);els.kettle.classList.remove("waiting");phase="play";els.phase.textContent="Çayı Doldur";els.hint.textContent="Basılı tutunca çay akar, bırakınca durur.";els.pour.disabled=false;last=0;raf=requestAnimationFrame(frame);countdown(10,l=>{if(l<=3&&l>0)tone(650,.09,"square",.035)},finish)})}
function grade(){const target=90,diff=Math.abs(fill-target);if(fill>104)return{title:"Acemi Çaycı",msg:"Bardak taştı! Bir dahaki sefere daha erken bırak.",bonus:false};if(diff<=2)return{title:"Çay Ustası",msg:"Kusursuz dolum! İnce belli bardağın tam kıvamında.",bonus:true};if(diff<=6)return{title:"Usta Çaycı",msg:"Harika dolum! Ustalığa yalnızca bir yudum kaldı.",bonus:true};if(diff<=14)return{title:"Çay Kalfası",msg:"Gayet iyi! Biraz daha dikkatle usta olacaksın.",bonus:false};if(fill>=45)return{title:"Çay Çırağı",msg:"Fena değil; bardağı hedef çizgisine yaklaştır.",bonus:false};return{title:"Acemi Çaycı",msg:"Çay biraz eksik kaldı, yeniden denemelisin.",bonus:false}}
function finish(){if(phase!=="play")return;phase="result";setPour(false);cancelAnimationFrame(raf);els.pour.disabled=true;const g=grade(),accuracy=Math.max(0,100-Math.abs(fill-90)*4),overflowPenalty=Math.max(0,fill-100)*18;const score=Math.max(0,Math.round(accuracy*10-overflowPenalty));els.resultTitle.textContent=g.title;els.resultScore.textContent=score+" Puan";els.resultMessage.textContent=g.msg;els.result.hidden=false;if(score>getBest()){localStorage.setItem(BEST_KEY,String(score));els.best.textContent=score;els.resultMessage.textContent="Yeni rekor! "+g.msg}if(g.bonus){sparkle();spoonSound();setTimeout(()=>{tone(784,.18,"sine",.08);tone(988,.25,"sine",.07,.14)},850)}else tone(190,.3,"triangle",.07);let left=10;els.resultTimer.textContent=left;timerId=setInterval(()=>{left--;els.resultTimer.textContent=Math.max(0,left);if(left<=0){clearInterval(timerId);reset()}},1000)}
function reset(){phase="idle";els.result.hidden=true;els.start.hidden=false;els.pour.classList.remove("active");els.phase.textContent="Başlamaya Hazır";els.timer.textContent="10";els.hint.textContent="Başlat'a dokun, sonra doldurmak için basılı tut.";setFill(0);overflowed=false}
function openNick(required=false){els.nickCancel.hidden=required;els.nickInput.value=localStorage.getItem(NAME_KEY)||"";els.nickError.textContent="";els.nickDialog.showModal();setTimeout(()=>els.nickInput.focus(),100)}
els.start.addEventListener("click",()=>{if(!localStorage.getItem(NAME_KEY))openNick(true);else begin()});["pointerdown","touchstart"].forEach(e=>els.pour.addEventListener(e,ev=>{ev.preventDefault();setPour(true)},{passive:false}));["pointerup","pointercancel","pointerleave","touchend"].forEach(e=>els.pour.addEventListener(e,ev=>{ev.preventDefault();setPour(false)},{passive:false}));els.nickSave.addEventListener("click",e=>{e.preventDefault();const name=els.nickInput.value.trim().replace(/[<>]/g,"");if(name.length<2){els.nickError.textContent="Nick en az 2 karakter olmalı.";return}localStorage.setItem(NAME_KEY,name.slice(0,18));els.nickDialog.close();setPlayer();if(phase==="idle")begin()});els.nickCancel.addEventListener("click",()=>els.nickDialog.close());els.changeNick.addEventListener("click",()=>openNick(false));els.sound.addEventListener("click",()=>{muted=!muted;if(muted)stopPourSound();els.sound.innerHTML=`<i class="fa-solid fa-volume-${muted?"xmark":"high"}"></i>`});document.addEventListener("visibilitychange",()=>{if(document.hidden){setPour(false);if(phase==="play")finish()}});setPlayer();if(!localStorage.getItem(NAME_KEY))setTimeout(()=>openNick(true),350)})();
