import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{addDoc,collection,doc,getFirestore,limit,onSnapshot,orderBy,query,serverTimestamp,updateDoc,where}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{ADMIN_UID,firebaseConfig}from"../firebase-config.js";
const defaultApp=initializeApp(firebaseConfig),legacyAuth=getAuth(defaultApp);
const app=initializeApp(firebaseConfig,"merchant-portal"),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let profile=null,orders=[],movements=[],uid="",toastTimer,pendingCancelOrder="";
const statusNames={pending:"Sipariş alındı",preparing:"Hazırlanıyor",on_the_way:"Yola çıktı",delivered:"Teslim edildi",cancelled:"İptal edildi"};
onAuthStateChanged(legacyAuth,user=>{if(user&&user.uid!==ADMIN_UID)signOut(legacyAuth).catch(console.error);});
$("logout").onclick=async()=>{await signOut(auth);location.replace("../esnaf-giris.html")};$("orderButton").onclick=()=>{if(!profile?.active)return toast("Hesabınız kullanıma kapalı.");$("dialogBalance").textContent=`${profile.balance||0} çay`;$("orderDialog").showModal()};$("closeDialog").onclick=()=>$("orderDialog").close();
$("quick").onclick=e=>{const b=e.target.closest("[data-count]");if(!b)return;$("quantity").value=b.dataset.count;document.querySelectorAll(".quick button").forEach(x=>x.classList.toggle("active",x===b))};
$("orderFilter").onchange=renderOrders;$("orderList").onclick=e=>{const b=e.target.closest("[data-cancel]");if(!b)return;pendingCancelOrder=b.dataset.cancel;$("cancelOrderDialog").showModal()};$("confirmCancelOrder").onclick=async()=>{if(!pendingCancelOrder)return;try{await updateDoc(doc(db,"merchantOrders",pendingCancelOrder),{status:"cancelled",cancelledAt:serverTimestamp(),updatedAt:serverTimestamp()});toast("Sipariş iptal edildi.");}catch{toast("Sipariş iptal edilemedi.")}finally{pendingCancelOrder=""}};
$("orderForm").onsubmit=async e=>{e.preventDefault();const quantity=Math.floor(Number($("quantity").value));if(!quantity||quantity<1||quantity>50)return;if(quantity>Number(profile.balance||0))return toast("Çay bakiyeniz bu sipariş için yetersiz.");$("submitOrder").disabled=true;try{await addDoc(collection(db,"merchantOrders"),{merchantId:uid,merchantName:profile.name||"",businessName:profile.businessName||"",quantity,note:$("note").value.trim(),status:"pending",createdAt:serverTimestamp(),createdAtMs:Date.now(),updatedAt:serverTimestamp()});$("orderDialog").close();$("orderForm").reset();toast("Siparişiniz alındı.");}catch(err){console.error(err);toast("Sipariş gönderilemedi.");}finally{$("submitOrder").disabled=false}};
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../esnaf-giris.html");return}uid=user.uid;let stopProfile=()=>{};stopProfile=onSnapshot(doc(db,"merchantProfiles",uid),{includeMetadataChanges:true},async snap=>{if(!snap.exists()){if(snap.metadata.fromCache)return;stopProfile();await signOut(auth);location.replace("../esnaf-giris.html?error=profile");return}if(snap.data().active===false){stopProfile();await signOut(auth);location.replace("../esnaf-giris.html?error=inactive");return}profile={id:snap.id,...snap.data()};renderProfile();subscribeLists();},error=>{console.error(error);toast("Profil bilgisi alınamadı. Firestore kurallarını kontrol edin.");});subscribeTea();});
let subscribed=false;function subscribeLists(){if(subscribed)return;subscribed=true;onSnapshot(query(collection(db,"merchantOrders"),where("merchantId","==",uid),limit(60)),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAtMs||0)-(a.createdAtMs||0));renderOrders()});onSnapshot(query(collection(db,"merchantBalanceMovements"),where("merchantId","==",uid),limit(30)),s=>{movements=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAtMs||0)-(a.createdAtMs||0));renderMovements()})}
function renderProfile(){const hour=new Date().getHours();$("greeting").textContent=hour<12?"Günaydın":hour<18?"İyi günler":"İyi akşamlar";$("businessName").textContent=profile.businessName||profile.name||"Esnafımız";$("balance").textContent=Math.floor(profile.balance||0);const low=Number(profile.balance||0)<=Number(profile.lowBalanceThreshold||10);$("balanceWarning").textContent=low?"Bakiyeniz azalıyor":"";$("balanceWarning").classList.toggle("is-low",low)}
function renderOrders(){const shown=$("orderFilter").value==="all"?orders:orders.filter(o=>!["delivered","cancelled"].includes(o.status));$("orderEmpty").hidden=shown.length>0;$("orderList").innerHTML=shown.map(o=>`<article class="order-item"><span class="order-icon"><i class="fa-solid fa-mug-hot"></i></span><div class="item-copy"><strong>${o.quantity} çay</strong><span>${dateTime(o.createdAtMs)}${o.note?` • ${esc(o.note)}`:""}</span>${o.status==="pending"?`<button data-cancel="${o.id}" style="justify-self:start;border:0;background:none;color:#8d2630;padding:4px 0;font-size:.72rem;cursor:pointer">Siparişi iptal et</button>`:""}</div><span class="status ${o.status}">${statusNames[o.status]||o.status}</span></article>`).join("")}
function renderMovements(){$("movementEmpty").hidden=movements.length>0;$("movementList").innerHTML=movements.map(m=>`<article class="movement-item"><span class="order-icon"><i class="fa-solid ${m.amount<0?"fa-mug-hot":"fa-plus"}"></i></span><div class="item-copy"><strong>${esc(m.description||"Bakiye hareketi")}</strong><span>${dateTime(m.createdAtMs)} • Kalan ${m.resultingBalance??0} çay</span></div><span class="move-amount ${m.amount<0?"minus":""}">${m.amount>0?"+":""}${m.amount} çay</span></article>`).join("")}
function subscribeTea(){onSnapshot(doc(db,"publicTea","status"),s=>renderTea(s.exists()?s.data():null),()=>renderTea(null))}
function renderTea(d){const brews=Array.isArray(d?.activeBrews)?d.activeBrews:[];if(d?.serviceOpen===false){$("teaTitle").textContent="Çay servisi kapalı";$("teaBadge").textContent="Servis kapalı";$("teaMinutes").textContent="—";$("teaMessage").textContent="Servis yeniden başladığında burada göreceksiniz.";$("teaDetail").textContent="";$("freshBar").style.width="0%";return}if(!brews.length){$("teaTitle").textContent="Şu anda aktif demlik yok";$("teaBadge").textContent="Dem bekleniyor";$("teaMinutes").textContent="0";$("teaMessage").textContent="Yeni dem başladığında burada göreceksiniz.";$("teaDetail").textContent="";$("freshBar").style.width="0%";return}const now=Date.now(),brew=brews[0],start=Number(brew.startedAtMs||now),ready=Number(brew.readyAtMs)||start+20*60000,elapsed=Math.max(0,now-start),freshAge=Math.max(0,now-ready),freshRemaining=Math.max(0,60-Math.floor(freshAge/60000)),pct=Math.max(0,Math.min(100,freshRemaining/60*100));$("teaTitle").textContent=brews.length>1?`${brews.length} demlik takipte`:"Demlik 1";$("freshBar").style.width=`${now<ready?Math.min(100,elapsed/(ready-start)*100):pct}%`;if(now<ready){const remain=Math.max(1,Math.ceil((ready-now)/60000));$("teaMinutes").textContent=remain;$("teaBadge").textContent="Demleniyor";$("teaMessage").textContent="Taze dem hazırlanıyor.";$("teaDetail").textContent=`Hazır olmasına yaklaşık ${remain} dakika kaldı.`}else if(freshAge<60*60000){$("teaMinutes").textContent=freshRemaining;$("teaBadge").textContent="Servise hazır";$("teaMessage").textContent="Çayınız taze, şimdi söyleyebilirsiniz.";$("teaDetail").textContent=`${brews.length} aktif demlik • ${freshRemaining} dakika tazelik süresi.`}else{$("teaMinutes").textContent="0";$("teaBadge").textContent="Süresi doldu";$("teaMessage").textContent="Yeni dem için hazırlık yapılıyor.";$("teaDetail").textContent="Siparişiniz yine işletmeye ulaşır."}}
function tick(){const d=new Date(),fmt=new Intl.DateTimeFormat("tr-TR",{timeZone:"Europe/Istanbul"});$("clock").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("date").textContent=fmt.format(d)}tick();setInterval(tick,1000);
fetch("https://api.open-meteo.com/v1/forecast?latitude=40.55&longitude=34.95&current=temperature_2m,weather_code&timezone=Europe%2FIstanbul").then(r=>r.json()).then(d=>{$("weather").textContent=`${Math.round(d.current.temperature_2m)}°`;const c=d.current.weather_code;$("weatherIcon").className=`fa-solid ${c<=1?"fa-sun":c<=3?"fa-cloud-sun":c<70?"fa-cloud-rain":"fa-snowflake"}`}).catch(()=>{$("weather").textContent="Çorum"});
function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2600)}function dateTime(ms){return ms?new Date(ms).toLocaleString("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Şimdi"}function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
