import{initializeApp,deleteApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{createUserWithEmailAndPassword,getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{ADMIN_UID,firebaseConfig}from"../firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let merchants=[],orders=[],busy=false,pendingDelivery="",toastTimer;
const statusNames={pending:"Sipariş alındı",preparing:"Hazırlanıyor",on_the_way:"Yola çıktı",delivered:"Teslim edildi",cancelled:"İptal edildi"},nextStatus={pending:"preparing",preparing:"on_the_way",on_the_way:"delivered"};
onAuthStateChanged(auth,async user=>{if(!user||user.uid!==ADMIN_UID){if(user)await signOut(auth);location.replace("../yonetici-giris.html?next=esnaf-yonetimi/");return}subscribe()});
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};$("merchantForm").onsubmit=saveMerchant;$("cancelEdit").onclick=resetForm;$("search").oninput=renderMerchants;$("orderFilter").onchange=renderOrders;$("merchantList").onclick=merchantAction;$("orderList").onclick=orderAction;$("closeBalance").onclick=()=>$("balanceDialog").close();$("balanceForm").oninput=balancePreview;$("balanceForm").onsubmit=saveBalance;$("confirmDelivery").onclick=()=>pendingDelivery&&deliverOrder(pendingDelivery);
function subscribe(){onSnapshot(collection(db,"merchantProfiles"),s=>{merchants=s.docs.map(d=>({id:d.id,...d.data()}));$("connection").innerHTML='<i class="fa-solid fa-circle-check"></i> Güncel';$("connection").classList.add("ok");renderAll()},connectionError);onSnapshot(query(collection(db,"merchantOrders"),orderBy("createdAtMs","desc"),limit(150)),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},connectionError)}
async function saveMerchant(e){e.preventDefault();if(busy)return;const id=$("editingId").value,data={name:$("name").value.trim(),businessName:$("businessName").value.trim(),phone:$("phone").value.trim(),lowBalanceThreshold:Number($("lowThreshold").value||0),note:$("merchantNote").value.trim(),active:$("active").checked,updatedAt:serverTimestamp()};if(id){setBusy(true);try{await updateDoc(doc(db,"merchantProfiles",id),data);toast("Esnaf bilgileri güncellendi.");resetForm()}catch(err){console.error(err);toast("Bilgiler güncellenemedi.")}finally{setBusy(false)}return}const username=normalize($("username").value),password=$("password").value;if(username.length<3)return toast("Kullanıcı adı en az 3 karakter olmalı.");if(merchants.some(x=>x.username===username))return toast("Bu kullanıcı adı zaten kullanılıyor.");setBusy(true);let secondary;try{secondary=initializeApp(firebaseConfig,`merchant-${Date.now()}`);const credential=await createUserWithEmailAndPassword(getAuth(secondary),`${username}@esnaf.fatihcayevi.local`,password);await setDoc(doc(db,"merchantProfiles",credential.user.uid),{...data,uid:credential.user.uid,username,loginEmail:`${username}@esnaf.fatihcayevi.local`,balance:0,createdAt:serverTimestamp(),createdAtMs:Date.now()});toast("Esnaf hesabı oluşturuldu.");resetForm()}catch(err){console.error(err);toast(err.code==="auth/email-already-in-use"?"Bu kullanıcı adı daha önce alınmış.":"Esnaf hesabı oluşturulamadı.")}finally{if(secondary)await deleteApp(secondary);setBusy(false)}}
function merchantAction(e){const add=e.target.closest("[data-balance]"),edit=e.target.closest("[data-edit]"),toggle=e.target.closest("[data-toggle]");if(add)openBalance(add.dataset.balance);if(edit)startEdit(edit.dataset.edit);if(toggle)toggleMerchant(toggle.dataset.toggle)}
function openBalance(id){const m=merchants.find(x=>x.id===id);if(!m)return;$("balanceMerchantId").value=id;$("balanceTitle").textContent=m.businessName||m.name;$("balanceAmount").value="";$("balanceNote").value="";$("balanceForm").elements.balanceType.value="topup";balancePreview();$("balanceDialog").showModal()}
async function saveBalance(e){e.preventDefault();if(busy)return;const id=$("balanceMerchantId").value,amount=Math.floor(Number($("balanceAmount").value)),type=$("balanceForm").elements.balanceType.value;if(!amount||amount<1)return;setBusy(true);try{await runTransaction(db,async tx=>{const ref=doc(db,"merchantProfiles",id),snap=await tx.get(ref);if(!snap.exists())throw Error("not-found");const m=snap.data(),signed=type==="topup"?amount:-amount,result=Number(m.balance||0)+signed;if(result<0)throw Error("negative");tx.update(ref,{balance:result,updatedAt:serverTimestamp()});tx.set(doc(collection(db,"merchantBalanceMovements")),{merchantId:id,merchantName:m.name||"",businessName:m.businessName||"",type:type==="topup"?"topup":"correction",amount:signed,previousBalance:Number(m.balance||0),resultingBalance:result,description:$("balanceNote").value.trim()||(type==="topup"?"Peşin çay bakiyesi yüklendi":"Bakiye düzeltmesi"),createdAt:serverTimestamp(),createdAtMs:Date.now(),createdBy:auth.currentUser.uid})});$("balanceDialog").close();toast("Çay bakiyesi güncellendi.")}catch(err){console.error(err);toast(err.message==="negative"?"Bakiye sıfırın altına düşemez.":"Bakiye kaydedilemedi.")}finally{setBusy(false)}}
function orderAction(e){const next=e.target.closest("[data-next]"),cancel=e.target.closest("[data-cancel]");if(next){const o=orders.find(x=>x.id===next.dataset.next);if(o?.status==="on_the_way"){pendingDelivery=o.id;$("confirmText").textContent=`${o.businessName||o.merchantName} için ${o.quantity} çay teslim edilip bakiyeden düşülecek.`;$("confirmDialog").showModal()}else updateOrder(next.dataset.next,nextStatus[o?.status])}if(cancel&&confirm("Sipariş iptal edilsin mi?"))updateOrder(cancel.dataset.cancel,"cancelled")}
async function updateOrder(id,status){try{await updateDoc(doc(db,"merchantOrders",id),{status,updatedAt:serverTimestamp(),...(status==="cancelled"?{cancelledAt:serverTimestamp()}:{})});toast(`Sipariş: ${statusNames[status]}`)}catch(err){console.error(err);toast("Sipariş güncellenemedi.")}}
async function deliverOrder(id){if(busy)return;setBusy(true);try{await runTransaction(db,async tx=>{const orderRef=doc(db,"merchantOrders",id),orderSnap=await tx.get(orderRef);if(!orderSnap.exists())throw Error("order");const o=orderSnap.data();if(o.status==="delivered"||o.status==="cancelled")throw Error("closed");const merchantRef=doc(db,"merchantProfiles",o.merchantId),merchantSnap=await tx.get(merchantRef);if(!merchantSnap.exists())throw Error("merchant");const m=merchantSnap.data(),before=Number(m.balance||0),qty=Number(o.quantity||0);if(before<qty)throw Error("balance");const result=before-qty;tx.update(merchantRef,{balance:result,updatedAt:serverTimestamp()});tx.update(orderRef,{status:"delivered",deliveredAt:serverTimestamp(),updatedAt:serverTimestamp(),balanceDeducted:true});tx.set(doc(collection(db,"merchantBalanceMovements")),{merchantId:o.merchantId,merchantName:o.merchantName||m.name||"",businessName:o.businessName||m.businessName||"",orderId:id,type:"order",amount:-qty,previousBalance:before,resultingBalance:result,description:`${qty} çay teslim edildi`,createdAt:serverTimestamp(),createdAtMs:Date.now(),createdBy:auth.currentUser.uid})});pendingDelivery="";toast("Teslimat tamamlandı, bakiye düşüldü.")}catch(err){console.error(err);toast(err.message==="balance"?"Esnafın çay bakiyesi yetersiz. Önce bakiye ekleyin.":"Teslimat tamamlanamadı.")}finally{setBusy(false)}}
function startEdit(id){const m=merchants.find(x=>x.id===id);if(!m)return;$("editingId").value=id;$("name").value=m.name||"";$("businessName").value=m.businessName||"";$("phone").value=m.phone||"";$("lowThreshold").value=m.lowBalanceThreshold??10;$("merchantNote").value=m.note||"";$("active").checked=m.active!==false;$("username").value=m.username||"";$("username").disabled=true;$("password").value="";$("password").required=false;$("password").disabled=true;$("formTitle").textContent="Esnaf Bilgilerini Düzenle";$("cancelEdit").hidden=false;$("saveMerchant").innerHTML='<i class="fa-solid fa-floppy-disk"></i> Değişiklikleri Kaydet';$("merchantForm").scrollIntoView({behavior:"smooth"})}
async function toggleMerchant(id){const m=merchants.find(x=>x.id===id);if(!m)return;try{await updateDoc(doc(db,"merchantProfiles",id),{active:m.active===false,updatedAt:serverTimestamp()});toast(m.active===false?"Esnaf hesabı açıldı.":"Esnaf hesabı kapatıldı.")}catch{toast("Hesap durumu değiştirilemedi.")}}
function renderAll(){renderSummary();renderMerchants();renderOrders()}function renderSummary(){$("activeCount").textContent=merchants.filter(m=>m.active!==false).length;$("totalBalance").textContent=merchants.reduce((s,m)=>s+Number(m.balance||0),0);$("pendingCount").textContent=orders.filter(o=>!["delivered","cancelled"].includes(o.status)).length;const today=new Date().toLocaleDateString("tr-TR");$("todayDelivered").textContent=orders.filter(o=>o.status==="delivered"&&o.deliveredAt?.toDate().toLocaleDateString("tr-TR")===today).reduce((s,o)=>s+Number(o.quantity||0),0)}
function renderMerchants(){const term=$("search").value.trim().toLocaleLowerCase("tr-TR"),list=merchants.filter(m=>`${m.name} ${m.businessName} ${m.username}`.toLocaleLowerCase("tr-TR").includes(term));$("merchantEmpty").hidden=list.length>0;$("merchantList").innerHTML=list.sort((a,b)=>(a.businessName||"").localeCompare(b.businessName||"","tr")).map(m=>`<article class="merchant-card"><span class="avatar"><i class="fa-solid fa-store"></i></span><div class="card-copy"><strong>${esc(m.businessName||m.name)}</strong><span>${esc(m.name||"")} • @${esc(m.username||"")} • ${m.active===false?"Giriş kapalı":"Aktif"}</span>${m.note?`<span>${esc(m.note)}</span>`:""}</div><div class="merchant-balance"><strong>${Number(m.balance||0)} çay</strong><span>${Number(m.balance||0)<=Number(m.lowBalanceThreshold||10)?"Düşük bakiye":"Bakiye yeterli"}</span></div><div class="card-actions"><button class="add" data-balance="${m.id}"><i class="fa-solid fa-coins"></i> Bakiye</button><button class="edit" data-edit="${m.id}"><i class="fa-solid fa-pen"></i></button><button class="toggle" data-toggle="${m.id}"><i class="fa-solid ${m.active===false?"fa-lock-open":"fa-lock"}"></i></button></div></article>`).join("")}
function renderOrders(){const list=$("orderFilter").value==="all"?orders:orders.filter(o=>!["delivered","cancelled"].includes(o.status));$("orderEmpty").hidden=list.length>0;$("orderList").innerHTML=list.map(o=>`<article class="order-card"><span class="avatar"><i class="fa-solid fa-mug-hot"></i></span><div class="card-copy"><strong>${esc(o.businessName||o.merchantName)} • ${o.quantity} çay</strong><span>${dateTime(o.createdAtMs)}${o.note?` • ${esc(o.note)}`:""}</span></div><span class="order-status">${statusNames[o.status]||o.status}</span>${!["delivered","cancelled"].includes(o.status)?`<div class="order-actions"><button class="next" data-next="${o.id}">${o.status==="pending"?"Hazırlamaya Al":o.status==="preparing"?"Yola Çıkar":"Teslim Et"}</button><button class="cancel-order" data-cancel="${o.id}">İptal</button></div>`:""}</article>`).join("")}
function balancePreview(){const m=merchants.find(x=>x.id===$("balanceMerchantId").value),amount=Number($("balanceAmount").value||0),signed=$("balanceForm").elements.balanceType.value==="topup"?amount:-amount;$("balancePreview").textContent=`Mevcut: ${m?.balance||0} çay → Yeni: ${Math.max(0,Number(m?.balance||0)+signed)} çay`}
function resetForm(){$("merchantForm").reset();$("editingId").value="";$("active").checked=true;$("lowThreshold").value=10;$("username").disabled=false;$("password").disabled=false;$("password").required=true;$("formTitle").textContent="Esnaf Müşterisi Ekle";$("cancelEdit").hidden=true;$("saveMerchant").innerHTML='<i class="fa-solid fa-user-plus"></i> Esnafı Kaydet'}
function setBusy(v){busy=v;$("saveMerchant").disabled=v}function connectionError(e){console.error(e);$("connection").textContent="Bağlantı hatası"}function normalize(v){return v.trim().toLocaleLowerCase("tr-TR").replaceAll("ı","i").replaceAll("ş","s").replaceAll("ğ","g").replaceAll("ü","u").replaceAll("ö","o").replaceAll("ç","c").replace(/[^a-z0-9._-]/g,"")}function dateTime(ms){return ms?new Date(ms).toLocaleString("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Şimdi"}function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML}function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2600)}
function tick(){const d=new Date();$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
