import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,deleteDoc,doc,getDoc,getFirestore,onSnapshot,serverTimestamp,setDoc,writeBatch}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{ADMIN_UID,firebaseConfig}from"../assets/js/firebase-config.js";
import{PERMISSION_DEFINITIONS,profileHasPermission}from"../assets/js/admin-access.js";

const app=getApps().find(x=>x.name==="[DEFAULT]")||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),functions=getFunctions(app,"europe-west1"),$=id=>document.getElementById(id);
const personnelCol=collection(db,"adminPersonnel"),staffUsersCol=collection(db,"staffUsers"),attendanceCol=collection(db,"adminPersonnelAttendance"),paymentsCol=collection(db,"adminPersonnelPayments"),cashMovementsCol=collection(db,"adminCashMovements"),financeDaysCol=collection(db,"adminFinanceDays"),shiftsCol=collection(db,"adminPersonnelShifts");
const updateStaffUser=httpsCallable(functions,"updateStaffUser");
const FINANCE_START_DATE="2026-08-13";
let personnel=[],staffUsers=[],attendance=[],payments=[],financeDays=[],shifts=[],selectedMonth=today().slice(0,7),selectedPersonnelId="",pendingDeletePaymentId="",pendingAttendance=null,toastTimer,started=false;

tick();setInterval(tick,1000);$("monthPicker").value=selectedMonth;
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("previousMonth").onclick=()=>changeMonth(-1);$("nextMonth").onclick=()=>changeMonth(1);
$("monthPicker").onchange=e=>{if(!e.target.value)return;e.target.value=e.target.value>today().slice(0,7)?today().slice(0,7):e.target.value;selectedMonth=e.target.value;render()};
$("newPersonnelButton").onclick=()=>openPersonnelDialog();$("editPersonnelButton").onclick=()=>openPersonnelDialog(selectedPerson());
$("personnelPermissionsButton").onclick=openPermissionsDialog;
$("personnelShiftButton").onclick=openShiftDialog;
$("newPaymentButton").onclick=()=>openPaymentDialog();
$("personnelList").onclick=e=>{const card=e.target.closest("[data-personnel-id]");if(card){selectedPersonnelId=card.dataset.personnelId;render();if(!$("personnelDetailDialog").open)$("personnelDetailDialog").showModal()}};
$("attendanceCalendar").onclick=e=>{const day=e.target.closest("[data-attendance-date]");if(day&&!day.disabled)openAttendanceDialog(day.dataset.attendanceDate)};
$("paymentList").onclick=paymentAction;
$("closePersonnelDetailDialog").onclick=()=>$("personnelDetailDialog").close();$("closePersonnelDialog").onclick=()=>$("personnelDialog").close();$("closeAttendanceDialog").onclick=()=>$("attendanceDialog").close();$("closeAttendanceWageDialog").onclick=()=>{$("attendanceWageDialog").close();pendingAttendance=null};$("closePaymentDialog").onclick=()=>$("paymentDialog").close();$("closePermissionsDialog").onclick=()=>$("permissionsDialog").close();
$("personnelForm").onsubmit=savePersonnel;$("permissionsForm").onsubmit=savePermissions;$("attendanceForm").onsubmit=saveAttendance;$("attendanceWageForm").onsubmit=e=>e.preventDefault();$("paymentForm").onsubmit=savePayment;$("confirmDeletePayment").onclick=deletePayment;
$("wageTrackingEnabled").onchange=renderWageSettings;$("personnelWageType").onchange=renderWageSettings;$("workedHours").oninput=updateHourlySuggestion;
document.querySelectorAll('input[name="attendanceStatus"]').forEach(input=>{input.onclick=()=>{if($("attendanceDialog").open)$("attendanceForm").requestSubmit()}});
$("wageActionOptions").onclick=e=>{const button=e.target.closest("[data-wage-action]");if(button)saveAttendanceWage(button.dataset.wageAction,button)};
$("personnelPermissionGrid").onchange=e=>{const input=e.target.closest('input[name="personnelPermission"]');if(!input)return;const all=[...document.querySelectorAll('input[name="personnelPermission"]')],personnel=all.find(x=>x.value==="personnel"),pos=all.find(x=>x.value==="pos"),transfer=all.find(x=>x.value==="currentAccountTransfer");if(input.value==="personnel"&&input.checked)all.filter(x=>x!==input).forEach(x=>x.checked=false);else if(input.checked&&personnel)personnel.checked=false;if(input.value==="currentAccountTransfer"&&input.checked&&pos)pos.checked=true;if(input.value==="pos"&&!input.checked&&transfer)transfer.checked=false};
$("shiftDialog").addEventListener("close",()=>{if($("shiftDialog").returnValue==="attendance"){document.querySelector(".attendance-card")?.scrollIntoView({behavior:"smooth",block:"start"})}});
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});

onAuthStateChanged(auth,async user=>{
  if(!user||user.uid!==ADMIN_UID){if(user)await signOut(auth);location.replace("../yonetici-giris.html?next=personel-yonetimi/");return}
  await ensureOwnerPersonnel(user);
  if(started)return;started=true;
  onSnapshot(personnelCol,s=>{personnel=s.docs.map(d=>({id:d.id,...d.data()})).sort(personSort);if(!selectedPersonnelId||!personnel.some(x=>x.id===selectedPersonnelId))selectedPersonnelId=personnel.find(x=>x.id===ADMIN_UID)?.id||personnel[0]?.id||"";connected();render()},loadError);
  onSnapshot(staffUsersCol,s=>{staffUsers=s.docs.map(d=>({uid:d.id,...d.data()})).sort((a,b)=>String(a.displayName||"").localeCompare(String(b.displayName||""),"tr"));connected();render()},loadError);
  onSnapshot(attendanceCol,s=>{attendance=s.docs.map(d=>({id:d.id,...d.data()}));connected();render()},loadError);
  onSnapshot(paymentsCol,s=>{payments=s.docs.map(d=>({id:d.id,...d.data()}));connected();render()},loadError);
  onSnapshot(financeDaysCol,s=>{financeDays=s.docs.map(d=>({id:d.id,...d.data()}));connected();render()},loadError);
  onSnapshot(shiftsCol,s=>{shifts=s.docs.map(d=>({id:d.id,...d.data()}));connected();render()},loadError);
});

async function ensureOwnerPersonnel(user){
  const ref=doc(db,"adminPersonnel",ADMIN_UID),snap=await getDoc(ref);
  if(snap.exists())return;
  const staffSnap=await getDoc(doc(db,"staffUsers",ADMIN_UID)).catch(()=>null),profile=staffSnap?.exists()?staffSnap.data():{};
  await setDoc(ref,{displayName:"Fatih Ali Altınlı",roleTitle:"Yönetici",phone:profile.phone||"",dailyWage:0,wageType:"daily",wageTrackingEnabled:false,active:true,linkedUserUid:ADMIN_UID,isOwnerProfile:true,createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:ADMIN_UID,updatedAtMs:Date.now(),updatedAt:serverTimestamp(),updatedBy:ADMIN_UID});
}
function connected(){$("connection").className="connection ok";$("connection").innerHTML='<i class="fa-solid fa-circle-check"></i> Canlı veri'}
function loadError(error){console.error(error);$("connection").className="connection error";$("connection").innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';toast("Personel verileri alınamadı.")}

function render(){
  $("monthTitle").textContent=monthName(selectedMonth);$("nextMonth").disabled=selectedMonth>=today().slice(0,7);$("monthPicker").value=selectedMonth;
  const active=personnel.filter(x=>x.active!==false),monthAttendance=attendance.filter(x=>String(x.businessDate||"").startsWith(selectedMonth)),monthPayments=payments.filter(x=>String(x.businessDate||"").startsWith(selectedMonth));
  const worked=monthAttendance.filter(x=>x.status==="worked"),earned=worked.reduce((sum,x)=>sum+attendanceWage(x,personnel.find(p=>p.id===x.personnelId)),0),paid=monthPayments.reduce((sum,x)=>sum+number(x.amount),0);
  $("activePersonnelCount").textContent=formatNumber(active.length);$("workedDayTotal").textContent=formatNumber(worked.length);$("earnedTotal").textContent=money(earned);$("paidTotal").textContent=money(paid);$("remainingTotal").textContent=money(earned-paid);
  $("personnelList").innerHTML=personnel.map(personnelCard).join("");$("personnelEmpty").hidden=personnel.length>0;
  renderDetail();
}
function personnelCard(person){
  const data=personMonth(person.id),linked=linkedUser(person),badge=person.isOwnerProfile?'<span class="owner-badge">SİSTEM SAHİBİ</span>':person.active===false?'<span class="inactive-badge">PASİF</span>':"";
  const wageText=person.wageTrackingEnabled===false?"Ücret takibi kapalı":`${money(person.dailyWage)}/${person.wageType==="hourly"?"saat":"gün"}`;
  return`<button class="personnel-card ${selectedPersonnelId===person.id?"selected":""} ${person.active===false?"inactive":""}" type="button" data-personnel-id="${esc(person.id)}">${badge}<span class="personnel-avatar"><i class="fa-solid ${person.isOwnerProfile?"fa-user-shield":"fa-user-tie"}"></i></span><span><strong>${esc(person.displayName||"Personel")}</strong><small>${esc(person.roleTitle||"Çalışan")} • ${wageText}</small><small class="account-state ${linked?"linked":""}"><i class="fa-solid ${linked?"fa-link":"fa-link-slash"}"></i>${linked?`${esc(linked.displayName||"Kullanıcı")} hesabı bağlı`:"Kullanıcı hesabı bağlı değil"}</small></span><span class="card-stats"><span>Çalıştı<b>${data.workedDays} Gün</b></span><span>Hak Etti<b>${money(data.earned)}</b></span><span>Ödendi<b>${money(data.paid)}</b></span><span>Kalan<b>${money(data.remaining)}</b></span></span></button>`
}
function renderDetail(){
  const person=selectedPerson(),panel=$("detailPanel");panel.hidden=!person;if(!person)return;
  const data=personMonth(person.id),linked=linkedUser(person);$("detailName").textContent=person.displayName||"Personel";$("detailRole").textContent=`${person.roleTitle||"Çalışan"}${person.phone?` • ${formatPhone(person.phone)}`:""}${person.active===false?" • Pasif":""} • ${linked?"Kullanıcı bağlı":"Kullanıcı bağlı değil"}`;
  $("detailWorkedDays").textContent=`${data.workedDays} Gün`;$("detailEarned").textContent=money(data.earned);$("detailPaid").textContent=money(data.paid);$("detailRemaining").textContent=money(data.remaining);
  $("newPaymentButton").disabled=person.active===false;$("newPaymentButton").title=person.active===false?"Pasif personele yeni ödeme eklenemez.":"";
  $("personnelPermissionsButton").disabled=!linked;$("personnelPermissionsButton").title=linked?"Personel kullanıcısının panel yetkilerini yönet":"Önce personele bir kullanıcı hesabı bağlayın";
  renderCalendar(person);renderPayments(person);
}
function personMonth(id){
  const rows=attendance.filter(x=>x.personnelId===id&&String(x.businessDate||"").startsWith(selectedMonth)&&x.status==="worked"),paid=payments.filter(x=>x.personnelId===id&&String(x.businessDate||"").startsWith(selectedMonth)).reduce((sum,x)=>sum+number(x.amount),0),person=personnel.find(x=>x.id===id),earned=rows.reduce((sum,x)=>sum+attendanceWage(x,person),0);
  return{workedDays:rows.length,earned,paid,remaining:earned-paid}
}
function renderCalendar(person){
  const [year,month]=selectedMonth.split("-").map(Number),days=new Date(Date.UTC(year,month,0)).getUTCDate(),first=(new Date(Date.UTC(year,month-1,1)).getUTCDay()+6)%7,rows=new Map(attendance.filter(x=>x.personnelId===person.id&&String(x.businessDate||"").startsWith(selectedMonth)).map(x=>[x.businessDate,x]));
  const cells=Array.from({length:first},()=>'<span class="calendar-day blank"></span>');
  for(let day=1;day<=days;day++){const date=`${selectedMonth}-${String(day).padStart(2,"0")}`,row=rows.get(date),future=date>today(),blocked=future||(person.active===false&&!row),label={worked:"Çalıştı",leave:"İzinli",absent:"Gelmedi"}[row?.status]||"Kayıt yok";cells.push(`<button class="calendar-day ${row?.status||""} ${date===today()?"today":""} ${blocked?"future":""}" type="button" data-attendance-date="${date}" ${blocked?"disabled":""}><b>${day}</b><small>${label}</small></button>`)}
  $("attendanceCalendar").innerHTML=cells.join("")
}
function renderPayments(person){
  const rows=payments.filter(x=>x.personnelId===person.id&&String(x.businessDate||"").startsWith(selectedMonth)).sort((a,b)=>String(b.businessDate).localeCompare(String(a.businessDate))||number(b.createdAtMs)-number(a.createdAtMs));
  $("paymentCount").textContent=`${rows.length} Ödeme`;$("paymentEmpty").hidden=rows.length>0;$("paymentList").innerHTML=rows.map(row=>{const locked=isFinanceLocked(row.businessDate),attendancePayment=row.automaticAttendancePayment===true,label={cash:"Nakit Kasa",bank:"Banka Hesabı",creditCard:"Kredi Kartı"}[row.account]||"Hesap";return`<article class="payment-row"><i class="fa-solid fa-money-bill-wave"></i><div><strong>${esc(row.note||"Personel ödemesi")}</strong><small>${formatDate(row.businessDate)} • ${label}${attendancePayment?" • Çalışma gününden işlendi":""}${locked?" • Finans günü kapalı":""}</small></div><div class="payment-side"><b>${money(row.amount)}</b><span class="payment-actions"><button type="button" data-edit-payment="${esc(row.id)}" ${locked?"disabled":""} title="Düzenle"><i class="fa-solid fa-pen"></i></button><button class="delete" type="button" data-delete-payment="${esc(row.id)}" ${locked||attendancePayment?"disabled":""} title="${attendancePayment?"Takvim gününden kaldırılır":"Sil"}"><i class="fa-solid fa-trash"></i></button></span></div></article>`}).join("")
}

function openPersonnelDialog(person=null){
  $("personnelForm").reset();$("personnelId").value=person?.id||"";$("personnelDialogTitle").textContent=person?"Personeli Düzenle":"Yeni Personel";$("personnelName").value=person?.displayName||"";$("personnelRole").value=person?.roleTitle||"Çalışan";$("personnelPhone").value=person?.phone||"";$("wageTrackingEnabled").checked=person?person.wageTrackingEnabled!==false:true;$("personnelWageType").value=person?.wageType==="hourly"?"hourly":"daily";$("personnelWage").value=number(person?.dailyWage)||"";renderWageSettings();$("personnelActive").checked=person?.active!==false;$("personnelActive").disabled=person?.isOwnerProfile===true;renderLinkedUserOptions(person);$("linkedUserUid").value=person?.isOwnerProfile?ADMIN_UID:person?.linkedUserUid||"";$("linkedUserUid").disabled=person?.isOwnerProfile===true;$("linkedUserHint").textContent=person?.isOwnerProfile?"Sistem sahibi hesabının bağlantısı kaldırılamaz.":"Personelin uygulamaya giriş yapacağı kullanıcı hesabını seçin. Bir hesap yalnızca bir personele bağlanabilir.";$("personnelMessage").textContent="";$("personnelDialog").showModal();setTimeout(()=>{$("personnelName").focus();$("personnelName").select()},60)
}
function renderWageSettings(){const enabled=$("wageTrackingEnabled").checked,type=$("personnelWageType").value;$("wageSettings").hidden=!enabled;$("personnelWage").required=enabled;$("personnelWageLabel").childNodes[0].nodeValue=type==="hourly"?"Saatlik ücret":"Günlük ücret";$("personnelWageHint").textContent=type==="hourly"?"Çalışılan saat ile çarpılarak önerilecek ücret.":"Çalışılan gün için önerilecek ücret."}
async function savePersonnel(e){
  e.preventDefault();const id=$("personnelId").value||doc(personnelCol).id,existing=personnel.find(x=>x.id===id),displayName=$("personnelName").value.trim(),roleTitle=$("personnelRole").value.trim(),wageTrackingEnabled=$("wageTrackingEnabled").checked,wageType=$("personnelWageType").value==="hourly"?"hourly":"daily",dailyWage=number($("personnelWage").value),linkedUserUid=existing?.isOwnerProfile?ADMIN_UID:$("linkedUserUid").value;if(!displayName||!roleTitle)return message("personnelMessage","Ad soyad ve görev zorunludur.");if(wageTrackingEnabled&&dailyWage<=0)return message("personnelMessage","Ücret takibi açıksa geçerli bir ücret girin.");if(linkedUserUid&&!staffUsers.some(x=>x.uid===linkedUserUid))return message("personnelMessage","Seçilen kullanıcı hesabı bulunamadı.");const conflict=personnel.find(x=>x.id!==id&&x.linkedUserUid===linkedUserUid);if(linkedUserUid&&conflict)return message("personnelMessage",`Bu kullanıcı hesabı ${conflict.displayName} personeline bağlı.`);
  e.submitter.disabled=true;try{const batch=writeBatch(db),now=Date.now(),oldLinkedUid=existing?.linkedUserUid||"";batch.set(doc(db,"adminPersonnel",id),{displayName,roleTitle,phone:$("personnelPhone").value.trim(),dailyWage,wageType,wageTrackingEnabled,active:existing?.isOwnerProfile?true:$("personnelActive").checked,linkedUserUid,isOwnerProfile:existing?.isOwnerProfile===true,createdAtMs:existing?.createdAtMs||now,createdBy:existing?.createdBy||auth.currentUser.uid,updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});if(oldLinkedUid&&oldLinkedUid!==linkedUserUid&&oldLinkedUid!==ADMIN_UID)batch.set(doc(db,"staffUsers",oldLinkedUid),{personnelId:"",personnelName:"",updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});if(linkedUserUid){const linkData={personnelId:id,personnelName:displayName,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};if(linkedUserUid===ADMIN_UID)Object.assign(linkData,{displayName:"Fatih Ali Altınlı",role:"owner",active:true,permissions:PERMISSION_DEFINITIONS.map(x=>x.id),permissionSchemaVersion:"r286",deviceLimit:7});batch.set(doc(db,"staffUsers",linkedUserUid),linkData,{merge:true})}await batch.commit();selectedPersonnelId=id;$("personnelDialog").close();toast(existing?"Personel ve ücret ayarları güncellendi.":"Yeni personel kaydedildi.")}catch(error){console.error(error);message("personnelMessage","Personel kaydedilemedi.")}finally{e.submitter.disabled=false}
}

function renderLinkedUserOptions(person){
  const current=person?.linkedUserUid||"",source=person?.isOwnerProfile&&!staffUsers.some(x=>x.uid===ADMIN_UID)?[{uid:ADMIN_UID,displayName:person.displayName,phone:person.phone,active:true},...staffUsers]:staffUsers,options=source.filter(user=>user.uid===current||user.uid===ADMIN_UID&&person?.isOwnerProfile||!personnel.some(item=>item.id!==person?.id&&item.linkedUserUid===user.uid));
  $("linkedUserUid").innerHTML='<option value="">Kullanıcı hesabı bağlı değil</option>'+options.map(user=>`<option value="${esc(user.uid)}">${esc(user.displayName||"Kullanıcı")} • ${esc(formatPhone(user.phone)||"Telefon yok")}${user.active===false?" • Pasif":""}</option>`).join("")
}
function linkedUser(person){if(!person?.linkedUserUid)return null;return staffUsers.find(x=>x.uid===person.linkedUserUid)||(person.isOwnerProfile?{uid:ADMIN_UID,displayName:person.displayName,phone:person.phone,role:"owner",active:true,permissions:PERMISSION_DEFINITIONS.map(x=>x.id),deviceLimit:7}:null)}
function openPermissionsDialog(){
  const person=selectedPerson(),user=linkedUser(person);if(!person||!user){toast("Önce personele bir kullanıcı hesabı bağlayın.");return}
  const owner=person.isOwnerProfile===true||user.uid===ADMIN_UID;$("permissionsForm").reset();$("permissionsDialogTitle").textContent=`${person.displayName} • Yetkiler`;$("linkedAccountSummary").innerHTML=`<i class="fa-solid ${owner?"fa-user-shield":"fa-user-check"}"></i><span><strong>${esc(user.displayName||person.displayName)}</strong><small>${esc(formatPhone(user.phone)||"Telefon bilgisi yok")} • ${owner?"Sistem sahibi":"Bağlı kullanıcı hesabı"}</small></span>`;
  $("personnelPermissionGrid").innerHTML=PERMISSION_DEFINITIONS.map(permission=>`<label class="${permission.kind==="action"?"permission-action":""}"><input type="checkbox" name="personnelPermission" value="${permission.id}" ${profileHasPermission(user,permission.id)?"checked":""} ${owner?"disabled":""}><i class="fa-solid ${permission.icon}"></i><span>${permission.name}</span></label>`).join("");$("personnelPermissionFieldset").disabled=owner;$("savePermissionsButton").hidden=owner;$("savePermissionsButton").innerHTML='<i class="fa-solid fa-floppy-disk"></i> Yetkileri Kaydet';message("permissionsMessage",owner?"Sistem sahibinin tam yetkisi değiştirilemez.":"");$("permissionsDialog").showModal()
}
async function savePermissions(e){
  e.preventDefault();const person=selectedPerson(),user=linkedUser(person);if(!person||!user||user.uid===ADMIN_UID)return;const permissions=[...document.querySelectorAll('input[name="personnelPermission"]:checked')].map(x=>x.value);if(!permissions.length)return message("permissionsMessage","En az bir panel yetkisi seçin.");e.submitter.disabled=true;try{await updateStaffUser({uid:user.uid,displayName:user.displayName||person.displayName,phone:user.phone,permissions,deviceLimit:user.deviceLimit||1,active:user.active!==false});$("permissionsDialog").close();toast("Personel yetkileri kaydedildi.")}catch(error){console.error(error);message("permissionsMessage",callableMessage(error))}finally{e.submitter.disabled=false}
}
function openShiftDialog(){const person=selectedPerson(),user=linkedUser(person);if(!person)return;$("shiftDialogTitle").textContent=`${person.displayName} • Kasa / Vardiya`;$("shiftAccountSummary").innerHTML=`<i class="fa-solid fa-cash-register"></i><span><strong>${user?"Kullanıcı hesabı bağlı":"Kullanıcı hesabı bağlı değil"}</strong><small>${user?esc(`${user.displayName||"Kullanıcı"} • ${formatPhone(user.phone)||"Telefon yok"}`):"Vardiya hesabı başlamadan önce kullanıcı bağlantısı yapılmalı."}</small></span>`;renderShiftHistory(person);$("shiftDialog").showModal()}
function renderShiftHistory(person){const rows=shifts.filter(item=>item.personnelId===person.id&&String(item.businessDate||"").startsWith(selectedMonth)).sort((a,b)=>number(b.openedAtMs)-number(a.openedAtMs));$("shiftHistoryEmpty").hidden=rows.length>0;$("shiftHistoryList").innerHTML=rows.map(item=>{const open=item.status==="open",duration=shiftDuration(item),difference=open?item.openingDifference:item.closingDifference;return`<article class="shift-history-row ${open?"is-open":""}"><i class="fa-solid ${open?"fa-clock":"fa-circle-check"}"></i><div><strong>${formatDate(item.businessDate)}</strong><small>Giriş ${formatClock(item.openedAtMs)} • Çıkış ${open?"Yapılmadı":formatClock(item.closedAtMs)}${duration?` • ${duration}`:""}</small><small>Açılış sayımı ${money(item.openingCount)}${open?"":` • Kapanış sayımı ${money(item.closingCount)}`}</small></div><b class="${number(difference)===0?"is-match":"is-difference"}">${number(difference)===0?"Kasa doğru":`${money(Math.abs(number(difference)))} ${number(difference)>0?"fazla":"eksik"}`}</b></article>`}).join("")}
function formatClock(ms){return ms?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(ms)):"—"}
function shiftDuration(item){if(!item.openedAtMs||!item.closedAtMs)return"";const minutes=Math.max(0,Math.round((number(item.closedAtMs)-number(item.openedAtMs))/60000)),hours=Math.floor(minutes/60),rest=minutes%60;return`${hours?`${hours} sa. `:""}${rest} dk.`}
function openAttendanceDialog(date,preset=""){
  const person=selectedPerson();if(!person)return;const existing=attendance.find(x=>x.personnelId===person.id&&x.businessDate===date);if(person.active===false&&!existing){toast("Pasif personele yeni çalışma günü eklenemez.");return}const status=preset||existing?.status||"none";$("attendanceDate").value=date;$("attendanceTitle").textContent=`${formatDate(date)} • ${person.displayName}`;document.querySelector(`input[name="attendanceStatus"][value="${status}"]`).checked=true;$("attendanceNote").value=existing?.note||"";$("attendanceMessage").textContent="";$("attendanceDialog").showModal()
}
async function saveAttendance(e){
  e.preventDefault();const person=selectedPerson(),date=$("attendanceDate").value,status=new FormData(e.currentTarget).get("attendanceStatus"),id=`${person.id}_${date}`,ref=doc(db,"adminPersonnelAttendance",id),existing=attendance.find(x=>x.id===id);if(!person||!date||date>today())return message("attendanceMessage","Geçerli bir gün seçin.");if(person.active===false&&!existing&&status!=="none")return message("attendanceMessage","Pasif personele yeni çalışma günü eklenemez.");
  if(status==="worked"&&person.wageTrackingEnabled!==false){const wagePerson=existing?.status==="worked"?{...person,wageType:existing.wageTypeSnapshot||person.wageType,dailyWage:existing.wageRateSnapshot??person.dailyWage}:person;pendingAttendance={person:wagePerson,date,id,note:$("attendanceNote").value.trim(),existing};$("attendanceDialog").close();openAttendanceWageDialog();return}
  const statusInputs=[...document.querySelectorAll('input[name="attendanceStatus"]')];statusInputs.forEach(x=>x.disabled=true);try{const batch=writeBatch(db),autoPaymentId=existing?.automaticPaymentId||`attendance_${id}`;if(status==="none")batch.delete(ref);else batch.set(ref,{personnelId:person.id,personnelName:person.displayName,businessDate:date,status,note:$("attendanceNote").value.trim(),wageSnapshot:0,workedHours:0,wageAction:"none",automaticPaymentId:"",updatedAtMs:Date.now(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});batch.delete(doc(db,"adminPersonnelPayments",autoPaymentId));batch.delete(doc(db,"adminCashMovements",autoPaymentId));await batch.commit();$("attendanceDialog").close();toast(status==="none"?"Gün eski boş haline getirildi.":status==="leave"?"Gün izinli olarak kaydedildi.":status==="absent"?"Gün gelmedi olarak kaydedildi.":"Çalışma günü kaydedildi.")}catch(error){console.error(error);message("attendanceMessage","Çalışma kaydı kaydedilemedi.")}finally{statusInputs.forEach(x=>x.disabled=false)}
}
function openAttendanceWageDialog(){
  const item=pendingAttendance;if(!item)return;const hourly=item.person.wageType==="hourly",hours=number(item.existing?.workedHours)||1,suggested=item.existing?.wageSnapshot!==undefined?number(item.existing.wageSnapshot):number(item.person.dailyWage)*(hourly?hours:1);item.suggestedAmount=suggested;$("attendanceWageForm").reset();$("attendanceWageTitle").textContent=`${formatDate(item.date)} • ${item.person.displayName}`;$("workedHoursLabel").hidden=!hourly;$("workedHours").required=hourly;$("workedHours").value=hourly?hours:"";$("attendanceWageAmount").value=suggested||"";$("wageActionOptions").dataset.currentAction=item.existing?.wageAction||"earned";message("attendanceWageMessage","");$("attendanceWageDialog").showModal();setTimeout(()=>{$("attendanceWageAmount").focus();$("attendanceWageAmount").select()},60)
}
function updateHourlySuggestion(){if(!pendingAttendance||pendingAttendance.person.wageType!=="hourly")return;const suggested=number($("workedHours").value)*number(pendingAttendance.person.dailyWage);pendingAttendance.suggestedAmount=suggested;$("attendanceWageAmount").value=suggested?suggested.toFixed(2):""}
async function saveAttendanceWage(wageAction,button){
  const item=pendingAttendance;if(!item)return;const entered=$("attendanceWageAmount").value.trim(),amount=entered===""?number(item.suggestedAmount):number(entered),workedHours=item.person.wageType==="hourly"?number($("workedHours").value):0;if(amount<=0)return message("attendanceWageMessage","Geçerli bir ücret tutarı girin.");if(item.person.wageType==="hourly"&&workedHours<=0)return message("attendanceWageMessage","Çalışılan saat bilgisini girin.");if((wageAction==="cash"||wageAction==="bank")&&isFinanceLocked(item.date))return message("attendanceWageMessage","Finans günü kapalı olduğu için bu güne ödeme işlenemez.");
  const buttons=[...$("wageActionOptions").querySelectorAll("button")];buttons.forEach(x=>x.disabled=true);button.classList.add("saving");try{const batch=writeBatch(db),now=Date.now(),attendanceRef=doc(db,"adminPersonnelAttendance",item.id),autoPaymentId=`attendance_${item.id}`,paymentRef=doc(db,"adminPersonnelPayments",autoPaymentId),cashRef=doc(db,"adminCashMovements",autoPaymentId),paid=wageAction==="cash"||wageAction==="bank";batch.set(attendanceRef,{personnelId:item.person.id,personnelName:item.person.displayName,businessDate:item.date,status:"worked",note:item.note,wageSnapshot:amount,workedHours,wageTypeSnapshot:item.person.wageType||"daily",wageRateSnapshot:number(item.person.dailyWage),wageAction,automaticPaymentId:paid?autoPaymentId:"",updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});
    if(paid){const account=wageAction==="cash"?"cash":"bank",note=`${formatDate(item.date)} çalışma ücreti`,common={personnelId:item.person.id,personnelName:item.person.displayName,businessDate:item.date,amount,account,note,attendanceId:item.id,automaticAttendancePayment:true,updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};batch.set(paymentRef,{...common,cashMovementId:autoPaymentId,createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid},{merge:true});batch.set(cashRef,{type:"expense",amount,account,fromAccount:"",toAccount:"",category:"Maaş Ödemesi",description:`${item.person.displayName} • ${note}`,businessDate:item.date,automatic:true,source:"staff-attendance-payment",sourceId:autoPaymentId,personnelId:item.person.id,attendanceId:item.id,createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid,updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true})}else{batch.delete(paymentRef);batch.delete(cashRef)}
    await batch.commit();$("attendanceWageDialog").close();pendingAttendance=null;toast(paid?"Çalışma ve ücret ödemesi kaydedildi.":"Çalışma ücreti hak edişe eklendi.")}catch(error){console.error(error);message("attendanceWageMessage","Çalışma ve ücret işlemi kaydedilemedi.")}finally{button.classList.remove("saving");buttons.forEach(x=>x.disabled=false)}
}
function openPaymentDialog(payment=null){
  const person=selectedPerson();if(!person)return;if(person.active===false&&!payment){toast("Pasif personele yeni ödeme eklenemez.");return}$("paymentForm").reset();$("paymentId").value=payment?.id||"";$("paymentDialogTitle").textContent=payment?"Ödemeyi Düzenle":`${person.displayName} • Ödeme`;$("paymentDate").value=payment?.businessDate||today();$("paymentDate").disabled=Boolean(payment);$("paymentAmount").value=number(payment?.amount)||"";$("paymentAccount").value=payment?.account||"cash";$("paymentNote").value=payment?.note||"";$("paymentMessage").textContent=payment?"Ödeme tarihi kayıt bütünlüğü için değiştirilemez.":"";$("paymentDialog").showModal();setTimeout(()=>{$("paymentAmount").focus();$("paymentAmount").select()},60)
}
async function savePayment(e){
  e.preventDefault();const person=selectedPerson(),id=$("paymentId").value||doc(paymentsCol).id,existing=payments.find(x=>x.id===id),businessDate=$("paymentDate").value,amount=number($("paymentAmount").value),account=$("paymentAccount").value,note=$("paymentNote").value.trim()||`${monthName(businessDate.slice(0,7))} personel ödemesi`;
  if(!person)return;if(person.active===false&&!existing)return message("paymentMessage","Pasif personele yeni ödeme eklenemez.");if(!businessDate||businessDate>today()||businessDate<FINANCE_START_DATE)return message("paymentMessage","Geçerli bir ödeme tarihi seçin.");if(isFinanceLocked(businessDate)||existing&&isFinanceLocked(existing.businessDate))return message("paymentMessage","Finans günü kapalı olan ödeme değiştirilemez.");if(amount<=0)return message("paymentMessage","Geçerli bir ödeme tutarı girin.");
  e.submitter.disabled=true;try{const batch=writeBatch(db),now=Date.now(),paymentRef=doc(db,"adminPersonnelPayments",id),cashRef=doc(db,"adminCashMovements",id),paymentData={personnelId:person.id,personnelName:person.displayName,businessDate,amount,account,note,cashMovementId:id,updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};if(!existing)Object.assign(paymentData,{createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});batch.set(paymentRef,paymentData,{merge:true});batch.set(cashRef,{type:"expense",amount,account,fromAccount:"",toAccount:"",category:"Maaş Ödemesi",description:`${person.displayName} • ${note}`,businessDate,automatic:true,source:"staff-payment",sourceId:id,personnelId:person.id,updatedAtMs:now,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid,...(!existing?{createdAtMs:now,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid}:{})},{merge:true});await batch.commit();$("paymentDialog").close();toast(existing?"Personel ödemesi güncellendi.":"Personel ödemesi Kasa'ya işlendi.")}catch(error){console.error(error);message("paymentMessage","Ödeme kaydedilemedi. Finans günü veya Firebase kurallarını kontrol edin.")}finally{e.submitter.disabled=false}
}
function paymentAction(e){const edit=e.target.closest("[data-edit-payment]"),remove=e.target.closest("[data-delete-payment]");if(edit){const payment=payments.find(x=>x.id===edit.dataset.editPayment);if(payment&&!isFinanceLocked(payment.businessDate)){if(payment.automaticAttendancePayment)openAttendancePaymentEdit(payment);else openPaymentDialog(payment)}}if(remove){const payment=payments.find(x=>x.id===remove.dataset.deletePayment);if(!payment||isFinanceLocked(payment.businessDate)||payment.automaticAttendancePayment)return;pendingDeletePaymentId=payment.id;$("deletePaymentText").textContent=`${formatDate(payment.businessDate)} tarihli ${money(payment.amount)} ödeme ve Kasa'daki bağlı gider kaydı silinecek.`;$("deletePaymentDialog").showModal()}}
function openAttendancePaymentEdit(payment){const person=personnel.find(x=>x.id===payment.personnelId),existing=attendance.find(x=>x.id===payment.attendanceId||x.personnelId===payment.personnelId&&x.businessDate===payment.businessDate);if(!person||!existing){toast("Bağlı çalışma günü bulunamadı.");return}const wagePerson={...person,wageType:existing.wageTypeSnapshot||person.wageType,dailyWage:existing.wageRateSnapshot??person.dailyWage};selectedPersonnelId=person.id;pendingAttendance={person:wagePerson,date:existing.businessDate,id:existing.id,note:existing.note||"",existing};openAttendanceWageDialog()}
async function deletePayment(){const payment=payments.find(x=>x.id===pendingDeletePaymentId);if(!payment||isFinanceLocked(payment.businessDate))return;const button=$("confirmDeletePayment");button.disabled=true;try{const batch=writeBatch(db);batch.delete(doc(db,"adminPersonnelPayments",payment.id));batch.delete(doc(db,"adminCashMovements",payment.cashMovementId||payment.id));await batch.commit();pendingDeletePaymentId="";$("deletePaymentDialog").close();toast("Personel ödemesi ve bağlı gider silindi.")}catch(error){console.error(error);toast("Ödeme silinemedi.")}finally{button.disabled=false}}

function selectedPerson(){return personnel.find(x=>x.id===selectedPersonnelId)||null}function personSort(a,b){return Number(b.isOwnerProfile)-Number(a.isOwnerProfile)||Number(b.active!==false)-Number(a.active!==false)||String(a.displayName).localeCompare(String(b.displayName),"tr")}
function attendanceWage(row,person){const value=row?.wageSnapshot;return value!==undefined&&value!==null&&value!==""&&Number.isFinite(Number(value))?Number(value):number(person?.dailyWage)}
function isFinanceLocked(date){return !date||date<FINANCE_START_DATE||financeDays.some(x=>(x.id===date||x.businessDate===date)&&x.locked===true)}
function changeMonth(offset){const d=new Date(`${selectedMonth}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+offset);selectedMonth=d.toISOString().slice(0,7);if(selectedMonth>today().slice(0,7))selectedMonth=today().slice(0,7);render()}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function monthName(value){return new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T12:00:00Z`))}function formatDate(value){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}function formatPhone(value){const n=String(value||"").replace(/\D/g,"").replace(/^90/,"");return n.length===10?`0${n.slice(0,3)} ${n.slice(3,6)} ${n.slice(6,8)} ${n.slice(8)}`:value}function number(value){return Number(value)||0}function money(value){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(number(value))}function formatNumber(value){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(number(value))}function tick(){const now=new Date;$("currentTime").textContent=now.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=now.toLocaleDateString("tr-TR")}function esc(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function message(id,value){$(id).textContent=value}function callableMessage(error){const code=String(error?.code||"");if(code.includes("already-exists"))return"Bu telefon numarası başka hesapta kayıtlı.";if(code.includes("permission-denied"))return"Bu işlem yalnızca ana yönetici tarafından yapılabilir.";if(code.includes("invalid-argument"))return"Kullanıcı bilgilerini ve yetkileri kontrol edin.";return"İşlem tamamlanamadı. İnternet bağlantısını kontrol edin."}function toast(value){clearTimeout(toastTimer);$("toast").textContent=value;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3200)}
