import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{systemConfirm}from"../assets/js/system-confirm.js?v=395";
import{savingsOwner,savingsApi,savingsKey,savingsError,savingsMoney,formatScaled,valuationCents,averageCostMicros,savingsTime,escSavings,todaySavings,unlockSavings,openSavingsMovement,savingsSummaryMarkup}from"../assets/js/savings.js?v=420";
const app=getApps().find(x=>x.name==="[DEFAULT]")||initializeApp(firebaseConfig),auth=getAuth(app),$=id=>document.getElementById(id),embedded=new URLSearchParams(location.search).get("embed")==="1",kinds={tl:"TL birikim",currency:"Döviz",gold:"Altın",silver:"Gümüş",term:"Vadeli hesap"};
if(!embedded)location.replace("../yonetim-merkezi/?birikim=1&r=422");
let state={accounts:[],operations:[],rates:{}},selectedId="",busy=false,expiryTimer,refreshId=0,accountRequestKey=savingsKey();
if(embedded)document.documentElement.classList.add("is-embedded");
$("historyMonth").value=todaySavings().slice(0,7);$("historyMonth").onchange=renderHistory;
$("logoutButton").onclick=async()=>{clearData();await signOut(auth);top.location.replace("../yonetici-giris.html")};
$("lockSavings").onclick=async()=>{try{await savingsApi("lock");clearData();if(embedded)parent.postMessage({type:"fatih-savings-close"},location.origin);else location.replace("../yonetim-merkezi/")}catch(e){pageError(e)}};
$("refreshSavings").onclick=()=>refresh(true).catch(pageError);
$("investSavings").onclick=()=>transfer({direction:"invest"});$("redeemSavings").onclick=()=>transfer({direction:"redeem"});
$("newAccount").onclick=()=>{if(busy)return;$("accountForm").reset();accountRequestKey=savingsKey();$("accountForm").querySelector(".savings-error").textContent="";accountFields();$("accountDialog").showModal();setTimeout(()=>$("accountForm").elements.name.focus(),60)};
$("accountForm").elements.kind.onchange=accountFields;$("accountForm").onsubmit=createAccount;
$("accountGrid").onclick=e=>{const b=e.target.closest("[data-account]");if(b)showAccount(b.dataset.account)};for(const name of ["allHistory","detailHistory"])$(name).onclick=historyAction;$("detailActions").onclick=detailAction;
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{if(!busy)$(b.dataset.close).close()});document.querySelectorAll("dialog").forEach(d=>d.addEventListener("cancel",e=>{if(busy)e.preventDefault()}));
onAuthStateChanged(auth,async user=>{if(!user){clearData();top.location.replace("../yonetici-giris.html?next=yonetim-merkezi/");return}if(!savingsOwner()){clearData();top.location.replace("../yonetim-merkezi/");return}try{if(!await unlockSavings()){closePage();return}await refresh(true)}catch(e){pageError(e)}});
function closePage(){if(embedded)parent.postMessage({type:"fatih-savings-close"},location.origin);else location.replace("../yonetim-merkezi/")}
function clearData(){refreshId++;clearTimeout(expiryTimer);state={accounts:[],operations:[],rates:{}};$("savingsApp").hidden=true;for(const id of ["accountGrid","allHistory","detailHistory","summary","detailBalance"])$(id).replaceChildren();document.querySelectorAll("dialog[open]").forEach(d=>d.close())}
function pageError(e){$("savingsPageError").textContent=savingsError(e);if($("savingsApp").hidden){$("savingsApp").hidden=false;$("connection").textContent="Birikim verileri alınamadı. Yenile ile tekrar deneyin."}}
async function refresh(updateRates=false){const current=++refreshId;$("connection").textContent="Güncelleniyor…";if(updateRates)await savingsApi("rates").catch(()=>{});const data=await savingsApi("read");if(current!==refreshId)return;state=data;$("savingsApp").hidden=false;$("savingsPageError").textContent="";const rate=data.rates||{},warning=rate.stale?" • Kur güncel değil":"";$("connection").textContent=`Kur kaynağı: ${rate.source||"Kur bekleniyor"} • Son güncelleme: ${savingsTime(rate.updatedAtMs)}${warning}`;$("connection").classList.toggle("is-stale",rate.stale===true);render();clearTimeout(expiryTimer);expiryTimer=setTimeout(closePage,Math.max(0,data.accessUntilMs-data.serverNowMs))}
function render(){$("summary").innerHTML=savingsSummaryMarkup(state);$("emptySavings").hidden=state.accounts.length>0;$("accountGrid").innerHTML=[...state.accounts].sort((a,b)=>Number(b.active)-Number(a.active)||a.name.localeCompare(b.name,"tr")).map(accountCard).join("");renderHistory();if($("detailDialog").open)renderDetail()}
function accountCard(a){const value=valuationCents(a),code=a.symbol||a.unit;return`<button type="button" class="savings-account ${a.active?"":"is-closed"}" data-account="${escSavings(a.id)}"><span class="account-card-head"><strong>${escSavings(a.name)}</strong><small>${escSavings(kinds[a.kind])} • ${escSavings(code)}${a.active?"":" • Kapalı"}</small></span><b class="account-quantity">${formatScaled(a.balanceUnits,a.precision)} ${escSavings(a.unit)}</b><small class="account-tl-value">${value===null?"Güncel TL değeri bulunamadı":savingsMoney(value)}</small></button>`}
function renderHistory(){const month=$("historyMonth").value,ops=state.operations.filter(o=>o.businessDate.startsWith(month)).sort((a,b)=>b.createdAtMs-a.createdAtMs);$("allHistory").innerHTML=historyMarkup(ops);const active=ops.filter(o=>o.status==="active"),invest=active.filter(o=>o.direction==="invest").reduce((s,o)=>s+o.amountCents,0),redeem=active.filter(o=>o.direction==="redeem").reduce((s,o)=>s+o.amountCents,0);$("monthlyTotals").textContent=`Yatırım: ${savingsMoney(invest)} • Bozdurma: ${savingsMoney(redeem)} • Gelir, gider ve satış toplamlarından ayrı.`}
function historyMarkup(ops){if(!ops.length)return'<p class="empty">Bu dönemde hareket yok.</p>';return ops.map(o=>{const status={active:"Aktif",cancelled:"İptal edildi",superseded:"Düzenlendi — eski kayıt"}[o.status],editable=o.status==="active"&&o.businessDate===todaySavings(),account={cash:"Nakit Kasa",bank:"Banka",card:"POS / Kart"}[o.tlAccount]||o.tlAccount;return`<article class="savings-row"><div><strong>${escSavings(o.accountName)} • ${o.direction==="invest"?"Yatırım":"Bozdurma"}</strong><small>${escSavings(o.description)}</small><small>${savingsTime(o.createdAtMs)} • ${escSavings(account)} • ${escSavings(status)}</small><small>Gerçek işlem tutarı: ${savingsMoney(o.amountCents)} • Birim maliyet: ${formatScaled(o.rateMicros,6)} TL</small><small>İşlem kimliği: ${escSavings(o.transactionId)}</small>${editable?`<div class="savings-row-actions"><button type="button" data-edit="${escSavings(o.id)}">Düzenle</button><button type="button" data-cancel="${escSavings(o.id)}">İptal Et</button></div>`:""}</div><div class="savings-amount"><strong>${formatScaled(o.quantityUnits,o.precision)} ${escSavings(o.unit)}</strong><small>${savingsMoney(o.amountCents)}</small></div></article>`}).join("")}
function showAccount(id){selectedId=id;renderDetail();$("detailDialog").showModal()}
function renderDetail(){const a=state.accounts.find(a=>a.id===selectedId);if(!a)return;const value=valuationCents(a),average=averageCostMicros(a),current=["tl","term"].includes(a.kind)?1000000:a.valuationRateMicros;$("detailTitle").textContent=a.name;$("detailBalance").innerHTML=`<div class="savings-detail-summary"><div><span>Mevcut miktar</span><b>${formatScaled(a.balanceUnits,a.precision)} ${escSavings(a.unit)}</b></div><div><span>Ortalama maliyet</span><b>${average?`${formatScaled(average,6)} TL / ${escSavings(a.unit)}`:"—"}</b></div><div><span>Güncel kur</span><b>${current?`${formatScaled(current,6)} TL / ${escSavings(a.unit)}`:"Kur bulunamadı"}</b><small>${escSavings(a.valuationSource||"")} • ${savingsTime(a.valuationAtMs)}</small></div><div><span>Güncel TL değeri</span><b>${value===null?"Kur bulunamadı":savingsMoney(value)}</b></div></div>`;$("detailActions").innerHTML=a.active?'<button type="button" class="soft" data-action="close">Hesabı Kapat</button>':'<button type="button" class="soft" data-action="reopen">Yeniden Aç</button>';$("detailHistory").innerHTML=historyMarkup(state.operations.filter(o=>o.accountId===a.id).sort((x,y)=>y.createdAtMs-x.createdAtMs))}
async function transfer(options){if(busy)return;busy=true;try{if(await openSavingsMovement(options))await refresh()}catch(e){pageError(e)}finally{busy=false}}
async function historyAction(e){const edit=e.target.closest("[data-edit]"),cancel=e.target.closest("[data-cancel]");if(edit||cancel)await transfer({operationId:edit?.dataset.edit||cancel.dataset.cancel,cancel:!!cancel})}
async function detailAction(e){const button=e.target.closest("[data-action]");if(!button||busy)return;const action=button.dataset.action;if(!await systemConfirm({title:action==="close"?"Birikim Hesabı Kapatılsın mı?":"Hesap Yeniden Açılsın mı?",message:action==="close"?"Bakiye ve işlem geçmişi korunacak.":"Hesap tekrar yatırım ve bozdurma seçeneklerinde görünecek.",confirmText:action==="close"?"Hesabı Kapat":"Yeniden Aç"}))return;busy=true;try{await savingsApi("account",{action,accountId:selectedId,clientKey:savingsKey(),businessDate:todaySavings()});await refresh()}catch(e){pageError(e)}finally{busy=false}}
function accountFields(){const f=$("accountForm").elements,kind=f.kind.value,label=$("assetLabel"),select=f.symbol;if(kind==="currency"){label.hidden=false;select.innerHTML='<option value="USD">Dolar — USD</option><option value="EUR">Euro — EUR</option>';$("accountUnitHint").textContent="Seçilen döviz kodu hesap birimi olarak otomatik kaydedilir."}else if(kind==="gold"){label.hidden=false;select.innerHTML='<option value="XAU">Altın — XAU • gram</option>';$("accountUnitHint").textContent="Altın hesabı gram ve XAU koduyla açılır."}else if(kind==="silver"){label.hidden=false;select.innerHTML='<option value="XAG">Gümüş — XAG • gram</option>';$("accountUnitHint").textContent="Gümüş hesabı gram ve XAG koduyla açılır."}else{label.hidden=true;select.innerHTML='<option value="">TL</option>';$("accountUnitHint").textContent=kind==="term"?"Vadeli hesap TL olarak takip edilir.":"Birim: TL"}}
async function createAccount(e){e.preventDefault();if(busy)return;busy=true;const form=e.target,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{await savingsApi("account",{action:"create",name:form.elements.name.value,kind:form.elements.kind.value,symbol:form.elements.symbol.value,clientKey:accountRequestKey,businessDate:todaySavings()});$("accountDialog").close();await refresh()}catch(err){form.querySelector(".savings-error").textContent=savingsError(err)}finally{busy=false;submit.disabled=false}}
function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
