import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{systemConfirm}from"../assets/js/system-confirm.js?v=395";
import{savingsOwner,savingsApi,savingsKey,savingsError,savingsMoney,formatScaled,plainScaled,valuationCents,savingsTime,escSavings,todaySavings,unlockSavings,openSavingsMovement,savingsSummaryMarkup}from"../assets/js/savings.js?v=416";
const app=getApps().find(x=>x.name==="[DEFAULT]")||initializeApp(firebaseConfig),auth=getAuth(app),$=id=>document.getElementById(id),kinds={tl:"TL birikim",currency:"Döviz",gold:"Altın",silver:"Gümüş",equity:"Hisse / fon",term:"Vadeli",custom:"Diğer yatırım"};
let state={accounts:[],operations:[]},selectedId="",busy=false,expiryTimer,refreshId=0,accountRequestKey=savingsKey();
$("historyMonth").value=todaySavings().slice(0,7);$("historyMonth").onchange=renderHistory;
$("logoutButton").onclick=async()=>{clearData();await signOut(auth);location.replace("../yonetici-giris.html")};
$("lockSavings").onclick=async()=>{try{await savingsApi("lock");clearData();location.replace("../yonetim-merkezi/")}catch(e){pageError(e)}};
$("refreshSavings").onclick=()=>refresh().catch(pageError);
$("newAccount").onclick=()=>{if(busy)return;$("accountForm").reset();accountRequestKey=savingsKey();$("accountForm").querySelector(".savings-error").textContent="";accountFields();$("accountDialog").showModal();setTimeout(()=>$("accountForm").elements.name.focus(),60)};
$("accountForm").elements.kind.onchange=accountFields;$("accountForm").onsubmit=createAccount;
$("transferSavings").onclick=()=>transfer({});
$("accountGrid").onclick=e=>{const b=e.target.closest("[data-account]");if(b)showAccount(b.dataset.account)};
for(const name of ["allHistory","detailHistory"])$(name).onclick=historyAction;
$("detailActions").onclick=detailAction;$("rateForm").onsubmit=saveRate;
$("exportSavings").onclick=exportData;
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{if(!busy)$(b.dataset.close).close()});document.querySelectorAll("dialog").forEach(d=>d.addEventListener("cancel",e=>{if(busy)e.preventDefault()}));
onAuthStateChanged(auth,async user=>{if(!user){clearData();location.replace("../yonetici-giris.html?next=birikim-hesaplari/");return}if(!savingsOwner()){clearData();location.replace("../yonetim-merkezi/");return}try{if(!await unlockSavings()){location.replace("../yonetim-merkezi/");return}await refresh()}catch(e){pageError(e)}});
function clearData(){refreshId++;clearTimeout(expiryTimer);state={accounts:[],operations:[]};$("savingsApp").hidden=true;for(const id of ["accountGrid","allHistory","detailHistory","summary","detailBalance"])$(id).replaceChildren();document.querySelectorAll("dialog[open]").forEach(d=>d.close())}
function pageError(e){$("savingsPageError").textContent=savingsError(e);if($("savingsApp").hidden){$("savingsApp").hidden=false;$("connection").textContent="Birikim verileri alınamadı. Yenile ile tekrar deneyin."}}
async function refresh(){const current=++refreshId;$("connection").textContent="Güncelleniyor…";const data=await savingsApi("read");if(current!==refreshId)return;state=data;$("savingsApp").hidden=false;$("savingsPageError").textContent="";$("connection").textContent=`Son kontrol: ${savingsTime(data.serverNowMs)} • Kaynak: manuel işlem ve değerleme kayıtları`;render();clearTimeout(expiryTimer);expiryTimer=setTimeout(()=>{clearData();location.replace("../yonetim-merkezi/")},Math.max(0,data.accessUntilMs-data.serverNowMs))}
function render(){
 $("summary").innerHTML=savingsSummaryMarkup(state);$("emptySavings").hidden=state.accounts.length>0;
 $("accountGrid").innerHTML=[...state.accounts].sort((a,b)=>Number(b.active)-Number(a.active)||a.name.localeCompare(b.name,"tr")).map(a=>`<button type="button" class="savings-account ${a.active?"":"is-closed"}" data-account="${escSavings(a.id)}"><strong>${escSavings(a.name)}</strong><span>${escSavings(kinds[a.kind])}${a.symbol?` • ${escSavings(a.symbol)}`:""} • ${a.active?"Aktif":"Kapalı"}</span><b>${formatScaled(a.balanceUnits,a.precision)} ${escSavings(a.unit)}</b>${accountValue(a)}</button>`).join("");renderHistory();if($("detailDialog").open)renderDetail()
}
function accountValue(a){const value=valuationCents(a),tl=["tl","term"].includes(a.kind),stale=!tl&&a.valuationAtMs&&Date.now()-a.valuationAtMs>86400000;return`<b class="savings-value">${value===null?"Kur bulunamadı":savingsMoney(value)}</b><small>İşlem maliyeti: ${savingsMoney(a.costCents)}</small><small>Değerleme: ${tl?"TL / 1:1":a.valuationRateMicros?`${formatScaled(a.valuationRateMicros,6)} TL / ${escSavings(a.unit)}`:"Kur girilmedi"}</small><small>Kaynak: ${tl?"Sabit TL":escSavings(a.valuationSource||"Manuel kur bekleniyor")}</small><small>Değerleme zamanı: ${tl?"Sabit TL — kur güncellemesi gerekmez":savingsTime(a.valuationAtMs)}${stale?" • Eski kur; güncelleyin":""}</small>`}
function renderHistory(){const month=$("historyMonth").value,ops=state.operations.filter(o=>o.businessDate.startsWith(month)).sort((a,b)=>b.createdAtMs-a.createdAtMs);$("allHistory").innerHTML=historyMarkup(ops);const active=ops.filter(o=>o.status==="active"),invest=active.filter(o=>o.direction==="invest").reduce((s,o)=>s+o.amountCents,0),redeem=active.filter(o=>o.direction==="redeem").reduce((s,o)=>s+o.amountCents,0);$("monthlyTotals").textContent=`Ay içi yatırma: ${savingsMoney(invest)} • Bozdurma / TL'ye dönüş: ${savingsMoney(redeem)} • Gelir ve gider toplamlarından ayrı.`}
function historyMarkup(ops){if(!ops.length)return'<p class="empty">Bu dönemde hareket yok.</p>';return ops.map(o=>{const status={active:"Aktif",cancelled:"İptal edildi",superseded:"Düzenlendi — eski kayıt"}[o.status],editable=o.status==="active"&&o.businessDate===todaySavings();return`<article class="savings-row"><div><strong>${escSavings(o.accountName)} • ${o.direction==="invest"?"Birikime yatırma":"Bozdurma / TL'ye dönüş"}</strong><small>${escSavings(o.description)}</small><small>${savingsTime(o.createdAtMs)} • ${o.tlAccount==="cash"?"Nakit Kasa":"Banka"} • ${escSavings(status)}</small><small>İşlem kuru: ${formatScaled(o.rateMicros,6)} TL / ${escSavings(o.unit)} • ${escSavings(o.rateSource)} • ${savingsTime(o.rateAtMs)}</small><small>İşlem kimliği: ${escSavings(o.transactionId)}</small>${o.replacementOf?`<small>Önceki işlem: ${escSavings(o.replacementOf)}</small>`:""}${editable?`<div class="savings-row-actions"><button type="button" data-edit="${escSavings(o.id)}">Düzenle</button><button type="button" data-cancel="${escSavings(o.id)}">İptal Et</button></div>`:""}</div><div class="savings-amount"><strong>${formatScaled(o.quantityUnits,o.precision)} ${escSavings(o.unit)}</strong><small>${savingsMoney(o.amountCents)}</small></div></article>`}).join("")}
function showAccount(id){selectedId=id;renderDetail();$("detailDialog").showModal()}
function renderDetail(){const a=state.accounts.find(a=>a.id===selectedId);if(!a)return;$("detailTitle").textContent=a.name;$("detailBalance").innerHTML=`<div class="savings-preview"><b>${formatScaled(a.balanceUnits,a.precision)} ${escSavings(a.unit)}</b>${accountValue(a)}</div>`;$("detailActions").innerHTML=a.active?`<button type="button" data-action="invest">Yatır</button><button type="button" data-action="redeem">Bozdur</button>${!["tl","term"].includes(a.kind)?'<button type="button" class="soft" data-action="rate">Değerleme Kuru</button>':""}<button type="button" class="soft" data-action="close">Hesabı Kapat</button>`:'<button type="button" class="soft" data-action="reopen">Yeniden Aç</button>';$("detailHistory").innerHTML=historyMarkup(state.operations.filter(o=>o.accountId===a.id).sort((a,b)=>b.createdAtMs-a.createdAtMs))}
async function transfer(options){if(busy)return;busy=true;try{if(await openSavingsMovement(options))await refresh()}catch(e){pageError(e)}finally{busy=false}}
async function historyAction(e){const edit=e.target.closest("[data-edit]"),cancel=e.target.closest("[data-cancel]");if(edit||cancel)await transfer({operationId:edit?.dataset.edit||cancel.dataset.cancel,cancel:!!cancel})}
async function detailAction(e){const button=e.target.closest("[data-action]");if(!button||busy)return;const action=button.dataset.action;if(["invest","redeem"].includes(action))return transfer({accountId:selectedId,direction:action});if(action==="rate"){const a=state.accounts.find(x=>x.id===selectedId);$("rateForm").elements.rate.value=a.valuationRateMicros?plainScaled(a.valuationRateMicros,6):"";$("rateForm").querySelector(".savings-error").textContent="";$("rateDialog").showModal();setTimeout(()=>{const f=$("rateForm").elements.rate;f.focus();f.select()},60);return}if(!await systemConfirm({title:action==="close"?"Birikim Hesabı Kapatılsın mı?":"Hesap Yeniden Açılsın mı?",message:action==="close"?"Bakiye ve geçmiş korunacak. Kapalı hesap yeni yatırma veya bozdurma işlemlerinde seçilemez.":"Hesap tekrar aktarım seçeneklerinde görünecek.",confirmText:action==="close"?"Hesabı Kapat":"Yeniden Aç"}))return;busy=true;try{await savingsApi("account",{action,accountId:selectedId,clientKey:savingsKey(),businessDate:todaySavings()});await refresh()}catch(e){pageError(e)}finally{busy=false}}
function accountFields(){const f=$("accountForm").elements,kind=f.kind.value;$("symbolLabel").hidden=!["currency","equity","custom"].includes(kind);$("unitLabel").hidden=!["equity","custom"].includes(kind);f.symbol.required=["currency","equity"].includes(kind);f.unit.required=["equity","custom"].includes(kind);$("accountUnitHint").textContent=["tl","term"].includes(kind)?"Birim: TL • 2 ondalık basamak":["gold","silver"].includes(kind)?"Birim: gram • 4 ondalık basamak":kind==="currency"?"Birim: girilen döviz kodu • 2 ondalık basamak":"Birim: pay / adet veya tanımladığın birim • 4 ondalık basamak"}
async function createAccount(e){e.preventDefault();if(busy)return;busy=true;const form=e.target,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{await savingsApi("account",{action:"create",name:form.elements.name.value,kind:form.elements.kind.value,symbol:form.elements.symbol.value,unit:form.elements.unit.value,clientKey:accountRequestKey,businessDate:todaySavings()});$("accountDialog").close();await refresh()}catch(err){form.querySelector(".savings-error").textContent=savingsError(err)}finally{busy=false;submit.disabled=false}}
async function saveRate(e){e.preventDefault();if(busy)return;busy=true;const form=e.target,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{await savingsApi("account",{action:"rate",accountId:selectedId,rate:form.elements.rate.value,clientKey:savingsKey(),businessDate:todaySavings()});$("rateDialog").close();await refresh()}catch(err){form.querySelector(".savings-error").textContent=savingsError(err)}finally{busy=false;submit.disabled=false}}
async function exportData(){if(busy)return;busy=true;try{const data=await savingsApi("read",{backup:true}),blob=new Blob([JSON.stringify({app:"Fatih Çay Evi",type:"savings-backup",version:416,...data},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`fatih-cay-evi-birikim-${todaySavings()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){pageError(e)}finally{busy=false}}
function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
