import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{addDoc,collection,deleteDoc,doc,getFirestore,limit,onSnapshot,orderBy,query,serverTimestamp,setDoc,updateDoc}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../firebase-config.js";
import{hasPanelAccess}from"../admin-access.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let schedules=[],toastTimer;
document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("active",x.dataset.panel===button.dataset.tab))});
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=bildirim-yonetimi/");return}if(!await hasPanelAccess(user,db,"notifications")){location.replace("../yonetici-giris.html");return}subscribe()});
function subscribe(){
  onSnapshot(collection(db,"pushSubscriptions"),snap=>{const counts={customer:0,admin:0,merchant:0},customerPrefs={tea:0,campaign:0};snap.forEach(d=>{const x=d.data();if(x.enabled!==false&&counts[x.audience]!==undefined){counts[x.audience]++;if(x.audience==="customer"){if(x.teaUpdates===true)customerPrefs.tea++;if(x.campaigns===true)customerPrefs.campaign++}}});$("customerCount").textContent=counts.customer;$("customerCount").title=`Taze Dem: ${customerPrefs.tea} • Kampanya: ${customerPrefs.campaign}`;$("adminCount").textContent=counts.admin;$("merchantCount").textContent=counts.merchant});
  onSnapshot(query(collection(db,"notificationSchedules"),orderBy("time"),limit(30)),snap=>{schedules=snap.docs.map(d=>({id:d.id,...d.data()}));renderSchedules()});
  onSnapshot(doc(db,"notificationSettings","tea"),snap=>{const x=snap.data()||{};const f=$("teaSettingsForm");f.readyEnabled.checked=x.readyEnabled!==false;f.expiredEnabled.checked=x.expiredEnabled!==false;f.readyBody.value=x.readyBody||"Demlik {no} hazır, çay demlendi.";f.expiredBody.value=x.expiredBody||"Demlik {no} tazelik süresi doldu."});
  onSnapshot(query(collection(db,"notificationHistory"),orderBy("createdAtMs","desc"),limit(20)),snap=>renderHistory(snap.docs.map(d=>({id:d.id,...d.data()}))));
}
document.querySelectorAll(".send-form").forEach(form=>form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector("button"),title=form.elements.title.value.trim(),body=form.elements.body.value.trim(),category=form.dataset.audience==="customer"?"campaign":"";if(!title||!body)return;button.disabled=true;try{await addDoc(collection(db,"notificationOutbox"),{audience:form.dataset.audience,category,title,body,status:"queued",url:targetUrl(form.dataset.audience),createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});form.elements.body.value="";toast("Bildirim gönderim sırasına alındı.")}catch(err){console.error(err);toast("Bildirim gönderilemedi.")}finally{button.disabled=false}});
$("scheduleForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.scheduleId.value,data={audience:"customer",category:"tea",time:f.elements.time.value,title:f.elements.title.value.trim(),body:f.elements.body.value.trim(),active:f.elements.active.checked,timezone:"Europe/Istanbul",updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};if(!data.time||!data.title||!data.body)return;try{id?await updateDoc(doc(db,"notificationSchedules",id),data):await addDoc(collection(db,"notificationSchedules"),{...data,createdAt:serverTimestamp()});resetSchedule();toast("Otomatik bildirim kaydedildi.")}catch(err){console.error(err);toast("Otomatik bildirim kaydedilemedi.")}};
$("cancelScheduleEdit").onclick=resetSchedule;
$("scheduleList").onclick=async e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]"),toggle=e.target.closest("[data-toggle]");if(edit){const x=schedules.find(s=>s.id===edit.dataset.edit),f=$("scheduleForm");f.elements.scheduleId.value=x.id;f.elements.time.value=x.time;f.elements.title.value=x.title;f.elements.body.value=x.body;f.elements.active.checked=x.active!==false;$("cancelScheduleEdit").hidden=false;f.scrollIntoView({behavior:"smooth",block:"center"})}if(toggle){const x=schedules.find(s=>s.id===toggle.dataset.toggle);await updateDoc(doc(db,"notificationSchedules",x.id),{active:x.active===false,updatedAt:serverTimestamp()})}if(del&&confirm("Bu otomatik bildirim silinsin mi?"))await deleteDoc(doc(db,"notificationSchedules",del.dataset.delete))};
$("teaSettingsForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await setDoc(doc(db,"notificationSettings","tea"),{readyEnabled:f.readyEnabled.checked,expiredEnabled:f.expiredEnabled.checked,readyBody:f.readyBody.value.trim(),expiredBody:f.expiredBody.value.trim(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Taze Dem bildirim ayarları kaydedildi.")}catch(err){console.error(err);toast("Ayarlar kaydedilemedi.")}};
document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>{document.querySelector('[data-audience="merchant"] textarea').value=b.dataset.copy});
function renderSchedules(){$("scheduleList").innerHTML=schedules.length?schedules.map(x=>`<article class="schedule-item ${x.active===false?"off":""}"><strong class="schedule-time">${esc(x.time)}</strong><div class="schedule-copy"><strong>${esc(x.title)}</strong><span>${esc(x.body)}</span></div><div class="row-actions"><button data-toggle="${x.id}" title="${x.active===false?"Aç":"Kapat"}"><i class="fa-solid ${x.active===false?"fa-toggle-off":"fa-toggle-on"}"></i></button><button data-edit="${x.id}" title="Düzenle"><i class="fa-solid fa-pen"></i></button><button data-delete="${x.id}" title="Sil"><i class="fa-solid fa-trash"></i></button></div></article>`).join(""):'<p class="empty">Henüz otomatik bildirim eklenmedi.</p>'}
function renderHistory(items){const names={customer:"Müşteri",admin:"Yönetici",merchant:"Esnaf"};$("historyList").innerHTML=items.length?items.map(x=>`<article class="history-item"><span class="status-pill">${names[x.audience]||x.audience}</span><div class="history-copy"><strong>${esc(x.title||"Fatih Çay Evi")}</strong><span>${esc(x.body||"")} • ${dateTime(x.createdAtMs)} • ${Number(x.successCount)||0} teslim</span></div></article>`).join(""):'<p class="empty">Henüz gönderim yok.</p>'}
function resetSchedule(){const f=$("scheduleForm");f.reset();f.elements.scheduleId.value="";f.elements.time.value="17:30";f.elements.title.value="Fatih Çay Evi";f.elements.active.checked=true;$("cancelScheduleEdit").hidden=true}
function targetUrl(a){return a==="merchant"?"https://fatihcayevicorum.github.io/esnaf-paneli/":a==="admin"?"https://fatihcayevicorum.github.io/bildirim-yonetimi/":"https://fatihcayevicorum.github.io/"}
function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
function dateTime(ms){return ms?new Date(ms).toLocaleString("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Şimdi"}function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML}function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2800)}
