import{getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{collection,doc,getFirestore,onSnapshot,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{hasPanelAccess}from"../assets/js/admin-access.js";

const app=getApps().find(x=>x.name==="[DEFAULT]")||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const refs={sales:collection(db,"adminSales"),closings:collection(db,"adminDailyClosings"),cash:collection(db,"adminCashMovements"),stocks:collection(db,"adminStockItems"),internal:collection(db,"adminInternalConsumptions"),current:collection(db,"adminCurrentAccounts"),menu:doc(db,"publicMenu","catalog"),pos:doc(db,"adminAppSettings","pos"),tea:doc(db,"adminTea","state"),settings:doc(db,"adminAppSettings","analytics")};
let sales=[],closings=[],cash=[],stocks=[],internal=[],current=[],catalog={categories:[],items:[]},teaState={activeBrews:[],history:[]},pos={},settings={teaGramsPerPot:90,expectedCupsPerPot:11,safetyPercent:10,inactiveDays:60},period="today",range={start:today(),end:today()},activeTab="overview",loaded=new Set(),failedSources=new Set(),toastTimer,analysis={};

onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=isletme-asistani/");return}if(!await hasPanelAccess(user,db,"reports")){location.replace("../yonetici-giris.html");return}subscribe()});
function subscribe(){
  onSnapshot(refs.sales,s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));ready('sales')},error=>fail(error,'sales'));onSnapshot(refs.closings,s=>{closings=s.docs.map(d=>({id:d.id,...d.data()}));ready('closings')},error=>fail(error,'closings'));onSnapshot(refs.cash,s=>{cash=s.docs.map(d=>({id:d.id,...d.data()}));ready('cash')},error=>fail(error,'cash'));onSnapshot(refs.stocks,s=>{stocks=s.docs.map(d=>({id:d.id,...d.data()}));ready('stocks')},error=>fail(error,'stocks'));onSnapshot(refs.internal,s=>{internal=s.docs.map(d=>({id:d.id,...d.data()}));ready('internal')},error=>fail(error,'internal'));onSnapshot(refs.current,s=>{current=s.docs.map(d=>({id:d.id,...d.data()}));ready('current')},error=>fail(error,'current'));onSnapshot(refs.menu,s=>{const d=s.data()||{};catalog={categories:Array.isArray(d.categories)?d.categories:[],items:Array.isArray(d.items)?d.items:[]};ready('menu')},error=>fail(error,'menu'));onSnapshot(refs.pos,s=>{pos=s.data()||{};if(period==="today")range={start:pos.currentBusinessDate||today(),end:pos.currentBusinessDate||today()};ready('pos')},error=>fail(error,'pos'));onSnapshot(refs.tea,s=>{teaState=s.data()||{activeBrews:[],history:[]};ready('tea')},error=>fail(error,'tea'));onSnapshot(refs.settings,s=>{settings={...settings,...s.data()};fillSettings();ready('settings')},error=>fail(error,'settings'))
}
function ready(source){loaded.add(source);failedSources.delete(source);const complete=loaded.size===Object.keys(refs).length&&!failedSources.size;$('connection').textContent=complete?'Canlı veri':failedSources.size?'Eksik veri • bağlantıyı kontrol edin':'Veriler yükleniyor…';$('connection').classList.toggle('error',failedSources.size>0);render()}
function fail(error,source){failedSources.add(source);console.error(error);$("connection").innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Bağlantı hatası';$("connection").classList.add("error");show("Analiz verilerinin bir bölümü alınamadı.")}

$("periodButtons").onclick=e=>{const b=e.target.closest("[data-period]");if(!b)return;period=b.dataset.period;[...$("periodButtons").children].forEach(x=>x.classList.toggle("active",x===b));$("dateRange").hidden=period!=="custom";if(period!=="custom"){range=periodRange(period);render()}};
$("applyRange").onclick=()=>{const start=$("startDate").value,end=$("endDate").value;if(!start||!end)return show("Başlangıç ve bitiş tarihini seçin.");if(start>end)return show("Başlangıç tarihi bitişten sonra olamaz.");range={start,end};render()};
$("analysisTabs").onclick=e=>{const b=e.target.closest("[data-tab]");if(!b)return;activeTab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===activeTab));document.querySelectorAll("[data-panel]").forEach(x=>x.hidden=x.dataset.panel!==activeTab);if(activeTab==="ask")setTimeout(()=>$("questionInput").focus(),60);if(activeTab==="overview")drawTrend()};
$("productSearch").oninput=renderProducts;$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("settingsButton").onclick=()=>{$("settingsDialog").showModal();setTimeout(()=>$("teaGramsPerPot").select(),60)};$("closeSettings").onclick=$("cancelSettings").onclick=()=>$("settingsDialog").close();
$("settingsForm").onsubmit=async e=>{e.preventDefault();const next={teaGramsPerPot:num($("teaGramsPerPot").value),expectedCupsPerPot:num($("expectedCupsPerPot").value),safetyPercent:num($("safetyPercent").value),inactiveDays:num($("inactiveDays").value),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};try{await setDoc(refs.settings,next,{merge:true});$("settingsDialog").close();show("Analiz ayarları kaydedildi.")}catch(error){console.error(error);show("Ayarlar kaydedilemedi.")}};
$("suggestedQuestions").onclick=e=>{const b=e.target.closest("button");if(!b)return;$("questionInput").value=b.textContent;askQuestion(b.textContent)};$("askForm").onsubmit=e=>{e.preventDefault();const q=$("questionInput").value.trim();if(q)askQuestion(q)};
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});window.addEventListener("resize",()=>{if(activeTab==="overview")drawTrend()});updateClock();setInterval(updateClock,1000);

function render(){analysis=buildAnalysis(range);const prev=previousRange(range),previous=buildAnalysis(prev);analysis.previous=previous;analysis.previousRange=prev;$("startDate").value=range.start;$("endDate").value=range.end;$("periodLabel").textContent=`${formatDate(range.start)}${range.start===range.end?"":` – ${formatDate(range.end)}`}`;$("compareLabel").textContent=`${formatDate(prev.start)}${prev.start===prev.end?"":` – ${formatDate(prev.end)}`} ile karşılaştırılıyor`;renderSummary();renderCategories();renderComparison();renderNarrative();renderTea();renderProducts();renderForecasts();renderAttention();requestAnimationFrame(drawTrend)}
function buildAnalysis(r){
  const selected=sales.filter(x=>!x.reversed&&!x.cancelled&&!String(x.recordType||"").startsWith("correction")&&inRange(saleDate(x),r)&&validCurrentDay(x,r)),products=new Map(),days=new Map(),merchantByDay=new Map();let revenue=0,cashPaid=0,bankPaid=0,cardPaid=0,cariWritten=0,merchantTea=0,gifts=0,giftTea=0,merchantCost=0,orders=0;
  for(const sale of selected){if(["merchant-topup","merchant-topup-correction","merchant-delivery","merchant-manual-delivery","correction"].includes(sale.recordType))continue;if(["payment","credit-payment","credit-topup","current-account-payment"].includes(sale.recordType)){continue}if(sale.recordType!=="sale"&&sale.items==null)continue;const date=saleDate(sale),merchant=sale.paymentType==="merchant-marka"||sale.settlementType==="merchant-marka"||sale.merchantMarka===true;if(merchant){const qty=num(sale.merchantTeaCount??sale.merchantMarkaCount);merchantTea+=qty;merchantCost+=(sale.items||[]).reduce((sum,item)=>sum+num(item.quantity)*analysisUnitCost(item),0);merchantByDay.set(date,(merchantByDay.get(date)||0)+qty);orders++;continue}const rounding=num(sale.roundingDiscount)||Math.max(0,-num(sale.roundingAmount)),saleRevenue=Math.max(0,(num(sale.baseTotal)||sumItems(sale.items))-rounding);revenue+=saleRevenue;cashPaid+=Math.max(0,num(sale.cashAmount??(sale.paymentType==="cash"?(sale.paymentAmount??sale.paidTotal):0))-num(sale.tipAmount));bankPaid+=num(sale.transferAmount);cardPaid+=num(sale.cardAmount??(sale.paymentType==="card"?(sale.paymentAmount??sale.paidTotal):0));if(sale.settlementType==="current-account")cariWritten+=num(sale.currentAccountAmount);orders++;const day=days.get(date)||{date,revenue:0,cost:0,profit:0,items:0};day.revenue+=saleRevenue;for(const item of sale.items||[]){const qty=num(item.quantity);if(item.complimentary){gifts+=qty;if(normalize(item.name)==="cay")giftTea+=qty;}const menuItem=catalog.items.find(x=>x.id===item.id),id=item.id||`${item.name}|${item.unitPrice}`,stock=stocks.find(x=>x.active!==false&&x.linkedMenuItemId===item.id),unitCost=Number.isFinite(item.unitCostSnapshot)?item.unitCostSnapshot:stocks.filter(x=>x.active!==false&&x.linkedMenuItemId===item.id).reduce((sum,x)=>sum+num(x.unitCost)*(num(x.deductionAmount)||1),0),cost=qty*unitCost,total=item.complimentary?0:qty*num(item.unitPrice)*(sumItems(sale.items)>0?saleRevenue/sumItems(sale.items):0),p=products.get(id)||{id,name:item.name||menuItem?.name||"Ürün",categoryId:menuItem?.categoryId||"other",quantity:0,revenue:0,cost:0,unitCost,stock};p.quantity+=item.complimentary?0:qty;p.servedQuantity=(p.servedQuantity||0)+qty;p.revenue+=total;p.cost+=cost;products.set(id,p);day.cost+=cost;day.items+=qty}days.set(date,day)}
  const expenseRows=cash.filter(x=>!x.reversed&&!x.cancelled&&x.type==="expense"&&x.source!=="stock-purchase"&&x.category!=="Toptancı / Ürün Alımı"&&inRange(String(x.businessDate||dateFromTimestamp(x.createdAt)),r)&&validCurrentDay(x,r)),expenses=expenseRows.reduce((s,x)=>s+num(x.amount),0);const productRows=[...products.values()].map(x=>({...x,profit:x.revenue-x.cost})).sort((a,b)=>b.revenue-a.revenue);const internalCost=internal.filter(x=>!x.reversed&&!x.cancelled&&inRange(String(x.businessDate||dateFromTimestamp(x.createdAt)),r)).reduce((sum,x)=>sum+num(x.totalCost),0),cost=productRows.reduce((s,x)=>s+x.cost,0)+merchantCost+internalCost,profit=revenue-cost,operating=profit-expenses;for(const d of days.values())d.profit=d.revenue-d.cost;const activeDays=Math.max(1,new Set([...days.keys(),...merchantByDay.keys()]).size);const teaProduct=productRows.find(x=>normalize(x.name)==="cay"),normalTea=num(teaProduct?.quantity),internalTea=internal.filter(x=>inRange(String(x.businessDate||dateFromTimestamp(x.createdAt)),r)).reduce((sum,row)=>sum+(row.items||[]).filter(x=>normalize(x.name)==="cay").reduce((s,x)=>s+num(x.quantity),0),0);const brewed=brewCount(r),teaServed=normalTea+giftTea+merchantTea+internalTea;const categories=groupCategories(productRows);return{range:r,revenue,cost,merchantCost,internalCost,profit,expenses,operating,cashPaid,bankPaid,cardPaid,cariWritten,merchantTea,gifts,giftTea,orders,products:productRows,categories,days:[...days.values()].sort((a,b)=>a.date.localeCompare(b.date)),activeDays,normalTea,internalTea,brewed,teaServed,grams:brewed*num(settings.teaGramsPerPot),receivable:current.reduce((s,x)=>s+Math.max(0,num(x.balance)),0),missingCosts:productRows.filter(x=>x.quantity>0&&!x.unitCost)}
}
function brewCount(r){const closed=closings.filter(x=>inRange(String(x.businessDate||x.id).slice(0,10),r)).reduce((s,x)=>s+num(x.brewedPotCount),0),closedDates=new Set(closings.filter(x=>inRange(String(x.businessDate||x.id).slice(0,10),r)).map(x=>String(x.businessDate||x.id).slice(0,10))),live=[...(teaState.history||[]),...(teaState.activeBrews||[])].filter(x=>inRange(x.businessDate||dateFromMs(x.startedAtMs),r)&&!closedDates.has(x.businessDate||dateFromMs(x.startedAtMs))).length;return closed+live}
function groupCategories(rows){const map=new Map;for(const p of rows){const id=p.categoryId||"other",x=map.get(id)||{id,name:categoryName(id),quantity:0,revenue:0,cost:0,profit:0};x.quantity+=p.quantity;x.revenue+=p.revenue;x.cost+=p.cost;x.profit+=p.profit;map.set(id,x)}return[...map.values()].sort((a,b)=>b.revenue-a.revenue)}
function renderSummary(){const a=analysis,cards=[["Toplam Satış",money(a.revenue),`${a.orders} kapanan adisyon`,"fa-chart-line","highlight"],["Ürün Maliyeti",money(a.cost),a.missingCosts.length?`${a.missingCosts.length} üründe maliyet eksik`:"İkram, marka ve dahili dahil • tahmini","fa-tags"],["Brüt Kazanç",money(a.profit),"Satış − ürün maliyeti","fa-coins"],["Günlük Gider",money(a.expenses),"Stok alışları ve aktarımlar hariç","fa-arrow-trend-down"],["Gider Sonrası",money(a.operating),"Tahmini işletme sonucu","fa-scale-balanced"]];$("summaryCards").innerHTML=cards.map(x=>`<article class="summary-card ${x[4]||""}"><i class="fa-solid ${x[3]}"></i><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("")}
function renderCategories(){const max=analysis.categories[0]?.revenue||1;$("categoryBars").innerHTML=analysis.categories.slice(0,7).map(x=>`<div class="category-bar"><header><strong>${esc(x.name)}</strong><span>${money(x.revenue)}</span></header><div class="bar"><i style="width:${Math.max(3,x.revenue/max*100)}%"></i></div><header><small>${formatNumber(x.quantity)} adet</small><small>${money(x.profit)} brüt kazanç</small></header></div>`).join("")||'<p class="empty">Bu dönemde kategori satışı bulunmuyor.</p>'}
function renderComparison(){const a=analysis,p=a.previous,rows=[["Toplam satış",a.revenue,p.revenue,money],["Brüt kazanç",a.profit,p.profit,money],["Günlük ortalama Çay",a.normalTea/a.activeDays,p.normalTea/p.activeDays,formatNumber],["Satılan ürün",a.products.reduce((s,x)=>s+x.quantity,0),p.products.reduce((s,x)=>s+x.quantity,0),formatNumber],["Gider",a.expenses,p.expenses,money]];$("comparisonRows").innerHTML=rows.map(x=>{const pct=change(x[1],x[2]),cls=pct>0?"up":pct<0?"down":"same";return`<div class="comparison-row"><strong>${x[0]}</strong><span>${x[3](x[1])} <small>önceki ${x[3](x[2])}</small></span><b class="change ${cls}">${changeText(pct)}</b></div>`}).join("")}
function renderNarrative(){const a=analysis,p=a.previous,ins=[];if(!a.revenue)ins.push("Seçilen dönemde tamamlanmış normal satış bulunmuyor. Kayıt oluştuğunda karşılaştırmalı yorumlar burada hazırlanacak.");else{ins.push(`${periodWords()} toplam ${money(a.revenue)} ürün satışı yapıldı. Kayıtlı ürünlerin tahmini maliyeti ${money(a.cost)}, brüt kazanç ${money(a.profit)} oldu. ${a.expenses?`${money(a.expenses)} gider düşüldüğünde tahmini sonuç ${money(a.operating)}.`:"Bu dönemde kayıtlı gider bulunmuyor."}`);const salesChange=change(a.revenue,p.revenue);if(p.revenue)ins.push(`Satış tutarı önceki eşit döneme göre ${Math.abs(salesChange).toLocaleString("tr-TR",{maximumFractionDigits:1})}% ${salesChange>=0?"yükseldi":"düştü"}. Karşılaştırma aynı sayıda takvim günü üzerinden yapıldı.`);const teaAvg=a.normalTea/a.activeDays,oldTea=p.normalTea/p.activeDays;if(oldTea)ins.push(`Günlük ortalama Çay satışı önceki dönemde ${formatNumber(oldTea)}, bu dönemde ${formatNumber(teaAvg)} bardak. ${teaAvg<oldTea?"Çay satışında düşüş var.":"Çay satışı önceki dönemin üzerinde."}`);const best=[...a.products].sort((x,y)=>y.profit-x.profit)[0];if(best)ins.push(`En fazla brüt kazanç sağlayan ürün ${best.name}: ${formatNumber(best.quantity)} adet satıştan yaklaşık ${money(best.profit)} brüt kazanç.`)}$("assistantNarrative").innerHTML=ins.map((x,i)=>`<div class="insight"><i class="fa-solid ${i?"fa-chart-simple":"fa-mug-hot"}"></i><p>${esc(x)}</p></div>`).join("");$("assistantTitle").textContent=`${periodWords()} Değerlendirmesi`}
function renderTea(){const a=analysis,expected=a.brewed*num(settings.expectedCupsPerPot),diff=a.teaServed-expected,cards=[["Demlenen",`${formatNumber(a.brewed)} demlik`],["Kuru çay",`${formatNumber(a.grams)} gram`],["Satış / İkram",`${formatNumber(a.normalTea)} / ${formatNumber(a.giftTea)} bardak`],["Marka / Dahili",`${formatNumber(a.merchantTea+a.internalTea)} bardak`],["Toplam servis",`${formatNumber(a.teaServed)} bardak`]];$("teaCards").innerHTML=cards.map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join("");$("teaNarrative").textContent=a.brewed?`${a.brewed} demlikten demlik başına ortalama ${formatNumber(a.teaServed/a.brewed)} bardak servis kaydı oluştu. Ayardaki ${settings.expectedCupsPerPot} bardak beklentisine göre ${Math.abs(diff)<1?"servis kaydı beklenen seviyede":`${formatNumber(Math.abs(diff))} bardak ${diff<0?"eksik":"fazla"} kayıt görünüyor`}. Bu fark doğrudan ziyan anlamına gelmez; ikram veya kayıt farkı olabilir.`:"Seçilen dönemde demleme kaydı bulunmuyor."}
function renderProducts(){const q=normalize($("productSearch").value),rows=analysis.products.filter(x=>!q||normalize(x.name).includes(q));$("productRows").innerHTML=rows.map(x=>`<article class="product-row"><div><strong>${esc(x.name)}</strong><small>${esc(categoryName(x.categoryId))} • ${formatNumber(x.quantity)} adet</small></div><span>${money(x.revenue)}</span><span class="${x.unitCost?"":"missing"}">${x.unitCost?money(x.cost):"Eksik"}</span><span class="positive">${x.unitCost?money(x.profit):"—"}</span><span>${x.stock?`${formatNumber(x.stock.quantity)} ${esc(x.stock.unit||"adet")}`:"Takipsiz"}</span></article>`).join("");$("productEmpty").hidden=rows.length>0}
function renderForecasts(){const days=Math.max(1,daysBetween(range.start,range.end)+1),yearFactor=365/days,safety=1+num(settings.safetyPercent)/100,rows=stocks.filter(x=>x.active!==false&&x.stockTrackingEnabled!==false&&x.linkedMenuItemId).map(stock=>{const p=analysis.products.find(x=>x.id===stock.linkedMenuItemId),sold=serviceQuantity(stock.linkedMenuItemId)*(num(stock.deductionAmount)||1),daily=sold/days,daysLeft=daily>0?num(stock.quantity)/daily:Infinity,annualUnits=sold*yearFactor*safety,packages=annualUnits/Math.max(1,num(stock.unitsPerPackage));return{stock,sold,daily,daysLeft,packages}}).filter(x=>x.sold>0).sort((a,b)=>a.daysLeft-b.daysLeft).slice(0,8);$("forecastRows").innerHTML=rows.map(x=>`<article class="forecast-row"><i class="fa-solid fa-boxes-stacked"></i><div><strong>${esc(x.stock.name)}</strong><p>Bu dönemki satış hızı devam ederse stok yaklaşık ${Number.isFinite(x.daysLeft)?`${Math.max(0,Math.round(x.daysLeft))} gün`:"uzun süre"} yeter. Yıllıklandırılmış ihtiyaç, %${settings.safetyPercent} güvenlik payıyla yaklaşık ${formatNumber(x.packages)} koli.</p></div></article>`).join("")||'<p class="empty">Tahmin için seçilen dönemde stok bağlantılı ürün satışı gerekiyor.</p>'}
function attentionItems(){const a=analysis,items=[];for(const x of a.missingCosts)items.push({type:"warning",icon:"fa-tags",title:`${x.name} maliyeti eksik`,text:"Satış var ancak birim alış maliyeti bulunmadığı için brüt kazanç olduğundan yüksek görünebilir."});const lookback={start:addDays(today(),-num(settings.inactiveDays)+1),end:today()},recent=buildProductQuantities(lookback);for(const item of catalog.items.filter(x=>x.available!==false)){if(!num(recent.get(item.id)))items.push({type:"info",icon:"fa-eye-slash",title:`${item.name} satılmadı`,text:`Aktif ürün son ${settings.inactiveDays} günde hiç satılmadı. Menüde kalıp kalmayacağını değerlendirebilirsin.`})}const days=Math.max(1,daysBetween(range.start,range.end)+1);for(const stock of stocks.filter(x=>x.active!==false&&x.stockTrackingEnabled!==false)){const p=a.products.find(x=>x.id===stock.linkedMenuItemId),daily=serviceQuantity(stock.linkedMenuItemId)*(num(stock.deductionAmount)||1)/days,daysLeft=daily?num(stock.quantity)/daily:Infinity;if(num(stock.quantity)<=0)items.push({type:"warning",icon:"fa-box-open",title:`${stock.name} tükendi`,text:"Stok takip miktarı sıfır görünüyor."});else if(daysLeft<=7)items.push({type:"warning",icon:"fa-hourglass-half",title:`${stock.name} yaklaşık ${Math.max(1,Math.round(daysLeft))} gün yeter`,text:"Seçilen dönemin satış hızına göre sipariş planını kontrol et."})}if(a.brewed&&a.teaServed<a.brewed*num(settings.expectedCupsPerPot)*.75)items.push({type:"warning",icon:"fa-mug-hot",title:"Çay verimi beklenenin altında",text:"Demlik sayısıyla kayıtlı servis arasında belirgin fark var; ikram ve kayıtları kontrol et."});return items.slice(0,30)}
function renderAttention(){const items=attentionItems();$("attentionBadge").textContent=items.length;$("attentionList").innerHTML=items.map(x=>`<article class="attention-item ${x.type}"><i class="fa-solid ${x.icon}"></i><div><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p></div></article>`).join("");$("attentionEmpty").hidden=items.length>0}
function buildProductQuantities(r){const map=new Map;for(const sale of sales.filter(x=>!x.reversed&&!x.cancelled&&!String(x.recordType||"").startsWith("correction")&&inRange(saleDate(x),r))){if(sale.recordType!=="sale"&&sale.items==null)continue;if(sale.paymentType==="merchant-marka"||sale.settlementType==="merchant-marka"||sale.merchantMarka===true)continue;for(const item of sale.items||[])if(!item.complimentary)map.set(item.id,(map.get(item.id)||0)+num(item.quantity))}return map}
function askQuestion(q){const input=$("questionInput");input.value="";addMessage(q,"user-message");const n=normalize(q),a=analysis,p=a.previous;let answer;const dates=parseQuestionDates(q);if(n.includes("karsilastir")||n.includes("fark")||n.includes("gecen donem")){if(dates.length>=2){const first=buildAnalysis({start:dates[0],end:dates[0]}),second=buildAnalysis({start:dates[1],end:dates[1]});answer=comparisonAnswer(second,first,formatDate(dates[1]),formatDate(dates[0]))}else if(n.includes("gecen ay")&&n.includes("bugun")){const now=pos.currentBusinessDate||today(),old=sameDayPreviousMonth(now),currentDay=buildAnalysis({start:now,end:now}),oldDay=buildAnalysis({start:old,end:old});answer=comparisonAnswer(currentDay,oldDay,formatDate(now),formatDate(old))}else answer=comparisonAnswer(a,p,"Seçilen dönem","Önceki eşit dönem")}else if(n.includes("en cok")||n.includes("kazandirdi")){const best=[...a.products].filter(x=>x.unitCost).sort((x,y)=>y.profit-x.profit)[0];answer=best?`En fazla brüt kazanç sağlayan ürün ${best.name}. ${formatNumber(best.quantity)} adet satış, ${money(best.revenue)} ciro ve yaklaşık ${money(best.profit)} brüt kazanç.`:"Kazanç sıralaması için ürün maliyetlerinin kayıtlı olması gerekiyor."}else if(n.includes("kazan")||/(^|\s)kar($|\s)/.test(n)){answer=`${periodWords()} ${money(a.revenue)} satıştan, kayıtlı ${money(a.cost)} ürün maliyeti sonrası yaklaşık ${money(a.profit)} brüt kazanç oluştu. ${money(a.expenses)} gider düşüldüğünde tahmini sonuç ${money(a.operating)}.`}else if(n.includes("stok")||n.includes("siparis"))answer=attentionItems().filter(x=>x.title.includes("gün yeter")||x.title.includes("tükendi")).slice(0,4).map(x=>x.title).join("; ")||"Seçilen satış hızına göre acil stok uyarısı görünmüyor.";else if(n.includes("satilma")||n.includes("hareketsiz"))answer=attentionItems().filter(x=>x.title.endsWith("satılmadı")).slice(0,8).map(x=>x.title.replace(" satılmadı","")).join(", ")||`Son ${settings.inactiveDays} günde hiç satılmayan aktif ürün görünmüyor.`;else if(n.includes("cay")||n.includes("dem"))answer=`${periodWords()} ${a.brewed} demlik hazırlandı, yaklaşık ${formatNumber(a.grams)} gram kuru çay kullanıldı ve toplam ${formatNumber(a.teaServed)} bardak servis kaydı oluştu. Bunun ${formatNumber(a.normalTea)} bardağı normal satış, ${formatNumber(a.merchantTea)} bardağı marka, ${formatNumber(a.internalTea)} bardağı dahili tüketim.`;else answer=`Bu dönemde ${money(a.revenue)} satış, ${money(a.profit)} brüt kazanç ve ${money(a.expenses)} gider görünüyor. Sorunu “Çay durumunu anlat”, “hangi stoklara dikkat etmeliyim?” veya “geçen dönemle karşılaştır” şeklinde sorabilirsin.`;setTimeout(()=>addMessage(answer,"assistant-message"),180)}
function comparisonAnswer(currentValue,previousValue,currentLabel,previousLabel){const salesChange=change(currentValue.revenue,previousValue.revenue),teaNow=currentValue.normalTea/currentValue.activeDays,teaOld=previousValue.normalTea/previousValue.activeDays,productNow=currentValue.products.reduce((s,x)=>s+x.quantity,0),productOld=previousValue.products.reduce((s,x)=>s+x.quantity,0);return`${previousLabel}: ${money(previousValue.revenue)} satış, ${formatNumber(teaOld)} günlük ortalama Çay ve ${formatNumber(productOld)} ürün. ${currentLabel}: ${money(currentValue.revenue)} satış, ${formatNumber(teaNow)} günlük ortalama Çay ve ${formatNumber(productNow)} ürün. Satış tutarındaki değişim ${changeText(salesChange)}; brüt kazanç ${money(previousValue.profit)} seviyesinden ${money(currentValue.profit)} seviyesine geldi.`}
function parseQuestionDates(value){const matches=[...String(value).matchAll(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/g)],year=Number(today().slice(0,4));return matches.map(x=>{const y=x[3]?Number(x[3].length===2?`20${x[3]}`:x[3]):year,m=Number(x[2]),d=Number(x[1]),date=new Date(y,m-1,d,12);return date.getFullYear()===y&&date.getMonth()===m-1&&date.getDate()===d?`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`:""}).filter(Boolean)}
function sameDayPreviousMonth(value){const d=new Date(`${value}T12:00:00`),day=d.getDate(),candidate=new Date(d.getFullYear(),d.getMonth()-1,1,12),last=new Date(d.getFullYear(),d.getMonth(),0,12).getDate();candidate.setDate(Math.min(day,last));return iso(candidate)}
function addMessage(text,cls){const div=document.createElement("div");div.className=`message ${cls}`;div.textContent=text;$("chatMessages").appendChild(div);$("chatMessages").scrollTop=$("chatMessages").scrollHeight}
function drawTrend(){const canvas=$("trendChart");if(!canvas||canvas.offsetParent===null)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,rect.width*dpr);canvas.height=Math.max(1,rect.height*dpr);const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,pad={l:42,r:14,t:15,b:32},rows=analysis.days||[],max=Math.max(1,...rows.flatMap(x=>[x.revenue,x.profit]));ctx.clearRect(0,0,w,h);ctx.strokeStyle="#e8ddd2";ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}if(!rows.length){ctx.fillStyle="#77686a";ctx.font="12px Poppins";ctx.textAlign="center";ctx.fillText("Seçilen dönemde grafik verisi yok",w/2,h/2);return}const x=i=>rows.length===1?(pad.l+w-pad.r)/2:pad.l+(w-pad.l-pad.r)*i/(rows.length-1),y=v=>h-pad.b-(h-pad.t-pad.b)*v/max;const line=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=3;ctx.lineJoin="round";ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(x(i),y(r[key])):ctx.moveTo(x(i),y(r[key])));ctx.stroke();rows.forEach((r,i)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x(i),y(r[key]),3,0,Math.PI*2);ctx.fill()})};line("revenue","#741722");line("profit","#d49e24");ctx.fillStyle="#77686a";ctx.font="10px Poppins";ctx.textAlign="center";const step=Math.max(1,Math.ceil(rows.length/7));rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1)ctx.fillText(r.date.slice(8,10),x(i),h-10)})}
function periodRange(type){const t=pos.currentBusinessDate||today(),d=new Date(`${t}T12:00:00`);if(type==="week"){const start=new Date(d);start.setDate(d.getDate()-(d.getDay()+6)%7);return{start:iso(start),end:t}}if(type==="month")return{start:`${t.slice(0,7)}-01`,end:t};if(type==="lastMonth"){const first=new Date(d.getFullYear(),d.getMonth()-1,1,12),last=new Date(d.getFullYear(),d.getMonth(),0,12);return{start:iso(first),end:iso(last)}}return{start:t,end:t}}
function previousRange(r){const length=daysBetween(r.start,r.end)+1,end=addDays(r.start,-1);return{start:addDays(end,-length+1),end}}
function validCurrentDay(x,r){if(r.start!==r.end||r.start!==(pos.currentBusinessDate||today()))return true;const start=num(pos.currentBusinessDayStartedAtMs),time=x.closedAt?.toMillis?.()||x.createdAt?.toMillis?.()||num(x.closedAtMs)||num(x.createdAtMs);return!start||!time||time>=start}
function saleDate(x){return String(x.businessDate||dateFromTimestamp(x.closedAt||x.createdAt)||"")}
function inRange(date,r){return date>=r.start&&date<=r.end}function sumItems(items){return(items||[]).filter(x=>!x.complimentary).reduce((s,x)=>s+num(x.quantity)*num(x.unitPrice),0)}function categoryName(id){return catalog.categories.find(x=>x.id===id)?.name||(id==="other"?"Diğer":"Kategorisiz")}
function change(now,before){return before?((now-before)/Math.abs(before))*100:now?100:0}function changeText(v){if(Math.abs(v)<.05)return"Değişmedi";return`${v>0?"▲":"▼"} %${Math.abs(v).toLocaleString("tr-TR",{maximumFractionDigits:1})}`}
function periodWords(){return period==="today"?"Bugün":period==="week"?"Bu hafta":period==="month"?"Bu ay":period==="lastMonth"?"Geçen ay":"Seçilen dönemde"}function fillSettings(){for(const id of["teaGramsPerPot","expectedCupsPerPot","safetyPercent","inactiveDays"])$(id).value=settings[id]}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function iso(d){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(d)}function addDays(v,n){const d=new Date(`${v}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)}function daysBetween(a,b){return Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/864e5)}function dateFromTimestamp(v){const d=v?.toDate?.();return d?iso(d):""}function dateFromMs(v){return num(v)?iso(new Date(num(v))):""}function formatDate(v){const[y,m,d]=String(v).split("-");return y&&m&&d?`${d}.${m}.${y}`:"—"}function num(v){return Number(v)||0}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2}).format(num(v))}function formatNumber(v){return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(num(v))}function normalize(v){return String(v||"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i")}
function updateClock(){const d=new Date();$("currentTime").textContent=new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(d);$("currentDate").textContent=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"Europe/Istanbul"}).format(d).replace(/\./g,"/")}function show(message){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

function analysisUnitCost(item){return Number.isFinite(item.unitCostSnapshot)?item.unitCostSnapshot:stocks.filter(x=>x.active!==false&&x.linkedMenuItemId===item.id).reduce((sum,x)=>sum+num(x.unitCost)*(num(x.deductionAmount)||1),0)}
function serviceQuantity(productId){let quantity=0;for(const sale of sales){if(sale.reversed||sale.cancelled||!inRange(saleDate(sale),range)||!validCurrentDay(sale,range)||(sale.recordType&&sale.recordType!=='sale'))continue;quantity+=(sale.items||[]).filter(x=>x.id===productId).reduce((sum,x)=>sum+num(x.quantity),0)}for(const row of internal.filter(x=>!x.reversed&&!x.cancelled&&inRange(String(x.businessDate||dateFromTimestamp(x.createdAt)),range)))quantity+=(row.items||[]).filter(x=>x.id===productId).reduce((sum,x)=>sum+num(x.quantity),0);return quantity}
