import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{isOwner}from"../assets/js/admin-access.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),functions=getFunctions(app,"europe-west1"),read=httpsCallable(functions,"readOperationHistory"),status=httpsCallable(functions,"operationHistoryStatus"),lock=httpsCallable(functions,"lockOperationHistory"),$=id=>document.getElementById(id);
const actions={create:"Eklendi",update:"Düzenlendi",delete:"Silindi",cancel:"İptal / Geri alındı",reopen:"Yeniden açıldı"},icons={create:"fa-plus",update:"fa-pen",delete:"fa-trash-can",cancel:"fa-rotate-left",reopen:"fa-folder-open"};
const labels={amount:"Tutar",quantity:"Miktar",price:"Birim fiyat",unitPrice:"Birim fiyat",total:"Toplam",balance:"Bakiye",status:"Durum",items:"Ürünler",lines:"Ürün satırları",payments:"Ödemeler",cashAmount:"Nakit",cardAmount:"Kart",transferAmount:"Havale",currentAccountAmount:"Cari hesaba yazılan",paymentAmount:"Ödeme tutarı",paymentType:"Ödeme türü",settlementType:"Ödeme şekli",unitCost:"Birim maliyet",purchaseTotal:"Alış tutarı",purchasePrice:"Koli alış fiyatı",packageCount:"Koli sayısı",unitsPerPackage:"Koli içi adet",previousQuantity:"Önceki stok",resultingQuantity:"Sonraki stok",warningThreshold:"Stok uyarı sınırı",note:"Açıklama",description:"Açıklama",reason:"Neden",businessDate:"İş günü",operationDate:"İşlem tarihi",name:"Ad",title:"Başlık",tableName:"Masa",customerName:"Cari adı",accountName:"Hesap adı",personnelName:"Personel",stockName:"Ürün adı",productName:"Ürün adı",active:"Kullanım durumu",reversed:"Geri alma durumu",type:"İşlem türü",action:"Yapılan işlem",permissions:"Yetkiler",displayName:"Ad soyad",roleTitle:"Görevi",phone:"Telefon",dailyWage:"Ücret",wageType:"Ücret türü",wageTrackingEnabled:"Ücret takibi",status:"Durum",workedHours:"Çalışılan saat",wageSnapshot:"Hesaplanan ücret",wageAction:"Ücret işlemi",amountCents:"Tutar",category:"Kategori",groupName:"Grup",account:"Hesap",fromAccount:"Çıkan hesap",toAccount:"Giren hesap",dueDate:"Son ödeme tarihi",paidAtMs:"Ödenme zamanı",source:"Kayıt kaynağı",direction:"Yön",kind:"Hesap türü",symbol:"Para / maden",unit:"Birim",balanceUnits:"Birikim miktarı",costCents:"Toplam maliyet",quantityUnits:"Miktar",rateMicros:"İşlem kuru",valuationRateMicros:"Güncel değerleme kuru",automatic:"Otomatik kayıt",recordType:"Kayıt türü",correctionType:"Düzeltme türü"};
const values={open:"Açık",closed:"Kapalı",active:"Aktif",pending:"Bekliyor",partial:"Kısmen tamamlandı",completed:"Tamamlandı",paid:"Ödendi",cancelled:"İptal edildi",canceled:"İptal edildi",void:"İptal edildi",reversed:"Geri alındı",superseded:"Düzenlenerek yenilendi",cash:"Nakit Kasa",card:"Kart / POS",creditCard:"Kredi Kartı",bank:"Banka Hesabı",bankLoan:"Banka Kredisi",savings:"Birikim hesabı",transfer:"Hesap aktarımı",income:"Gelir",expense:"Gider",payment:"Ödeme",correction:"Düzeltme",in:"Stok girişi",out:"Stok çıkışı",set:"Stok sayımı",reversal:"Geri alma",cancel:"İptal",edit:"Düzenleme",create:"Ekleme",close:"Hesabı kapatma",reopen:"Yeniden açma",rate:"Kur güncelleme",invest:"Birikime yatırma",redeem:"Birikimi bozdurma",worked:"Geldi",absent:"Gelmedi",leave:"İzinli",none:"İşaretlenmedi",daily:"Günlük",hourly:"Saatlik",earned:"Hak edişe eklendi",manual:"Elle girildi",tl:"Türk lirası",term:"Vadeli TL",currency:"Döviz",gold:"Altın",silver:"Gümüş",pos:"Adisyon",stockPurchase:"Stok alımı",true:"Evet",false:"Hayır"};
const sourceNames={adminOrders:"Adisyon",adminSales:"Adisyon ödemesi",adminCashMovements:"Kasa hareketi",adminCashCounts:"Kasa sayımı",adminPaymentReminders:"Ödeme hatırlatması",adminCurrentAccounts:"Cari hesap",adminCurrentAccountMovements:"Cari hesap hareketi",adminCreditCustomers:"Eski cari hesap",adminCreditMovements:"Eski cari hareket",adminStockItems:"Stok ürünü",adminStockMovements:"Stok hareketi",adminPurchaseOrders:"Sipariş listesi",adminPurchaseDrafts:"Sipariş taslağı",adminInternalConsumptions:"Dahili tüketim",adminInternalConsumptionDrafts:"Dahili tüketim taslağı",staffUsers:"Kullanıcı hesabı",staffUserAudit:"Kullanıcı hesabı",merchantOrders:"Esnaf siparişi",merchantBalanceMovements:"Esnaf hesap hareketi",merchantProfiles:"Esnaf hesabı",adminPersonnel:"Personel",adminPersonnelAttendance:"Personel çalışma günü",adminPersonnelPayments:"Personel ödemesi",adminSavingsAudit:"Birikim işlemi",publicMenu:"Menü",adminAppSettings:"Sistem ayarı",adminCashSettings:"Kasa ayarı",adminDailyClosings:"Gün sonu",adminFinanceDays:"Finans günü"};
const hiddenFields=new Set(["id","uid","actor","actorUid","createdBy","updatedBy","reversedBy","cancelledBy","deletedBy","linkedUserUid","personnelId","stockItemId","linkedMenuItemId","categoryId","groupId","cashMovementId","transactionId","orderId","saleId","sourceId","targetSaleId","targetMovementId","movementId","accountId","currentAccountId","operationId","originalOperationId","replacementOf","reversalOf","reversalTransactionId","lastTransactionId","schemaVersion","cashMovementVersion","businessDayStartedAtMs","createdAt","updatedAt","deletedAt","reversedAt","cancelledAt","recordedAt","createdAtMs","updatedAtMs","addedAtMs","valuationAtMs","rateAtMs","changedAtMs","fingerprint","source","recordType","correctionType"]);
const moneyFields=new Set(["amount","price","unitPrice","total","balance","cashAmount","cardAmount","transferAmount","currentAccountAmount","paymentAmount","unitCost","purchaseTotal","purchasePrice","dailyWage","wageSnapshot"]);
let rows=[],groups=[],cursor=null,busy=false,expires=0,epoch=0,filters={},detailRequest=0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dateText=ms=>new Date(ms).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"});
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}
$("startDate").value=today();$("endDate").value=today();
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../yonetici-giris.html?next=yonetim-merkezi/");return}if(!isOwner(user)){location.replace("../yonetim-merkezi/");return}try{const result=await status({});if(!result.data.unlocked){location.replace("../yonetim-merkezi/");return}expires=result.data.expiresAtMs;$("lockedPanel").hidden=true;$("historyApp").hidden=false;await load(true);$("searchInput").focus()}catch{location.replace("../yonetim-merkezi/")}});
function clearView(message=""){epoch++;detailRequest++;expires=0;rows=[];cursor=null;busy=false;$("recordList").replaceChildren();$("detailBody").replaceChildren();$("detailTitle").textContent="İşlem";$("detailDialog").close();$("historyApp").hidden=true;$("lockedPanel").hidden=false;$("lockMessage").textContent=message;controls()}
$("lockButton").onclick=async()=>{clearView();await lock({}).catch(()=>{});location.replace("../yonetim-merkezi/")};
$("logoutButton").onclick=async()=>{await lock({}).catch(()=>{});clearView();await signOut(auth);location.replace("../yonetici-giris.html")};
$("filterForm").onsubmit=e=>{e.preventDefault();load(true)};$("refreshButton").onclick=()=>load(true);$("moreButton").onclick=()=>load(false);
$("historyCategories").onclick=e=>{const button=e.target.closest("[data-section]");if(!button)return;const section=button.dataset.section;$("sectionFilter").value=section;document.querySelectorAll("#historyCategories button").forEach(b=>b.classList.toggle("active",b===button));load(true)};
function controls(){for(const id of["filterButton","refreshButton","moreButton"])$(id).disabled=busy}
async function load(reset,silent=false){if(busy||!expires)return;busy=true;if(!silent)controls();const turn=++epoch,previousCursor=cursor;if(reset){filters={start:$("startDate").value,end:$("endDate").value,section:$("sectionFilter").value,action:"",actor:"",search:$("searchInput").value.trim()};if(!silent){rows=[];cursor=null;render()}}if(!silent)$("statusText").textContent="Kayıtlar yükleniyor…";try{const result=await read({...filters,cursor:reset?null:cursor});if(turn!==epoch)return;const data=result.data;expires=data.expiresAtMs;let changed=true;if(reset&&silent){const ids=new Set(data.records.map(r=>r.id)),nextRows=[...data.records,...rows.filter(r=>!ids.has(r.id))],fingerprint=list=>list.map(r=>`${r.id}:${r.eventAtMs}:${r.action}:${r.title}`).join("|");changed=fingerprint(nextRows)!==fingerprint(rows);rows=nextRows;cursor=rows.length>data.records.length?previousCursor:data.cursor}else{rows.push(...data.records);cursor=data.cursor}if(changed)render();if(!silent)$("statusText").textContent=cursor?"Daha eski kayıtlar için Diğer kayıtları getir düğmesini kullan.":"Seçilen tarih aralığının sonuna ulaşıldı."}catch(e){if(turn!==epoch)return;if(String(e.code).includes("permission-denied")||String(e.code).includes("unauthenticated"))location.replace("../yonetim-merkezi/");else if(!silent)$("statusText").textContent=String(e.code).includes("invalid-argument")?"Geçerli bir tarih aralığı seç (en fazla 1 yıl).":"Kayıtlar yüklenemedi. Bağlantını ve güncellemenin tamamlandığını kontrol et; Yenile ile tekrar dene."}finally{if(turn===epoch){busy=false;if(!silent)controls()}}}
function displayActor(value=""){return String(value).trim().split(/\s+/)[0]||"Kullanıcı"}
function money(value){return`${(Number(value)||0).toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2})} TL`}
function paymentName(value){return({cash:"Nakit",card:"Kart",bank:"Havale",transfer:"Havale",credit:"Cari Hesap",rounding:"Yuvarlama"})[value]||values[value]||value||"Belirtilmemiş"}
function saleAmount(data={}){return Number(data.paymentAmount??data.amount??data.baseTotal??data.total)||0}
function technicalTitle(value=""){const text=String(value).trim();return!text||/^[a-f0-9]{18,}$/i.test(text)||/^[A-Za-z0-9_-]{24,}$/.test(text)||/^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)+$/.test(text)||/^(catalog|config|pos|analytics|notification-draft|income|expense|transfer|correction)$/i.test(text)}
function displayTitle(r){const raw=String(r.title||"").trim();if(!technicalTitle(raw)&&raw!==String(r.recordId||""))return values[raw]||raw;return sourceNames[r.source]||r.section||"İşlem"}
function rowHeadline(r){if(r.source==="adminSales"&&r.action==="create"){const amount=Number(r.amount)||0;return`${displayActor(r.actorName)} ${amount?money(amount):"ödeme"} ${paymentName(r.paymentType).toLocaleLowerCase("tr-TR")} aldı`}return`${displayActor(r.actorName)} • ${(sourceNames[r.source]||r.section||"İşlem").toLocaleLowerCase("tr-TR")} ${(actions[r.action]||r.action||"kaydedildi").toLocaleLowerCase("tr-TR")}`;}
function groupedRows(){const map=new Map;for(const r of rows){const key=r.groupKey||`${r.source}:${r.id}`;if(!map.has(key))map.set(key,{key,ids:[],records:[],title:displayTitle(r),section:r.section,eventAtMs:r.eventAtMs,action:r.action,actorName:r.actorName});const g=map.get(key);g.ids.push(r.id);g.records.push(r);if(r.eventAtMs>=g.eventAtMs){g.eventAtMs=r.eventAtMs;g.title=displayTitle(r);g.action=r.action;g.actorName=r.actorName}}return[...map.values()].sort((a,b)=>b.eventAtMs-a.eventAtMs)}
function compactActivities(records){const raw=[];for(const r of records)for(const a of r.activities||[])raw.push({...a,eventAtMs:a.eventAtMs||r.eventAtMs,actor:displayActor(r.actorName),source:r.source,action:r.action});raw.sort((a,b)=>a.eventAtMs-b.eventAtMs);const result=[];for(const a of raw){const product=/^product-|^quantity-change$/.test(a.kind),last=result.at(-1),same=product&&last?last._product===String(a.productName||"").toLocaleLowerCase("tr-TR")&&a.eventAtMs-last._lastAt<=10000:false,from=a.kind==="product-add"?0:Number(a.fromQty??a.quantity)||0,to=a.kind==="product-add"?Number(a.toQty??a.quantity)||0:a.kind==="product-remove"?0:Number(a.toQty)||0;if(!same){if(product)result.push({...a,kind:"product-burst",fromQty:from,toQty:Math.max(0,to),_product:String(a.productName||"").toLocaleLowerCase("tr-TR"),_lastAt:a.eventAtMs});else result.push(a);continue}if(from!==Number(last.toQty)&&from===Number(last.fromQty)&&to>from&&Number(last.toQty)>from)last.fromQty=0;last.toQty=Math.max(0,to);last.eventAtMs=a.eventAtMs;last._lastAt=a.eventAtMs;last.actor=a.actor}return result.map(({_product,_lastAt,...a})=>a)}
function render(){groups=groupedRows();$("recordCount").textContent=`${groups.length} işlem grubu gösteriliyor`;$('recordList').innerHTML=groups.map((g,n)=>`<button type="button" class="record-card" data-group="${n}"><span class="record-icon"><i class="fa-solid ${g.section.startsWith("Adisyon")?"fa-receipt":icons[g.action]||"fa-clock-rotate-left"}"></i></span><span class="record-copy"><strong>${esc(g.title)}</strong><small>${esc(g.section.startsWith("Adisyon")?`${compactActivities(g.records).length} hareket • ürün, adet ve ödeme geçmişi`:rowHeadline(g.records[0]))}</small></span><span class="record-meta"><span class="badge ${esc(g.action)}">${esc(g.section.startsWith("Adisyon")?"Adisyon":actions[g.action]||g.action)}</span><time>${esc(dateText(g.eventAtMs))}</time></span></button>`).join("");$("moreButton").hidden=!cursor;$("emptyState").hidden=groups.length>0;$("emptyState").textContent=cursor?"Taranan kayıtlarda eşleşme yok. Diğer kayıtları getir ile aramaya devam et.":"Seçilen aralıkta bu filtrelere uygun kayıt bulunamadı."}
function decimalScaled(value,precision=2){return(Number(value||0)/10**Number(precision||0)).toLocaleString("tr-TR",{maximumFractionDigits:6})}
function readable(v,field="",context={}){if(v===null||v===undefined||v==="")return"—";if(moneyFields.has(field))return money(v);if(field==="amountCents"||field==="costCents")return money(Number(v)/100);if(field==="rateMicros"||field==="valuationRateMicros")return(Number(v||0)/1000000).toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:6});if(field==="quantityUnits"||field==="balanceUnits")return`${decimalScaled(v,context.precision??context.account?.precision??context.operation?.precision??2)}${context.unit||context.account?.unit||context.operation?.unit?` ${context.unit||context.account?.unit||context.operation?.unit}`:""}`;if(/(?:AtMs)$/.test(field)&&Number.isFinite(Number(v)))return dateText(Number(v));if((field==="businessDate"||field==="operationDate"||field==="dueDate")&&/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return new Date(`${v}T12:00:00+03:00`).toLocaleDateString("tr-TR");if(typeof v==="boolean")return v?"Evet":"Hayır";if(typeof v==="string")return values[v]||(/^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)+$/.test(v)?"Sistem işlemi":v);if(typeof v==="number")return v.toLocaleString("tr-TR",{maximumFractionDigits:6});if(Array.isArray(v)){if(field==="permissions")return`${v.length} yetki seçili`;if(field==="items"||field==="lines")return v.length?v.map(item=>{const name=item?.name||item?.productName||"Ürün",qty=Number(item?.quantity)||0,price=Number(item?.unitPrice)||0;return`${qty?`${qty} adet `:""}${name}${price?` • ${money(price)}`:""}`}).join("\n"):"Ürün yok";return v.length?v.map((item,index)=>`${index+1}. ${readable(item,"",context)}`).join("\n"):"—"}if(typeof v==="object"){const visible=Object.entries(v).filter(([key])=>labels[key]&&!hiddenFields.has(key));return visible.length?visible.map(([key,value])=>`${labels[key]}: ${readable(value,key,v)}`).join("\n"):"Ayrıntı kaydı"}return String(v)}
function fact(title,value){return`<div><dt>${esc(title)}</dt><dd>${esc(value||"—")}</dd></div>`}
function productRows(items=[]){return items.filter(i=>i&&Number(i.quantity)>0).map(i=>`<div class="simple-product"><strong>${esc(i.name||"Ürün")}</strong><span>${esc(Number(i.quantity).toLocaleString("tr-TR"))} adet${Number(i.unitPrice)>0?` × ${esc(money(i.unitPrice))}`:""}</span><b>${Number(i.unitPrice)>0?esc(money(Number(i.quantity)*Number(i.unitPrice))):""}</b></div>`).join("")}
function saleDetail(r){const data=r.after||r.before||{},amount=saleAmount(data),type=paymentName(data.paymentType||data.settlementType),items=Array.isArray(data.items)?data.items:[],verb=r.action==="cancel"||r.action==="delete"?"iptal etti":r.action==="reopen"?"yeniden açtı":r.action==="update"?"düzeltti":"aldı";return`<section class="simple-summary"><div class="summary-icon"><i class="fa-solid fa-receipt"></i></div><div><p>${esc(displayActor(r.actorName))} <strong>${esc(money(amount))}</strong> ${esc(type.toLocaleLowerCase("tr-TR"))} ${verb}.</p><small>${esc(r.title)} • ${esc(dateText(r.eventAtMs))}</small></div></section><div class="simple-payment"><span>Ödeme</span><strong>${esc(money(amount))} • ${esc(type)}</strong></div>${items.length?`<section class="simple-products"><h3>Ürünler</h3>${productRows(items)}</section>`:""}`}
const usefulFields=new Set(Object.keys(labels).filter(field=>!hiddenFields.has(field)));
function genericDetail(r){const changes=(r.changes||[]).filter(c=>usefulFields.has(c.field)&&!hiddenFields.has(c.field));const reason=r.reason&&r.reason!=="Belirtilmemiş"?`<div class="simple-reason"><span>Açıklama</span><strong>${esc(r.reason)}</strong></div>`:"";const action=actions[r.action]||"Kaydedildi";return`<section class="simple-summary"><div class="summary-icon"><i class="fa-solid ${icons[r.action]||"fa-clock-rotate-left"}"></i></div><div><p><strong>${esc(displayActor(r.actorName))}</strong> • ${esc(sourceNames[r.source]||r.section||"İşlem")} ${esc(action.toLocaleLowerCase("tr-TR"))}.</p><small>${esc(displayTitle(r))} • ${esc(dateText(r.eventAtMs))}</small></div></section>${reason}${changes.length?`<section class="simple-changes"><h3>Ne değişti?</h3>${changes.map(c=>`<div><span>${esc(labels[c.field])}</span><strong>${c.before!=null&&c.after!=null?`${esc(readable(c.before,c.field,r.before||{}))} → ${esc(readable(c.after,c.field,r.after||{}))}`:esc(readable(c.after??c.before,c.field,r.after||r.before||{}))}</strong></div>`).join("")}</section>`:`<p class="detail-note">Bu işlem için gösterilecek ek bilgi bulunmuyor. İşlemin kim tarafından ve ne zaman yapıldığı yukarıda kayıtlıdır.</p>`}`}
function savingsDetail(r){const old=r.before||{},next=r.after||{},account=next.account||old.account||next||old,operation=next.operation||old.operation||null,name=account.name||operation?.accountName||"Birikim hesabı",precision=Number(operation?.precision??account.precision??2),unit=operation?.unit||account.unit||"",quantity=operation?decimalScaled(operation.quantityUnits,precision):"",amount=operation?money(Number(operation.amountCents||0)/100):"",rate=operation?(Number(operation.rateMicros||0)/1000000).toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:6}):"",direction=operation?.direction==="redeem"?"bozdurma":operation?.direction==="invest"?"yatırma":"hesap",summary=operation?`${quantity} ${unit} ${direction} • ${amount}${rate?` • Kur ${rate}`:""}`:`${name} hesabı ${(actions[r.action]||"kaydedildi").toLocaleLowerCase("tr-TR")}`;return`<section class="simple-summary"><div class="summary-icon"><i class="fa-solid fa-piggy-bank"></i></div><div><p><strong>${esc(name)}</strong></p><small>${esc(displayActor(r.actorName))} • ${esc(dateText(r.eventAtMs))}</small></div></section><div class="simple-payment"><span>İşlem</span><strong>${esc(summary)}</strong></div>${operation?.description?`<div class="simple-reason"><span>Açıklama</span><strong>${esc(operation.description)}</strong></div>`:""}${operation?.tlAccount?`<div class="simple-reason"><span>TL hesabı</span><strong>${esc(values[operation.tlAccount]||operation.tlAccount)}</strong></div>`:""}`}
function menuDetail(r){const oldItems=Array.isArray(r.before?.items)?r.before.items:[],nextItems=Array.isArray(r.after?.items)?r.after.items:[],key=item=>String(item?.id||item?.name||""),oldMap=new Map(oldItems.map(item=>[key(item),item])),nextMap=new Map(nextItems.map(item=>[key(item),item])),changes=[];for(const id of new Set([...oldMap.keys(),...nextMap.keys()])){const before=oldMap.get(id),after=nextMap.get(id),name=after?.name||before?.name||"Ürün";if(!before&&after)changes.push(`${name} menüye eklendi`);else if(before&&!after)changes.push(`${name} menüden silindi`);else{const parts=[];if(before.name!==after.name)parts.push(`adı: ${before.name} → ${after.name}`);if(Number(before.price)!==Number(after.price))parts.push(`fiyatı: ${money(before.price)} → ${money(after.price)}`);if(before.active!==after.active)parts.push(after.active===false?"satışa kapatıldı":"satışa açıldı");if(before.posVisible!==after.posVisible)parts.push(after.posVisible===false?"adisyondan gizlendi":"adisyonda gösterildi");if(parts.length)changes.push(`${name} • ${parts.join(" • ")}`)}}return`<section class="simple-summary"><div class="summary-icon"><i class="fa-solid fa-mug-hot"></i></div><div><p><strong>${esc(displayActor(r.actorName))}</strong> menüyü güncelledi.</p><small>${esc(dateText(r.eventAtMs))}</small></div></section>${changes.length?`<section class="simple-changes"><h3>Menüde ne değişti?</h3>${changes.slice(0,60).map(text=>`<div><strong>${esc(text)}</strong></div>`).join("")}</section>`:`<p class="detail-note">Menü ayarları güncellendi; ürün adı veya fiyatında görünen bir değişiklik bulunmuyor.</p>`}`}
function detailHtml(r){return r.source==="adminSales"?saleDetail(r):r.source==="adminSavingsAudit"?savingsDetail(r):r.source==="publicMenu"?menuDetail(r):genericDetail(r)}
function clock(ms){return new Date(ms).toLocaleTimeString("tr-TR",{timeZone:"Europe/Istanbul",hour:"2-digit",minute:"2-digit"})}
function itemSummary(items=[]){const totals=new Map;for(const item of items||[]){const name=String(item?.name||"Ürün"),qty=Number(item?.quantity)||0;if(qty>0)totals.set(name,(totals.get(name)||0)+qty)}return[...totals].map(([name,qty])=>`${qty} ${name}`).join(" • ")}
function activityText(a,actor){if(a.kind==="product-burst"){if(a.toQty<=0)return[`${a.productName} silindi`,`${a.fromQty} adetten silindi • ${actor}`];if(a.fromQty<=0)return[`${a.productName} eklendi`,`${a.toQty} adet • ${actor}`];return[`${a.productName} toplam adedi ${a.fromQty} → ${a.toQty} oldu`,actor]}if(a.kind==="payment"){const products=itemSummary(a.items),rounding=Number(a.roundingAmount??(a.paymentType==="rounding"?a.amount:0))||0;if(a.paymentType==="rounding")return[`${actor} ${money(rounding)} hesap yuvarlaması yaptı`,products?`${products} • Adisyon kapatıldı`:"Adisyon kapatıldı"];return[`${actor} ${money(a.amount)} ${paymentName(a.paymentType).toLocaleLowerCase("tr-TR")} aldı`,products?`${products} • Adisyon kapatıldı`:"Adisyon kapatıldı"]}if(a.kind==="cancel")return[`${actor} adisyonu iptal etti`,""];if(a.kind==="reopen")return[`${actor} adisyonu yeniden açtı`,""];return["Adisyon açıldı",actor]}
function reconcileClosedOrder(events){const payment=events.findLast(a=>a.kind==="payment"&&Array.isArray(a.items));if(!payment)return events;const finalTotals=new Map;for(const item of payment.items){const key=String(item?.name||"Ürün").toLocaleLowerCase("tr-TR"),qty=Number(item?.quantity)||0;if(qty>0)finalTotals.set(key,{name:item.name||"Ürün",qty:(finalTotals.get(key)?.qty||0)+qty})}for(const [key,total] of finalTotals){const productEvents=events.filter(a=>a.kind==="product-burst"&&String(a.productName||"").toLocaleLowerCase("tr-TR")===key);if(productEvents.length===1){productEvents[0].fromQty=0;productEvents[0].toQty=total.qty;productEvents[0].productName=total.name}}return events}
function timelineDetail(records){const hasFinish=records.some(r=>(r.activities||[]).some(a=>a.kind==="payment"||a.kind==="cancel")),usable=hasFinish?records.map(r=>r.source==="adminOrders"&&r.action==="delete"?{...r,activities:[]}:r):records,events=reconcileClosedOrder(compactActivities(usable));return`<section class="simple-summary"><div class="summary-icon"><i class="fa-solid fa-receipt"></i></div><div><p><strong>${events.length} adisyon hareketi</strong></p><small>Hızlı ürün hareketleri birleştirilir; kapanışta kesin ürün toplamıyla doğrulanır.</small></div></section><div class="timeline">${events.map(a=>{const [main,sub]=activityText(a,a.actor);return`<div class="timeline-row"><time>${esc(clock(a.eventAtMs))}</time><span class="timeline-mark"></span><div class="timeline-copy"><strong>${esc(main)}</strong>${sub?`<small>${esc(sub)}</small>`:""}</div></div>`}).join("")||"<p class=\"detail-note\">Gösterilecek adisyon hareketi bulunamadı.</p>"}</div>`}
$("recordList").onclick=async e=>{const button=e.target.closest("[data-group]");if(!button)return;const group=groups[Number(button.dataset.group)];if(!group)return;const request=++detailRequest;$("detailTitle").textContent=group.title;$("detailSection").textContent="Yükleniyor";$("detailBody").textContent="Kayıt yükleniyor…";$("detailDialog").showModal();try{const result=await read({ids:group.ids});if(request!==detailRequest||!expires)return;const records=result.data.records;$("detailTitle").textContent=group.title;$("detailSection").textContent=group.section.startsWith("Adisyon")?"ADİSYON HAREKETLERİ":group.section;$("detailBody").innerHTML=group.section.startsWith("Adisyon")?timelineDetail(records):detailHtml(records.at(-1)||group.records[0])}catch(e){if(request!==detailRequest)return;if(String(e.code).includes("permission-denied"))location.replace("../yonetim-merkezi/");else $("detailBody").textContent="İşlem ayrıntısı yüklenemedi. Kapatıp tekrar dene."}};
$("closeDetail").onclick=()=>{detailRequest++;$("detailDialog").close();$("detailBody").replaceChildren();load(true,true)};$("detailDialog").addEventListener("cancel",()=>{detailRequest++;$("detailBody").replaceChildren();setTimeout(()=>load(true,true),0)});
function tick(){$("currentTime").textContent=new Date().toLocaleTimeString("tr-TR",{timeZone:"Europe/Istanbul",hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=new Date().toLocaleDateString("tr-TR",{timeZone:"Europe/Istanbul"});if(expires&&Date.now()>=expires)location.replace("../yonetim-merkezi/")}
tick();setInterval(tick,1000);setInterval(()=>{if(document.visibilityState==="visible"&&!$("detailDialog").open)load(true,true)},10000);document.addEventListener("visibilitychange",()=>{tick();if(document.visibilityState==="visible"&&!$("detailDialog").open)load(true,true)});
