import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{firebaseConfig}from"../assets/js/firebase-config.js";
import{isOwner}from"../assets/js/admin-access.js";
import{requireServerSensitiveAccess}from"../assets/js/sensitive-access.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),functions=getFunctions(app,"europe-west1"),read=httpsCallable(functions,"readOperationHistory"),unlock=httpsCallable(functions,"unlockOperationHistory"),lock=httpsCallable(functions,"lockOperationHistory"),$=id=>document.getElementById(id);
const actions={create:"Eklendi",update:"Düzenlendi",delete:"Silindi",cancel:"İptal / Geri alındı",reopen:"Yeniden açıldı"},icons={create:"fa-plus",update:"fa-pen",delete:"fa-trash-can",cancel:"fa-rotate-left",reopen:"fa-folder-open"};
const labels={amount:"Tutar (TL)",quantity:"Miktar",price:"Birim fiyat (TL)",unitPrice:"Birim fiyat (TL)",total:"Toplam (TL)",balance:"Bakiye",status:"Durum",items:"Ürünler",lines:"Ürün satırları",payments:"Ödemeler",cashAmount:"Nakit (TL)",cardAmount:"Kart (TL)",transferAmount:"Havale (TL)",paymentAmount:"Ödeme tutarı (TL)",paymentType:"Ödeme türü",unitCost:"Birim maliyet (TL)",purchaseTotal:"Alış tutarı (TL)",previousQuantity:"Önceki stok",resultingQuantity:"Sonraki stok",note:"Açıklama",description:"Açıklama",reason:"Neden",businessDate:"İş günü",operationDate:"İşlem tarihi",name:"Ad",title:"Başlık",tableName:"Masa",customerName:"Cari adı",stockName:"Ürün adı",active:"Aktif",reversed:"Geri alınmış",reversedBy:"Geri alan kullanıcı",reversedAt:"Geri alma zamanı",type:"İşlem türü",action:"İşlem",before:"Önceki kayıt",after:"Sonraki kayıt",permissions:"Yetkiler",displayName:"Kullanıcı adı",phone:"Telefon",balanceUnits:"Birikim miktarı (alt birim)",costCents:"Maliyet (kuruş)",quantityUnits:"Miktar (alt birim)",amountCents:"Tutar (kuruş)",transactionId:"Bağlı işlem kimliği",recordType:"Kayıt türü",correctionType:"Düzeltme türü",cancelledAt:"İptal zamanı",account:"Hesap",category:"Kategori",createdBy:"Oluşturan",updatedBy:"Düzenleyen"};
const values={open:"Açık",closed:"Kapalı",cancelled:"İptal edildi",canceled:"İptal edildi",reversed:"Geri alındı",superseded:"Yeni kayıtla değiştirildi",cash:"Nakit",card:"Kart",bank:"Banka",transfer:"Havale / Aktarım",income:"Gelir",expense:"Gider",payment:"Ödeme",correction:"Düzeltme",in:"Giriş",out:"Çıkış",set:"Sayım",reversal:"Geri alma",cancel:"İptal",edit:"Düzenleme"};
let rows=[],cursor=null,busy=false,expires=0,epoch=0,filters={},detailRequest=0,pinPending=false;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dateText=ms=>new Date(ms).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"});
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}
$("startDate").value=today();$("endDate").value=today();
onAuthStateChanged(auth,user=>{if(!user){clearView();location.replace("../yonetici-giris.html?next=islem-gecmisi/");return}if(!isOwner(user)){clearView();location.replace("../yonetim-merkezi/");return}openAccess()});
$("unlockButton").onclick=openAccess;
async function openAccess(){if(pinPending||!auth.currentUser||!isOwner(auth.currentUser))return;pinPending=true;$("lockMessage").textContent="";try{const ok=await requireServerSensitiveAccess(async data=>{const result=await unlock(data);expires=result.data.expiresAtMs;return result},{title:"İşlem Geçmişi Merkezi"});if(!ok)return;$("lockedPanel").hidden=true;$("historyApp").hidden=false;await load(true);$("searchInput").focus()}finally{pinPending=false}}
function clearView(message=""){epoch++;detailRequest++;expires=0;rows=[];cursor=null;busy=false;$("recordList").replaceChildren();$("detailBody").replaceChildren();$("detailTitle").textContent="İşlem";$("detailDialog").close();$("historyApp").hidden=true;$("lockedPanel").hidden=false;$("lockMessage").textContent=message;controls()}
$("lockButton").onclick=async()=>{clearView();try{await lock({})}catch{$("lockMessage").textContent="Ekran kilitlendi. Sunucu oturumu en geç 10 dakika içinde kapanır."}};
$("logoutButton").onclick=async()=>{await lock({}).catch(()=>{});clearView();await signOut(auth);location.replace("../yonetici-giris.html")};
$("filterForm").onsubmit=e=>{e.preventDefault();load(true)};$("refreshButton").onclick=()=>load(true);$("moreButton").onclick=()=>load(false);
function controls(){for(const id of["filterButton","refreshButton","moreButton"])$(id).disabled=busy}
async function load(reset){if(busy||!expires)return;busy=true;controls();const turn=++epoch;if(reset){rows=[];cursor=null;filters={start:$("startDate").value,end:$("endDate").value,section:$("sectionFilter").value,action:$("actionFilter").value,actor:$("actorFilter").value.trim(),search:$("searchInput").value.trim()};render()}$("statusText").textContent="Kayıtlar yükleniyor…";try{const result=await read({...filters,cursor});if(turn!==epoch)return;const data=result.data;expires=data.expiresAtMs;rows.push(...data.records);cursor=data.cursor;if($("sectionFilter").options.length===1)for(const section of data.sections||[]){const option=document.createElement("option");option.value=section;option.textContent=section;$("sectionFilter").append(option)}render();$("statusText").textContent=cursor?"Daha eski kayıtlar için Diğer kayıtları getir düğmesini kullan.":"Seçilen tarih aralığının sonuna ulaşıldı."}catch(e){if(turn!==epoch)return;if(String(e.code).includes("permission-denied")||String(e.code).includes("unauthenticated"))clearView("Oturum süresi doldu. PIN ile yeniden aç.");else $("statusText").textContent=String(e.code).includes("invalid-argument")?"Geçerli bir tarih aralığı seç (en fazla 1 yıl).":"Kayıtlar yüklenemedi. Bağlantını ve güncellemenin tamamlandığını kontrol et; Yenile ile tekrar dene."}finally{if(turn===epoch){busy=false;controls()}}}
function render(){$("recordCount").textContent=`${rows.length} kayıt gösteriliyor`;$("recordList").innerHTML=rows.map(r=>`<button type="button" class="record-card" data-id="${esc(r.id)}"><span class="record-icon"><i class="fa-solid ${icons[r.action]||"fa-clock-rotate-left"}"></i></span><span class="record-copy"><strong>${esc(r.title)}</strong><small>${esc(r.section)} • ${esc(r.actorName)}${r.actorVerified?"":" • Kayıt / sistem bilgisi"}</small></span><span class="record-meta"><span class="badge ${esc(r.action)}">${esc(actions[r.action]||r.action)}</span><time>${esc(dateText(r.eventAtMs))}</time></span></button>`).join("");$("moreButton").hidden=!cursor;$("emptyState").hidden=rows.length>0;$("emptyState").textContent=cursor?"Taranan kayıtlarda eşleşme yok. Diğer kayıtları getir ile aramaya devam et.":"Seçilen aralıkta bu filtrelere uygun kayıt bulunamadı."}
function readable(v){if(v===null||v===undefined)return"—";if(typeof v==="boolean")return v?"Evet":"Hayır";if(typeof v==="string")return values[v]||v;if(typeof v==="number")return v.toLocaleString("tr-TR",{maximumFractionDigits:6});if(Array.isArray(v))return v.length?v.map((item,index)=>`${index+1}. ${readable(item)}`).join("\n\n"):"—";return Object.entries(v).map(([key,value])=>`${labels[key]||key}: ${readable(value)}`).join("\n")}
function fact(title,value){return`<div><dt>${esc(title)}</dt><dd>${esc(value||"—")}</dd></div>`}
$("recordList").onclick=async e=>{const button=e.target.closest("[data-id]");if(!button)return;const request=++detailRequest;$("detailTitle").textContent="İşlem ayrıntısı";$("detailSection").textContent="Yükleniyor";$("detailBody").textContent="Kayıt yükleniyor…";$("detailDialog").showModal();try{const result=await read({id:button.dataset.id});if(request!==detailRequest||!expires)return;const r=result.data.record;$("detailTitle").textContent=r.title;$("detailSection").textContent=`${r.section} • ${actions[r.action]||r.action}`;$("detailBody").innerHTML=`<dl class="detail-facts">${fact("Tarih / Saat",dateText(r.eventAtMs))}${fact("Kullanıcı",r.actorName)}${fact("Kullanıcı bilgisinin kaynağı",r.actorBasis)}${fact("İş günü",r.businessDate)}${fact("Neden / Açıklama",r.reason)}${fact("İşlem kimliği",r.recordId)}${fact("Bağlı işlem",r.relatedId)}${fact("Kayıt kaynağı",r.sourcePath)}</dl><p class="detail-note">Bakiye ve rapor etkisini ilgili tutar, ödeme ve stok alanlarındaki eski–yeni değerlerden inceleyebilirsin. Bir işlem farklı bölümlerde bağlantılı kayıtlar oluşturabilir; bu satırlar toplanarak ciro hesaplanmaz.</p>${r.truncated?'<p class="notice">Bu büyük kaydın ayrıntıları kısaltılmıştır.</p>':""}<h2>Değişen alanlar</h2>${r.changes.map(c=>`<section class="change-row"><h3>${esc(labels[c.field]||c.field)}</h3><div class="change-values"><div><small>Önce</small><pre>${esc(readable(c.before))}</pre></div><div><small>Sonra</small><pre>${esc(readable(c.after))}</pre></div></div></section>`).join("")}<details><summary>Önceki kayıt ayrıntıları</summary><pre class="snapshot">${esc(readable(r.before))}</pre></details><details><summary>Sonraki kayıt ayrıntıları</summary><pre class="snapshot">${esc(readable(r.after))}</pre></details>`}catch(e){if(request!==detailRequest)return;if(String(e.code).includes("permission-denied"))clearView("Oturum süresi doldu. PIN ile yeniden aç.");else $("detailBody").textContent="İşlem ayrıntısı yüklenemedi. Kapatıp tekrar dene."}};
$("closeDetail").onclick=()=>{detailRequest++;$("detailDialog").close();$("detailBody").replaceChildren()};$("detailDialog").addEventListener("cancel",()=>{detailRequest++;$("detailBody").replaceChildren()});
function tick(){$("currentTime").textContent=new Date().toLocaleTimeString("tr-TR",{timeZone:"Europe/Istanbul",hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=new Date().toLocaleDateString("tr-TR",{timeZone:"Europe/Istanbul"});if(expires&&Date.now()>=expires)clearView("Oturum süresi doldu. PIN ile yeniden aç.")}
tick();setInterval(tick,1000);document.addEventListener("visibilitychange",tick);
