import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, deleteDoc, doc, getFirestore, onSnapshot, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig } from "../assets/js/firebase-config.js";
import { hasPanelAccess } from "../assets/js/admin-access.js";
import { lockSensitiveAccess, requireSensitiveAccess } from "../assets/js/sensitive-access.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const movementsCol=collection(db,"adminCashMovements"),closingsCol=collection(db,"adminDailyClosings"),salesCol=collection(db,"adminSales"),remindersCol=collection(db,"adminPaymentReminders"),settingsRef=doc(db,"adminCashSettings","config"),financeDaysCol=collection(db,"adminFinanceDays");
const HISTORY_START_DATE="2026-08-01",FINANCE_START_DATE="2026-08-13";
const defaultIncome=["İşletmeye Para Girişi","PET Şişe Dönüşüm İadesi","Diğer Gelir"];
const defaultExpense=["Toptancı / Ürün Alımı","Faturalar","Kira","Elektrik","Su","İnternet","Demirbaş","Temizlik","Market","Manav","Bakım ve Onarım","Maaş Ödemesi","Diğer Gider"];
let manualMovements=[],closings=[],sales=[],reminders=[],financeDays=[],settings=normalizeSettings({}),selectedDate=today(),pendingDeleteId="",pendingReminderPaidId="",started=false,settingsPromptShown=false,toastTimer;

updateClock();setInterval(updateClock,1000);
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("lockButton").onclick=async()=>{lockSensitiveAccess();if(!await unlock())location.replace("../yonetim-merkezi/")};
$("previousDay").onclick=()=>changeDay(-1);$("nextDay").onclick=()=>changeDay(1);
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openDialog(b.dataset.open));
$("closeDialog").onclick=()=>$("movementDialog").close();$("cancelDialog").onclick=()=>$("movementDialog").close();$("movementForm").onsubmit=saveMovement;$("dailyLedger").onclick=movementAction;$("bankSummaryButton").onclick=openBankSummary;$("closeBankSummary").onclick=()=>$("bankSummaryDialog").close();$("bankSummaryList").onclick=movementAction;
$("closeFinanceDayButton").onclick=openFinanceClose;$("cancelFinanceClose").onclick=()=>$("financeCloseDialog").close();$("confirmFinanceClose").onclick=closeFinanceDay;$("cancelDelete").onclick=()=>$("deleteDialog").close();$("confirmDelete").onclick=deleteMovement;
$("reportButton").onclick=openReport;$("closeReport").onclick=()=>$("reportDialog").close();$("reportMonth").onchange=renderReport;$("reportPdfButton").onclick=printReport;
$("settingsButton").onclick=openSettings;$("closeSettings").onclick=()=>$("settingsDialog").close();$("openingForm").onsubmit=saveOpeningBalances;$("settingsMenu").onclick=e=>{const button=e.target.closest("[data-settings-panel]");if(button)openSettingsPanel(button.dataset.settingsPanel)};document.querySelectorAll("[data-settings-back]").forEach(button=>button.onclick=returnToSettings);
document.querySelectorAll("[data-category-form]").forEach(form=>form.onsubmit=addCategory);$("incomeCategoryList").onclick=categoryAction;$("expenseCategoryList").onclick=categoryAction;
[$("incomeCategoryList"),$("expenseCategoryList")].forEach(list=>list.addEventListener("keydown",categoryListKeys));
$("remindersButton").onclick=()=>{$("reminderDueDate").value=today();renderReminders();$("remindersDialog").showModal()};$("reminderForm").onsubmit=saveReminder;$("reminderList").onclick=reminderAction;$("paidReminderList").onclick=reminderAction;document.querySelectorAll("[data-close-dialog]").forEach(button=>button.onclick=()=>$(button.dataset.closeDialog).close());
$("cancelReminderPaid").onclick=closeReminderPaidConfirm;$("confirmReminderPaid").onclick=confirmReminderPaid;
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});

onAuthStateChanged(auth,async user=>{
  if(!user){location.replace("../yonetici-giris.html?next=kasa-hesap-yonetimi/");return}
  if(!await hasPanelAccess(user,db,"cash")){location.replace("../yonetici-giris.html");return}
  if(!await unlock()){location.replace("../yonetim-merkezi/");return}
  document.documentElement.classList.remove("cash-pending");if(started)return;started=true;
  onSnapshot(movementsCol,s=>{manualMovements=s.docs.map(d=>({id:d.id,...d.data(),automatic:d.data().automatic===true}));render()},loadError);
  onSnapshot(closingsCol,s=>{closings=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(salesCol,s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(financeDaysCol,s=>{financeDays=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(remindersCol,s=>{reminders=s.docs.map(d=>({id:d.id,...d.data()}));renderReminders();renderReminderBadge()},loadError);
  onSnapshot(settingsRef,s=>{settings=normalizeSettings(s.exists()?s.data():{});render();renderSettings();if(!settings.openingConfigured&&!settingsPromptShown){settingsPromptShown=true;setTimeout(openSettings,250)}},loadError);
});
async function unlock(){return requireSensitiveAccess({title:"Kasa ve Hesaplar",message:"Kasa defterini açmak için yönetici PIN'ini girin."})}
function loadError(error){console.error(error);toast("Kasa kayıtları yüklenemedi. Firebase kurallarını kontrol edin.")}

function normalizeSettings(data){const configured=data.financeV3Configured===true&&data.financeV3StartDate===FINANCE_START_DATE;return{startDate:FINANCE_START_DATE,openingConfigured:configured,openingCash:configured?number(data.financeV3OpeningCash):0,openingBank:configured?number(data.financeV3OpeningBank):0,openingCard:configured?number(data.financeV3OpeningCard):0,openingCardDebt:configured?number(data.financeV3OpeningCardDebt):0,legacyOpeningCash:number(data.legacyOpeningCash??data.openingCash),legacyOpeningBank:number(data.legacyOpeningBank??data.openingBank),legacyOpeningCard:number(data.legacyOpeningCard??data.openingCard),incomeCategories:normalizeCategories(data.incomeCategories,defaultIncome,"income"),expenseCategories:normalizeCategories(data.expenseCategories,defaultExpense,"expense")}}
function normalizeCategories(items,defaults,type){const list=Array.isArray(items)&&items.length?items:defaults.map((name,i)=>({id:`${type}-${i+1}`,name,active:true}));return list.map((x,i)=>typeof x==="string"?{id:`${type}-${i+1}`,name:x,active:true}:{id:String(x.id||`${type}-${i+1}`),name:String(x.name||"Kalem"),active:x.active!==false})}
function activeCategories(type){return(type==="income"?settings.incomeCategories:settings.expenseCategories).filter(x=>x.active)}

function automaticMovements(){const rows=[];for(const c of closings){const date=c.businessDate;if(!date||date<HISTORY_START_DATE||c.accountingMode==="report-only"||c.cashTransferDisabled===true)continue;const cash=number(c.cashTotal),bank=number(c.transferTotal),card=number(c.cardTotal);if(cash)rows.push({id:`closing-cash-${c.id}`,type:"income",account:"cash",amount:cash,category:"Gün Sonu",description:"Nakit Satış Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true});if(bank)rows.push({id:`closing-bank-${c.id}`,type:"income",account:"bank",amount:bank,category:"Gün Sonu",description:"Banka Havalesi Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true});if(card)rows.push({id:`closing-card-${c.id}`,type:"income",account:"card",amount:card,category:"Gün Sonu",description:"Kart / POS Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true})}return rows}
function allMovements(){return[...manualMovements,...automaticMovements()].filter(m=>m.businessDate>=HISTORY_START_DATE)}
function changeDay(offset){selectedDate=shiftDate(selectedDate,offset);if(selectedDate>today())selectedDate=today();if(selectedDate<HISTORY_START_DATE)selectedDate=HISTORY_START_DATE;render()}
function balancesThrough(date){const legacy=date<FINANCE_START_DATE,r={cash:legacy?settings.legacyOpeningCash:settings.openingCash,bank:legacy?settings.legacyOpeningBank:settings.openingBank,card:legacy?0:settings.openingCard,cardDebt:legacy?settings.legacyOpeningCard:settings.openingCardDebt},start=legacy?HISTORY_START_DATE:FINANCE_START_DATE;for(const m of allMovements().filter(x=>x.businessDate>=start&&x.businessDate<=date&&(legacy||isFinanceDayClosed(x.businessDate))).sort(sortMovements)){const v=number(m.amount);if(m.type==="income"){if(m.account==="cash")r.cash+=v;if(m.account==="bank")r.bank+=v;if(m.account==="card")r.card+=v}if(m.type==="expense"){if(m.account==="cash")r.cash-=v;if(m.account==="bank")r.bank-=v;if(m.account==="creditCard"||m.account==="card"&&legacy)r.cardDebt+=v}if(m.type==="transfer"){transferOut(r,m.fromAccount,v);transferIn(r,m.toAccount,v)}}return r}
function transferOut(b,a,v){if(a==="cash")b.cash-=v;if(a==="bank")b.bank-=v;if(a==="card")b.card-=v;if(a==="creditCard")b.cardDebt+=v}function transferIn(b,a,v){if(a==="cash")b.cash+=v;if(a==="bank")b.bank+=v;if(a==="card")b.card+=v;if(a==="creditCard")b.cardDebt-=v}

function openingBalances(){return{cash:settings.openingCash,bank:settings.openingBank,card:settings.openingCard,cardDebt:settings.openingCardDebt}}
function previousBalances(date){return date===FINANCE_START_DATE?openingBalances():date<=HISTORY_START_DATE?{cash:settings.legacyOpeningCash,bank:settings.legacyOpeningBank,card:0,cardDebt:settings.legacyOpeningCard}:balancesThrough(shiftDate(date,-1))}
function accountBalancesForDate(date){if(date<FINANCE_START_DATE)return balancesThrough(date);if(isFinanceDayClosed(date))return balancesThrough(date);const previousDate=shiftDate(date,-1),previous=balancesThrough(previousDate),balances=date===FINANCE_START_DATE?openingBalances():isFinanceDayClosed(previousDate)?previous:{cash:0,bank:0,card:0,cardDebt:previous.cardDebt};for(const m of manualMovements.filter(x=>x.businessDate===date)){const value=number(m.amount);if(m.type==="expense"){if(m.account==="cash")balances.cash-=value;if(m.account==="bank")balances.bank-=value;if(m.account==="creditCard")balances.cardDebt+=value}if(m.type==="transfer"){transferOut(balances,m.fromAccount,value);transferIn(balances,m.toAccount,value)}}return balances}
function adisyonInfoForDate(date){return sales.filter(s=>s.businessDate===date&&s.recordType!=="correction"&&!s.reversed&&!['merchant-topup','merchant-topup-correction','merchant-delivery','merchant-manual-delivery'].includes(s.recordType)).reduce((result,s)=>{result.tips+=number(s.tipAmount);if(s.recordType==="sale"||!s.recordType)result.rounding+=number(s.roundingDiscount)||Math.max(0,-number(s.roundingAmount));return result},{tips:0,rounding:0})}
function renderBase(){const rows=allMovements().filter(m=>m.businessDate===selectedDate).sort(sortMovements),totals=dayTotals(rows),adisyon=adisyonInfoForDate(selectedDate),balances=accountBalancesForDate(selectedDate),previous=previousBalances(selectedDate),locked=isFinanceLocked(selectedDate),editable=canEditSelectedDate(),status=$("financeDayStatus");$("selectedDateLabel").textContent=formatBusinessDate(selectedDate);$("selectedDayName").textContent=dayName(selectedDate);$("previousDay").disabled=selectedDate<=HISTORY_START_DATE;$("nextDay").disabled=selectedDate>=today();$("previousCashBalance").textContent=money(previous.cash);$("previousBankBalance").textContent=money(previous.bank);$("dayCashIncome").textContent=money(totals.cashIncome);$("dayBankIncome").textContent=money(totals.bankIncome);$("dayCardIncome").textContent=money(totals.cardIncome);$("dayCashExpense").textContent=money(totals.cashExpense);$("dayBankExpense").textContent=money(totals.bankExpense+totals.bankTransferOut);$("dayCreditCardExpense").textContent=money(totals.cardExpense);$("dayExpense").textContent=money(totals.expense);$("cashBalance").textContent=money(balances.cash);$("bankBalance").textContent=money(balances.bank);$("cardBalance").textContent=money(Math.max(0,balances.cardDebt));$("cardAccountBalance").textContent=money(balances.card);status.textContent=selectedDate<FINANCE_START_DATE?"12.08.2026 ve öncesi salt okunur":locked?"Finans günü kapalı • kayıtlar kilitli":selectedDate!==today()?"Geçmiş gün • salt okunur":"Finans günü açık";status.classList.toggle("is-locked",locked||selectedDate!==today());$("closeFinanceDayButton").disabled=locked||selectedDate>today();document.querySelectorAll("[data-open]").forEach(button=>button.disabled=!editable);renderSimpleMovements(rows,adisyon,editable)}
function render(){renderBase();$("totalCreditCardDebt").textContent=money(Math.max(0,accountBalancesForDate(selectedDate).cardDebt));if($("bankSummaryDialog").open)renderBankSummary()}
function renderSimpleMovements(rows,adisyon,editable){const expenses=rows.filter(m=>m.type==="expense"),incomes=rows.filter(m=>m.type==="income");if(number(adisyon.rounding)>0)expenses.push({id:`rounding-${selectedDate}`,type:"expense",account:"",amount:adisyon.rounding,category:"Adisyon",description:"Eksi Yuvarlama",businessDate:selectedDate,automatic:true,source:"rounding-note",createdAtMs:0});if(number(adisyon.tips)>0)incomes.push({id:`tips-${selectedDate}`,type:"income",account:"cash",amount:adisyon.tips,category:"Adisyon",description:"Bahşiş",businessDate:selectedDate,automatic:true,source:"tip-note",createdAtMs:0});$("expenseMovementList").innerHTML=expenses.map(m=>simpleMovementMarkup(m,editable)).join("");$("incomeMovementList").innerHTML=incomes.map(m=>simpleMovementMarkup(m,editable)).join("");$("expenseMovementEmpty").hidden=expenses.length>0;$("incomeMovementEmpty").hidden=incomes.length>0;$("ledgerEditStatus").textContent=editable?"Bugünkü manuel işlemler doğrudan satırdan düzenlenebilir veya silinebilir.":isFinanceDayClosed(selectedDate)?"Finans günü kapalı • kayıtlar salt okunur.":"Geçmiş gün • kayıtlar salt okunur."}
function simpleMovementMarkup(m,editable){const automatic=m.automatic===true,actions=!automatic&&editable?movementButtons(m.id):automatic?'<span class="simple-record-badge"><i class="fa-solid fa-lock"></i> Otomatik</span>':'<span class="simple-record-badge readonly"><i class="fa-solid fa-eye"></i> Salt okunur</span>',time=formatTime(number(m.updatedAtMs)||number(m.createdAtMs)),detail=[m.category||typeName(m.type),formatBusinessDate(m.businessDate||selectedDate),time].filter(Boolean).join(" • "),title=m.automatic&&m.type==="income"&&m.category==="Gün Sonu"?"Adisyondan Gelen":m.description||m.category||typeName(m.type),payment=m.source==="rounding-note"?"Kasadan düşmez":accountText(m);return`<article class="simple-movement-row ${m.type}"><div class="simple-movement-copy"><strong>${esc(title)}</strong><small>${esc(detail)}</small></div><span class="simple-payment-method">${esc(payment||"—")}</span><b class="simple-movement-amount">${m.type==="expense"?"−":"+"} ${money(m.amount)}</b><div class="simple-movement-actions">${actions}</div></article>`}
function movementButtons(id){return`<button type="button" data-edit="${esc(id)}"><i class="fa-solid fa-pen"></i><span>Düzelt</span></button><button type="button" class="delete" data-delete="${esc(id)}"><i class="fa-solid fa-trash"></i><span>Sil</span></button>`}
function openBankSummary(){renderBankSummary();$("bankSummaryDialog").showModal()}
function renderBankSummary(){const rows=allMovements().filter(m=>m.businessDate===selectedDate&&(m.account==="bank"||m.type==="transfer"&&(m.fromAccount==="bank"||m.toAccount==="bank"))).sort(sortMovements),editable=canEditSelectedDate(),balance=accountBalancesForDate(selectedDate);$("bankSummaryDate").textContent=formatBusinessDate(selectedDate);$("bankSummaryBalance").textContent=money(balance.bank);$("bankSummaryList").innerHTML=rows.map(m=>bankMovementMarkup(m,editable)).join("");$("bankSummaryEmpty").hidden=rows.length>0}
function bankMovementMarkup(m,editable){const transfer=m.type==="transfer",outgoing=m.type==="expense"||transfer&&m.fromAccount==="bank",direction=outgoing?"−":"+",kind=transfer?"Hesap aktarımı":m.type==="expense"?"Banka gideri":"Bankaya gelen",automatic=m.automatic===true,actions=!automatic&&editable?movementButtons(m.id):automatic?'<span class="simple-record-badge"><i class="fa-solid fa-lock"></i> Otomatik</span>':'<span class="simple-record-badge readonly"><i class="fa-solid fa-eye"></i> Salt okunur</span>',time=formatTime(number(m.updatedAtMs)||number(m.createdAtMs)),details=[kind,m.category||"",transfer?accountText(m):"",formatBusinessDate(m.businessDate||selectedDate),time],detail=details.filter((value,index)=>value&&details.findIndex(item=>String(item).toLocaleLowerCase("tr-TR")===String(value).toLocaleLowerCase("tr-TR"))===index).join(" • ");return`<article class="bank-movement-row ${outgoing?"outgoing":"incoming"}"><div class="bank-movement-copy"><strong>${esc(m.description||m.category||kind)}</strong><small>${esc(detail)}</small></div><b>${direction} ${money(m.amount)}</b><div class="bank-movement-actions">${actions}</div></article>`}
function dayTotals(rows){return rows.reduce((t,m)=>{const value=number(m.amount);if(m.type==="income"){t.income+=value;if(m.account==="cash")t.cashIncome+=value;if(m.account==="bank")t.bankIncome+=value;if(m.account==="card")t.cardIncome+=value;if(m.automatic===true){if(m.account==="cash")t.automaticCashIncome+=value;if(m.account==="bank")t.automaticBankIncome+=value;if(m.account==="card")t.automaticCardIncome+=value}else t.manualIncome+=value}if(m.type==="expense"){t.expense+=value;if(m.account==="cash")t.cashExpense+=value;if(m.account==="bank")t.bankExpense+=value;if(m.account==="creditCard"||m.account==="card")t.cardExpense+=value;if(m.category==="Eksi Yuvarlama")t.roundingExpense+=value}if(m.type==="transfer"&&m.fromAccount==="bank")t.bankTransferOut+=value;return t},{income:0,cashIncome:0,bankIncome:0,cardIncome:0,expense:0,cashExpense:0,bankExpense:0,bankTransferOut:0,cardExpense:0,automaticCashIncome:0,automaticBankIncome:0,automaticCardIncome:0,roundingExpense:0,manualIncome:0})}

function openDialog(type,m=null){if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt eklenemez veya değiştirilemez.":"Geçmiş gün kayıtları değiştirilemez.");$("movementForm").reset();$("movementType").value=type;$("movementId").value=m?.id||"";$("dialogTitle").textContent=m?"Hareketi Düzenle":type==="income"?"Gelir Ekle":type==="expense"?"Gider Ekle":"Hesap Aktarımı";$("saveMovementButton").textContent=m?"Değişikliği Kaydet":"Kaydet";$("movementDateText").textContent=`İşlem tarihi: ${formatBusinessDate(selectedDate)}`;const transfer=type==="transfer";$("accountLabel").hidden=transfer;$("fromLabel").hidden=!transfer;$("toLabel").hidden=!transfer;$("categoryLabel").hidden=transfer;if(type==="income"){$("account").innerHTML='<option value="cash">Nakit Kasa</option><option value="bank">Banka</option><option value="card">Kart / POS</option>';setOptions($("category"),activeCategories("income"),m?.category)}if(type==="expense"){$("account").innerHTML='<option value="cash">Nakit Kasa</option><option value="bank">Banka</option><option value="creditCard">Kredi Kartı</option>';setOptions($("category"),activeCategories("expense"),m?.category)}if(m){$("amount").value=number(m.amount)||"";$("description").value=m.description||"";if(transfer){$("fromAccount").value=m.fromAccount||"cash";$("toAccount").value=m.toAccount||"bank"}else{$("account").value=m.account||"cash";$("category").value=m.category}}$("movementDialog").showModal();setTimeout(()=>{$("amount").focus();$("amount").select()},50)}
function setOptions(select,items,legacy=""){const names=items.map(x=>x.name);if(legacy&&!names.includes(legacy))names.unshift(legacy);select.innerHTML=names.map(x=>`<option>${esc(x)}</option>`).join("")}
async function saveMovement(e){e.preventDefault();if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt kaydedilemez.":"Geçmiş gün kayıtları değiştirilemez.");const type=$("movementType").value,amount=number($("amount").value),data={type,amount,account:type==="transfer"?"":$("account").value,fromAccount:type==="transfer"?$("fromAccount").value:"",toAccount:type==="transfer"?$("toAccount").value:"",category:type==="transfer"?"Hesap Aktarımı":$("category").value,description:$("description").value.trim(),businessDate:selectedDate,automatic:false,source:"manual",updatedAtMs:Date.now(),updatedAt:serverTimestamp()};if(amount<=0)return toast("Geçerli bir tutar girin.");if(type!=="transfer"&&!data.category)return toast("Önce Kasa Ayarları'ndan bir kategori ekleyin.");if(!data.description)return toast("İşlem için kısa bir açıklama girin.");if(type==="transfer"&&data.fromAccount===data.toAccount)return toast("Gönderen ve alan hesap farklı olmalıdır.");try{const id=$("movementId").value;if(id)await updateDoc(doc(db,"adminCashMovements",id),{...data,updatedBy:auth.currentUser.uid});else await setDoc(doc(movementsCol),{...data,createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});$("movementDialog").close();toast(id?"Hareket güncellendi.":"Hareket kaydedildi.")}catch(error){console.error(error);toast("Hareket kaydedilemedi.")}}
function movementAction(e){const edit=e.target.closest("[data-edit]"),remove=e.target.closest("[data-delete]");if(!edit&&!remove)return;if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıtlar değiştirilemez.":"Geçmiş gün kayıtları değiştirilemez.");if($("bankSummaryDialog").open)$("bankSummaryDialog").close();if(edit){const m=manualMovements.find(x=>x.id===edit.dataset.edit);if(m)openDialog(m.type,m)}if(remove){pendingDeleteId=remove.dataset.delete;$("deleteDialog").showModal()}}
async function deleteMovement(){if(!pendingDeleteId)return;if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt silinemez.":"Geçmiş gün kayıtları silinemez.");try{await deleteDoc(doc(db,"adminCashMovements",pendingDeleteId));pendingDeleteId="";$("deleteDialog").close();toast("Hareket silindi.")}catch(error){console.error(error);toast("Hareket silinemedi.")}}

async function saveReminder(e){e.preventDefault();const name=$("reminderName").value.trim(),amount=number($("reminderAmount").value),dueDate=$("reminderDueDate").value;if(!name||!dueDate)return;try{await setDoc(doc(remindersCol),{name,amount,dueDate,status:"pending",createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});$("reminderForm").reset();$("reminderDueDate").value=today();toast("Ödeme hatırlatması eklendi.")}catch(error){console.error(error);toast("Hatırlatma eklenemedi.")}}
async function reminderAction(e){const paid=e.target.closest("[data-reminder-paid]"),restore=e.target.closest("[data-reminder-restore]"),remove=e.target.closest("[data-reminder-delete]");if(paid)return openReminderPaidConfirm(paid.dataset.reminderPaid);try{if(restore)await updateDoc(doc(db,"adminPaymentReminders",restore.dataset.reminderRestore),{status:"pending",updatedAtMs:Date.now(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});if(remove)await deleteDoc(doc(db,"adminPaymentReminders",remove.dataset.reminderDelete));if(restore)toast("Ödeme tekrar bekleyenlere alındı.");if(remove)toast("Hatırlatma silindi.")}catch(error){console.error(error);toast("Hatırlatma güncellenemedi.")}}
function openReminderPaidConfirm(id){const reminder=reminders.find(x=>x.id===id);if(!reminder)return;pendingReminderPaidId=id;$("reminderPaidText").innerHTML=`<strong>${esc(reminder.name)}</strong>${number(reminder.amount)>0?`<span>${money(reminder.amount)}</span>`:""}<small>Bu kayıt Ödenenler bölümüne taşınacak.</small>`;$("reminderPaidDialog").showModal()}
function closeReminderPaidConfirm(){pendingReminderPaidId="";$("reminderPaidDialog").close()}
async function confirmReminderPaid(){if(!pendingReminderPaidId)return;const id=pendingReminderPaidId,button=$("confirmReminderPaid");button.disabled=true;try{await updateDoc(doc(db,"adminPaymentReminders",id),{status:"paid",paidAtMs:Date.now(),paidAt:serverTimestamp(),updatedBy:auth.currentUser.uid});closeReminderPaidConfirm();toast("Ödeme tamamlandı olarak işaretlendi.")}catch(error){console.error(error);toast("Hatırlatma güncellenemedi.")}finally{button.disabled=false}}
function pendingReminders(){return reminders.filter(x=>x.status!=="paid").sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)))}
function renderReminders(){const target=$("reminderList");if(!target)return;const items=pendingReminders(),paidItems=reminders.filter(x=>x.status==="paid").sort((a,b)=>number(b.paidAtMs)-number(a.paidAtMs));target.innerHTML=items.map(x=>{const overdue=x.dueDate<today();return`<article class="reminder-row ${overdue?"is-overdue":""}"><i class="fa-solid ${overdue?"fa-triangle-exclamation":"fa-calendar-day"}"></i><div><strong>${esc(x.name)}</strong><small>${formatBusinessDate(x.dueDate)}${number(x.amount)>0?` • ${money(x.amount)}`:""}${overdue?" • Gecikti":""}</small></div><div class="reminder-actions"><button class="paid" data-reminder-paid="${esc(x.id)}"><i class="fa-solid fa-check"></i> Ödendi</button><button data-reminder-delete="${esc(x.id)}"><i class="fa-solid fa-trash"></i></button></div></article>`}).join("");$("reminderEmpty").hidden=items.length>0;const history=$("paidReminderList"),historyEmpty=$("paidReminderEmpty");if(history)history.innerHTML=paidItems.map(x=>`<article class="reminder-row is-paid"><i class="fa-solid fa-circle-check"></i><div><strong>${esc(x.name)}</strong><small>${formatBusinessDate(x.dueDate)}${number(x.amount)>0?` • ${money(x.amount)}`:""} • Ödendi</small></div><div class="reminder-actions"><button data-reminder-restore="${esc(x.id)}" title="Tekrar bekleyenlere al"><i class="fa-solid fa-rotate-left"></i> Bekleyene Al</button><button data-reminder-delete="${esc(x.id)}" title="Geçmişten sil"><i class="fa-solid fa-trash"></i></button></div></article>`).join("");if(historyEmpty)historyEmpty.hidden=paidItems.length>0}
function renderReminderBadge(){const items=pendingReminders(),overdue=items.filter(x=>x.dueDate<today()).length;$("reminderBadge").textContent=overdue?`${overdue} gecikmiş ödeme`:items.length?`${items.length} bekleyen ödeme`:"Yaklaşan ödeme yok"}

function openSettings(){renderSettings();closeSettingsPanels();$("settingsDialog").showModal()}
function openSettingsPanel(name){const dialogs={opening:"openingSettingsDialog",income:"incomeSettingsDialog",expense:"expenseSettingsDialog"},target=$(dialogs[name]);if(!target)return;$("settingsDialog").close();renderSettings();target.showModal();if(name==="income"||name==="expense")setTimeout(()=>$(name==="income"?"incomeCategoryList":"expenseCategoryList").focus({preventScroll:true}),60)}
function returnToSettings(e){e?.preventDefault();closeSettingsPanels();renderSettings();$("settingsDialog").showModal()}
function closeSettingsPanels(){["openingSettingsDialog","incomeSettingsDialog","expenseSettingsDialog"].forEach(id=>{const dialog=$(id);if(dialog?.open)dialog.close()})}
function renderSettings(){$("openingCash").value=settings.openingCash;$('openingBank').value=settings.openingBank;$('openingCard').value=settings.openingCard;$('openingCardDebt').value=settings.openingCardDebt;renderCategoryList("income");renderCategoryList("expense")}
function renderCategoryList(type){const target=$(type==="income"?"incomeCategoryList":"expenseCategoryList"),items=type==="income"?settings.incomeCategories:settings.expenseCategories;target.innerHTML=items.map((x,i)=>`<article class="category-row ${x.active?'':'is-passive'}"><input value="${esc(x.name)}" maxlength="60" data-category-name="${esc(x.id)}" data-type="${type}"><div><button data-category-move="up" data-id="${esc(x.id)}" data-type="${type}" ${i===0?'disabled':''}><i class="fa-solid fa-chevron-up"></i></button><button data-category-move="down" data-id="${esc(x.id)}" data-type="${type}" ${i===items.length-1?'disabled':''}><i class="fa-solid fa-chevron-down"></i></button><button data-category-toggle="${esc(x.id)}" data-type="${type}">${x.active?'Pasife Al':'Aktif Et'}</button></div></article>`).join("")}
function categoryListKeys(e){if(e.target!==this)return;const steps={ArrowDown:51,ArrowUp:-51,PageDown:this.clientHeight,PageUp:-this.clientHeight};if(e.key in steps){e.preventDefault();this.scrollBy({top:steps[e.key],behavior:"smooth"})}else if(e.key==="Home"){e.preventDefault();this.scrollTo({top:0,behavior:"smooth"})}else if(e.key==="End"){e.preventDefault();this.scrollTo({top:this.scrollHeight,behavior:"smooth"})}}
async function saveOpeningBalances(e){e.preventDefault();try{await setDoc(settingsRef,{startDate:FINANCE_START_DATE,financeV3StartDate:FINANCE_START_DATE,financeV3Configured:true,legacyOpeningCash:settings.legacyOpeningCash,legacyOpeningBank:settings.legacyOpeningBank,legacyOpeningCard:settings.legacyOpeningCard,financeV3OpeningCash:number($("openingCash").value),financeV3OpeningBank:number($("openingBank").value),financeV3OpeningCard:number($("openingCard").value),financeV3OpeningCardDebt:number($("openingCardDebt").value),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Başlangıç bakiyeleri kaydedildi.");returnToSettings()}catch(error){console.error(error);toast("Başlangıç bakiyeleri kaydedilemedi.")}}
async function addCategory(e){e.preventDefault();const type=e.currentTarget.dataset.categoryForm,input=e.currentTarget.querySelector("input"),name=input.value.trim();if(!name)return;const items=[...(type==="income"?settings.incomeCategories:settings.expenseCategories)];if(items.some(x=>x.name.toLocaleLowerCase("tr-TR")===name.toLocaleLowerCase("tr-TR")))return toast("Bu kategori zaten bulunuyor.");items.push({id:`${type}-${Date.now()}`,name,active:true});await saveCategories(type,items);input.value=""}
async function categoryAction(e){const nameInput=e.target.closest("[data-category-name]"),toggle=e.target.closest("[data-category-toggle]"),move=e.target.closest("[data-category-move]");if(nameInput&&e.type==="click")return;if(toggle){const type=toggle.dataset.type,items=[...(type==="income"?settings.incomeCategories:settings.expenseCategories)],item=items.find(x=>x.id===toggle.dataset.categoryToggle);if(item)item.active=!item.active;await saveCategories(type,items)}if(move){const type=move.dataset.type,items=[...(type==="income"?settings.incomeCategories:settings.expenseCategories)],i=items.findIndex(x=>x.id===move.dataset.id),j=move.dataset.categoryMove==="up"?i-1:i+1;if(i>=0&&j>=0&&j<items.length)[items[i],items[j]]=[items[j],items[i]];await saveCategories(type,items)}}
$("incomeCategoryList").onchange=$("expenseCategoryList").onchange=async e=>{const input=e.target.closest("[data-category-name]");if(!input)return;const name=input.value.trim();if(!name)return renderSettings();const type=input.dataset.type,items=[...(type==="income"?settings.incomeCategories:settings.expenseCategories)],item=items.find(x=>x.id===input.dataset.categoryName);if(item)item.name=name;await saveCategories(type,items)};
async function saveCategories(type,items){try{await setDoc(settingsRef,{[type==="income"?"incomeCategories":"expenseCategories"]:items,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Kasa kategorileri güncellendi.")}catch(error){console.error(error);toast("Kategoriler güncellenemedi.")}}

function isFinanceDayClosed(date){return financeDays.some(x=>x.id===date&&x.locked===true)}
function isFinanceLocked(date){return date<FINANCE_START_DATE||isFinanceDayClosed(date)}
function canEditSelectedDate(){return selectedDate===today()&&!isFinanceLocked(selectedDate)}
function openFinanceClose(){if(isFinanceLocked(selectedDate))return toast("Bu finans günü zaten kapalı.");$("financeCloseText").textContent=`${formatBusinessDate(selectedDate)} kapatıldıktan sonra bu tarihe gelir, gider veya aktarım eklenemez; kayıtlar değiştirilemez ve silinemez. İşlem ayrıntıları geçmiş günlerde görünmeye devam eder.`;$("financeCloseDialog").showModal()}
async function closeFinanceDay(){if(isFinanceLocked(selectedDate))return;try{await setDoc(doc(db,"adminFinanceDays",selectedDate),{businessDate:selectedDate,locked:true,closedAtMs:Date.now(),closedAt:serverTimestamp(),closedBy:auth.currentUser.uid});$("financeCloseDialog").close();toast(`${formatBusinessDate(selectedDate)} finans kayıtları kapatıldı.`)}catch(error){console.error(error);toast("Finans günü kapatılamadı. Firebase kurallarını kontrol edin.")}}

function openReport(){$("reportMonth").value=selectedDate.slice(0,7);renderReport();$("reportDialog").showModal()}
function reportData(){let month=$("reportMonth").value||today().slice(0,7);if(month<"2026-08")month="2026-08";$("reportMonth").value=month;const rows=allMovements().filter(m=>m.businessDate?.startsWith(month)),totals=dayTotals(rows),balances=balancesThrough(`${month}-31`),incomes=[["Nakit Gelir",totals.cashIncome],["Banka Geliri",totals.bankIncome],["Kart / POS Geliri",totals.cardIncome]].filter(([,value])=>Math.abs(value)>.001);return{month,rows,totals,balances,expenses:groupAmounts(rows.filter(m=>m.type==="expense"),m=>m.category||"Diğer"),incomes,products:groupProducts(closings.filter(c=>c.businessDate>=HISTORY_START_DATE&&c.businessDate?.startsWith(month)))}}
function renderReport(){const d=reportData();$("reportContent").innerHTML=`<div class="report-totals"><div class="report-stat"><span>Nakit Gelir</span><b>${money(d.totals.cashIncome)}</b></div><div class="report-stat"><span>Banka Geliri</span><b>${money(d.totals.bankIncome)}</b></div><div class="report-stat"><span>Kart / POS Geliri</span><b>${money(d.totals.cardIncome)}</b></div><div class="report-stat"><span>Toplam Gider</span><b>${money(d.totals.expense)}</b></div></div><div class="report-accounts"><div class="report-stat"><span>Ay Sonu Nakit</span><b>${money(d.balances.cash)}</b></div><div class="report-stat"><span>Ay Sonu Banka</span><b>${money(d.balances.bank)}</b></div><div class="report-stat"><span>Ay Sonu Kart / POS</span><b>${money(d.balances.card)}</b></div><div class="report-stat"><span>Kredi Kartı Genel Borç</span><b>${money(Math.max(0,d.balances.cardDebt))}</b></div></div>${reportSection("Gelirler",d.incomes,"Bu ay gelir yok.")}${reportSection("Giderler",d.expenses,"Bu ay gider yok.")}${productSection(d.products)}`}
function printReport(){const d=reportData(),title=monthName(d.month),content=$("reportContent").innerHTML,w=window.open("","_blank","width=900,height=700");if(!w)return toast("PDF penceresi açılamadı.");w.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>${esc(title)} Kasa Raporu</title><style>body{font-family:Arial;color:#352522;padding:28px}header{display:flex;align-items:center;border-bottom:3px solid #7d1b24;padding-bottom:14px;margin-bottom:18px}header img{width:72px;height:72px;object-fit:contain;margin-right:14px}h1,h2,h3,p{margin:0}header p{color:#777;margin-top:4px}.report-totals,.report-accounts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.report-stat{border:1px solid #ddd;border-radius:8px;padding:10px}.report-stat span,.report-stat b{display:block}.report-stat span{font-size:11px;color:#777}.report-stat b{margin-top:5px}.report-section{margin-top:18px}.report-row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:7px 0;font-size:12px}.empty{color:#777}button{display:none}@media print{body{padding:0}}</style></head><body><header><img src="../assets/images/logo.png"><div><h1>Fatih Çay Evi</h1><h2>${esc(title)} Kasa Raporu</h2><p>Oluşturulma: ${new Date().toLocaleString("tr-TR")}</p></div></header>${content}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`);w.document.close()}
function groupAmounts(rows,key){const map=new Map;for(const row of rows){const name=key(row);map.set(name,(map.get(name)||0)+number(row.amount))}return[...map].sort((a,b)=>b[1]-a[1])}function groupProducts(items){const map=new Map;for(const c of items)for(const p of c.products||[]){const name=p.name||"Ürün",v=map.get(name)||{quantity:0,total:0};v.quantity+=number(p.quantity);v.total+=number(p.total);map.set(name,v)}return[...map].sort((a,b)=>b[1].quantity-a[1].quantity)}function reportSection(title,rows,empty){return`<section class="report-section"><h3>${title}</h3>${rows.length?rows.map(([name,total])=>`<div class="report-row"><span>${esc(name)}</span><b>${money(total)}</b></div>`).join(""):`<p class="empty">${empty}</p>`}</section>`}function productSection(rows){return`<section class="report-section"><h3>Ürün Satışları</h3>${rows.length?rows.map(([name,v])=>`<div class="report-row"><span>${esc(name)}</span><b>${v.quantity} adet <small>• ${money(v.total)}</small></b></div>`).join(""):'<p class="empty">Bu ay kapatılmış ürün satışı yok.</p>'}</section>`}

function sortMovements(a,b){return number(b.createdAtMs)-number(a.createdAtMs)||String(b.id).localeCompare(String(a.id))}function movementIcon(m){return m.automatic?"fa-lock":m.type==="income"?"fa-arrow-trend-up":m.type==="expense"?"fa-arrow-trend-down":"fa-right-left"}function sign(m){return m.type==="income"?"+":m.type==="expense"?"−":"↔"}function typeName(t){return t==="income"?"Gelir":t==="expense"?"Gider":"Aktarım"}function accountText(m){const n={cash:"Nakit",bank:"Banka Havalesi",card:"Kart / POS",creditCard:"Kredi Kartı"};return m.type==="transfer"?`${n[m.fromAccount]||""} → ${n[m.toAccount]||""}`:n[m.account]||""}function number(v){return Number(v)||0}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(number(v))}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function shiftDate(v,n){const d=new Date(`${v}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}function dateObject(v){return new Date(`${v}T12:00:00Z`)}function formatBusinessDate(v){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(dateObject(v))}function dayName(v){return new Intl.DateTimeFormat("tr-TR",{weekday:"long",timeZone:"UTC"}).format(dateObject(v))}function monthName(v){return new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}-01T12:00:00Z`))}function formatTime(ms){return ms?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(ms)):""}function updateClock(){const n=new Date();$("currentTime").textContent=n.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=n.toLocaleDateString("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit"})}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function toast(message){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}
