import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, deleteDoc, doc, getFirestore, getDoc, onSnapshot, runTransaction, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { ADMIN_UID, firebaseConfig } from "../assets/js/firebase-config.js";
import { savingsOwner,openSavingsMovement,savingsError } from "../assets/js/savings.js?v=420";
import { hasPanelAccess } from "../assets/js/admin-access.js";
import { lockSensitiveAccess, requireSensitiveAccess } from "../assets/js/sensitive-access.js";
import { hasLocalPendingInternalConsumption, hasPendingInternalConsumptionDraft } from "../assets/js/internal-consumption-guard.js?v=395";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const movementsCol=collection(db,"adminCashMovements"),closingsCol=collection(db,"adminDailyClosings"),salesCol=collection(db,"adminSales"),staffUsersCol=collection(db,"staffUsers"),remindersCol=collection(db,"adminPaymentReminders"),settingsRef=doc(db,"adminCashSettings","config"),financeDaysCol=collection(db,"adminFinanceDays"),currentAccountsCol=collection(db,"adminCurrentAccounts"),currentAccountMovementsCol=collection(db,"adminCurrentAccountMovements");
const HISTORY_START_DATE="2026-08-01",FINANCE_START_DATE="2026-08-13";
const defaultIncome=["İşletmeye Para Girişi","PET Şişe Dönüşüm İadesi","Diğer Gelir"];
const defaultExpense=["Toptancı / Ürün Alımı","Faturalar","Kira","Elektrik","Su","İnternet","Demirbaş","Temizlik","Market","Manav","Bakım ve Onarım","Maaş Ödemesi","Diğer Gider"];
const defaultTransfer=["Hesap Aktarımı","Kredi Kartı Borç Ödeme","Banka Kredisi Taksit Ödemesi"];
let categoryPanelMode="",pendingCategoryDelete=null,manualMovements=[],closings=[],sales=[],staffUsers=[],reminders=[],financeDays=[],currentAccounts=[],currentAccountMovements=[],settings=normalizeSettings({}),selectedDate=today(),calendarMonth=selectedDate.slice(0,7),pendingDeleteId="",pendingReminderPaidId="",accountSummaryView="bank-all",started=false,settingsPromptShown=false,toastTimer;

updateClock();setInterval(updateClock,1000);
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("lockButton").onclick=async()=>{lockSensitiveAccess();if(!await unlock())location.replace("../yonetim-merkezi/")};
$("previousDay").onclick=()=>changeDay(-1);$("nextDay").onclick=()=>changeDay(1);$("datePickerButton").onclick=openDatePicker;$("closeDatePicker").onclick=()=>$("datePickerDialog").close();$("calendarPreviousMonth").onclick=()=>changeCalendarMonth(-1);$("calendarNextMonth").onclick=()=>changeCalendarMonth(1);$("calendarToday").onclick=()=>selectCalendarDate(today());$("calendarDays").onclick=e=>{const day=e.target.closest("[data-calendar-date]");if(day&&!day.disabled)selectCalendarDate(day.dataset.calendarDate)};
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openDialog(b.dataset.open));
$("closeDialog").onclick=()=>$("movementDialog").close();$("cancelDialog").onclick=()=>$("movementDialog").close();$("movementForm").onsubmit=saveMovement;$("dailyLedger").onclick=movementAction;$("cashSummaryButton").onclick=()=>openAccountSummary("cash-income");$("bankSummaryButton").onclick=()=>openAccountSummary("bank-income");$("cardSummaryButton").onclick=()=>openAccountSummary("card-income");$("closeBankSummary").onclick=()=>$("bankSummaryDialog").close();document.querySelector(".financial-overview").onclick=e=>{const card=e.target.closest("[data-monthly-view]");if(card)openAccountSummary(card.dataset.monthlyView)};
$("closeFinanceDayButton").onclick=openFinanceClose;$("cancelFinanceClose").onclick=()=>$("financeCloseDialog").close();$("confirmFinanceClose").onclick=closeFinanceDay;$("cancelDelete").onclick=()=>$("deleteDialog").close();$("confirmDelete").onclick=deleteMovement;
$("closeFinanceDayEndWarning").onclick=()=>$("financeDayEndWarningDialog").close();$("goToAdisyonFromFinanceWarning").onclick=()=>location.href="../adisyon/";
$("reportButton").onclick=openReport;$("closeReport").onclick=()=>$("reportDialog").close();$("reportMonth").onchange=()=>{renderReport();$("reportContent").scrollTop=0;requestAnimationFrame(updateReportScroll)};$("reportPdfButton").onclick=printReport;
$("reportContent").addEventListener("scroll",updateReportScroll,{passive:true});$("reportScrollUp").onclick=()=>scrollReport(-260);$("reportScrollDown").onclick=()=>scrollReport(260);$("reportScrollTrack").addEventListener("pointerdown",startReportScrollDrag);$("reportScrollTrack").addEventListener("pointermove",moveReportScrollDrag);$("reportScrollTrack").addEventListener("pointerup",stopReportScrollDrag);$("reportScrollTrack").addEventListener("pointercancel",stopReportScrollDrag);$("reportScrollTrack").addEventListener("keydown",reportScrollKey);window.addEventListener("resize",updateReportScroll);
$("settingsButton").onclick=openSettings;$("closeSettings").onclick=()=>$("settingsDialog").close();$("openingForm").onsubmit=saveOpeningBalances;$("settingsMenu").onclick=e=>{const button=e.target.closest("[data-settings-panel]");if(button)openSettingsPanel(button.dataset.settingsPanel)};document.querySelectorAll("[data-settings-back]").forEach(button=>button.onclick=returnToSettings);
document.querySelectorAll("[data-category-form]").forEach(form=>form.onsubmit=addCategory);document.querySelectorAll("[data-group-form]").forEach(form=>form.onsubmit=addGroup);for(const type of ["income","expense"]){$(type+"GroupList").onclick=groupAction;$(type+"GroupList").onchange=groupChange;$(type+"CategoryList").addEventListener("change",categoryGroupChange)}$("movementCategoryButton").onclick=()=>$("movementCategoryPicker").hidden?openMovementCategoryPicker():closeMovementCategoryPicker();$("movementCategoryPicker").onclick=selectMovementCategory;document.addEventListener("pointerdown",e=>{if(!$("movementCategoryPicker").hidden&&!$("movementCategoryPicker").contains(e.target)&&!$("movementCategoryButton").contains(e.target))closeMovementCategoryPicker()});$("movementDialog").addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("movementCategoryPicker").hidden){e.preventDefault();e.stopPropagation();closeMovementCategoryPicker();$("movementCategoryButton").focus()}});$("movementDialog").addEventListener("close",closeMovementCategoryPicker);$("movementForm").addEventListener("scroll",()=>{if(!$("movementCategoryPicker").hidden)positionMovementCategoryPicker()});window.addEventListener("resize",()=>{if(!$("movementCategoryPicker").hidden)positionMovementCategoryPicker()});$("cancelCategoryDelete").onclick=()=>{$("categoryDeleteDialog").close();pendingCategoryDelete=null};$("confirmCategoryDelete").onclick=confirmCategoryDelete;$("incomeCategoryList").onclick=categoryAction;$("expenseCategoryList").onclick=categoryAction;$("transferCategoryList").onclick=categoryAction;
[$("incomeCategoryList"),$("expenseCategoryList"),$("transferCategoryList")].forEach(list=>list.addEventListener("keydown",categoryListKeys));
$("remindersButton").onclick=()=>{$("reminderDueDate").value=today();renderReminders();$("remindersDialog").showModal()};$("reminderForm").onsubmit=saveReminder;$("reminderList").onclick=reminderAction;$("paidReminderList").onclick=reminderAction;document.querySelectorAll("[data-close-dialog]").forEach(button=>button.onclick=()=>$(button.dataset.closeDialog).close());
$("cancelReminderPaid").onclick=closeReminderPaidConfirm;$("confirmReminderPaid").onclick=confirmReminderPaid;
document.addEventListener("click",e=>{const menu=document.querySelector(".panel-menu");if(menu?.open&&!menu.contains(e.target))menu.removeAttribute("open")});

onAuthStateChanged(auth,async user=>{
  if(!user){location.replace("../yonetici-giris.html?next=kasa-hesap-yonetimi/");return}
  if(!await hasPanelAccess(user,db,"cash")){location.replace("../yonetici-giris.html");return}
  if(!await unlock()){location.replace("../yonetim-merkezi/");return}
  $("savingsPageLink").hidden=!savingsOwner();document.documentElement.classList.remove("cash-pending");if(started)return;started=true;
  onSnapshot(movementsCol,s=>{manualMovements=s.docs.filter(d=>d.data().reversed!==true).map(d=>({id:d.id,...d.data(),...(d.data().source==="savings"?{amount:d.data().amountCents/100}:{}),automatic:d.data().automatic===true}));render()},loadError);
  onSnapshot(closingsCol,s=>{closings=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(salesCol,s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(staffUsersCol,s=>{staffUsers=s.docs.map(d=>({uid:d.id,...d.data()}));render()},loadError);
  onSnapshot(financeDaysCol,s=>{financeDays=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(currentAccountsCol,s=>{currentAccounts=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(currentAccountMovementsCol,s=>{currentAccountMovements=s.docs.map(d=>({id:d.id,...d.data()}));render()},loadError);
  onSnapshot(remindersCol,s=>{reminders=s.docs.map(d=>({id:d.id,...d.data()}));renderReminders();renderReminderBadge()},loadError);
  onSnapshot(settingsRef,s=>{settings=normalizeSettings(s.exists()?s.data():{});render();renderSettings();if(!settings.openingConfigured&&!settingsPromptShown){settingsPromptShown=true;setTimeout(openSettings,250)}},loadError);
});
async function unlock(){return requireSensitiveAccess({title:"Kasa ve Hesaplar",message:"Kasa defterini açmak için yönetici PIN'ini girin."})}
function loadError(error){console.error(error);toast("Kasa kayıtları yüklenemedi. Firebase kurallarını kontrol edin.")}

function normalizeSettings(data){const configured=data.financeV3Configured===true&&data.financeV3StartDate===FINANCE_START_DATE;return{startDate:FINANCE_START_DATE,openingConfigured:configured,openingCash:configured?number(data.financeV3OpeningCash):0,openingBank:configured?number(data.financeV3OpeningBank):0,openingCard:configured?number(data.financeV3OpeningCard):0,openingCardDebt:configured?number(data.financeV3OpeningCardDebt):0,legacyOpeningCash:number(data.legacyOpeningCash??data.openingCash),legacyOpeningBank:number(data.legacyOpeningBank??data.openingBank),legacyOpeningCard:number(data.legacyOpeningCard??data.openingCard),incomeCategories:normalizeCategories(data.incomeCategories,defaultIncome,"income"),expenseCategories:normalizeCategories(data.expenseCategories,defaultExpense,"expense"),incomeGroups:normalizeGroups(data.incomeGroups,"income"),expenseGroups:normalizeGroups(data.expenseGroups,"expense"),transferCategories:normalizeCategories(data.transferCategories,defaultTransfer,"transfer")}}
function normalizeCategories(items,defaults,type){const list=Array.isArray(items)&&items.length?items:defaults.map((name,i)=>({id:`${type}-${i+1}`,name,active:true})),normalized=list.map((x,i)=>typeof x==="string"?{id:`${type}-${i+1}`,name:x,active:true}:{id:String(x.id||`${type}-${i+1}`),name:String(x.name||"Kalem"),active:x.active!==false,groupId:String(x.groupId||""),aliases:Array.isArray(x.aliases)?x.aliases.map(String):[]});return type==="transfer"?normalized.filter(x=>!legacySavingsTransferCategory(x.name)):normalized}
function legacySavingsTransferCategory(name){const value=String(name||"").toLocaleLowerCase("tr-TR");return value.includes("birikim hesab")||value.includes("birikime")||value.includes("birikimden")||value.includes("yatırım hesab")}
function normalizeGroups(items,type){const list=Array.isArray(items)?items:[];return[{id:`${type}-legacy`,name:"Diğer",active:true},...list.filter(x=>x&&x.id!==`${type}-legacy`).map(x=>({id:String(x.id),name:String(x.name||"Grup"),active:x.active!==false}))]}
function groupItems(type){return type==="income"?settings.incomeGroups:settings.expenseGroups}
function groupForCategory(type,item){return groupItems(type).find(g=>g.id===item?.groupId)||groupItems(type)[0]}
function categoryItems(type){return type==="income"?settings.incomeCategories:type==="expense"?settings.expenseCategories:settings.transferCategories}
function activeCategories(type){return categoryItems(type).filter(x=>x.active)}

function automaticMovements(){const rows=[];for(const c of closings){const date=c.businessDate;if(!date||date<HISTORY_START_DATE||c.accountingMode==="report-only"||c.cashTransferDisabled===true)continue;const cash=number(c.cashTotal),bank=number(c.transferTotal),card=number(c.cardTotal);if(cash)rows.push({id:`closing-cash-${c.id}`,type:"income",account:"cash",amount:cash,category:"Gün Sonu",description:"Nakit Satış Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true});if(bank)rows.push({id:`closing-bank-${c.id}`,type:"income",account:"bank",amount:bank,category:"Gün Sonu",description:"Banka Havalesi Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true});if(card)rows.push({id:`closing-card-${c.id}`,type:"income",account:"card",amount:card,category:"Gün Sonu",description:"Kart / POS Geliri",businessDate:date,createdAtMs:number(c.closedAtMs),automatic:true})}return rows}
function allMovements(){return[...manualMovements,...automaticMovements()].filter(m=>m.businessDate>=HISTORY_START_DATE&&!(m.type==="transfer"&&(m.fromAccount==="personnel"||m.toAccount==="personnel")))}
function changeDay(offset){selectedDate=shiftDate(selectedDate,offset);if(selectedDate>today())selectedDate=today();if(selectedDate<HISTORY_START_DATE)selectedDate=HISTORY_START_DATE;render()}
function openDatePicker(){calendarMonth=selectedDate.slice(0,7);renderDatePicker();$("datePickerDialog").showModal()}
function changeCalendarMonth(offset){const [year,month]=calendarMonth.split("-").map(Number),d=new Date(Date.UTC(year,month-1+offset,1,12));calendarMonth=d.toISOString().slice(0,7);const minMonth=HISTORY_START_DATE.slice(0,7),maxMonth=today().slice(0,7);if(calendarMonth<minMonth)calendarMonth=minMonth;if(calendarMonth>maxMonth)calendarMonth=maxMonth;renderDatePicker()}
function selectCalendarDate(date){if(!date||date<HISTORY_START_DATE||date>today())return;selectedDate=date;calendarMonth=date.slice(0,7);$("datePickerDialog").close();render()}
function renderDatePicker(){const [year,month]=calendarMonth.split("-").map(Number),first=new Date(Date.UTC(year,month-1,1,12)),days=new Date(Date.UTC(year,month,0,12)).getUTCDate(),start=(first.getUTCDay()+6)%7,minMonth=HISTORY_START_DATE.slice(0,7),maxMonth=today().slice(0,7),cells=[];$("calendarMonthLabel").textContent=monthName(calendarMonth);$("calendarPreviousMonth").disabled=calendarMonth<=minMonth;$("calendarNextMonth").disabled=calendarMonth>=maxMonth;for(let i=0;i<start;i++)cells.push('<span class="calendar-day blank" aria-hidden="true"></span>');for(let day=1;day<=days;day++){const date=`${calendarMonth}-${String(day).padStart(2,"0")}`,disabled=date<HISTORY_START_DATE||date>today(),classes=["calendar-day"];if(date===selectedDate)classes.push("selected");if(date===today())classes.push("today");if(disabled)classes.push("disabled");cells.push(`<button type="button" class="${classes.join(" ")}" data-calendar-date="${date}" ${disabled?"disabled":""} aria-label="${formatBusinessDate(date)}"><b>${day}</b>${date===today()?'<small>Bugün</small>':date===selectedDate?'<small>Seçili</small>':""}</button>`)}$("calendarDays").innerHTML=cells.join("")}
function balancesThrough(date){const legacy=date<FINANCE_START_DATE,r={cash:legacy?settings.legacyOpeningCash:settings.openingCash,bank:legacy?settings.legacyOpeningBank:settings.openingBank,card:legacy?0:settings.openingCard,cardDebt:legacy?settings.legacyOpeningCard:settings.openingCardDebt},start=legacy?HISTORY_START_DATE:FINANCE_START_DATE;for(const m of allMovements().filter(x=>x.businessDate>=start&&x.businessDate<=date&&(legacy||isFinanceDayClosed(x.businessDate))).sort(sortMovements)){const v=number(m.amount);if(m.type==="income"){if(m.account==="cash")r.cash+=v;if(m.account==="bank")r.bank+=v;if(m.account==="card")r.card+=v}if(m.type==="expense"){if(m.account==="cash")r.cash-=v;if(m.account==="bank")r.bank-=v;if(m.account==="creditCard"||m.account==="card"&&legacy)r.cardDebt+=v}if(m.type==="transfer"){transferOut(r,m.fromAccount,v);transferIn(r,m.toAccount,v)}}return r}
function transferOut(b,a,v){if(a==="cash")b.cash-=v;if(a==="bank")b.bank-=v;if(a==="card")b.card-=v;if(a==="creditCard")b.cardDebt+=v}function transferIn(b,a,v){if(a==="cash")b.cash+=v;if(a==="bank")b.bank+=v;if(a==="card")b.card+=v;if(a==="creditCard")b.cardDebt-=v}

function openingBalances(){return{cash:settings.openingCash,bank:settings.openingBank,card:settings.openingCard,cardDebt:settings.openingCardDebt}}
function previousBalances(date){return date===FINANCE_START_DATE?openingBalances():date<=HISTORY_START_DATE?{cash:settings.legacyOpeningCash,bank:settings.legacyOpeningBank,card:0,cardDebt:settings.legacyOpeningCard}:balancesThrough(shiftDate(date,-1))}
function accountBalancesForDate(date){if(date<FINANCE_START_DATE)return balancesThrough(date);if(isFinanceDayClosed(date))return balancesThrough(date);const previousDate=shiftDate(date,-1),previous=balancesThrough(previousDate),balances=date===FINANCE_START_DATE?openingBalances():isFinanceDayClosed(previousDate)?previous:{cash:0,bank:0,card:0,cardDebt:previous.cardDebt};for(const m of manualMovements.filter(x=>x.businessDate===date&&!(x.type==="transfer"&&(x.fromAccount==="personnel"||x.toAccount==="personnel")))){const value=number(m.amount);if(m.type==="income"&&m.account==="bank")balances.bank+=value;if(m.type==="expense"){if(m.account==="cash")balances.cash-=value;if(m.account==="bank")balances.bank-=value;if(m.account==="creditCard")balances.cardDebt+=value}if(m.type==="transfer"){transferOut(balances,m.fromAccount,value);transferIn(balances,m.toAccount,value)}}return balances}
function adisyonInfoForDate(date){const tips=new Map,roundings=new Map,add=(map,sale,amount)=>{if(amount<=.001)return;const uid=String(sale.createdBy||"legacy"),current=map.get(uid)||{uid,name:userDisplayName(sale.createdBy)||"Eski Kayıt",amount:0,createdAtMs:0};current.amount+=amount;current.createdAtMs=Math.max(current.createdAtMs,number(sale.createdAtMs||sale.closedAtMs));map.set(uid,current)};for(const sale of sales.filter(s=>s.businessDate===date&&s.recordType!=="correction"&&!s.reversed&&!['merchant-topup','merchant-topup-correction','merchant-delivery','merchant-manual-delivery'].includes(s.recordType))){add(tips,sale,number(sale.tipAmount));if(sale.recordType==="sale"||!sale.recordType)add(roundings,sale,number(sale.roundingDiscount)||Math.max(0,-number(sale.roundingAmount)))}const byName=(a,b)=>a.name.localeCompare(b.name,"tr");return{tips:[...tips.values()].sort(byName),roundings:[...roundings.values()].sort(byName)}}
function renderBase(){const rows=allMovements().filter(m=>m.businessDate===selectedDate).sort(sortMovements),totals=dayTotals(rows),adisyon=adisyonInfoForDate(selectedDate),balances=accountBalancesForDate(selectedDate),previous=previousBalances(selectedDate),locked=isFinanceLocked(selectedDate),editable=canEditSelectedDate(),status=$("financeDayStatus");$("selectedDateLabel").textContent=formatBusinessDate(selectedDate);$("selectedDayName").textContent=dayName(selectedDate);$("previousDay").disabled=selectedDate<=HISTORY_START_DATE;$("nextDay").disabled=selectedDate>=today();$("previousCashBalance").textContent=money(previous.cash);$("previousBankBalance").textContent=money(previous.bank);$("dayCashIncome").textContent=money(totals.cashIncome);$("dayBankIncome").textContent=money(totals.bankIncome);$("dayCardIncome").textContent=money(totals.cardIncome);$("dayCashExpense").textContent=money(totals.cashExpense);$("dayBankExpense").textContent=money(totals.bankExpense+totals.bankTransferOut);$("dayCreditCardExpense").textContent=money(totals.cardExpense);$("dayExpense").textContent=money(totals.expense);$("cashBalance").textContent=money(balances.cash);$("bankBalance").textContent=money(balances.bank);$("cardBalance").textContent=money(Math.max(0,balances.cardDebt));$("cardAccountBalance").textContent=money(balances.card);status.textContent=selectedDate<FINANCE_START_DATE?"12.08.2026 ve öncesi salt okunur":locked?"Finans günü kapalı • kayıtlar kilitli":selectedDate<today()?"Açık finans günü • kayıt eklenebilir":"Finans günü açık";status.classList.toggle("is-locked",locked);$("closeFinanceDayButton").disabled=locked||selectedDate>today();document.querySelectorAll("[data-open]").forEach(button=>button.disabled=!editable);renderSimpleMovements(rows,adisyon,editable)}
function render(){renderBase();const balances=accountBalancesForDate(selectedDate);$("totalCreditCardDebt").textContent=money(Math.max(0,balances.cardDebt));if($("bankSummaryDialog").open)renderAccountSummary()}
function userDisplayName(uid){const id=String(uid||"");if(!id)return"";const user=staffUsers.find(item=>item.uid===id);return String(user?.personnelName||user?.displayName||(id===ADMIN_UID?"Fatih Ali Altınlı":"Kullanıcı")).trim()}
function renderSimpleMovements(rows,adisyon,editable){const expenses=rows.filter(m=>m.type==="expense"||m.type==="transfer"),incomes=incomeRowsForDisplay(rows.filter(m=>m.type==="income"),selectedDate);for(const item of adisyon.roundings)expenses.push({id:`rounding-${selectedDate}-${item.uid}`,type:"expense",account:"",amount:item.amount,category:"Adisyon",description:`${item.name} • Eksi Yuvarlama`,businessDate:selectedDate,automatic:true,source:"rounding-note",createdAtMs:item.createdAtMs});for(const item of adisyon.tips)incomes.push({id:`tips-${selectedDate}-${item.uid}`,type:"income",account:"cash",amount:item.amount,category:"Adisyon",description:`${item.name} • Bahşiş`,businessDate:selectedDate,automatic:true,source:"tip-note",createdAtMs:item.createdAtMs});$("expenseMovementList").innerHTML=expenses.map(m=>simpleMovementMarkup(m,editable)).join("");$("incomeMovementList").innerHTML=incomes.map(m=>simpleMovementMarkup(m,editable)).join("");$("expenseMovementEmpty").hidden=expenses.length>0;$("incomeMovementEmpty").hidden=incomes.length>0;$("ledgerEditStatus").textContent=editable?"Açık finans gününün manuel işlemleri düzenlenebilir veya silinebilir.":isFinanceDayClosed(selectedDate)?"Finans günü kapalı • kayıtlar salt okunur.":"Bu tarihe kayıt eklenemez."}
function incomeRowsForDisplay(incomes,date){const details=userIncomeDetails(date),rows=[];for(const movement of incomes){if(movement.automatic!==true||movement.source!=="pos-instant"){rows.push(movement);continue}const key=`${movement.account}|${number(movement.businessDayStartedAtMs)}`,items=details.get(key)||[];let remaining=Math.max(0,number(movement.amount));for(const item of items){if(remaining<=.001)break;const available=Math.max(0,number(item.unusedAmount));if(available<=.001)continue;const used=Math.min(remaining,available);rows.push({...item,amount:used});item.unusedAmount=available-used;remaining-=used}if(remaining>.001)rows.push({...movement,amount:remaining})}return rows.sort(sortMovements)}
function userIncomeDetails(date){const grouped=new Map(),activeSales=sales.filter(sale=>sale.businessDate===date&&sale.recordType!=="correction"&&sale.reversed!==true&&sale.cancelled!==true&&sale.cashMovementApplied===true);for(const sale of activeSales){const start=number(sale.businessDayStartedAtMs),person=userDisplayName(sale.createdBy),current=sale.recordType==="current-account-payment",accountName=current?currentAccountPaymentName(sale):"",amounts={cash:number(sale.cashAmount),bank:number(sale.transferAmount),card:number(sale.cardAmount)};for(const [account,amount] of Object.entries(amounts)){if(amount<=.001)continue;const org=sale.organizationMode===true&&!current,orgTitle=org?String(sale.title||"Organizasyon").trim():"",groupKey=[account,start,sale.createdBy||"legacy",current?"current":org?`org-${sale.orderId||orgTitle}`:"sale"].join("|");if(!grouped.has(groupKey))grouped.set(groupKey,{id:`user-income-${groupKey}`,type:"income",account,amount:0,unusedAmount:0,category:current?"Cari Tahsilatı":"Günlük Gelir",description:current?[person,"Cari Tahsilatı"].filter(Boolean).join(" • "):org?[orgTitle,number(sale.organizationDiscountAmount)>0?`${sale.organizationDiscountMode==="all"?`%${number(sale.organizationDiscountPercent)} `:"Ürün bazlı "}indirim ${money(sale.organizationDiscountAmount)}`:""].filter(Boolean).join(" • "):[person,"Adisyondan Gelen"].filter(Boolean).join(" • ")||"Adisyondan Gelen",businessDate:date,businessDayStartedAtMs:start,createdAtMs:0,automatic:true,source:"sale-user-display",createdBy:sale.createdBy||"",currentAccountNames:new Set});const row=grouped.get(groupKey);if(org&&number(sale.organizationDiscountAmount)>0)row.description=[orgTitle,sale.organizationDiscountMode==="all"?`%${number(sale.organizationDiscountPercent)} indirim ${money(sale.organizationDiscountAmount)}`:`Ürün bazlı indirim ${money(sale.organizationDiscountAmount)}`].join(" • ");row.amount+=amount;row.unusedAmount+=amount;row.createdAtMs=Math.max(row.createdAtMs,number(sale.createdAtMs||sale.closedAtMs));if(accountName)row.currentAccountNames.add(accountName)}}const groups=new Map;for(const row of grouped.values()){if(row.currentAccountNames.size===1)row.description=`${userDisplayName(row.createdBy)} • ${[...row.currentAccountNames][0]} • Cari Tahsilatı`;delete row.currentAccountNames;const key=`${row.account}|${row.businessDayStartedAtMs}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}for(const rows of groups.values())rows.sort((a,b)=>number(b.createdAtMs)-number(a.createdAtMs));return groups}
function currentAccountPaymentName(sale){const direct=String(sale.currentAccountName||"").trim(),title=String(sale.title||"").replace(/^Cari Tahsilatı\s*•?\s*/i,"").trim();return direct||title||"Cari Hesap"}
function movementTextKey(value){return String(value||"").trim().toLocaleLowerCase("tr-TR")}
function movementTextParts(value){return String(value||"").split("•").map(part=>part.trim()).filter(Boolean)}
function uniqueMovementText(parts){const seen=new Set;return parts.filter(part=>{const key=movementTextKey(part);if(!key||seen.has(key))return false;seen.add(key);return true})}
function movementDisplayText(m,kind,person,description){const personKey=movementTextKey(person),kindKey=movementTextKey(kind),descriptionParts=movementTextParts(description).filter(part=>{const key=movementTextKey(part);return key!==personKey&&key!==kindKey}),title=uniqueMovementText([kind,...descriptionParts]).join(" • ")||kind,detail=uniqueMovementText([person,formatBusinessDate(m.businessDate||selectedDate),formatTime(number(m.updatedAtMs)||number(m.createdAtMs))]).join(" • ");return{title,detail}}
function simpleMovementMarkup(m,editable){const automatic=m.automatic===true,transfer=m.type==="transfer",actions=!automatic&&editable?movementButtons(m.id):automatic?'<span class="simple-record-badge"><i class="fa-solid fa-lock"></i> Otomatik</span>':'<span class="simple-record-badge readonly"><i class="fa-solid fa-eye"></i> Salt okunur</span>',kind=transfer?(m.toAccount==="creditCard"?"Kredi Kartı Ödemesi":m.toAccount==="bankLoan"?"Banka Kredisi Taksit Ödemesi":"Hesap Aktarımı"):m.category||typeName(m.type),person=userDisplayName(m.createdBy),adisyonIncome=m.automatic&&m.type==="income"&&(m.category==="Gün Sonu"||m.source==="pos-instant"),description=m.source==="sale-user-display"?m.description:adisyonIncome?"Adisyondan Gelen":m.description||kind,display=movementDisplayText(m,kind,person,description),payment=m.source==="rounding-note"?"Kasadan düşmez":accountText(m),prefix=transfer?"↔":m.type==="expense"?"−":"+";return`<article class="simple-movement-row ${m.type}"><div class="simple-movement-copy"><strong>${esc(display.title)}</strong><small>${esc(display.detail)}</small></div><span class="simple-payment-method">${esc(payment||"—")}</span><b class="simple-movement-amount">${prefix} ${money(m.amount)}</b><div class="simple-movement-actions">${actions}</div></article>`}
function movementButtons(id){const savings=manualMovements.find(x=>x.id===id)?.source==="savings";if(savings&&!savingsOwner())return'<span class="simple-record-badge readonly">Salt okunur</span>';return`<button type="button" data-edit="${esc(id)}"><i class="fa-solid fa-pen"></i><span>Düzelt</span></button><button type="button" class="delete" data-delete="${esc(id)}"><i class="fa-solid fa-trash"></i><span>${savings?"İptal Et":"Sil"}</span></button>`}
function openAccountSummary(view){accountSummaryView=view||"bank-all";renderAccountSummary();$("bankSummaryDialog").showModal()}
function monthlyDisplayRows(){const month=selectedDate.slice(0,7),base=allMovements().filter(m=>m.businessDate?.startsWith(month)),out=base.filter(m=>m.type!=="income");for(const date of [...new Set(base.filter(m=>m.type==="income").map(m=>m.businessDate))])out.push(...incomeRowsForDisplay(base.filter(m=>m.type==="income"&&m.businessDate===date),date));return out.sort(sortMovements)}
function accountSummaryConfig(view){const configs={"cash-all":{title:"Nakit Kasa Hareketleri",account:"cash",mode:"all",label:"Güncel nakit kasa",note:"Nakit giriş, çıkış ve hesap aktarımları birlikte görünür."},"bank-all":{title:"Banka Hesabı Hareketleri",account:"bank",mode:"all",label:"Güncel banka bakiyesi",note:"Bankaya giren, bankadan çıkan ve hesap aktarımları birlikte görünür."},"card-all":{title:"POS Hesabı Hareketleri",account:"card",mode:"all",label:"Güncel POS hesabı",note:"Kart / POS gelirleri ve hesaba ait aktarımlar birlikte görünür."},"cash-income":{title:"Nakit Gelir Hareketleri",account:"cash",mode:"income",label:"İlgili ay nakit gelir",note:"İlgili ayda adisyondan ve diğer kaynaklardan gelen nakit gelirler görünür."},"bank-income":{title:"Havale Gelir Hareketleri",account:"bank",mode:"income",label:"İlgili ay banka geliri",note:"İlgili ayda bankaya gelen adisyon, cari ve diğer gelirler görünür."},"card-income":{title:"Kart / POS Gelir Hareketleri",account:"card",mode:"income",label:"İlgili ay kart geliri",note:"İlgili ayda çekilen kart / POS gelirleri görünür."},"cash-expense":{title:"Nakit Gider Hareketleri",account:"cash",mode:"expense",label:"İlgili ay nakit gider",note:"İlgili ayda nakit kasadan yapılan giderler görünür."},"bank-expense":{title:"Bankadan Çıkan Hareketler",account:"bank",mode:"outgoing",label:"İlgili ay bankadan çıkan",note:"İlgili ayın banka ödemeleri ve bankadan yapılan hesap aktarımları birlikte görünür."},"credit-expense":{title:"Kredi Kartı Harcamaları",account:"creditCard",mode:"expense",label:"İlgili ay kredi kartı harcaması",note:"İlgili ayda kredi kartıyla yapılan harcamalar açıklama ve tarihleriyle görünür."}};return configs[view]||configs["bank-all"]}
function accountSummaryRows(view){const cfg=accountSummaryConfig(view);return monthlyDisplayRows().filter(m=>{if(cfg.mode==="income")return m.type==="income"&&m.account===cfg.account;if(cfg.mode==="expense")return m.type==="expense"&&m.account===cfg.account;if(cfg.mode==="outgoing")return m.type==="expense"&&m.account===cfg.account||m.type==="transfer"&&m.fromAccount===cfg.account;return m.type==="transfer"?(m.fromAccount===cfg.account||m.toAccount===cfg.account):m.account===cfg.account})}
function accountSummaryValue(cfg,rows){if(cfg.mode!=="all")return rows.reduce((sum,m)=>sum+number(m.amount),0);const b=accountBalancesForDate(today());return cfg.account==="cash"?b.cash:cfg.account==="bank"?b.bank:b.card}
function renderAccountSummary(){const cfg=accountSummaryConfig(accountSummaryView),rows=accountSummaryRows(accountSummaryView),month=selectedDate.slice(0,7);$("bankSummaryTitle").textContent=cfg.title;$("bankSummaryDate").textContent=monthName(month);$("bankSummaryBalanceLabel").textContent=cfg.label;$("bankSummaryBalance").textContent=money(accountSummaryValue(cfg,rows));$("bankSummaryNote").textContent=cfg.note;$("bankSummaryList").innerHTML=rows.map(m=>accountMovementMarkup(m,cfg.account)).join("");$("bankSummaryEmpty").hidden=rows.length>0;$("bankSummaryEmpty").textContent=`${monthName(month)} içinde bu türde hareket bulunmuyor.`}
function accountMovementMarkup(m,account){const transfer=m.type==="transfer",outgoing=m.type==="expense"||transfer&&m.fromAccount===account,direction=outgoing?"−":"+",adisyonIncome=m.automatic===true&&m.type==="income"&&(m.category==="Gün Sonu"||m.source==="pos-instant"),kind=transfer?"Hesap aktarımı":m.type==="expense"?"Gider":m.category==="Cari Tahsilatı"?"Cari tahsilatı":adisyonIncome?"Adisyondan gelen":"Gelir",person=userDisplayName(m.createdBy),time=formatTime(number(m.updatedAtMs)||number(m.createdAtMs)),title=m.source==="sale-user-display"?m.description:adisyonIncome?"Adisyondan Gelen":[m.description||m.category||kind,person].filter(Boolean).join(" • "),details=[kind,m.category||"",person,transfer?accountText(m):accountText(m),formatBusinessDate(m.businessDate||today()),time].filter(Boolean),detail=details.filter((value,index)=>details.findIndex(item=>String(item).toLocaleLowerCase("tr-TR")===String(value).toLocaleLowerCase("tr-TR"))===index).join(" • ");return`<article class="bank-movement-row ${outgoing?"outgoing":"incoming"}"><div class="bank-movement-copy"><strong>${esc(title)}</strong><small>${esc(detail)}</small></div><b>${direction} ${money(m.amount)}</b></article>`}
function dayTotals(rows){return rows.reduce((t,m)=>{const value=number(m.amount);if(m.type==="income"){t.income+=value;if(m.account==="cash")t.cashIncome+=value;if(m.account==="bank")t.bankIncome+=value;if(m.account==="card")t.cardIncome+=value;if(m.automatic===true){if(m.account==="cash")t.automaticCashIncome+=value;if(m.account==="bank")t.automaticBankIncome+=value;if(m.account==="card")t.automaticCardIncome+=value}else t.manualIncome+=value}if(m.type==="expense"){t.expense+=value;if(m.account==="cash")t.cashExpense+=value;if(m.account==="bank")t.bankExpense+=value;if(m.account==="creditCard")t.cardExpense+=value;if(m.category==="Eksi Yuvarlama")t.roundingExpense+=value}if(m.type==="transfer"&&m.fromAccount==="bank")t.bankTransferOut+=value;return t},{income:0,cashIncome:0,bankIncome:0,cardIncome:0,expense:0,cashExpense:0,bankExpense:0,bankTransferOut:0,cardExpense:0,automaticCashIncome:0,automaticBankIncome:0,automaticCardIncome:0,roundingExpense:0,manualIncome:0})}

function resetTransferAccounts(){$("fromAccount").innerHTML='<option value="cash">Nakit Kasa</option><option value="bank">Banka</option><option value="card">Kart / POS Hesabı</option><option value="creditCard">Kredi Kartı</option>';$("toAccount").innerHTML='<option value="bank">Banka</option><option value="cash">Nakit Kasa</option><option value="card">Kart / POS Hesabı</option><option value="creditCard">Kredi Kartı Borç Ödeme</option><option value="bankLoan">Banka Kredisi Taksit Ödeme</option>'}
function openDialog(type,m=null){if(m?.source==="savings"){openSavingsMovement({operationId:m.transactionId,businessDate:selectedDate}).catch(e=>toast(savingsError(e)));return}if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt eklenemez veya değiştirilemez.":"Geçmiş gün kayıtları değiştirilemez.");$("movementForm").reset();$("movementType").value=type;$("movementId").value=m?.id||"";$("dialogTitle").textContent=m?"Hareketi Düzenle":type==="income"?"Gelir Ekle":type==="expense"?"Gider Ekle":"Hesap Aktarımı";$("saveMovementButton").textContent=m?"Değişikliği Kaydet":"Kaydet";$("movementDateText").textContent=`İşlem tarihi: ${formatBusinessDate(selectedDate)}`;const transfer=type==="transfer";$("accountLabel").hidden=transfer;$("fromLabel").hidden=!transfer;$("toLabel").hidden=!transfer;$("categoryLabel").hidden=transfer;$("transferCategoryLabel").hidden=!transfer;closeMovementCategoryPicker();if(type==="income"){$("account").innerHTML='<option value="cash">Nakit Kasa</option><option value="bank">Banka</option><option value="card">Kart / POS</option>';renderMovementCategoryPicker(type,m)}if(type==="expense"){$("account").innerHTML='<option value="cash">Nakit Kasa</option><option value="bank">Banka</option><option value="creditCard">Kredi Kartı</option>';renderMovementCategoryPicker(type,m)}if(transfer){resetTransferAccounts();setOptions($("transferCategory"),activeCategories("transfer"),m?.category||"Hesap Aktarımı")}if(m){$("amount").value=number(m.amount)||"";$("description").value=m.description||"";if(transfer){$("fromAccount").value=m.fromAccount||"cash";$("toAccount").value=m.toAccount||"bank";$("transferCategory").value=m.category||"Hesap Aktarımı"}else $("account").value=m.account||"cash"}$("movementDialog").showModal();setTimeout(()=>{$("amount").focus();$("amount").select()},50)}
const movementCategoryOrder=new Intl.Collator("tr",{numeric:true,sensitivity:"base"});
function renderMovementCategoryPicker(type,m=null){const selected=categoryItems(type).find(x=>x.id===m?.categoryId)||categoryItems(type).find(x=>x.name===m?.category),groups=groupItems(type).filter(g=>g.active||g.id===selected?.groupId).sort((a,b)=>movementCategoryOrder.compare(a.name,b.name)),items=activeCategories(type);$("category").value=selected?.id||"";$("movementCategoryText").textContent=selected?.name||"Kategori seçin";$("movementCategoryButton").classList.toggle("is-selected",!!selected);$("movementCategoryPicker").innerHTML=groups.map(group=>{const children=items.filter(item=>groupForCategory(type,item).id===group.id);if(selected&&groupForCategory(type,selected).id===group.id&&!children.some(x=>x.id===selected.id))children.push(selected);children.sort((a,b)=>movementCategoryOrder.compare(a.name,b.name));return `<div class="movement-category-group">${esc(group.name)}</div>${children.length?children.map(item=>`<button type="button" role="option" data-movement-category="${esc(item.id)}" class="movement-category-option" aria-selected="${item.id===selected?.id}">${esc(item.name)}</button>`).join(""):'<p class="movement-category-empty">Bu grupta aktif kategori yok.</p>'}`}).join("")||'<p class="movement-category-empty">Kategori bulunamadı.</p>'}
function positionMovementCategoryPicker(){const field=$("movementCategoryButton").getBoundingClientRect(),box=$("movementDialog").getBoundingClientRect(),picker=$("movementCategoryPicker");picker.style.left=`${field.left-box.left}px`;picker.style.top=`${field.bottom-box.top+4}px`;picker.style.width=`${field.width}px`;picker.style.maxHeight=`${Math.max(80,Math.min(360,window.innerHeight-field.bottom-12))}px`}
function openMovementCategoryPicker(){positionMovementCategoryPicker();$("movementCategoryPicker").hidden=false;$("movementCategoryButton").setAttribute("aria-expanded","true");$("movementCategoryPicker").scrollTop=0}
function closeMovementCategoryPicker(){$("movementCategoryPicker").hidden=true;$("movementCategoryButton").setAttribute("aria-expanded","false")}
function selectMovementCategory(e){const option=e.target.closest("[data-movement-category]");if(!option)return;const type=$("movementType").value,item=categoryItems(type).find(x=>x.id===option.dataset.movementCategory);if(!item)return;$("category").value=item.id;$("movementCategoryText").textContent=item.name;$("movementCategoryButton").classList.add("is-selected");closeMovementCategoryPicker();$("movementCategoryButton").focus()}
function setOptions(select,items,legacy=""){const names=items.map(x=>x.name);if(legacy&&!names.includes(legacy))names.unshift(legacy);select.innerHTML=names.map(x=>`<option>${esc(x)}</option>`).join("")}
async function saveMovement(e){e.preventDefault();if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt kaydedilemez.":"Geçmiş gün kayıtları değiştirilemez.");const type=$("movementType").value,amount=number($("amount").value),data={type,amount,account:type==="transfer"?"":$("account").value,fromAccount:type==="transfer"?$("fromAccount").value:"",toAccount:type==="transfer"?$("toAccount").value:"",category:type==="transfer"?$("transferCategory").value:$("category").value,description:$("description").value.trim(),businessDate:selectedDate,automatic:false,source:"manual",updatedAtMs:Date.now(),updatedAt:serverTimestamp()};if(type!=="transfer"){const item=categoryItems(type).find(x=>x.id===$("category").value),group=groupForCategory(type,item);if(!item||!group||!group.active)return toast("Kategori seçin.");data.category=item.name;data.categoryId=item.id;data.groupId=group.id;data.groupName=group.name}else{delete data.categoryId;delete data.groupId;delete data.groupName}if(amount<=0)return toast("Geçerli bir tutar girin.");if(type!=="transfer"&&!data.category)return toast("Önce Kasa Ayarları'ndan bir kategori ekleyin.");if(!data.description)return toast("İşlem için kısa bir açıklama girin.");if(type==="transfer"&&data.toAccount==="bankLoan"){if(!["cash","bank","card"].includes(data.fromAccount))return toast("Kredi taksiti için nakit, banka veya POS hesabı seçin.");data.category="Banka Kredisi Taksit Ödemesi"}if(type==="transfer"&&data.fromAccount===data.toAccount)return toast("Gönderen ve alan hesap farklı olmalıdır.");try{const id=$("movementId").value;if(id)await updateDoc(doc(db,"adminCashMovements",id),{...data,updatedBy:auth.currentUser.uid});else await setDoc(doc(movementsCol),{...data,createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});$("movementDialog").close();toast(id?"Hareket güncellendi.":"Hareket kaydedildi.")}catch(error){console.error(error);toast("Hareket kaydedilemedi.")}}
function movementAction(e){const edit=e.target.closest("[data-edit]"),remove=e.target.closest("[data-delete]");if(!edit&&!remove)return;const savings=manualMovements.find(x=>x.id===(edit?.dataset.edit||remove?.dataset.delete)&&x.source==="savings");if(savings&&remove){openSavingsMovement({operationId:savings.transactionId,businessDate:selectedDate,cancel:true}).catch(e=>toast(savingsError(e)));return}if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıtlar değiştirilemez.":"Geçmiş gün kayıtları değiştirilemez.");if($("bankSummaryDialog").open)$("bankSummaryDialog").close();if(edit){const m=manualMovements.find(x=>x.id===edit.dataset.edit);if(m)openDialog(m.type,m)}if(remove){pendingDeleteId=remove.dataset.delete;$("deleteDialog").showModal()}}
async function deleteMovement(){if(!pendingDeleteId)return;const savings=manualMovements.find(x=>x.id===pendingDeleteId&&x.source==="savings");if(savings){$("deleteDialog").close();pendingDeleteId="";try{await openSavingsMovement({operationId:savings.transactionId,businessDate:selectedDate,cancel:true})}catch(e){toast(savingsError(e))}return}if(!canEditSelectedDate())return toast(selectedDate===today()?"Bu finans günü kapalı; kayıt silinemez.":"Geçmiş gün kayıtları silinemez.");try{await deleteDoc(doc(db,"adminCashMovements",pendingDeleteId));pendingDeleteId="";$("deleteDialog").close();toast("Hareket silindi.")}catch(error){console.error(error);toast("Hareket silinemedi.")}}

async function saveReminder(e){e.preventDefault();const name=$("reminderName").value.trim(),amount=number($("reminderAmount").value),dueDate=$("reminderDueDate").value;if(!name||!dueDate)return;try{await setDoc(doc(remindersCol),{name,amount,dueDate,status:"pending",createdAtMs:Date.now(),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});$("reminderForm").reset();$("reminderDueDate").value=today();toast("Ödeme hatırlatması eklendi.")}catch(error){console.error(error);toast("Hatırlatma eklenemedi.")}}
async function reminderAction(e){const paid=e.target.closest("[data-reminder-paid]"),restore=e.target.closest("[data-reminder-restore]"),remove=e.target.closest("[data-reminder-delete]");if(paid)return openReminderPaidConfirm(paid.dataset.reminderPaid);try{if(restore)await updateDoc(doc(db,"adminPaymentReminders",restore.dataset.reminderRestore),{status:"pending",updatedAtMs:Date.now(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});if(remove)await deleteDoc(doc(db,"adminPaymentReminders",remove.dataset.reminderDelete));if(restore)toast("Ödeme tekrar bekleyenlere alındı.");if(remove)toast("Hatırlatma silindi.")}catch(error){console.error(error);toast("Hatırlatma güncellenemedi.")}}
function openReminderPaidConfirm(id){const reminder=reminders.find(x=>x.id===id);if(!reminder)return;pendingReminderPaidId=id;$("reminderPaidText").innerHTML=`<strong>${esc(reminder.name)}</strong>${number(reminder.amount)>0?`<span>${money(reminder.amount)}</span>`:""}<small>Bu kayıt Ödenenler bölümüne taşınacak.</small>`;$("reminderPaidDialog").showModal()}
function closeReminderPaidConfirm(){pendingReminderPaidId="";$("reminderPaidDialog").close()}
async function confirmReminderPaid(){if(!pendingReminderPaidId)return;const id=pendingReminderPaidId,button=$("confirmReminderPaid");button.disabled=true;try{await updateDoc(doc(db,"adminPaymentReminders",id),{status:"paid",paidAtMs:Date.now(),paidAt:serverTimestamp(),updatedBy:auth.currentUser.uid});closeReminderPaidConfirm();toast("Ödeme tamamlandı olarak işaretlendi.")}catch(error){console.error(error);toast("Hatırlatma güncellenemedi.")}finally{button.disabled=false}}
function pendingReminders(){return reminders.filter(x=>x.status!=="paid").sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)))}
function renderReminders(){const target=$("reminderList");if(!target)return;const items=pendingReminders(),paidItems=reminders.filter(x=>x.status==="paid").sort((a,b)=>number(b.paidAtMs)-number(a.paidAtMs));target.innerHTML=items.map(x=>{const overdue=x.dueDate<today();return`<article class="reminder-row ${overdue?"is-overdue":""}"><i class="fa-solid ${overdue?"fa-triangle-exclamation":"fa-calendar-day"}"></i><div><strong>${esc(x.name)}</strong><small>${formatBusinessDate(x.dueDate)}${number(x.amount)>0?` • ${money(x.amount)}`:""}${overdue?" • Gecikti":""}</small></div><div class="reminder-actions"><button class="paid" data-reminder-paid="${esc(x.id)}"><i class="fa-solid fa-check"></i> Ödendi</button><button data-reminder-delete="${esc(x.id)}"><i class="fa-solid fa-trash"></i></button></div></article>`}).join("");$("reminderEmpty").hidden=items.length>0;const history=$("paidReminderList"),historyEmpty=$("paidReminderEmpty");if(history)history.innerHTML=paidItems.map(x=>`<article class="reminder-row is-paid"><i class="fa-solid fa-circle-check"></i><div><strong>${esc(x.name)}</strong><small>${formatBusinessDate(x.dueDate)}${number(x.amount)>0?` • ${money(x.amount)}`:""} • Ödendi</small></div><div class="reminder-actions"><button data-reminder-restore="${esc(x.id)}" title="Tekrar bekleyenlere al"><i class="fa-solid fa-rotate-left"></i> Bekleyene Al</button><button data-reminder-delete="${esc(x.id)}" title="Geçmişten sil"><i class="fa-solid fa-trash"></i></button></div></article>`).join("");if(historyEmpty)historyEmpty.hidden=paidItems.length>0}
function renderReminderBadge(){const items=pendingReminders(),overdue=items.filter(x=>x.dueDate<today()).length;$("reminderBadge").textContent=overdue?`${overdue} gecikmiş ödeme`:items.length?`${items.length} bekleyen ödeme`:"Yaklaşan ödeme yok"}

function openSettings(){renderSettings();closeSettingsPanels();$("settingsDialog").showModal()}
function openSettingsPanel(name){const dialogs={opening:"openingSettingsDialog",income:"incomeSettingsDialog",expense:"expenseSettingsDialog"},panel=name==="transfer"?"expense":name,target=$(dialogs[panel]);if(!target)return;$("settingsDialog").close();categoryPanelMode=name==="income"||name==="expense"||name==="transfer"?name:"";if(categoryPanelMode){target.classList.toggle("transfer-mode",name==="transfer");const title=target.querySelector("h2"),form=target.querySelector("[data-category-form]"),input=form?.querySelector("input"),list=$("expenseCategoryList");if(name==="transfer"){title.textContent="Aktarım Kategorileri";form.dataset.categoryForm="transfer";form.querySelector("[data-category-group]").disabled=true;input.placeholder="Yeni aktarım kategorisi"}else if(name==="expense"){title.textContent="Giderler";form.dataset.categoryForm="expense";form.querySelector("[data-category-group]").disabled=false;input.placeholder="Yeni gider kategorisi";list.id="expenseCategoryList"}else{title.textContent="Gelirler";form.dataset.categoryForm="income";input.placeholder="Yeni gelir kategorisi"}renderCategoryList(name)}else renderSettings();target.showModal();if(categoryPanelMode)setTimeout(()=>$(categoryPanelMode==="income"?"incomeCategoryList":"expenseCategoryList").focus({preventScroll:true}),60)}
function returnToSettings(e){e?.preventDefault();if(categoryPanelMode==="transfer"){const dialog=$("expenseSettingsDialog"),title=dialog.querySelector("h2"),form=dialog.querySelector("[data-category-form]"),input=form.querySelector("input");title.textContent="Giderler";form.dataset.categoryForm="expense";form.querySelector("[data-category-group]").disabled=false;dialog.classList.remove("transfer-mode");input.placeholder="Yeni gider kategorisi"}categoryPanelMode="";closeSettingsPanels();renderSettings();$("settingsDialog").showModal()}
function closeSettingsPanels(){["openingSettingsDialog","incomeSettingsDialog","expenseSettingsDialog","transferSettingsDialog"].forEach(id=>{const dialog=$(id);if(dialog?.open)dialog.close()})}
function renderSettings(){$("openingCash").value=settings.openingCash;$('openingBank').value=settings.openingBank;$('openingCard').value=settings.openingCard;$('openingCardDebt').value=settings.openingCardDebt;renderCategoryList("income");if(categoryPanelMode!=="transfer")renderCategoryList("expense")}
function renderCategoryList(type){const target=$(type==="income"?"incomeCategoryList":"expenseCategoryList"),items=categoryItems(type);if(type!=="transfer"){const groups=groupItems(type),select=document.querySelector(`[data-category-group="${type}"]`),prior=select.value;select.innerHTML=groups.filter(g=>g.active).map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join("");if([...select.options].some(o=>o.value===prior))select.value=prior;$(type+"GroupList").innerHTML=groups.map(g=>`<div class="cash-group-chip ${g.active?"":"is-passive"}"><input maxlength="60" value="${esc(g.name)}" data-group-name="${esc(g.id)}" data-type="${type}" ${g.id===`${type}-legacy`?"readonly":""}><button type="button" data-group-toggle="${esc(g.id)}" data-type="${type}" ${g.id===`${type}-legacy`?"disabled":""}>${g.active?"Pasife Al":"Aktif Et"}</button><button type="button" data-group-delete="${esc(g.id)}" data-type="${type}" ${g.id===`${type}-legacy`?"disabled":""} aria-label="Grubu sil"><i class="fa-solid fa-trash"></i></button></div>`).join("")}
 target.innerHTML=items.map((x,i)=>`<article class="category-row ${x.active?'':'is-passive'}"><input value="${esc(x.name)}" maxlength="60" data-category-name="${esc(x.id)}" data-type="${type}">${type!=="transfer"?`<select data-category-assign="${esc(x.id)}" data-type="${type}" aria-label="Grup seç">${groupItems(type).map(g=>`<option value="${esc(g.id)}" ${groupForCategory(type,x).id===g.id?'selected':''}>${esc(g.name)}</option>`).join("")}</select>`:""}<div><button data-category-move="up" data-id="${esc(x.id)}" data-type="${type}" ${i===0?'disabled':''}><i class="fa-solid fa-chevron-up"></i></button><button data-category-move="down" data-id="${esc(x.id)}" data-type="${type}" ${i===items.length-1?'disabled':''}><i class="fa-solid fa-chevron-down"></i></button><button data-category-toggle="${esc(x.id)}" data-type="${type}">${x.active?'Pasife Al':'Aktif Et'}</button>${type!=="transfer"?`<button data-category-delete="${esc(x.id)}" data-type="${type}" aria-label="Kategoriyi sil"><i class="fa-solid fa-trash"></i></button>`:""}</div></article>`).join("")}
function categoryGroupChange(e){const select=e.target.closest("[data-category-assign]");if(!select)return;const type=select.dataset.type,items=categoryItems(type).map(x=>({...x})),item=items.find(x=>x.id===select.dataset.categoryAssign);if(!item)return;item.groupId=select.value;saveCategories(type,items)}
async function addGroup(e){e.preventDefault();const type=e.currentTarget.dataset.groupForm,input=e.currentTarget.querySelector("input"),name=input.value.trim(),groups=groupItems(type);if(!name)return;if(groups.some(g=>g.name.toLocaleLowerCase("tr-TR")===name.toLocaleLowerCase("tr-TR")))return toast("Bu grup zaten var.");await saveGroups(type,[...groups,{id:`${type}-group-${Date.now()}`,name,active:true}]);input.value=""}
async function groupAction(e){const button=e.target.closest("[data-group-toggle],[data-group-delete]");if(!button)return;const type=button.dataset.type,id=button.dataset.groupToggle||button.dataset.groupDelete,groups=groupItems(type).map(g=>({...g})),group=groups.find(g=>g.id===id);if(!group||id===`${type}-legacy`)return;if(button.dataset.groupToggle){group.active=!group.active;await saveGroups(type,groups);return}if(categoryItems(type).some(x=>groupForCategory(type,x).id===id)||manualMovements.some(m=>m.type===type&&m.groupId===id))return toast("Bu grupta kayıt var. Önce kategorileri taşıyın; geçmiş işlemler için grubu pasife alın.");askCategoryDelete({type,id,kind:"group",name:group.name})}
async function groupChange(e){const input=e.target.closest("[data-group-name]");if(!input||input.readOnly)return;const type=input.dataset.type,name=input.value.trim(),groups=groupItems(type).map(g=>({...g}));if(!name||groups.some(g=>g.id!==input.dataset.groupName&&g.name.toLocaleLowerCase("tr-TR")===name.toLocaleLowerCase("tr-TR")))return renderSettings();groups.find(g=>g.id===input.dataset.groupName).name=name;await saveGroups(type,groups)}
function askCategoryDelete(item){pendingCategoryDelete=item;$("categoryDeleteText").textContent=`${item.name} silinecek. Bu işlem geri alınamaz.`;$("categoryDeleteDialog").showModal()}
async function confirmCategoryDelete(){const item=pendingCategoryDelete;if(!item)return;const list=item.kind==="group"?groupItems(item.type):categoryItems(item.type);if(item.kind==="group"&&categoryItems(item.type).some(x=>groupForCategory(item.type,x).id===item.id))return toast("Grubun kategorileri var.");if(item.kind==="category"&&manualMovements.some(m=>m.type===item.type&&(m.categoryId===item.id||m.category===item.name||(item.aliases||[]).includes(m.category))))return toast("Bu kategori kullanılmış. Silmek yerine pasife alın.");const next=list.filter(x=>x.id!==item.id);if(item.kind==="group")await saveGroups(item.type,next);else await saveCategories(item.type,next);$("categoryDeleteDialog").close();pendingCategoryDelete=null}
async function saveGroups(type,groups){try{await setDoc(settingsRef,{[type+"Groups"]:groups.filter(g=>g.id!==`${type}-legacy`),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Gruplar güncellendi.")}catch(error){console.error(error);toast("Gruplar güncellenemedi.")}}

function categoryListKeys(e){if(e.target!==this)return;const steps={ArrowDown:51,ArrowUp:-51,PageDown:this.clientHeight,PageUp:-this.clientHeight};if(e.key in steps){e.preventDefault();this.scrollBy({top:steps[e.key],behavior:"smooth"})}else if(e.key==="Home"){e.preventDefault();this.scrollTo({top:0,behavior:"smooth"})}else if(e.key==="End"){e.preventDefault();this.scrollTo({top:this.scrollHeight,behavior:"smooth"})}}
async function saveOpeningBalances(e){e.preventDefault();try{await setDoc(settingsRef,{startDate:FINANCE_START_DATE,financeV3StartDate:FINANCE_START_DATE,financeV3Configured:true,legacyOpeningCash:settings.legacyOpeningCash,legacyOpeningBank:settings.legacyOpeningBank,legacyOpeningCard:settings.legacyOpeningCard,financeV3OpeningCash:number($("openingCash").value),financeV3OpeningBank:number($("openingBank").value),financeV3OpeningCard:number($("openingCard").value),financeV3OpeningCardDebt:number($("openingCardDebt").value),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Başlangıç bakiyeleri kaydedildi.");returnToSettings()}catch(error){console.error(error);toast("Başlangıç bakiyeleri kaydedilemedi.")}}
async function addCategory(e){e.preventDefault();const type=e.currentTarget.dataset.categoryForm,input=e.currentTarget.querySelector("input"),name=input.value.trim();if(!name)return;const items=[...(categoryItems(type))];if(items.some(x=>x.name.toLocaleLowerCase("tr-TR")===name.toLocaleLowerCase("tr-TR")))return toast("Bu kategori zaten bulunuyor.");items.push({id:`${type}-${Date.now()}`,name,active:true,groupId:type==="transfer"?"":document.querySelector(`[data-category-group="${type}"]`).value});await saveCategories(type,items);input.value=""}
async function categoryAction(e){const nameInput=e.target.closest("[data-category-name]"),toggle=e.target.closest("[data-category-toggle]"),move=e.target.closest("[data-category-move]");if(nameInput&&e.type==="click")return;const remove=e.target.closest("[data-category-delete]");if(remove){const type=remove.dataset.type,item=categoryItems(type).find(x=>x.id===remove.dataset.categoryDelete);if(manualMovements.some(m=>m.type===type&&(m.categoryId===item?.id||m.category===item?.name||(item?.aliases||[]).includes(m.category))))return toast("Bu kategori kullanılmış. Silmek yerine pasife alın.");if(item)askCategoryDelete({type,id:item.id,kind:"category",name:item.name});return}if(toggle){const type=toggle.dataset.type,items=[...(categoryItems(type))],item=items.find(x=>x.id===toggle.dataset.categoryToggle);if(item)item.active=!item.active;await saveCategories(type,items)}if(move){const type=move.dataset.type,items=[...(categoryItems(type))],i=items.findIndex(x=>x.id===move.dataset.id),j=move.dataset.categoryMove==="up"?i-1:i+1;if(i>=0&&j>=0&&j<items.length)[items[i],items[j]]=[items[j],items[i]];await saveCategories(type,items)}}
$("incomeCategoryList").onchange=$("expenseCategoryList").onchange=$("transferCategoryList").onchange=async e=>{const input=e.target.closest("[data-category-name]");if(!input)return;const name=input.value.trim();if(!name)return renderSettings();const type=input.dataset.type,items=[...(categoryItems(type))],item=items.find(x=>x.id===input.dataset.categoryName);if(item){if(item.name!==name)item.aliases=[...new Set([...(item.aliases||[]),item.name])];item.name=name}await saveCategories(type,items)};
async function saveCategories(type,items){try{await setDoc(settingsRef,{[type==="income"?"incomeCategories":type==="expense"?"expenseCategories":"transferCategories"]:items,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});toast("Kasa kategorileri güncellendi.")}catch(error){console.error(error);toast("Kategoriler güncellenemedi.")}}

function isFinanceDayClosed(date){return financeDays.some(x=>x.id===date&&x.locked===true)}
function isAdisyonDayClosed(date){return closings.some(x=>x.businessDate===date)}
function isFinanceLocked(date){return date<FINANCE_START_DATE||isFinanceDayClosed(date)}
function canEditSelectedDate(){return selectedDate>=FINANCE_START_DATE&&selectedDate<=today()&&!isFinanceLocked(selectedDate)}
function showFinanceDayEndWarning(){$("financeDayEndWarningTitle").textContent="Önce gün sonunu kapatın";if($("financeCloseDialog").open)$("financeCloseDialog").close();$("financeDayEndWarningText").textContent=`${formatBusinessDate(selectedDate)} için Adisyon bölümündeki gün sonu henüz kapatılmadı. Önce açık adisyonları ve aktif demlikleri tamamlayıp “Günü Kapat” işlemini yapın.`;$("financeDayEndWarningDialog").showModal()}
async function pendingInternalConsumption(date){if(hasLocalPendingInternalConsumption(date))return true;const snap=await getDoc(doc(db,"adminInternalConsumptionDrafts",date));return hasPendingInternalConsumptionDraft(snap.data())}
function showFinanceInternalWarning(){if($("financeCloseDialog").open)$("financeCloseDialog").close();$("financeDayEndWarningTitle").textContent="Dahili tüketim bekliyor";$("financeDayEndWarningText").textContent="Bu tarihte dahili tüketim için bekleyen ürünler var. Önce Adisyon bölümünden stoktan düşün veya listeyi temizleyin.";$("financeDayEndWarningDialog").showModal()}
async function openFinanceClose(){if(isFinanceLocked(selectedDate))return toast("Bu finans günü zaten kapalı.");if(!isAdisyonDayClosed(selectedDate))return showFinanceDayEndWarning();try{if(await pendingInternalConsumption(selectedDate))return showFinanceInternalWarning()}catch(error){console.error(error);return toast("Dahili tüketim kontrol edilemedi. Bağlantıyı kontrol edin.")} $("financeCloseText").textContent=`${formatBusinessDate(selectedDate)} kapatıldıktan sonra bu tarihe gelir, gider veya aktarım eklenemez; kayıtlar değiştirilemez ve silinemez. İşlem ayrıntıları geçmiş günlerde görünmeye devam eder.`;$("financeCloseDialog").showModal()}
async function closeFinanceDay(){if(isFinanceLocked(selectedDate))return;if(!isAdisyonDayClosed(selectedDate))return showFinanceDayEndWarning();try{const date=selectedDate;if(hasLocalPendingInternalConsumption(date))return showFinanceInternalWarning();await runTransaction(db,async tx=>{const draft=await tx.get(doc(db,"adminInternalConsumptionDrafts",date)),financeRef=doc(db,"adminFinanceDays",date),existing=await tx.get(financeRef);if(hasPendingInternalConsumptionDraft(draft.data()))throw new Error("pending-internal-consumption");if(existing.exists())throw new Error("already-closed");tx.set(financeRef,{businessDate:date,locked:true,closedAtMs:Date.now(),closedAt:serverTimestamp(),closedBy:auth.currentUser.uid})});$("financeCloseDialog").close();toast(`${formatBusinessDate(date)} finans kayıtları kapatıldı.`)}catch(error){console.error(error);if(error.message==="pending-internal-consumption")showFinanceInternalWarning();else toast(error.message==="already-closed"?"Bu finans günü zaten kapalı.":"Finans günü kapatılamadı. Bağlantıyı ve Firebase kurallarını kontrol edin.")}}

function openReport(){$("reportMonth").value=selectedDate.slice(0,7);renderReport();$("reportContent").scrollTop=0;$("reportDialog").showModal();requestAnimationFrame(updateReportScroll)}
function currentAccountReport(month){let cash=0,bank=0,card=0;for(const sale of sales){if(sale.reversed===true||sale.cancelled===true)continue;const date=String(sale.businessDate||"");if(!date.startsWith(month)||sale.recordType!=="current-account-payment")continue;cash+=number(sale.cashAmount);bank+=number(sale.transferAmount);card+=number(sale.cardAmount)}return{receivable:currentAccountReceivableAtMonthEnd(month),cash,bank,card}}
function currentAccountReceivableAtMonthEnd(month){if(month===today().slice(0,7))return Math.max(0,currentAccounts.reduce((sum,account)=>sum+number(account.balance),0));const monthEnd=`${month}-31`,latestByAccount=new Map;for(const movement of currentAccountMovements){if(movement.reversed===true)continue;const date=String(movement.businessDate||"");if(!date||date>monthEnd||!movement.accountId)continue;const order=`${date}|${String(number(movement.createdAtMs)).padStart(16,"0")}|${movement.id||""}`,current=latestByAccount.get(movement.accountId);if(!current||order>current.order)latestByAccount.set(movement.accountId,{order,balance:Math.max(0,number(movement.balanceAfter))})}return[...latestByAccount.values()].reduce((sum,item)=>sum+item.balance,0)}

let reportDragOffset=null;
function updateReportScroll(){
 const content=$("reportContent"),track=$("reportScrollTrack"),thumb=$("reportScrollThumb");
 const maximum=Math.max(0,content.scrollHeight-content.clientHeight),height=track.clientHeight;
 const thumbHeight=maximum?Math.min(height,Math.max(24,Math.round(height*content.clientHeight/content.scrollHeight))):height;
 thumb.style.height=`${thumbHeight}px`;
 thumb.style.transform=`translateY(${maximum?(height-thumbHeight)*content.scrollTop/maximum:0}px)`;
 track.setAttribute("aria-valuenow",String(maximum?Math.round(100*content.scrollTop/maximum):0));
 track.setAttribute("aria-disabled",String(!maximum));
 $("reportScrollUp").disabled=content.scrollTop<=0;
 $("reportScrollDown").disabled=content.scrollTop>=maximum-1;
}
function scrollReport(amount){$("reportContent").scrollBy({top:amount,behavior:"smooth"})}
function setReportScrollFromPointer(event,offset){
 const content=$("reportContent"),track=$("reportScrollTrack"),thumb=$("reportScrollThumb"),rect=track.getBoundingClientRect();
 const travel=rect.height-thumb.offsetHeight,maximum=content.scrollHeight-content.clientHeight;
 if(travel>0&&maximum>0)content.scrollTop=Math.max(0,Math.min(1,(event.clientY-rect.top-offset)/travel))*maximum;
}
function startReportScrollDrag(event){
 const track=$("reportScrollTrack"),thumb=$("reportScrollThumb"),rect=thumb.getBoundingClientRect();
 reportDragOffset=event.clientY>=rect.top&&event.clientY<=rect.bottom?event.clientY-rect.top:thumb.offsetHeight/2;
 track.setPointerCapture(event.pointerId);setReportScrollFromPointer(event,reportDragOffset);event.preventDefault();
}
function moveReportScrollDrag(event){if(reportDragOffset!==null)setReportScrollFromPointer(event,reportDragOffset)}
function stopReportScrollDrag(){reportDragOffset=null}
function reportScrollKey(event){
 const steps={ArrowUp:-70,ArrowDown:70,PageUp:-400,PageDown:400,Home:-Infinity,End:Infinity};
 if(!(event.key in steps))return;
 event.preventDefault();const amount=steps[event.key];
 if(Number.isFinite(amount))scrollReport(amount);else $("reportContent").scrollTop=amount<0?0:$("reportContent").scrollHeight;
}
function reportData(){let month=$("reportMonth").value||today().slice(0,7);if(month<"2026-08")month="2026-08";$("reportMonth").value=month;const rows=allMovements().filter(m=>m.businessDate?.startsWith(month)),totals=dayTotals(rows),balances=balancesThrough(`${month}-31`),currentAccount=currentAccountReport(month),totalIncome=totals.cashIncome+totals.bankIncome+totals.cardIncome,profitLoss=totalIncome-totals.expense,incomes=[["Nakit Gelir",totals.cashIncome],["Banka Geliri",totals.bankIncome],["Kart / POS Geliri",totals.cardIncome]].filter(([,value])=>Math.abs(value)>.001);incomes.push(["Cari Hesaptan Gelen Nakit",currentAccount.cash],["Cari Hesaptan Gelen Havale",currentAccount.bank],["Cari Hesaptan Gelen Kart",currentAccount.card]);return{month,rows,totals,balances,currentAccount,totalIncome,profitLoss,expenses:groupAmounts(rows.filter(m=>m.type==="expense"),m=>m.category||"Diğer"),incomes,products:groupProducts(closings.filter(c=>c.businessDate>=HISTORY_START_DATE&&c.businessDate?.startsWith(month)))}}
function reportResult(d){const positive=d.profitLoss>0.001,negative=d.profitLoss<-.001,label=positive?"Kârınız":negative?"Zararınız":"Kâr / Zarar",cls=positive?"profit":negative?"loss":"neutral";return`<div class="report-result ${cls}"><span>${label}</span><b>${money(Math.abs(d.profitLoss))}</b></div>`}
function renderReport(){const d=reportData();$("reportContent").innerHTML=`<div class="report-totals"><div class="report-stat"><span>Nakit Gelir</span><b>${money(d.totals.cashIncome)}</b></div><div class="report-stat"><span>Banka Geliri</span><b>${money(d.totals.bankIncome)}</b></div><div class="report-stat"><span>Kart / POS Geliri</span><b>${money(d.totals.cardIncome)}</b></div><div class="report-stat total-income-stat"><span>Toplam Gelir</span><b>${money(d.totalIncome)}</b></div><div class="report-stat"><span>Toplam Gider</span><b>${money(d.totals.expense)}</b></div></div><div class="report-accounts"><div class="report-stat"><span>Ay Sonu Nakit</span><b>${money(d.balances.cash)}</b></div><div class="report-stat"><span>Ay Sonu Banka</span><b>${money(d.balances.bank)}</b></div><div class="report-stat"><span>Ay Sonu Kart / POS</span><b>${money(d.balances.card)}</b></div><div class="report-stat"><span>Kredi Kartı Genel Borç</span><b>${money(Math.max(0,d.balances.cardDebt))}</b></div><div class="report-stat current-account-balance"><span>Cari Hesap Toplam Alacak</span><b>${money(d.currentAccount.receivable)}</b></div></div>${reportResult(d)}${reportSection("Gelirler",d.incomes,"Bu ay gelir yok.")}${reportSection("Giderler",d.expenses,"Bu ay gider yok.")}${reportSection("Banka kredisi taksit ödemeleri (gider toplamından ayrı)",groupAmounts(d.rows.filter(m=>m.type==="transfer"&&m.toAccount==="bankLoan"),m=>m.description||"Banka kredisi"),"Bu ay kredi taksit ödemesi yok.")}${reportSection("Birikime Yatırma (gelir-giderden ayrı)",groupAmounts(d.rows.filter(m=>m.source==="savings"&&m.fromAccount!=="savings"),m=>m.category),"Bu ay birikime yatırma yok.")}${reportSection("Birikimden TL Hesabına Dönüş (gelir-giderden ayrı)",groupAmounts(d.rows.filter(m=>m.source==="savings"&&m.fromAccount==="savings"),m=>m.category),"Bu ay bozdurma yok.")}${productSection(d.products)}`}
function printReport(){const d=reportData(),title=monthName(d.month),content=$("reportContent").innerHTML,w=window.open("","_blank","width=900,height=700");if(!w)return toast("PDF penceresi açılamadı.");w.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>${esc(title)} Kasa Raporu</title><style>body{font-family:Arial;color:#352522;padding:28px}header{display:flex;align-items:center;border-bottom:3px solid #7d1b24;padding-bottom:14px;margin-bottom:18px}header img{width:72px;height:72px;object-fit:contain;margin-right:14px}h1,h2,h3,p{margin:0}header p{color:#777;margin-top:4px}.report-totals,.report-accounts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.report-stat{border:1px solid #ddd;border-radius:8px;padding:10px}.report-stat span,.report-stat b{display:block}.report-stat span{font-size:11px;color:#777}.report-stat b{margin-top:5px}.current-account-balance b{color:#b3262d}.total-income-stat b{color:#315f89}.report-result{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:12px 0;padding:12px 14px;border:1px solid #ddd;border-radius:8px;font-weight:700}.report-result.profit{border-color:#b8d8c5;background:#eef8f2;color:#207245}.report-result.loss{border-color:#e5b9bd;background:#fff0f1;color:#b3262d}.report-result.neutral{background:#f4f1ed;color:#6f6460}.report-section{margin-top:18px}.report-row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:7px 0;font-size:12px}.empty{color:#777}button{display:none}@media print{body{padding:0}}</style></head><body><header><img src="../assets/images/logo.png"><div><h1>Fatih Çay Evi</h1><h2>${esc(title)} Kasa Raporu</h2><p>Oluşturulma: ${new Date().toLocaleString("tr-TR")}</p></div></header>${content}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`);w.document.close()}
function groupAmounts(rows,key){const map=new Map;for(const row of rows){const name=key(row);map.set(name,(map.get(name)||0)+number(row.amount))}return[...map].sort((a,b)=>b[1]-a[1])}function groupProducts(items){const map=new Map;for(const c of items)for(const p of c.products||[]){const name=p.name||"Ürün",v=map.get(name)||{quantity:0,total:0};v.quantity+=number(p.quantity);v.total+=number(p.total);map.set(name,v)}return[...map].sort((a,b)=>b[1].quantity-a[1].quantity)}function reportSection(title,rows,empty){return`<section class="report-section"><h3>${title}</h3>${rows.length?rows.map(([name,total])=>`<div class="report-row"><span>${esc(name)}</span><b>${money(total)}</b></div>`).join(""):`<p class="empty">${empty}</p>`}</section>`}function productSection(rows){return`<section class="report-section"><h3>Ürün Satışları</h3>${rows.length?rows.map(([name,v])=>`<div class="report-row"><span>${esc(name)}</span><b>${v.quantity} adet <small>• ${money(v.total)}</small></b></div>`).join(""):'<p class="empty">Bu ay kapatılmış ürün satışı yok.</p>'}</section>`}

function sortMovements(a,b){return number(b.createdAtMs)-number(a.createdAtMs)||String(b.id).localeCompare(String(a.id))}function movementIcon(m){return m.automatic?"fa-lock":m.type==="income"?"fa-arrow-trend-up":m.type==="expense"?"fa-arrow-trend-down":"fa-right-left"}function sign(m){return m.type==="income"?"+":m.type==="expense"?"−":"↔"}function typeName(t){return t==="income"?"Gelir":t==="expense"?"Gider":"Aktarım"}function accountText(m){const n={cash:"Nakit",bank:"Banka Havalesi",card:"Kart / POS",creditCard:"Kredi Kartı",bankLoan:"Banka Kredisi",savings:"Birikim"};return m.type==="transfer"?`${n[m.fromAccount]||""} → ${n[m.toAccount]||""}`:n[m.account]||""}function number(v){return Number(v)||0}function money(v){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(number(v))}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date())}function shiftDate(v,n){const d=new Date(`${v}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}function dateObject(v){return new Date(`${v}T12:00:00Z`)}function formatBusinessDate(v){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(dateObject(v))}function dayName(v){return new Intl.DateTimeFormat("tr-TR",{weekday:"long",timeZone:"UTC"}).format(dateObject(v))}function monthName(v){return new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}-01T12:00:00Z`))}function formatTime(ms){return ms?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(ms)):""}function updateClock(){const n=new Date();$("currentTime").textContent=n.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=n.toLocaleDateString("tr-TR",{day:"2-digit",month:"2-digit",year:"2-digit"})}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function toast(message){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}
