import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{connectFunctionsEmulator,getFunctions,httpsCallable}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import{ADMIN_UID,firebaseConfig}from"../assets/js/firebase-config.js";
import{disableAdminPushDevice,registerAdminPushDevice,startForegroundPush}from"../assets/js/push-client.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),functions=getFunctions(app,"europe-west1"),$=id=>document.getElementById(id);
const dashboard=httpsCallable(functions,"getNotificationDashboard"),send=httpsCallable(functions,"sendAnnouncement"),saveSettings=httpsCallable(functions,"setTeaNotificationSettings");let user=null,busy=false;
onAuthStateChanged(auth,async current=>{if(!current||current.uid!==ADMIN_UID){location.replace("../yonetici-giris.html?next=bildirim-merkezi/");return}user=current;if(Notification.permission==="granted")startForegroundPush();await load()});
$("logoutButton").onclick=async()=>{await signOut(auth);location.replace("../yonetici-giris.html")};
$("enableAdminPush").onclick=async()=>{if(!user||busy)return;setBusy(true);$("adminPushStatus").textContent="Bildirim izni hazırlanıyor…";try{await registerAdminPushDevice(user.uid);$("adminPushStatus").textContent="Bu cihazda yönetici bildirimleri açık.";toast("Yönetici bildirimleri açıldı.");await load()}catch(error){$("adminPushStatus").textContent=error.message==="permission-denied"?"Bildirim izni verilmedi.":"Bildirim cihazı kaydedilemedi."}finally{setBusy(false)}};
$("disableAdminPush").onclick=async()=>{if(!user||busy)return;setBusy(true);try{await disableAdminPushDevice(user.uid);$("adminPushStatus").textContent="Bu cihazda yönetici bildirimleri kapalı.";toast("Bu cihazdaki yönetici bildirimleri kapatıldı.");await load()}catch{toast("Bildirim kapatılamadı.")}finally{setBusy(false)}};
$("announcementForm").onsubmit=event=>{event.preventDefault();if(busy)return;const title=$("announcementTitle").value.trim(),body=$("announcementBody").value.trim();if(!title||!body)return;$("confirmText").textContent=`“${title}” başlıklı bildirim, duyuru izni veren cihazlara gönderilecek.`;$("confirmDialog").showModal()};
$("confirmDialog").addEventListener("close",async()=>{if($("confirmDialog").returnValue!=="confirm"||busy)return;setBusy(true);try{const result=(await send({title:$("announcementTitle").value.trim(),body:$("announcementBody").value.trim()})).data;$("announcementForm").reset();toast(`${result.successCount||0} cihaza bildirim gönderildi.`);await load()}catch(error){toast(callableMessage(error,"Bildirim gönderilemedi."))}finally{setBusy(false)}});
$("saveTeaSettings").onclick=async()=>{if(busy)return;setBusy(true);try{await saveSettings({customerTeaReadyEnabled:$("customerTeaToggle").checked,adminTeaAlertsEnabled:$("adminTeaToggle").checked});toast("Taze Dem ayarları kaydedildi.");await load()}catch(error){toast(callableMessage(error,"Ayarlar kaydedilemedi."))}finally{setBusy(false)}};
async function load(){try{const data=(await dashboard()).data;$("totalDevices").textContent=data.counts.total;$("announcementDevices").textContent=data.counts.announcements;$("teaDevices").textContent=data.counts.teaReady;$("customerTeaToggle").checked=data.settings.customerTeaReadyEnabled!==false;$("adminTeaToggle").checked=data.settings.adminTeaAlertsEnabled!==false;$("lastTeaSend").textContent=data.settings.lastTeaSentAtMs?dateTime(data.settings.lastTeaSentAtMs):"Henüz yok";renderHistory(data.logs||[]);const localId=localStorage.getItem("fatihAdminPushDeviceId"),active=(data.adminDevices||[]).includes(localId);$("adminPushStatus").textContent=active?"Bu cihazda yönetici bildirimleri açık.":"Bu cihazda yönetici bildirimleri kapalı."}catch(error){toast(callableMessage(error,"Bildirim bilgileri alınamadı."))}}
function renderHistory(items){$("historyList").innerHTML=items.length?items.map(item=>`<article class="history-item"><i class="fa-solid ${item.type==="announcement"?"fa-bullhorn":"fa-mug-hot"}"></i><div><strong>${escapeHtml(item.title||"Bildirim")}</strong><span>${escapeHtml(item.body||"")}</span></div><time>${dateTime(item.createdAtMs)}</time></article>`).join(""):'<p class="empty">Henüz bildirim gönderilmedi.</p>'}
function setBusy(value){busy=value;document.querySelectorAll("button").forEach(button=>{if(button.closest(".header-actions"))return;button.disabled=value})}
function toast(message){const element=$("toast");element.textContent=message;element.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove("show"),3000)}
function callableMessage(error,fallback){return String(error?.message||"").replace(/^FirebaseError:\s*/,"").replace(/^[^:]+:\s*/,"")||fallback}
function dateTime(value){return new Date(Number(value)||Date.now()).toLocaleString("tr-TR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
function tick(){const d=new Date;$("currentTime").textContent=d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("currentDate").textContent=d.toLocaleDateString("tr-TR")}tick();setInterval(tick,1000);
